### ISSUE TITLE
Built in categories it won't append them

### ISSUE THREAD

**Issue by twopirllc** [twopirllc/pandas-ta#100]
even with the build in categories it won't append them, am I missing something?
```
    df = pd.read_csv("../data/price_data/XBTUSD-1h-data.csv")

    df.ta.strategy(name="Momentum", timed=True, append=True)
    print(df.columns)
```
The output is:
`Index(['timestamp', 'symbol', 'open', 'high', 'low', 'close', 'trades',
       'volume', 'vwap', 'lastSize', 'turnover', 'homeNotional',
       'foreignNotional'],
      dtype='object')`

Here is another example:
```
    df = pd.read_csv("../data/price_data/XBTUSD-1h-data.csv")
    print(ta.categories)
    df.ta.strategy(name="trend", verbose=True)
    print(df.columns)
```
Output:
```
['candles', 'momentum', 'overlap', 'performance', 'statistics', 'trend', 'volatility', 'volume']
[i] ta.strategy(name=trend)
[+] Strategy: trend
[i] Indicators with the following arguments: {'append': True}
[i] Total indicators: 0
[i] Columns added: 0
Index(['timestamp', 'symbol', 'open', 'high', 'low', 'close', 'trades',
       'volume', 'vwap', 'lastSize', 'turnover', 'homeNotional',
       'foreignNotional'],
      dtype='object')

Process finished with exit code 0
```

But when I try it with all indicators it works, but with everything else it won't

_Originally posted by @Fr3d1sk in https://github.com/twopirllc/pandas-ta/issues/98#issuecomment-675123940_

**Comment by twopirllc** [comment]
Hello  @Fr3d1sk,

Doh! Thanks. I'll look into it.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @Fr3d1sk,

Is this happening in a Jupyter Notebook or a .py or both?

Thanks,
KJ

**Comment by Fr3d1sk** [comment]
It happend in a .py file

**Comment by Fr3d1sk** [comment]
![image](https://user-images.githubusercontent.com/48406090/90578281-33abf080-e1c3-11ea-9c44-f8843e3f62e4.png)
Shouldn't indicators on line 543 be list with the indicators^^?

I run into this problem with and without mp and tested it on following categories: volatility, momentum, statistics
(just adding normal indicators with "dataframe.ta.adx(append=True, length=adx_time)" works perfect)

Fredi

**Comment by twopirllc** [comment]
Thanks for the feedback.
