### ISSUE TITLE
Elder Ray Index

### ISSUE THREAD

**Issue by sv136** [twopirllc/pandas-ta#102]
Hello,

I try to use the latest version, and I don't see Elder Ray Index (eri), mentioned on main page. A list of indicators (ta.indicators()) doesn't contain eri too. Is it implemented?
Thnx

**Comment by twopirllc** [comment]
Hello @sv136,

I assume by no response that the solition provided was sufficient. Thus I will be closing this issue in a few days.

Please ⭐ if you find the library useful.

Thanks,
KJ
