### ISSUE TITLE
[Question] How to calculate the slope from the vertical and an indicator?

### ISSUE THREAD

**Issue by cbogithub** [twopirllc/pandas-ta#103]
how calculate slope between a indicator with h-line (same image below) ?
thanks
![Screenshot_2020-08-22 (PNG Image, 1034 × 587 pixels)](https://user-images.githubusercontent.com/9572613/90918708-5fbbb180-e40f-11ea-9448-dcba68fa837b.png)

**Comment by twopirllc** [comment]
Hello @cbogithub,

Apologies for not replying earlier. That is an interesting question! However, I am still uncertain about which two components you would like to compare to calculate slope.
* The green arrow is pointing to the red arc. Is that the angle you wish to compute? The angle from the vertical line down to the Moving Average?
* Slope between the _teal_ horizontal line (above the Moving Average and before the vertical line) and the Moving Average below it?
* Slope of the Moving Average?
    * In that case, you can use ```ta.slope(close, length=1, as_angle=False, to_degrees=False)```. Just replace _close_ with your Moving Average like so: ```ta.slope(ta.sma(close, 200), length=1, as_angle=False, to_degrees=False)``` and set ```as_angle=True``` if you want radians and ```as_angle=True``` **and** ```to_degrees=True``` if you prefer degrees. You will have to fiddle with it to get what you are looking for. Let me know what you get and the results if you go this route.

Perhaps you have another sample that I could understand.

Thanks,
KJ

**Comment by cbogithub** [comment]
thanks @twopirllc , 

I was confused between the vertical axis and the horizontal axis

**Comment by twopirllc** [comment]
So, the red arc?

**Comment by cbogithub** [comment]
![Untitled-2](https://user-images.githubusercontent.com/9572613/91602166-0e726b80-e995-11ea-9d96-31a5ab4b996b.jpg)
@twopirllc ,yes 👍 calc slop ema200 and vertical line   . 

if calc slop ema200 and horizontal line , how i can do ?

**Comment by twopirllc** [comment]
@cbogithub,

I'll fool around with it.  Thanks for a clearer chart to understand the request.

Thanks
KJ

**Comment by twopirllc** [comment]
Hey @cbogithub,

Apologies for the delay.

If you want the angle from the vertical, and assuming degrees here, then you can do the following:

```python
import math

df = <Your Datasource>
ema200 = df.ta.ema(length=200, append=True)
ema_angle = df.ta.slope(close=ema200, as_angle=True, to_degrees=True)
df["EMA200_VA"] = 90 - ema_angle

# As degrees in one line:
df["EMA200_VA"] = 90 - df.ta.slope(close=df.ta.ema(length=200, append=True), as_angle=True, to_degrees=True)

# As radians in one line:
df["EMA200_VAr"] = 0.5 * math.pi - df.ta.slope(close=df.ta.ema(length=200, append=True), as_angle=True)
```

Hope this helps! Please let me know if this is what you had in mind.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hi @cbogithub,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Thanks,
KJ
