### ISSUE TITLE
Inside bar indicator request

### ISSUE THREAD

**Issue by SoftDevDanial** [twopirllc/pandas-ta#109]
Hi , can you please add the inside bar indicator from cma?
link: https://www.tradingview.com/script/IyIGN1WO-Inside-Bar/

I couldn't find it in the readme area unless it is in a different name
This indicator seems like it has 900 likes (just saying in case this would increase your reason to do this indicator XD)
Thanks

**Comment by twopirllc** [comment]
Hello @SoftDevDanial,

It has not been implemented yet. I'll take a look at it when I get a chance and other pending Issues to complete. However, you are welcome to take a stab at it 😉.

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
Hi @twopirllc ,

Can you review, modify to be like pandas-ta format and comment on my code. I already made the code for it but i'm unable to use corr on it which i don't know why(tried my best to make it as similar style to pandas-ta code). So since corr() cant be used on this, i did manual comparison and its 100% the same. Below is the code and the results(in excel).
```
def InBar(open , high ,low , close ):
    """Indicator: Inside Bar"""
    close = ta.verify_series(close).apply(ta.zero)
    open = ta.verify_series(open).apply(ta.zero)
    high = ta.verify_series(high).apply(ta.zero)
    low = ta.verify_series(low).apply(ta.zero)
    prevBar = 1

    bodyStat = (close >= open).rename('bodystat').replace({True: 1 , False:-1})
    isIn = ((high < high.shift(prevBar)) & (low > low.shift(prevBar))).rename('isin')

    cc = pd.concat([isIn,bodyStat] , axis = 1)
    cc['Res'] = ""
    for i in cc.index:
        if cc['isin'][i] == True:
            cc.loc[cc.index[i],'Res'] = cc['bodystat'][i]
        else:
            cc.loc[cc.index[i],'Res'] = 0
    return cc
data = pd.read_csv("test.csv") 
dropped = ['time' , 'EMA #1' , 'EMA #2' , 'EMA #3', 'EMA #4' , "Upper","Basis","Lower" , "%K" , "%D"]
data.drop(columns=dropped , inplace=True)
results = InBar(data['open'] , data['high'] , data['low'] , data['close'])
data['InBar'] = results['Res']
dropped = ['close' , 'low' , 'high' , 'open']
data.drop(columns=dropped , inplace=True)
print(data.corr())
```

**Results**
[results.xlsx](https://github.com/twopirllc/pandas-ta/files/5179240/results.xlsx)

**Comment by SoftDevDanial** [comment]
```
def inbar(self , open , high ,low , close , offset = None , **kwargs ):
        """Indicator: Inside Bar"""
        # Validate arguments
        close = verify_series(close).apply(zero)
        open = verify_series(open).apply(zero)
        high = verify_series(high).apply(zero)
        low = verify_series(low).apply(zero)
        offset = get_offset(offset)
        prevBar = 1

        #Calculate Result
        bodyStat = (close >= open).rename('bodystat').replace({True: 1 , False:-1})
        isIn = ((high < high.shift(prevBar)) & (low > low.shift(prevBar))).rename('isin')
        res = pd.Series(index = close.index , dtype = 'int64')
        
        for i in close.index:
            if isIn[i] == True:
                res[i] = bodyStat[i]
                print('here')
            else:
                res[i] = 0

        # Offset
        if offset != 0:
            res = res.shift(offset)

        # Handle fills
        if 'fillna' in kwargs:
            res.fillna(kwargs['fillna'], inplace=True)

        if 'fill_method' in kwargs:
            res.fillna(method=kwargs['fill_method'], inplace=True)

        # Name and Categorize it
        res.name = "InBar"
        res.category = 'insidebar'
        
        return res
```

Update to the code.. Here is the closest i can do to make it similar to pandas-ta style of coding

Do review and comment

**Comment by twopirllc** [comment]
Hi @SoftDevDanial,

You want to make a pull request with your inclusion? I will take it from there. Your contribution will definitely same me some time and I would appreciate it. 😎 

Just to be clear, you want the default to return an integer whether or not it's an Inside Bar or not? ```True: 1, False: 0```?

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
hi @twopirllc .

Alright will do. By default, i want it to return `True:1 , False:-1` . the 1 and -1 shows the bullish and bearish signs while 0 means neutral. My code  is referenced from this https://www.tradingview.com/script/IyIGN1WO-Inside-Bar/

Thanks

**Comment by twopirllc** [comment]
@SoftDevDanial,

Easy to give it the ability to return ```bool```, binary ```1,0```, or ternary ```-1,0,1```.

Out of curiosity, what percentage of bars return 0?
```python
def inbar(self , open , high ,low , close , offset = None , **kwargs ):
        """Indicator: Inside Bar"""
        # ...

        k = 0
        for i in close.index:
            if isIn[i] == True:
                res[i] = bodyStat[i]
            else:
                res[i] = 0
                k +=1
        print(f"notIn: {k} / {len(close)}, percent= {100 * k / len(close) }%")
        # ...
```

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
@twopirllc 
`notIn: 602 / 675, percent= 89.18518518518519%`

Above is the results. I ran this from a starting date of 2018-01-01

**Comment by twopirllc** [comment]
Almost done!
