### ISSUE TITLE
A question about Supertrend vs Tradingview's Supertrend

### ISSUE THREAD

**Issue by Jacks349** [twopirllc/pandas-ta#111]
First of all, thank you for open sourcing this library, it's incredibly easy to use and it has indicators/studies that none of the other libraries i've checked have. 

I was trying to run a backtest on the Supertrend indicator, and since i noticed a substantial difference from how it is implemented on Tradingview, i wanted to investigate a little more on this. I tried the following:

`st = ta.supertrend(df['high'], df['low'], df['close'], 10, 4.0)`

Where `df` is my OHLC dataframe. This got me the following result:
![30m](https://user-images.githubusercontent.com/65462643/92301934-15d2df80-ef68-11ea-8cfb-1531aa67f6e1.png)

While, with the same data (retrieved from [here](https://api.binance.com/api/v1/klines?&symbol=TRXBTC&interval=30m&limit=1750) ) Tradingview will look like this (i'm using [this](https://www.tradingview.com/script/VLWVV7tH-SuperTrend/) implementation): https://www.tradingview.com/x/Xi38z7Hn/

Now i know the question might be naive, but is there a difference on how the indicator is calculated on this library and Tradingview? Or am i just missing something or doing something wrong?

Again, thank you for making this awesome library available to everyone. Keep up the good work!

**Comment by twopirllc** [comment]
Hello @Jacks349,

Thanks for using Pandas TA!

> Now i know the question might be naive, but is there a difference on how the indicator is calculated on this library and Tradingview? Or am i just missing something or doing something wrong?

Trading View does not have a builtin Super Trend, but there are many user created [Super Trend variations](https://www.tradingview.com/scripts/supertrend/). Everget, like many others, typically enhance a standard calculation of an indicator for various reasons and it is very easy to do so with Pinescript. So there is _likely_ a difference in the Everget's Super Trend on Trading View versus Pandas TA.

To reduce complexity and ensure accuracy, I try and implement the standard implementation before considering external variations. The purest form Super Trend, meaning no additional features in their calculation, I have found to implement for Pandas TA is described [here](http://www.freebsensetips.com/blog/detail/7/What-is-supertrend-indicator-its-calculation).

Also to help with charting in Python, I have slightly modified Pandas TA to return a DataFrame with four columns: _SUPERT_ (trend), SUPERTd (direction), _SUPERTl_ (long), _SUPERTs_ (short) columns. The first _SUPERT_ is Super Trend of course, the second _SUPERTd_ returns the direction 1 (for long) -1 (for short), _SUPERTl_ returns only the long portions of _SUPERT_ and _SUPERTs_ returns only the short portions of _SUPERT_. Visually, the first chart below is _SUPERTd_ (blue area). The second chart is _SUPERT_ (blue). Finally, the third chart is both _SUPERTl_ (green) and _SUPERTs_ (red).

<img width="631" alt="Screen Shot 2020-09-05 at 8 53 29 AM" src="https://user-images.githubusercontent.com/18198392/92309314-56772c80-ef59-11ea-80cc-f1fb208b32e9.png">

You can find more information about a Pandas TA indicator by using ```help()```
```python
import pandas_ta as ta
help(ta.supertrend)
````

> First of all, thank you for open sourcing this library, it's incredibly easy to use and it has indicators/studies that none of the other libraries i've checked have.

If you find this library useful, please add a :star:.

Hope this helps!

Thanks,
KJ

**Comment by Jacks349** [comment]
This was incredibly helpful! Thank you a lot! Everything is clear now! Added my star, keep up the awesome work!

**Comment by twopirllc** [comment]
Thank you @Jacks349. I appreciate it!

Good luck with your trading and investing.
