### ISSUE TITLE
Potential fix to stoch (maybe)

### ISSUE THREAD

**Issue by SoftDevDanial** [twopirllc/pandas-ta#112]
Hi ,

So i used .corr on pandas_ta stoch with the stoch in trading view. I might be doing it wrong but the correlation for slowk/%k is 0.599302 and slowd/%d is 0.605692 . So i made my own code by referring to the stoch page provided by pandas_ta (https://www.tradingview.com/support/solutions/43000502332-stochastic-stoch/) and it seems i think a potential fix is to change the slow_k in rolling to fast_k
```
lowest_low   =  low.rolling(slow_k).min()
highest_high = high.rolling(slow_k).max()
```

Here is my code and i got both 1 correlation for k and d.
```
data = pd.read_csv("Kc.csv")
high = ta.verify_series(data['high'])
low = ta.verify_series(data['low'])
close = ta.verify_series(data['close'])
lowest_low = low.rolling(14).min()
highest_high = high.rolling(14).max()

nom = (close - lowest_low)
dem = highest_high - lowest_low
results = 100*(nom / dem)
slow_k = ta.sma(results , length = 3).rename("slow_k")
slow_d = ta.sma(slow_k , length = 3).rename("slow_d")
df = pd.concat([slow_k , slow_d] , axis=1)
data.ta.stoch(append = True , fast_k = 14 , slow_k = 3 , slow_d = 3)
dropped = ['time' , 'close' ,'open', 'high', 'low', 'EMA #1' , 'EMA #2' , 'EMA #3', 'EMA #4' , "Upper","Basis","Lower"]
data.drop(columns=dropped , inplace=True)
df_cc = pd.concat([data,df] , axis=1)
print(df_cc.corr())
```
and here is the result comparing tradingview,pandas_ta and my code.
![image](https://user-images.githubusercontent.com/64815604/92311870-a0115700-efed-11ea-94d3-00d1e1c0f8c9.png)

One thing to note is that, theirs a small difference for the last row of data between my slowk and slowd with tradingsview %k and %d. However, all the other rows are the same.

**Column Names according to the dataframe**
%K - %D - STOCHFk - STOCHFd - STOCHk - STOCHd - slow_k - slow_d

![image](https://user-images.githubusercontent.com/64815604/92311854-77895d00-efed-11ea-85d5-cf5e35e29b2f.png)

So as you can see , the last data has a slight difference but if im not mistaken , the others are exactly the same

Thanks

**Comment by twopirllc** [comment]
Awesome @SoftDevDanial!

Just needed fresh eyes to solve it. Thanks! If you know where in the code to fix, please fork, edit and make a pull request and I'll review it on the development branch.

Thanks,
KJ
