### ISSUE TITLE
ichimoku data leak?

### ISSUE THREAD

**Issue by andybrewer** [twopirllc/pandas-ta#115]
I'm seeing strong correlations with `ICS_26` and found this line:
https://github.com/twopirllc/pandas-ta/blob/master/pandas_ta/overlap/ichimoku.py#L28

That appears to be shifting future `close` values into the present. Also, in my dataframe, the ICS values start on day 1, but aren't present for the final 26 days of the dataframe.

There was a similar negative shift value in `dpo` as well which was reported here: https://github.com/twopirllc/pandas-ta/issues/60. I don't think any indicators should be shifting future values to the present, right?

**Comment by twopirllc** [comment]
Hey @andybrewer,

Here is some information about Ichimoku Clouds:

<img width="809" alt="Screen Shot 2020-09-05 at 7 28 37 PM" src="https://user-images.githubusercontent.com/18198392/92316846-6d943980-efae-11ea-8fd7-ef51fe454810.png">

### Ichimoku and DPO (Centered) Chart

Below is Trading View's default Ichimoku overlay as well as Trading View's default _centered_ **dpo** (Issue #60).

![Ichimoku Cloud2](https://user-images.githubusercontent.com/18198392/92316883-c368e180-efae-11ea-9b8f-8b7aaec85d9c.png)

### DPO

[Here](https://getsatisfaction.com/tradingvew/topics/centered_detrend_oscillator) is Trading View responding to a users issue just like Issue #60 seven years ago. [This](https://school.stockcharts.com/doku.php?id=technical_indicators:detrended_price_osci) is there rational and description behind Issue #60.

These offsets or shifts are features of both indicators.

Hope this helps!
KJ

**Comment by andybrewer** [comment]
Thanks for the detailed response! The trading view link doesn't work for me (maybe it's a gated page?), but the other information is really helpful. Thanks again!

**Comment by twopirllc** [comment]
@andybrewer 

That's weird. 🤷‍♂️ 

No worries. Here is the result I found from Google search.

<img width="617" alt="Screen Shot 2020-09-06 at 8 32 07 AM" src="https://user-images.githubusercontent.com/18198392/92329229-f6e15580-f01a-11ea-8fcc-e2360511343a.png">

Here is the entire thread from that link with the reference to Stock Charts DPO description I posted in the last response.

<img width="976" alt="Screen Shot 2020-09-06 at 8 31 27 AM" src="https://user-images.githubusercontent.com/18198392/92329246-22fcd680-f01b-11ea-9010-0e4c707fc4eb.png">
<img width="732" alt="Screen Shot 2020-09-06 at 8 31 43 AM" src="https://user-images.githubusercontent.com/18198392/92329249-26905d80-f01b-11ea-9458-e9772e1c4bd2.png">

Hope this helps!
KJ

**Comment by andybrewer** [comment]
For those coming across this in the future, the `chikou` span (the `ICS_` prefix) is basically a Series of future close values:
https://github.com/twopirllc/pandas-ta/blob/master/pandas_ta/overlap/ichimoku.py#L28

It's the correct way to plot the chart per: https://school.stockcharts.com/doku.php?id=technical_indicators:ichimoku_cloud, but when analyzed as a data column without context would lead to data leaks.
