### ISSUE TITLE
CFO (Chande Forcast Ocsilator) 

### ISSUE THREAD

**Issue by codesutras** [twopirllc/pandas-ta#124]
Hey @twopirllc,

I'm still using pandas-ta==0.1.36b0 version at this moment and added one indicator on my own in my project. This indicator is known as Chande Forcast Oscilator (CFO). 

Here is the working code for the same. You man alter it according to the current codebase and include it. 

```
import pandas_ta as ta_p

period = 14
data['linreg'] = ta_p.linreg(data['close'],length=period)
data['linreg'] =  data['linreg'].round(decimals=2)
data['cfo'] =  ((data['close']-data['linreg'])/data['close'] *100)
data['cfo'] =  data['cfo'].round(decimals=2)
```

And here is a [link](https://www.fmlabs.com/reference/default.htm?url=ForecastOscillator.htm) for the formula.

Let me know if you need more details before you include it in the master code.
Cheers !!

**Comment by twopirllc** [comment]
Hey @codesutras,

Cool! I can add it no problem! I just do not have a timeframe yet unfortunately. I'll keep you posted when I get around to it or someone else feels like picking it up sooner.

Thanks,
KJ

**Comment by codesutras** [comment]
Let me pick it this time Kevin. Give me the write access and assign it to me.

**Comment by twopirllc** [comment]
@codesutras,

We can split the work. If you have not already, you need to fork the repository. Add the indicator file to 'momentum' directory, update the __init__.py in the 'momentum' directory and make a _Pull Request_. I will take it from there by linking the rest of the pieces to the DataFrame and I'll write the tests for you. Sound good?

Thanks,
KJ

**Comment by codesutras** [comment]
Yup, I'm okay with it.

**Comment by codesutras** [comment]
@twopirllc Merge request sent. Please review that.

**Comment by twopirllc** [comment]
@codesutras,

Thanks for your patience and contribution! I appreciate it. It is now up on Github and hopefully added to _pip_ in a few days if no major bugs happen till then.

Thanks,
KJ
