### ISSUE TITLE
vwap raises false warning on "[!] VWAP volume series is not datetime ordered. Results may not be as expected."

### ISSUE THREAD

**Issue by phelbton** [twopirllc/pandas-ta#128]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.2.02b

**Upgrade.**
done

**Describe the bug**
vwap indicator performs a datetime check on the volume series which shouldn't be date time and raises a warning flag

**To Reproduce**
(Assuming you have AAPL.csv file in your script folder):
```
import pandas as pd
import pandas_ta as ta

df = pd.read_csv("AAPL.csv", sep=",")
df.ta.vwap()
```

**Expected behavior**
not raising that warning flag...

**Screenshots**
[!] VWAP volume series is not datetime ordered. Results may not be as expected.

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @phelbton,

Thanks for using Pandas TA!

It's not a **bug** as it is not breaking anything nor altering the data in any form when the condition is met. I understand it is a nuisance for you and you can remove or comment out the following two lines from ```vwap.py``` in the ```overlap``` directory on your local filesystem.

```python
def vwap(...):
    # ...
    if not is_datetime_ordered(volume):
        print(f"[!] VWAP volume series is not datetime ordered. Results may not be as expected.")
    # ...
```

However it does point out that your DataFrame ```df``` index is not _datetime ordered_ which will be problematic in the future when VWAP fixed for intraday. See also Issue #38.

Don't forget to ⭐ if you find the library useful.

Hope this helps!
KJ

**Comment by twopirllc** [comment]
Hello @phelbton,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Add ⭐ if you find the library useful.

Thanks,
KJ

**Comment by PandaSobao** [comment]
Just in case, if the dataframe in question only has 1 row then pandas-ta's `is_datetime_ordered` will produce a `False` due to the [inequality line](https://github.com/twopirllc/pandas-ta/blob/bc3b292bf1cc1d5f2aba50bb750a75209d655b37/pandas_ta/utils/_core.py#L41) accessing the same row datetime index.
