### ISSUE TITLE
Support for add all features 

### ISSUE THREAD

**Issue by diegolovison** [twopirllc/pandas-ta#129]
Support for add all features 
```
import pandas_ta as ta
df = pd.read_csv(csv_path)
df = ta.add_all_ta_features(df, open="open", high="high", low="low", close="close", volume="volume", fillna=True)
```

Thanks

**Comment by twopirllc** [comment]
Hello @diegolovison,

Thanks for using **Pandas TA**!

On the **README**, it shows you how to run **ALL** the indicators/features with the ```strategy``` method, you just have to use the DataFrame mode.

In short:
```python
import pandas as pd
import pandas_ta as ta

df = pd.read_csv("path/to/symbol.csv") # Or however you access data
df.ta.strategy(verbose=True) # Runs ALL the indicators and appends to the DataFrame
print(', '.join(list(df.columns)))
```

Here is the README excerpt on the ```strategy``` method and how to create Strategies in this [Example Notebook](https://github.com/twopirllc/pandas-ta/blob/master/examples/PandasTA_Strategy_Examples.ipynb).

<img width="782" alt="Screen Shot 2020-09-15 at 7 13 22 PM" src="https://user-images.githubusercontent.com/18198392/93284952-a9868600-f788-11ea-9006-9b740d73fade.png">

Add a :star: if you find this library useful.

Thanks,
KJ
