### ISSUE TITLE
Idea: "All Tech"

### ISSUE THREAD

**Issue by kabonker** [twopirllc/pandas-ta#13]

**Comment by kabonker** [comment]
Not sure if you have a set up for all?   Meaning I have a Pandas DataFrame with the basic open close...  I have written code like this:  

`stock_df.ta(kind='ema',length=3,append=True)`

But I would actually like to just add "ALL" technical key figures as columns to the data frame in one command?  Instead of coding them separately?   Is that possible?  then even if you add more, the program still works over time.

thanks
john

**Comment by twopirllc** [comment]
Hello John.

Sorry for responding so late.  To clarify, you would like: `stock_df.ta(kind='all', append=True)`
to run all the indicators?  Should be possible with the exception of a few indicators.  I will take
a look at it and try to incorporate it.

**Comment by kabonker** [comment]
Kevin

It may require that you set up a bunch of defaults. 

But imagine not knowing which one matters.   

Easier to just pick all.   Then if you add like 5 more they will auto hit the stream.  

Thanks
John

John Vaughan
757-256-8216

**Comment by lluissalord** [comment]
Hi,

From my side, using a code like the following one allow me to generate almost all cases, but I believe it should be better ways for that.

```
def generateTAFeatures(data, exclude_ind=[], args=None):
    # Indicators not posible to use 'short_run' and 'cross'
    not_ind = ['long_run', 'short_run', 'cross']
    not_ind.append('ichimoku') # Output has to be treaten different because is returning two DataFrames
    not_ind.append('trend_return') # Required trend column

    # Add exclude_ind
    not_ind += exclude_ind

    indicators = [ind for ind in data.ta.indicators(as_list=True) if ind not in not_ind]

    if args is None:
        basic_args = {'append': True, 'ewm': True, 'adjust': True}
        basic_args = dict(zip(indicators, [basic_args] * len(indicators)))

        args = basic_args

    n_args = len(args)
    for i, (ind, arg) in enumerate(args.items()):
        print(f'{i} out of {n_args} features', end='\r')
        data.ta(kind=ind, **arg)

    return data
```

**Comment by twopirllc** [comment]
Hi @lluissalord,

Looks like a start.  It's kinda how I imagined it but haven't gotten to code it yet.  Another for exclusion is ```vp``` as it does not return a time series but price buckets with volumes (but that's an easy exclusion to add).

I was contemplating the idea of saving indicator settings via json and using that to load and generate the DataFrame as well.  Any thoughts on that?

Thanks,
KJ

**Comment by lluissalord** [comment]
Hi @twopirllc,

I think that a json file is a good idea. It could be used a default values json file which could be used directly on each indicator module and also when used by `ta(kind='all')`. 

Besides, some ideas of features that it could have the `ta(kind='all')` are:
1. The arguments passed on the call would be good to be used for all the indicators (as it could be `append=True` or `ewm=True`).
2. List of indicators included on `all` be the ones which are compatible.
3. As we are on this work, could be interesting other groups base on the nature of the indicstor like: `momentum`, `trend`, etc. Other interesting groups could be based on range which is bound the indicator (as for example some indicators are bound between 0-100, others between 0-1, others around the price range and others which are not bound)

These are some idees that could be interesting, but probably there are more of them.

**Comment by twopirllc** [comment]
Hi @lluissalord,

All good points.  Perhaps the default json config contain at a minimum "all" and then they can edit the file and load/save separate strategies from there.

Example ```ta.json```:
```json
[
    {
        "name":"all",
        "alias":"ALL",
        "desc":"Builds a massive Pandas DataFrame with all time series indicators",
        "required":{"append":"True"},
        "kind":[
            {"name":"sma", "length": 50},
            {"name":"sma", "length": 200},
            {"name":"ema", "length": 8},
            {"name":"ema", "length": 21}
        ]
    },
    {
        "name":"mac",
        "alias":"MAC",
        "desc":"Big MAC",
        "required":{"append":"True"},
        "kind":[
            {"name":"ema", "length": 50},
            {"name":"ema", "length": 200},
            {"name":"macd", "fast": 50, "slow": 200}
        ]
    },
    {
        "name":"momentum",
        "alias":"momo",
        "desc":"All momentum indicators",
        "required":{"append":"True"},
        "kind":[...]
    }
]
```
Also, I don't want to feature creep ```pandas_ta``` too much.  But do simplify some tasks that are or can be more cumbersome 

What do you think?

Thanks,
KJ

**Comment by lluissalord** [comment]
It seems a pretty good idea. Besides, I would think that the list inside `kind` node could be presented without arguments to take the default, but with the possibility of adding them (probably some indicators will have arguments and other no). In this way, if we want to modify the default values we only have to modify on the indicator function and not in two places.

Even, a better approach could be to have another `default.json` with the default values for each indicator to have all in one file.

What do you think?

Regards,
Lluis

**Comment by sword134** [comment]
Hello @twopirllc
Seeing how this thread has been a year underway now, may one ask when the add all technical indicators feature is going to launch? Manually coding all the indicators takes a while and takes focus off what's more important.

Cheers

**Comment by twopirllc** [comment]
Hello @sword134,

I do not have a time frame on when it will be completed, but I will make it a greater priority now that it has more requests.  I will implement a naive approach for the time being.  But be warned that using "all" will yield a Massive DataFrame.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @kabonker & @sword134,

Here is the relevant README section covering the new Strategy Method:

Strategy is a new __Pandas (TA)__ method to facilitate bulk indicator processing. By default, running ```df.ta.strategy()``` will append __all
applicable__ indicators to DataFrame ```df```.  Utility methods like ```above```, ```below``` et al are not included.

* The ```ta.strategy()``` method is still __under development__. Future iterations will allow you to load a ```ta.json``` config file with your specific strategy name and parameters to automatically run you bulk indicators.

```python
# Runs and appends all indicators to the current DataFrame by default
# The resultant DataFrame will be large.
df.ta.strategy()
# Or equivalently use name='all'
df.ta.strategy(name='all')

# Use verbose if you want to make sure it is running.
df.ta.strategy(verbose=True)

# Maybe you do not want certain indicators.
# Just exclude (a list of) them.
df.ta.strategy(exclude=['bop', 'mom', 'percent_return', 'wcp', 'pvi'], verbose=True)

# Perhaps you want to use different values for indicators.
# This will run ALL indicators that have fast or slow as parameters.
# Check your results and exclude as necessary.
df.ta.strategy(fast=10, slow=50, verbose=True)

# Sanity check. Make sure all the columns are there
df.columns
```

Let me know if you run into any issues.  I will close this issue in a few days otherwise.

Thanks again for using,
KJ
