### ISSUE TITLE
pandas required *before* running pip install

### ISSUE THREAD

**Issue by pbrumblay** [twopirllc/pandas-ta#133]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
pandas-ta-0.2.2b0

**Describe the bug**
Because `setup.py` references the "version" attribute in `core.py`, `pandas_ta/__init__.py` is run and all dependencies must be present *before* "pip install". 

**To Reproduce**
```
docker run --rm -it python:buster bash
root@51ce3645b16f:/# pip install -U git+https://github.com/twopirllc/pandas-ta
Collecting git+https://github.com/twopirllc/pandas-ta
  Cloning https://github.com/twopirllc/pandas-ta to /tmp/pip-req-build-g9y88i3a
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-g9y88i3a/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-g9y88i3a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mkdgw2l2
         cwd: /tmp/pip-req-build-g9y88i3a/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-g9y88i3a/setup.py", line 3, in <module>
        from pandas_ta.core import version
      File "/tmp/pip-req-build-g9y88i3a/pandas_ta/__init__.py", line 49, in <module>
        from pandas_ta.core import *
      File "/tmp/pip-req-build-g9y88i3a/pandas_ta/core.py", line 11, in <module>
        import pandas as pd
    ModuleNotFoundError: No module named 'pandas'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Expected behavior**
'pip install' should work without needing to manually install dependencies first. I used docker in the steps to reproduce because it's a quick way to get a clean environment (and I discovered the problem when running pip install from within a container). I suspect the same issue exists with a new virtual environment.

**Additional context**
I spent some time trying to come up with a solution which would allow you to keep the version attribute in `core.py` but came up empty. My best suggestion is to set it in two places, `setup.py` and `pandas_ta/core.py` and keep them in sync but that seems ... tedious. If it's not needed you could remove it from `pandas_ta/core.py` That would involve some documentation changes I think.

I'm going to remove version from `pandas_ta/core.py` from my own fork to clean up my build files which all need to 'pip install pandas' first at the moment. Let me know if you'd like me to issue a PR.

**Comment by pbrumblay** [comment]
I've opened a PR to address this with what I *think* is an ok solution. I'm using pkg_resources which appears to be a reasonable <= 3.7 solution according to this: https://stackoverflow.com/a/17767076. In the same issue this https://stackoverflow.com/a/56331414 is supposedly the 3.8+ way to do it. I've tested this solution locally in a docker container and it seems ok...

**Comment by twopirllc** [comment]
Hello @pbrumblay,

Thanks for bringing this to my attention with a detailed description and potential solution for those using containers. Also, thanks for making a PR. I will merge it into _development_ soon.

Thanks,
KJ
