### ISSUE TITLE
Variable Index Dynamic Average (VIDYA)

### ISSUE THREAD

**Issue by putraxor** [twopirllc/pandas-ta#136]
Need implementation of Variable Index Dynamic Average (VIDYA). I have tried to calculate based on this indicator on tradingview [Variable Index Dynamic Average (VIDYA)](https://www.tradingview.com/script/hdrf0fXV-Variable-Index-Dynamic-Average-VIDYA/) but it results in wrong calculation

```python
p = 10
alpha = 2 / (p + 1)
df['cmo'] = ta.cmo(df.close, length=p, talib=False).abs()
df['vidya'] = 0
df['vidya'] = (df.close * alpha * df.cmo) + (1 - alpha * df.cmo) * df.vidya.shift(1)
print(df.tail(5))
```

this is the result:
```
AUD/CAD
                              open     high      low    close  actual1        cmo     vidya
time                                                                                       
2020-03-17 23:56:00+00:00  0.85291  0.85347  0.85291  0.85339        0  11.640212  1.806116
2020-03-17 23:57:00+00:00  0.85339  0.85359  0.85331  0.85337        0  16.574586  2.571683
2020-03-17 23:58:00+00:00  0.85339  0.85340  0.85296  0.85304        1   3.431373  0.532200
2020-03-17 23:59:00+00:00  0.85304  0.85369  0.85301  0.85326        0   2.955665  0.458536
2020-03-18 00:00:00+00:00  0.85326  0.85331  0.85309  0.85313        0   7.469880  1.158687
```

**Comment by twopirllc** [comment]
Hello @putraxor,

Thanks for using **Pandas TA**!

Added to the queue.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @putraxor,

While your original code on the surface looks correct, **vidya** actually relies on a prior value to calculate it's current value. Unfortunately ```df.vidya.shift(1)``` is just _zeros_ so it zeros the second term in the _vidya_ calculation column.
```python
# ...
df['vidya'] = 0
df['vidya'] = (df.close * alpha * df.cmo) + (1 - alpha * df.cmo) * df.vidya.shift(1)
# is equivalent to:
# df['vidya'] = df.close * alpha * df.cmo
# since df.vidya.shift(1) = [NaN, 0, ..., 0]
```

To get it working, first set **cmo**'s keyword argument ```scalar=1```  as it defaults to _100_ and then you will create a _for_ loop to effectively capture the prior **vidya** value.
```python
abs_cmo = ta.cmo(df.close, length=p, scalar=1, talib=False).abs()
vidya_ = pd.Series(0, index=df.index)
for i in range(length, m):
    vidya_.iloc[i] = alpha * abs_cmo.iloc[i] * df.close.iloc[i] + vidya_.iloc[i - 1] * (1 - alpha * abs_cmo.iloc[i])
```

In any case, I will have **vidya** on the _development_ branch for you to test in a couple of days. After I put it up, it can be installed like so:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Hope this helps!

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @putraxor,

So **vidya** is available on the latest release:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Let me know how it is working for you. Thanks for your patience.

Regards,
KJ

**Comment by putraxor** [comment]
thank you very much, you are awesome

**Comment by twopirllc** [comment]
Thanks for using **Pandas TA**!
