### ISSUE TITLE
NameError: name 'watchlist' is not defined

### ISSUE THREAD

**Issue by ravijvora** [twopirllc/pandas-ta#139]
NameError: name 'watchlist' is not defined
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**

**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @ravijvora,

So you got the following error: ```NameError: name 'watchlist' is not defined``` How did you get it? What did you do? Do you have any source code leading up to and including the error? Do you have a screenshot of the code and the error? Do you have any additional context to help to help you? Why did you not answer the questions?

So please answer them **soon** before I close issue.

1. **Which version are you running?** Run the following to find out and tell me.
```python
import pandas_ta as ta
print(ta.version)
```
1. **To Reproduce**
Where is the code?

1. **Screenshots**
Show me! Give me something to figure it out.

Regards,
KJ

**Comment by ravijvora** [comment]
![Untitled17 - Jupyter Notebook - Google Chrome 9_30_2020 8_03_04 PM](https://user-images.githubusercontent.com/70810494/94699532-06bd3280-0358-11eb-9d4e-cff77af9f281.png)

**Comment by ravijvora** [comment]
![Untitled17 - Jupyter Notebook - Google Chrome 9_30_2020 8_10_21 PM](https://user-images.githubusercontent.com/70810494/94700409-0d987500-0359-11eb-9ab0-d9cf681a1f2c.png)

**Comment by ravijvora** [comment]
![Untitled17 - Jupyter Notebook - Google Chrome 9_30_2020 8_11_16 PM](https://user-images.githubusercontent.com/70810494/94700486-22750880-0359-11eb-9c11-ff72e8e0a99f.png)

**Comment by ravijvora** [comment]
pls help 
I want to learn pandas ta

**Comment by ravijvora** [comment]
![stocks-practice - Jupyter Notebook - Google Chrome 9_30_2020 7_13_15 PM (2)](https://user-images.githubusercontent.com/70810494/94700713-6b2cc180-0359-11eb-8d39-24f2baaa412b.png)

**Comment by ravijvora** [comment]
this is my one more error pls guide

**Comment by twopirllc** [comment]
@ravijvora,

You are running the last stable version from pip. You should upgrade to the latest version.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Then we can go from there.

**Comment by ravijvora** [comment]
![Uploading Untitled17 - Jupyter Notebook - Google Chrome 9_30_2020 10_30_05 PM.png…]()

**Comment by ravijvora** [comment]
Collecting git+https://github.com/twopirllc/pandas-ta
  Cloning https://github.com/twopirllc/pandas-ta to c:\users\lenovo\appdata\local\temp\pip-req-build-7j0dj3ks
Note: you may need to restart the kernel to use updated packages.
  Running command git clone -q https://github.com/twopirllc/pandas-ta 'C:\Users\LENOVO\AppData\Local\Temp\pip-req-build-7j0dj3ks'
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/twopirllc/pandas-ta 'C:\Users\LENOVO\AppData\Local\Temp\pip-req-build-7j0dj3ks'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by twopirllc** [comment]
If you do not have git installed, download zip.

<img width="351" alt="Screen Shot 2020-09-30 at 10 26 47 AM" src="https://user-images.githubusercontent.com/18198392/94719094-8b339500-0307-11eb-9e50-1cbc0e39be7e.png">

Unzip in your project directory. It should have content. The ```watchlist``` is in the _examples_ directory.

<img width="460" alt="Screen Shot 2020-09-30 at 10 33 21 AM" src="https://user-images.githubusercontent.com/18198392/94719769-73a8dc00-0308-11eb-8cdf-dba9a4830c0a.png">


Then install **Pandas TA** locally with pip. See if it is installed in pip too.

```sh
C:\Users\LENOVO\..\project > pip install -e panda-ta-master
C:\Users\LENOVO\..\project > pip list
```

Keep me posted.

Thanks,
KJ

**Comment by twopirllc** [comment]
You might also want to check Anaconda help on how to install packages locally by downloading the code.

The pip version will be updated by the weekend. But this is a good exercise in case other packages need to be installed manually.

**Comment by ravijvora** [comment]
![Untitled10 - Jupyter Notebook - Google Chrome 10_1_2020 12_04_26 AM](https://user-images.githubusercontent.com/70810494/94725683-c9699c80-0379-11eb-9d11-3e5c1e837484.png)

**Comment by ravijvora** [comment]
thanks for pandas ta updated but watchlist show error

**Comment by twopirllc** [comment]
Look in the ```examples\watchlist.py``` file and see if it is there.

**Comment by twopirllc** [comment]
Try:

```python
from examples.watchlist import Watchlist, colors
```

**Comment by twopirllc** [comment]
Also in a Jupyter Notebook, in a cell if you type: ```import <tab><tab>``` where ```<tab>``` is the _tab key_, you will get a list of _modules_ and _packages_ (since your importing) in your environment.

<img width="411" alt="Screen Shot 2020-09-30 at 12 59 18 PM" src="https://user-images.githubusercontent.com/18198392/94733800-297e2580-031d-11eb-8cb3-9b9215cf98f8.png">
<img width="377" alt="Screen Shot 2020-09-30 at 12 59 35 PM" src="https://user-images.githubusercontent.com/18198392/94733804-2c791600-031d-11eb-81c7-35afca043f88.png">

You can even do it to see what's in a _module_/_package_:

<img width="357" alt="Screen Shot 2020-09-30 at 1 03 43 PM" src="https://user-images.githubusercontent.com/18198392/94734061-7feb6400-031d-11eb-9d8b-f4ad75ce3bc9.png">

Hope this helps!

**Comment by ravijvora** [comment]
its 

> Try:
> 
> ```python
> from examples.watchlist import Watchlist, colors
> ```

its work 

thanks

**Comment by twopirllc** [comment]
Excellent!

Thanks for the response.

Regards,
KJ

**Comment by prajwalshrestha381** [comment]
> its
> 
> > Try:
> > ```python
> > from examples.watchlist import Watchlist, colors
> > ```
> 
> I had the same issue, so I followed the instructions in this thread all the way to "from examples.watchlist import Watchlist, colors", but it still shows error
 please advise  
<img width="1792" alt="Screen Shot 2020-12-20 at 7 43 01 PM" src="https://user-images.githubusercontent.com/17186964/102728902-4151be00-42fc-11eb-8a05-5cc791ec516e.png">
<img width="1792" alt="Screen Shot 2020-12-20 at 7 43 38 PM" src="https://user-images.githubusercontent.com/17186964/102728924-59c1d880-42fc-11eb-9451-4eb11be57db4.png">
<img width="1616" alt="Screen Shot 2020-12-20 at 7 44 04 PM" src="https://user-images.githubusercontent.com/17186964/102728946-7100c600-42fc-11eb-9c6e-f7c069d7b026.png">

**Comment by twopirllc** [comment]
Hello @prajwalshrestha381,

Upon reexamining this Issue, I realized that I was not clear in the Example Notebooks that ```watchlist.py``` is a standalone module and is not part of Pandas TA. But it does come with Pandas TA but is is also _experimental_. The easiest way to use it is copy the file somewhere local to your project folder and import it that way.

I will update the Notebook to remind users to copy ```watchlist.py``` locally with the next version.

Hope this helps! Let me know if that works.

Thanks,
KJ

**Comment by prajwalshrestha381** [comment]
it worked man, thanks :)

`import sys
sys.path.append('/Users/plutus/Desktop/Data/watchlist.py')`

**Comment by twopirllc** [comment]
Awesome!

Thanks for keeping me posted.
