### ISSUE TITLE
Trades returned by trend_return shifted in wrong direction?

### ISSUE THREAD

**Issue by chrishuygens** [twopirllc/pandas-ta#144]
**Which version are you running?** 
`0.2.20b0`

**Describe the bug**
Either I did not quite get the concept of `trend_return` or something with the returned trades is wrong: When comparing the trades with the given `long`-values, the returned trade values seem to be shifted in the wrong direction.

I made a very trivial example (plot and code below) in order to illustrate my point: The strategy goes long from day 8 to day 14. These long values are fed into `trend_return` and the results are shown in the bottom subplot. The returned trades indicated by the red dashed lines are on day 9 (buy) and 16 (sell). But in order to be in the market at day 8 and out of market at day 15, there should rather be a buy at day 7 and a sell on day 14 as indicated by the black dashed lines.

Maybe line 46 in `pandas_ta/performance/trend_return.py` is the reason for this strange behaviour?
```python
        f"{_props}_Trades": trends.diff().shift(1).fillna(0).astype(int),
```
Changing `shift(1)` to `shift(-1)` yields the behavior I am expecting.

Regards Daniel

**Screenshots**
[trend_return_example.pdf](https://github.com/twopirllc/pandas-ta/files/5333958/trend_return_example.pdf)

**To Reproduce**
```python
import numpy as np
import pandas as pd
import pandas_ta as ta
import matplotlib.pyplot as plt
print(ta.version)

# generate random data for illustration
np.random.seed(0)
length = 20
close = pd.Series(4 + np.random.random(length) + np.cos(np.linspace(0, 3*np.pi, length)))

# define long intervals
slow_sma = ta.sma(close, 5)
fast_sma = ta.sma(close, 2)
long = fast_sma > slow_sma

# calculate cumulated trend return
trendy = ta.trend_return(close=close, trend=long, log=True, cumulative=True)

# plot result
fig, axs = plt.subplots(nrows=3, ncols=1, squeeze=False, figsize=(8, 8))

axs[0, 0].set_title("Example data and indicators")
axs[0, 0].plot(close, marker=".", label="close")
axs[0, 0].plot(slow_sma, marker=".", label="slow_sma")
axs[0, 0].plot(fast_sma, marker=".", label="fast_sma")

axs[1, 0].set_title("Long position according to trivial strategy")
axs[1, 0].plot(long, marker=".", label="long")

axs[2, 0].set_title("Results of ta.trend_return")
trendy.plot(ax=axs[2, 0], marker=".", xlabel="Day")

for ax in axs.flatten():
    for x in trendy.index[trendy.CLTR_Trades != 0]:
        ax.axvline(x=x, color="r", linestyle=":")
        ax.axvline(x=x-2, color="k", linestyle=":")
    ax.legend(loc=3)
    ax.set_xticks(np.linspace(0, 20, 11))
fig.set_tight_layout(True)
fig.savefig("trend_return_example.pdf", bbox_inches="tight")
```

**Comment by twopirllc** [comment]
Hello @chrishuygens,

Ahh yes! Thank you for finding this careless mistake (bug) and providing me with a detailed and convincing analysis.

I have decided to put in a ```trade_offset``` parameter that defaults to -1. That way the user can shift it according to their needs. So line 46 will look like:
```python
f"{_props}_Trades": trends.diff().shift(trade_offset).fillna(0).astype(int)
```

Thanks for using **Pandas TA** and please drop a :star: if you find it useful.

Thanks,
KJ

**Comment by chrishuygens** [comment]
Hi  @twopirllc,

thank you so much for your blazing fast fix!

Daniel
