### ISSUE TITLE
module not found error: dataclasses

### ISSUE THREAD

**Issue by fonzmeister** [twopirllc/pandas-ta#146]
I wanted to try this library, but I get an import error 

I just installed the latest version (not the stable) on my ubuntu server and windows machine and they give the same error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "###/bot/lib/python3.6/site-packages/pandas_ta/__init__.py", line 96, in <module>
    from pandas_ta.core import *
  File "####/bot/lib/python3.6/site-packages/pandas_ta/core.py", line 2, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'

```

**Comment by twopirllc** [comment]
Hello @fonzmeister,

Dataclasses were implemented in Python 3.7. So I recommend using Python 3.7 or greater.

Please let me know how that works out for you and when you get Pandas TA installed.

Thanks,
KJ

**Comment by fonzmeister** [comment]
ah sorry, that was it. Upgraded python and it all works. Thanks

**Comment by twopirllc** [comment]
@fonzmeister,

Excellent! Thanks for keeping me informed.

Regards,
KJ

**Comment by mklosi** [comment]
@twopirllc   Is there a previous version of "pandas_ta" that works with py36? The issue is that I have a constraint on the versions of python I can use. I'm stuck on 3.6.9 for the time being.

**Comment by twopirllc** [comment]
Hello @mklosi,

You can download the code of [**Pandas TA** v _0.1.75b_](https://github.com/twopirllc/pandas-ta/tree/7e36ac1ded2e21a5096111e36b8f265f7d6b0f57). The is the last version prior to Python 3.7s ```dataclass``` was implemented.

Hope this helps!

If you find the library useful or easy to use, I would appreciate a :star:.

Regards,
KJ
