### ISSUE TITLE
How to use squeeze with conventional 

### ISSUE THREAD

**Issue by punno** [twopirllc/pandas-ta#147]
How to use squeeze with conventional and candle data , OPEN ,MAX,MIN ,CLOSE /Thankyou

**Comment by twopirllc** [comment]
Hello @punno,

By conventional, do you mean John Carter's version? Do you have any code that you have done so far?

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @punno,

I would like to help you, so could you provide some code that you have tried so I know how you are using the library.

If this continues to remain unanswered, I will be closing this issue out in a few days.

Regards,
KJ
