### ISSUE TITLE
Ehlers Super Smoother Filter

### ISSUE THREAD

**Issue by DrPaprikaa** [twopirllc/pandas-ta#148]
Hi @twopirllc,

Could it be possible to add the [Ehlers Super Smoother Filter](https://www.tradingview.com/script/VdJy0yBJ-Ehlers-Super-Smoother-Filter/) indicator ?

I quickly tried implementing it in Python but I'm lost in the conversion. I guess it should be quick to translate !

Thanks,
DrPaprikaa

**Comment by twopirllc** [comment]
Hey @DrPaprikaa,

It's now on the list. However, I have some other projects that have fallen by the wayside that I have to get up to speed so it may take a little while.

Regards,
KJ

**Comment by twopirllc** [comment]
Hey @DrPaprikaa,

I plan to work on this this week. It seems there are two versions, with 2 poles and 3 poles. I will default to 2 poles version first and get that up as soon as I can before adding the 3 poles version if that is ok with you.

Hope all is well and I appreciate your patience.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hi @DrPaprikaa,

So _Ehler's Super Smoother Filter_ (**ssf**) is now up on the _development_ branch if you want to play with it before I push it to the _master_ branch. Let me know what you think.

Thanks,
KJ

**Comment by twopirllc** [comment]
@DrPaprikaa,

> Thank you a lot for your work ! I tested the indicator with my use-cases, it seems to work properly.

No worries. I am glad that it is working as intended. 😄 

> I suggest adding a bit of info about what the poles are in the indicator's help if that's not too much trouble, it will help understand what it does.

Yeah. I will have to make something up because there is not much literature by Ehler or others that I could initially find regarding the poles. I will put it on _master_ soon.

Best regards,
KJ

**Comment by twopirllc** [comment]
@DrPaprikaa,

Ok it's ready on _master_. Thanks for your patience.

KJ
