### ISSUE TITLE
Question: Example of Heikin-Ashi candle

### ISSUE THREAD

**Issue by mtvu** [twopirllc/pandas-ta#154]
Hi Kevin, 

Thanks for pandas_ta. Just wondering if you could provide examples of using  HA candle in a strategy. My strategy uses HA and EMA to determine the state of a stock for trading

Thanks,

**Comment by twopirllc** [comment]
Hello @mtvu,

Sure. I'll draft an example soon.

Thanks,
KJ

**Comment by twopirllc** [comment]
@mtvu,

Here is a simple way to convert to HA and then process TA on the HA candles.
1. Create the HA candles and append them to the df
1. Rename the original columns with *OG_* prefix and rename *HA_* prefixes to standard "ohlc".
1. Then process TA as normal
1. Chart as a visual verification

```python
df.ta.ha(append=True)
ha_ohlc = {
    "open": "OG_open", "high": "OG_high", "low": "OG_low", "close": "OG_close",
    "HA_open": "open", "HA_high": "high", "HA_low": "low", "HA_close": "close"
}
df.rename(columns=ha_ohlc, inplace=True)
df.ta.ema(append=True)
df[["close", "EMA_10"]].tail(252).plot(figsize=(16,8), color=["black", "blue"], grid=True)
```

Hope this helps!

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @mtvu,

I hope this has this worked for you. Or did you have something else in mind?

Regards,
KJ

**Comment by mtvu** [comment]
Thanks Kevin. The example is very useful. I'm trying to build something similar to this feature from TradeStation  http://help.tradestation.com/10_00/eng/tradestationhelp/rs/about_radarscreen.htm.  With pandas_ta, I can create a column in a df using multiple indicators and produce a signal to Buy or Sell.

**Comment by twopirllc** [comment]
@mtvu 

Great! Yeah a Radar/Scanner is a needed component for any trader/investor.

> With pandas_ta, I can create a column in a df using multiple indicators and produce a signal to Buy or Sell.

Have you built one already or in the process? If in process, the [Watchlist Class](https://github.com/twopirllc/pandas-ta/blob/master/examples/watchlist.py)(watchlist.py) in ```examples/``` while still in _development_, might have some useful code to help you build it. Essentially the **Watchlist** can load/download financial market data and automatically apply Technical Analysis indicators with a Pandas TA Strategy. You will have to modify the data source to get it to work with your data. When using HA candles, remember to rename the columns like above before apply TA.

Would be interested in what you come up with.

Regards,
KJ

**Comment by mtvu** [comment]
Here is a simple strategy with the HA candle. I used watchlist to bulk download data. I don't know how to use Strategy with HA candle so I stick with the classic data frame approach. 

I also have a look at the Strategy Examples notebook but I don't know how to do a proper backtest with pandas_ta yet. I guess it might not be your intention to make pandas_ta a full-fledge backtest package. 

```
from pandas_datareader import data
from IPython.display import display, HTML
import pandas as pd
import datetime

start = datetime.datetime(1900, 1, 1)
end = datetime.datetime.now()
ticker = "AAPL"
df = data.DataReader(ticker, 
                       start=start, 
                       end=end, 
                       data_source='yahoo')
df.ta.ha(append=True)
ha_ohlc = {
    "open": "OG_open", "high": "OG_high", "low": "OG_low", "close": "OG_close",
    "HA_open": "open", "HA_high": "high", "HA_low": "low", "HA_close": "close"
}

df.rename(columns=ha_ohlc, inplace=True)
df.ta.ema(length=21, append=True)
df.ta.atr(append=True)


def trade(row):
    #Buy on Green HA candle when close price crosses EMA21
    if (row['close'] - row['EMA_21']) >= 0.01 and row['close'] > row['open'] :
       return "BUY AT {} | STOP LOSS {}".format(row['close'], row['close'] - row['ATR_14']*1.5 )
       
    # Sell on Red HA candle when close price crosses EMA21
    if (row['close'] - row['EMA_21']) <= -0.01 and row['close'] < row['open']:
       return "SELL AT {} | STOP LOSS {}".format(row['close'], row['close'] + row['ATR_14']*1.5 )
    
df = df[["open","close","EMA_21","ATR_14"]].tail(200)
df['SIGNAL'] = df.apply(trade, axis=1)

display(HTML(df.tail(200).to_html()))
df[["close", "EMA_21"]].tail(252).plot(figsize=(16,8), color=["black", "blue"], grid=True)
```

**Comment by twopirllc** [comment]
> I used watchlist to bulk download data. I don't know how to use Strategy with HA candle so I stick with the classic data frame approach.

Yeah, you will have to modify your copy of ```watchlist.py``` to include _pandas_datareader_ (at line 187) as a data source as well as add an kwarg option to switch to HA before applying the TA.
```python
class Watchlist(object):
   # ...

   def load(self, ticker: str = None, tf: str = None, index: str = "date",
        drop: list = [], plot: bool = False, **kwargs) -> pd.DataFrame:
        # ...

        # Add pandas_datareader call

        # Remove select columns
        df = self._drop_columns(df, drop)

        # Add lines like these
        if kwargs.pop("ha", False):
            df.ta.ha(append=True)
            ha_ohlc = {
                "open": "OG_open", "high": "OG_high", "low": "OG_low", "close": "OG_close",
                "HA_open": "open", "HA_high": "high", "HA_low": "low", "HA_close": "close"
            }
            df.rename(columns=ha_ohlc, inplace=True)

        if kwargs.pop("analyze", True):
            if self.debug: print(f"[+] TA[{len(self.strategy.ta)}]: {self.strategy.name}")
            df.ta.strategy(self.strategy, timed=self.timed, **kwargs)
```
Once you modify your ```watchlist.py```, then you can do something _like_ the following:
```python
ema_atr = ta.Strategy(name="EMA + ATR", ta=[{"kind": "ema", "length": 21}, {"kind": "atr"}])
radar = Watchlist(["SPY", "IWM"], timed=False)
# Load custom_a into Watchlist and verify
radar.strategy = ema_atr
print(watch.strategy)
radar.load(ha=True, verbose=True)
```

Now that we are discussing this, I will incorporate the HA kwarg option in ```watchlist.py``` as soon as I am able. But for now, that should hopefully get you started.

#### Pandas TA Strategies

Pandas TA Strategies let you create a collection of TA indicators that you frequently use and bulk processes them with multiprocessing.

#### Pandas TA Backtesting

Yes _Pandas TA_ is not a full fledged Backtester, but does have some Backtesting Metrics such as: _cagr_, _calmar_ratio_, _downside_deviation_, _jensens_alpha_, _log_max_drawdown_, _max_drawdown_, _pure_profit_score_, _sharpe_ratio_, _sortino_ratio_, and _volatility_ which only return a singular value. The Metric functions are located in [utils/_metrics.py](https://github.com/twopirllc/pandas-ta/blob/master/pandas_ta/utils/_metrics.py). It also has _drawdown_ "indicator" which returns a series like any other indicator in the library. Unfortunately, there is not a lot of documentation regarding Backtesting with _Pandas TA_ as it is still under development.

For example if you wanted the _sortino_ratio_ and _cagr_, you can simply do:
```python
metrics = {
    "Sortino": ta.sortino_ratio(df.close),
    "CAGR": ta.cagr(df.close),
}
print(f"Metrics:\n{json.dumps(metrics, indent=2)}")
```

**Comment by mtvu** [comment]
Thanks Kevin. 

This is my attempt to calculate daily return ( percentage ) for a stock. Could you let me know if this is the right way to use "percent_return".  Just wondering if there is a clean way to calculate Weekly, Montly, YTD return 

```
from pandas_datareader import data
from IPython.display import display, HTML
import pandas as pd
import datetime

start = datetime.datetime(1900, 1, 1)
end = datetime.datetime.now()
ticker = "AAPL"
df = data.DataReader(ticker, 
                       start=start, 
                       end=end, 
                       data_source='yahoo')
df.ta.percent_return(cumulative=False, append=True)
df['PCTRET_1'] = df['PCTRET_1'].apply(lambda x: x*100)  
display(HTML(df.tail(60).to_html()))
```

**Comment by twopirllc** [comment]
@mtvu,

No worries.

> This is my attempt to calculate daily return ( percentage ) for a stock. Could you let me know if this is the right way to use "percent_return".

Looks good.

>  Just wondering if there is a clean way to calculate Weekly, Monthly, YTD return.

Not off the top of my head. But it is a feature I would like to provide. Trying to find time as well as add more Backtesting features, Example Notebooks, and possibly some data generation (stochastics).

You would need to create new DataFrames per period that are resampled from a primary lower time frame. Since we are talking Daily, it would be the primary lower time frame. From the Daily time frame, you resample up to Weekly, Monthly, Quarterly, Annually. Since they are new DataFrames, you can do: 

```python
# ^^ Resampling code above ^^
weekly.ta.percent_return(cumulative=False, append=True)
weeklyPCTRET_1'] = df['PCTRET_1'].apply(lambda x: x*100)
# vv Other higher time frames: Monthly, ... vv
```

There is code out there to do the resampling, but I have not had the time to play with it and see how best to integrate it with Pandas TA. If you have any good ideas or can do it, that would be appreciative.

KJ

**Comment by mtvu** [comment]
I managed to use your sample watchlist code to display the daily stock price with TA indicators. 

'''
import pandas_ta as ta

def recent_bars(dft, tf: str = "1y"):
    # All Data: 0, Last Four Years: 0.25, Last Two Years: 0.5, This Year: 1, Last Half Year: 2, Last Quarter: 4
    yearly_divisor = {"all": 0, "10y": 0.1, "5y": 0.2, "4y": 0.25, "3y": 1./3, "2y": 0.5, "1y": 1, "6mo": 2, "3mo": 4}
    yd = yearly_divisor[tf] if tf in yearly_divisor.keys() else 0
    return int(ta.RATE["TRADING_DAYS_PER_YEAR"] / yd) if yd > 0 else dft.shape[0]

def add_pandas_ta(tickers):
    
    ema_atr = ta.Strategy(name="EMA + ATR", ta=[{"kind": "ema", "length": 21}, {"kind": "atr"}])
    radar = Watchlist(tickers, timed=False)
    radar.strategy = ema_atr
    radar.load(tickers, analyze=True, verbose=False)

    df_list = []
    duration = "3mo"
    for ticker in tickers:
           
            recent = recent_bars(radar.data[ticker], duration)
            temp_df = radar.data[ticker].copy().tail(recent)
            today = temp_df.iloc[[ -1]]
            today.drop(columns=['Unnamed: 0'], axis=1, inplace=True)   
            today.insert(0, 'ticker', ticker)           
            df_list.append(today)

    return pd.concat(df_list)

tickers = ["SPY", "UVXY", "TLT", "GLD"]
today_df = add_pandas_ta(tickers)
display(HTML(today_df.to_html()))

'''

**Comment by twopirllc** [comment]
Looks good!
