### ISSUE TITLE
Using new Strategy class: SMA not properly calculated?

### ISSUE THREAD

**Issue by sh39sxn** [twopirllc/pandas-ta#157]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.2.24b0

**Describe the bug**
I was trying the playbook from https://github.com/twopirllc/pandas-ta/blob/master/examples/PandasTA_Strategy_Examples.ipynb
using the Stock Apple (AAPL).

**To Reproduce**
```python
import datetime as dt
import pandas as pd
import pandas_ta as ta
from alphaVantageAPI.alphavantage import AlphaVantage  # pip install alphaVantage-api
from watchlist import Watchlist


AllStrategy = ta.AllStrategy
print("name =", AllStrategy.name)
print("description =", AllStrategy.description)
print("created =", AllStrategy.created)
print("ta =", AllStrategy.ta)

custom_a = ta.Strategy(name="MyStrategy", ta=[{"kind": "sma", "length": 50}, {"kind": "sma", "length": 200}])
print(custom_a)

AV = AlphaVantage(
    api_key="XXXX", premium=False,
    output_size='full', clean=True,
    export_path=".", export=True
)
#print(AV)

watch = Watchlist(["AAPL"], timed=False)
#print(watch)

watch.load(verbose=True)

#print(watch.data["AAPL"])

watch.strategy = custom_a
print(watch.strategy)

print(watch.load("AAPL"))

df = pd.DataFrame()
print(df.ta.indicators())

```

**Expected behavior**
I compared the results for SMA 50 and SMA 200 from console output (see screenshot below) with SMA 50 and SMA 200 from yahoo finance (https://finance.yahoo.com/quote/AAPL/chart?p=AAPL#eyJpbnRlcnZhbCI6ImRheSIsInBlcmlvZGljaXR5IjoxLCJ0aW1lVW5pdCI6bnVsbCwiY2FuZGxlV2lkdGgiOjgsImZsaXBwZWQiOmZhbHNlLCJ2b2x1bWVVbmRlcmxheSI6dHJ1ZSwiYWRqIjp0cnVlLCJjcm9zc2hhaXIiOnRydWUsImNoYXJ0VHlwZSI6ImxpbmUiLCJleHRlbmRlZCI6ZmFsc2UsIm1hcmtldFNlc3Npb25zIjp7fSwiYWdncmVnYXRpb25UeXBlIjoib2hsYyIsImNoYXJ0U2NhbGUiOiJsaW5lYXIiLCJzdHVkaWVzIjp7IuKAjHZvbCB1bmRy4oCMIjp7InR5cGUiOiJ2b2wgdW5kciIsImlucHV0cyI6eyJpZCI6IuKAjHZvbCB1bmRy4oCMIiwiZGlzcGxheSI6IuKAjHZvbCB1bmRy4oCMIn0sIm91dHB1dHMiOnsiVXAgVm9sdW1lIjoiIzAwYjA2MSIsIkRvd24gVm9sdW1lIjoiI2ZmMzMzYSJ9LCJwYW5lbCI6ImNoYXJ0IiwicGFyYW1ldGVycyI6eyJ3aWR0aEZhY3RvciI6MC40NSwiY2hhcnROYW1lIjoiY2hhcnQifX0sIuKAjG1h4oCMICg1MCxDLG1hLDApIjp7InR5cGUiOiJtYSIsImlucHV0cyI6eyJQZXJpb2QiOjUwLCJGaWVsZCI6IkNsb3NlIiwiVHlwZSI6InNpbXBsZSIsIk9mZnNldCI6MCwiaWQiOiLigIxtYeKAjCAoNTAsQyxtYSwwKSIsImRpc3BsYXkiOiLigIxtYeKAjCAoNTAsQyxtYSwwKSJ9LCJvdXRwdXRzIjp7Ik1BIjoiI2FkNmVmZiJ9LCJwYW5lbCI6ImNoYXJ0IiwicGFyYW1ldGVycyI6eyJjaGFydE5hbWUiOiJjaGFydCJ9fX0sInBhbmVscyI6eyJjaGFydCI6eyJwZXJjZW50IjoxLCJkaXNwbGF5IjoiQUFQTCIsImNoYXJ0TmFtZSI6ImNoYXJ0IiwiaW5kZXgiOjAsInlBeGlzIjp7Im5hbWUiOiJjaGFydCIsInBvc2l0aW9uIjpudWxsfSwieWF4aXNMSFMiOltdLCJ5YXhpc1JIUyI6WyJjaGFydCIsIuKAjHZvbCB1bmRy4oCMIl19fSwic2V0U3BhbiI6e30sImxpbmVXaWR0aCI6Miwic3RyaXBlZEJhY2tncm91bmQiOnRydWUsImV2ZW50cyI6dHJ1ZSwiY29sb3IiOiIjMDA4MWYyIiwic3RyaXBlZEJhY2tncm91ZCI6dHJ1ZSwiZXZlbnRNYXAiOnsiY29ycG9yYXRlIjp7ImRpdnMiOnRydWUsInNwbGl0cyI6dHJ1ZX0sInNpZ0RldiI6e319LCJzeW1ib2xzIjpbeyJzeW1ib2wiOiJBQVBMIiwic3ltYm9sT2JqZWN0Ijp7InN5bWJvbCI6IkFBUEwiLCJxdW90ZVR5cGUiOiJFUVVJVFkiLCJleGNoYW5nZVRpbWVab25lIjoiQW1lcmljYS9OZXdfWW9yayJ9LCJwZXJpb2RpY2l0eSI6MSwiaW50ZXJ2YWwiOiJkYXkiLCJ0aW1lVW5pdCI6bnVsbCwic2V0U3BhbiI6e319XX0-)

Unfortunately the results were very differently.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/17112364/98288336-004d5680-1fa7-11eb-9f0d-6c77a7e26510.png)

For example:
11/04/2020 SMA 50:
pandas-ta calculates 138.9455 but yahoo finance calculates values between 110-115

**Additional context**
How can these different values happen?

In the example code above: SMA 50 is calculated for each day. That means calculation per hour is not possible? If yes what needs to be changed? In Yahoo I can the SMA values in the same detail level as the stock price itself.

FYI:
My goal is to calculate trends during short timeframes (1-2 hours).

Thanks for your help!

**Comment by twopirllc** [comment]
Hello @sh39sxn,

> Unfortunately the results were very differently.

Yes, your results will vary when you compare apples with oranges, in this case Yahoo Finance (YF) Data and AlphaVantage (AV) Data. When comparing Yahoo Finance Data with AlphaVantage below, one does not need to run a correlation test to determine that the data sets are incongruent: ```open != open```, ```high != high```, ... , ```volume != volume``` and ```adj close != adj_close```. However, that does not imply that **ta.sma** is incorrect either. In fact **ta.sma** is correlated with the _de facto_ TA Lib and other common TA libraries.

```python
import datetime
import pandas as pd
from pandas_datareader import data
import alphaVantageAPI as AV
import pandas_ta as ta

# YFinance Data (Adjusted Data) + Clean + SMA50
start, end = datetime.datetime(1900, 1, 1), datetime.datetime.now()
ticker = "AAPL"
aapl_yf = data.DataReader(ticker, start=start, end=end, data_source='yahoo')
aapl_yf.columns = aapl_yf.columns.str.lower()
aapl_yf = aapl_yf.tail(5289).copy() # 10061 rows
aapl_yf.drop(aapl_yf.tail(1).index, inplace=True) # Remove Current Date so it matches the same Dates with AV
aapl_yf.ta.sma(close="adj close",length=50, append=True) # Apply SMA 50 using Adjusted Close to match AV

# AV Data + SMA50 (Adjusted Close)
av = AV.AlphaVantage(api_key="XXXX", premium=False, output_size='full', clean=True, export_path=".", export=False)
aapl_av = av.data(ticker, "DA")
aapl_av.drop(columns=["dividend", "split_coefficient"], inplace=True)
aapl_av.ta.sma(close="adj_close", length=50, append=True) # Apply SMA 50 using Adjusted Close to match YF

adj_data_corr = aapl_yf['adj close'].corr(aapl_av['adj_close'])
data_corr = aapl_yf['SMA_50'].corr(aapl_av['SMA_50'])
print(f"\nYF vs AV Adjusted Close Correlation: {100 * adj_data_corr:.2f}% [{adj_data_corr}]")
print(f"YF vs AV Adjusted SMA 50 Correlation: {100 * data_corr:.2f}% [{data_corr}]")
```

<img width="619" alt="Screen Shot 2020-11-05 at 2 45 56 PM" src="https://user-images.githubusercontent.com/18198392/98304878-aa13ef80-1f75-11eb-8eec-af69caa4a1cf.png">

Despite the _minor_ differences between the "adj close"s between the datasets, the SMA 50 between the two are nearly 100% correlated.

Hope this helps and clears up the confusion.

Regards,
KJ

**Comment by twopirllc** [comment]
Hi @sh39sxn,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Thanks,
KJ
