### ISSUE TITLE
Question: just want to know why drawdown doesn't in the default strategy

### ISSUE THREAD

**Issue by tangxianrong** [twopirllc/pandas-ta#158]

**Comment by twopirllc** [comment]
Hello @tangxianrong,

Well _drawdown_ is new to **Pandas TA** so it was not incorporated into ta.CommonStrategy. Common Strategy is mainly composed of the indicators that are usually presented on many Financial News TV Networks and _drawdown_ is not among them. What's more important is not the Common Strategy, but creating your own Pandas Strategy with the indicators that you commonly use.

Regards,
KJ
