### ISSUE TITLE
use strategy to get Signals - line cross checking

### ISSUE THREAD

**Issue by hamedf62** [twopirllc/pandas-ta#159]
**Which version are you running? The lastest version is Github. Pip is for major releases.**
0.2.26b0

**Is your feature request related to a problem? Please describe.**
i need to get signals (ENTER _ EXIT) for different strategies, by check if cross happen based on different condition. for example if Tenkan crosses Kijun in Ichimoku. indeed have done it myself by adding previous row as lag by shift. but seeking if there is more efficient way. indeed i don't have issue to do same for Backtesting but main problem is efficient way for many indicators of mix strategy,
i need to run cross checking for multiple indicators in same time, something like Technical Analysis in Tradingview.com which shows signals to enter or exit for different timeframes.

**Describe the solution you'd like**
know you have _signal.py which do the same but never seen and example or manual.

Thank you for the Fast and Reliable package

**Comment by twopirllc** [comment]
Hello @hamedf62,

Thanks for using **Pandas TA**! Glad you find it useful!

Other than **ichimoku,** what other indicators are you using?

Considering your example case, **ichimoku** and that you just want the Entries/Exits, you can try *trend_return*. This is similar to what has been done in this [Example Notebook](https://github.com/twopirllc/pandas-ta/blob/master/examples/AIExample.ipynb):

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pandas_ta as ta

years = 1
k_bars = years * ta.RATE["TRADING_DAYS_PER_YEAR"]

df = # your ohlcv data
# Tenkan crosses above Kijun -> long trend
tenkan, kijun = currentdf[currentdf.columns[2]], currentdf[currentdf.columns[3]]
tenkan_xa_kijun = tenkan > kijun

# Column Reduction
recentdf = pd.concat([df.close, tenkan, kijun], axis=1, sort=True)

# Calculate the Trend Return of Tenkan crosses Kijun to get the Entries and Exits of the Trades
# TR appends DataFrame Columns: CumLogReturn, TR_LogReturn, CumLogReturn Trends, CumLogReturn Trades
recentdf.ta.trend_return(trend=tenkan_xa_kijun, cumulative=True, log=False, append=True)

chartdf = recentdf.copy()
return_cols = list(recentdf.columns[3:5])
chartdf.drop(return_cols, axis=1, inplace=True, errors="ignore")

# Create Entries
entries = (chartdf.iloc[:,-1] > 0).astype(int) * chartdf.close
entries[entries < 0.0001] = np.nan
entries.name = "Entry"

# Create Exits
exits = (chartdf.iloc[:,-1] < 0).astype(int) * chartdf.close
exits[exits < 0.0001] = np.nan
exits.name = "Exit"

total_trades = chartdf.iloc[:,-1].abs().sum()

all_trades = chartdf.iloc[:,-1].copy().fillna(0)
all_trades = all_trades[all_trades != 0]
trades = pd.DataFrame({"Signal": all_trades, entries.name: entries.dropna(), exits.name: exits.dropna()})
print(f"Total Trades: {total_trades}")
print(trades)

# Plot Price Chart with Entries (lime) and Exits (red)
price_figsize, sub_figsize = (16, 6.8), (16, 3)
chartdf[chartdf.columns[:3]].plot(figsize=price_figsize, color=["black", "violet", "purple"], title=f"{ticker} Tenkan XA Kinjun", grid=True)
entries.plot(figsize=price_figsize, color=["lime"], marker="^", markersize=12, alpha=0.8)
exits.plot(figsize=price_figsize, color=["red"], marker="v", markersize=12, alpha=0.8, grid=True)

# Plot Returns
returnsdf = recentdf[return_cols]
returnsdf.plot(figsize=sub_figsize, color=["black", "blue"], grid=True, title=f"{ticker} Tenkan XA Kinjun Returns")

# Cumulative Returns
cumreturns = returnsdf[returnsdf.columns[0]].cumsum()
cumreturns.plot(figsize=sub_figsize, kind="area", stacked=False, color=["green"], alpha=0.35, grid=True, title=f"{ticker} Tenkan XA Kinjun Cumulative Returns")
```

> I know you have _signal.py which do the same but never seen and example or manual.

Yes, another user created those methods that he wanted applied to some of the indicators. For example in the source of [**macd**](https://github.com/twopirllc/pandas-ta/blob/master/pandas_ta/momentum/macd.py), [**er**](https://github.com/twopirllc/pandas-ta/blob/286aea7e634e446775fa33816aa8717f5b43dc34/pandas_ta/momentum/er.py), and [**rsi**](https://github.com/twopirllc/pandas-ta/blob/9efd629dda32297f54f6b795faf500b760f3b9fe/pandas_ta/momentum/rsi.py) you can see how he applies the signals to the indicator results and builds the signals from there. I do not use them, I use trends instead for signal generation like above.

Hope this helps!

Regards,
KJ

**Comment by hamedf62** [comment]
> ```python
> currentdf
> ```

Thank you for fast and complete replay. 
trying to run suggested code.
what is "currentdf"? it may referee to indicator dataframe or else? as you used columns 2 & 3 of CURRENTDF.

**Comment by twopirllc** [comment]
@hamedf62,

Oops! Sorry about that! I updated the code above. Hope that works and makes more sense.
Also note that **Ichimoku** is a special case in terms of output for technical indicators. It is one of a couple of indicators that returns two DataFrames.

KJ

**Comment by hamedf62** [comment]
> @hamedf62,
> 
> Oops! Sorry about that! I updated the code above. Hope that works and makes more sense.
> Also note that **Ichimoku** is a special case in terms of output for technical indicators. It is one of a couple of indicators that returns two DataFrames.
> 
> KJ

Thank you, all is well.

in cross calculation shall we consider SHIFT -1 row to check for example lagA<lagB in last record (date) and for current record (date) A>B

how this calculation is possible.

as i understood TA only compare single row values for cross checking.

Regards

**Comment by twopirllc** [comment]
@hamedf62 

Did the code above help? Were you able to plot the charts in a Notebook?

> in cross calculation shall we consider SHIFT -1 row to check for example lagA<lagB in last record (date) and for current record (date) A>B
> how this calculation is possible.

Do you mean, how do you calculate a crossing? This is the standard code for a [**cross**](https://github.com/twopirllc/pandas-ta/blob/515d4297e7209d0a8b49cab8b5fbc7cac90e1bb3/pandas_ta/utils/_signals.py#L75-L79)

```python
def cross(series_a, series_b above= True, asint= True, offset= None, **kwargs):
    # ...
    current = series_a > series_b  # current is above
    previous = series_a.shift(1) < series_b.shift(1)  # previous is below
    # above if both are true, below if both are false
    cross = current & previous if above else ~current & ~previous
    # ...
```

Or are you asking how it is calculated in the *ta.trend_return* method?

> as i understood TA only compare single row values for cross checking.

Not necessarily true. As long as you have numerical values at the current index or in the past, you can compare prior indexes as well. You can _shift_ as much as you need, but that usually is not desirable for a _cross_.

Hope this helps!

Regards,
KJ

**Comment by twopirllc** [comment]
Hello @hamedf62,

I assume by no response that the solution provided was sufficient.
Please ⭐ if you find the library useful.

Thanks,
KJ
