### ISSUE TITLE
Unexpected behavior when computing all pandas_ta indicators on a given dataset

### ISSUE THREAD

**Issue by Pap8** [twopirllc/pandas-ta#160]
**Describe the problem**
First of all, thank you very much for this great package! The unexpected behavior encountered is that after computing pandas_ta indicators on a pandas Dataframe with OHLCV columns and an index of date-time values, we end-up with an empty dataset (no indicators) if we try to remove all kinds of None values from the dataset.

**To Reproduce**

```python
<code for loading data>
...
dataset.columns = [col.lower() for col in list(dataset.columns)]
#dataset columns here: 'open', 'high', 'low', 'close', 'volume'

#here we compute all pandas_ta indicators on the OHLCV columns    
dataset.ta.strategy(verbose=1)
    
##Removing first 300 columns to avoid any kind of None values regards to indicators computed for long periods
dataset = dataset.iloc[300:,:]

#dropping any dataset rows that contain any kind of None value in any column
dataset.dropna(inplace=True,axis=0)

###after the above line we end up with an empty dataset..
......
<more code that is irrelevant to the issue>
```

**Expected behavior**
After computing all pandas_ta indicators and also dropping the first 300 rows to account for indicators that need long periods for their first value to be computed (e.g. EMA200), the expected dataset shall not contain any kind of None values. That would leave us with all pandas-ta indicators for modelling.

**Additional context**
pandas_ta.version = 0.2.23b
python --version = Python 3.8.6
OS: Windows 10

Thank you very much for the help!

**Comment by twopirllc** [comment]
Hello @Pap8,

That's unfortunate! What data source are you using? Would you mind sharing 500 rows via _csv_ with me so I can see what is happening?

Thanks
KJ

**Comment by twopirllc** [comment]
Hello @Pap8,

I assume by no response that you have resolved the issue yourself? If that is the case, please close this _Issue_. If that is incorrect, please provide a _csv_ of 500 rows of _ohlcv_ data so I can help troubleshoot the Issue _with_ you. If neither happens, I will be closing this _Issue_ in a few days.

Regards,
KJ

**Comment by Pap8** [comment]
Hi @twopirlic,

Apologies for the late reply, I have sent you an e-mail (to: appliedmathkj@gmail.com) about the data.

Thanks again,
Pap

**Comment by twopirllc** [comment]
Hello @Pap8,

There is no data attached with the email. Please email the csv attachment of the data when you get a chance.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @Pap8,

Thanks for your patience!

> **Expected behavior**
> After computing all pandas_ta indicators and also dropping the first 300 rows to account for indicators that need long periods for their first value to be computed (e.g. EMA200), the expected dataset shall not contain any kind of None values. That would leave us with all pandas-ta indicators for modelling.

Some indicator columns have _NaN_ values as placeholders so it makes charting simpler. So the code below will _not_ return **all** the indicators for modeling, only a slightly smaller subset. If you need those indicator columns with _NaN_ values, then you need to handle the _NaN_ values on your own prior to calling ```dataset.drop(columns=columns_with_nan, axis=0, inplace=True)``` as mentioned in the code below.

Ok, here is what I have done. Given that the dataset you sent me, let me know if this works.

```python
import pandas as pd
import pandas_ta as ta

dataset = pd.read_csv("data.csv") # get dataset

# Run all available strategies
dataset.ta.strategy(verbose=1)

# Find the first maximum valid row of all the columns
first_valid_loc = dataset.apply(lambda col: col.first_valid_index()).max()
# Then remove rows before the first valid row
dataset = dataset.iloc[first_valid_loc:,:]

# Find dataset columns that contain any kind of NaN value
nan_values = dataset.isna()
nan_columns = nan_values.any()
# columns_with_nan = dataset.columns[nan_columns]#.tolist()
columns_with_nan = list(dataset.columns[nan_columns])
print(f"[i] Columns with NaN [{len(columns_with_nan)}]: {', '.join(columns_with_nan)}")

# Handle NaN values here if you don't want to drop the columns_with_nan
< Fill some NaN values >

# Drop dataset columns that contain any kind of NaN value
dataset.drop(columns=columns_with_nan, axis=0, inplace=True)

print(dataset)
```

Hope this helps!

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @Pap8,

I assume this has solved your issue. If not reopen when ready.

Thanks,
KJ

**Comment by Pap8** [comment]
Hello Kevin,

Hope you've been well.

Thank you very much for the code you have shared, it was really helpful for
me in solving the issue. I can confirm that I don't experience this issue
anymore.

Regards,
Frixos
