### ISSUE TITLE
Good First Issue >> Price Relative Indicator

### ISSUE THREAD

**Issue by twopirllc** [twopirllc/pandas-ta#161]
**Describe the solution you'd like**
Price Relative Indicator
* Takes a _base_ and _other_ Series.
* kwarg: ```unit:bool = False```. When ```True```, toggles whether to have the series start from _one_.
* kwarg: ```invert:bool = False```. Toggles whether to invert or take the reciprocal of the result.

**Describe alternatives you've considered**
[Price Relative Indicator](https://www.tradingview.com/script/MYSXTMq2-Price-Relative-Relative-Strength/)

**Which version are you running?** The lastest.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Is your feature request related to a problem? Please describe.**
Nope

**Additional context**
Good first issue.

**Comment by adgnabro** [comment]
Hey ! I may help on this one. Could you provide more information please ?

**Comment by twopirllc** [comment]
Hello @adgnabro,

That would be great! There is a link in the original post. Hope that helps!

Thanks,
KJ

**Comment by logan-e-dutton** [comment]
Hello! Are you looking for someone to make a function? Or are you looking for something interactive like the link provided in the original post?

**Comment by twopirllc** [comment]
Hello @logan-e-dutton,

> Are you looking for someone to make a function?

Yes. That would be great!

> Or are you looking for something interactive like the link provided in the original post?

Do you know how to do this also? 😎 

Thanks,
KJ

**Comment by logan-e-dutton** [comment]
Hi @twopirllc,

I do not, unfortunately, but I would love to try and create a function for a Price Relative Indicator.
