### ISSUE TITLE
Good First Issue >> Strictly Increasing / Decreasing

### ISSUE THREAD

**Issue by RajeshDhalange** [twopirllc/pandas-ta#162]
Thanks for Pandas-Ta
Can you add a "strictly" boolean parameter to the Increasing / Decreasing function?
Now you are checking the difference between the current value with a length value ie. increasing = close.diff(length) > 0
But I want to check continuous increasing / decreasing condition like 
```python
test_list = [1, 4, 5, 7, 8, 10] 
res = all(i < j for i, j in zip(test_list, test_list[1:])) 
which result True

test_list = [1, 8, 5, 4, 8, 10] 
result = False
```

**Comment by twopirllc** [comment]
Hello @RajeshDhalange,

Thanks for using **Pandas TA**!

I think this is a good idea. Do you want to try and make the changes and submit a Pull Request?

Thanks,
KJ

**Comment by RajeshDhalange** [comment]
Beginner in python if you still want to try I can.

**Comment by RajeshDhalange** [comment]
I tried the following code
```  
    def increasing(close, length=None, asint=True, strictly=False, offset=None, **kwargs):
    # Validate Arguments
    close = verify_series(close)
    length = int(length) if length and length > 0 else 1
    offset = get_offset(offset)

    # Calculate Result
    if strictly:
        increasing = all(i < j for i, j in zip(close[-length:], close[1:]))
    else:
        increasing = close.diff(length) > 0
    
    if asint:
        increasing = increasing.astype(int)
```

Can you help me to how to execute the test which I found in   test_indicator_trend.py file

**Comment by twopirllc** [comment]
@RajeshDhalange 

Code looks good.

To run the test:
```sh
$ python -m unittest -v tests/test_indicator_trend.py
```

If not sure or how to do the test stuff, I can take care of that.

Thanks,
KJ

**Comment by RajeshDhalange** [comment]
Submitted pull request 
Thanks for encouraging

Thanks 

Rajesh

**Comment by twopirllc** [comment]
No worries. Thanks for contributing.

Regards,
KJ
