### ISSUE TITLE
Good First Issue >> Price Volume Rank

### ISSUE THREAD

**Issue by twopirllc** [twopirllc/pandas-ta#163]
**Which version are you running?**
The latest.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
[Price Volume Rank](https://www.fmlabs.com/reference/default.htm)

**Additional context**
Good first issue.

**Comment by GotchaLogic** [comment]
Your shit wasted my time. thanks.

**Comment by twopirllc** [comment]
@GotchaLogic 

Excuse me? What are you talking about?

**Comment by twrobel** [comment]
Which folder should it go to?

**Comment by twopirllc** [comment]
Hello @twrobel,

Good question. Let's keep it simple and put in the _volume_ folder.

Thanks,
KJ
