### ISSUE TITLE
pandas_ta/overlap/ssf default value set to None

### ISSUE THREAD

**Issue by itpmngt** [twopirllc/pandas-ta#165]
Hi

In `pandas_ta/overlap/ssf.py` the `offset' default value is set to None, but it should be '0' - as later it checks if 0

```    # Offset
    if offset != 0:
        ssf = ssf.shift(offset)
```

and it breaks in some setups

Best,
Joe Rosa

**Comment by twopirllc** [comment]
Hello @itpmngt,

> In pandas_ta/overlap/ssf.py the `offset' default value is set to None, but it should be '0' - as later it checks if 0

But it is set to zero since ```ssf``` calls ```get_offset(offset)```:
```python
# In pandas_ta/overlap/ssf.py
def ssf(close, length=None, poles=None, offset=None, **kwargs):
    """Indicator: Ehler's Super Smoother Filter (SSF)"""
    # Validate Arguments
    close = verify_series(close)
    length = int(length) if length and length > 0 else 10
    poles = int(poles) if poles in [2, 3] else 2
    offset = get_offset(offset)

    # ...
```

In ```pandas_ta/utils/_core.py```:
```python
def get_offset(x: int) -> int:
    """Returns an int, otherwise defaults to zero."""
    return int(x) if isinstance(x, int) else 0
```

Please show me an example of it breaking in some setups? Do you have an source to share?

Thanks,
KJ

**Comment by itpmngt** [comment]
Hello KJ

Just using the indicator (without the frame)

```
    from pandas_ta.overlap import ssf

    ssf(df.close)
```
We get:

```
<ipython-input-2-5e114f6166d5> in ssf(close, period, poles, offset, **kwargs)
     33     # Offset
     34     if offset != 0:
---> 35         ssf = ssf.shift(offset)
     36 
     37     # Name
.
.
.

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

just to follow the good practice that a module should be independent - loose-coupling

Best,

Joe

**Comment by itpmngt** [comment]
Hi KJ

I just realised what you mentioned - you resolve that on ``` def get_offset() ``` - so not a bug per se, just a styling code that made me confused - although would be simple to default to `0` - loose-coupling 'stuff'

Anyway, coding style..

BTW - great library, i highly as first reference - Thank You
(closing issue)

Best

Joe

**Comment by twopirllc** [comment]
Hello Joe (@itpmngt),

> I just realised what you mentioned - you resolve that on def get_offset() - so not a bug per se, just a styling code that made me confused.

No worries. Glad that you noticed it.

> although would be simple to default to 0 - loose-coupling 'stuff'

True. Maybe I will go through and update the trivial None's to default values.

Also I ran your use case and was unable to duplicate your error. 🤷‍♂️ 

<img width="329" alt="Screen Shot 2020-11-22 at 10 34 52 AM" src="https://user-images.githubusercontent.com/18198392/99913785-6e379480-2cae-11eb-836c-28cb722bbfd8.png">

Anyhow thanks for using **Pandas TA**! If you find it useful, please drop a ⭐ if you don't mind.

Thanks,
KJ
