### ISSUE TITLE
ZLMA newbie question

### ISSUE THREAD

**Issue by ekremus** [twopirllc/pandas-ta#167]
hello, I am new in Pandas and Pandas Ta,

here is my code:
```python
data=[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10] #etc.. 
df = DataFrame (data,columns=["Close"])
zlma_list= ta.zlma(pd.Series(df['Close']))
```

How can I change the original values of ZLMA
```python
def zlma(close, length=None, mamode=None, offset=0, **kwargs):
```

I tried this:

```python
zlma_list= ta.zlma(close=pd.Series(df['Close'],length=21,mamode=sma))
#changing the length is crucial for me. I did changes on original codes but it should be easier.
```
but it doesnt work.

also what is kwargs stand for? what is the aim of kwargs.

thank you for understanding. I dont know is it good place to ask.

**Comment by twopirllc** [comment]
Hello @ekremus,

This should solve your issue. If not, please show me more of your code.
```python
import pandas as pd
import pandas_ta as ta

closedf = pd.DataFrame({"Close": [1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10]})
zlmadf= ta.zlma(closedf, length=21, mamode="sma")
print(zlmadf)
```

The named arguments (_close_, _length_, _mamode_, _offset_) are the most common arguments that users are likely to use to modify **zlma**. The only required parameter is _close_ and it needs to be a Pandas Series. Where as _length_ has to be an integer. Finally the _mamode_ argument requires a string if you do not want it to use the default "ema" (which is None by default)

The **kwargs**  are additional arguments and values you may want to pass to make adjustments to an indicator's calculation or do post modifications before returning the result. The **kwargs** vary from indicator to indicator so use ```help(ta.<indicator>)``` (```help(ta.zlma)``` in this case) to see what the default arguments are and possible **kwargs**. Here is a [link](https://www.programiz.com/python-programming/args-and-kwargs) about Python and arguments and keyword arguments.

Hope this helps! Let me know how it goes.

Regards,
KJ

**Comment by ekremus** [comment]
First of all, thank you for your kind and informative answer.

I tried this code:
```
import pandas as pd
import pandas_ta as ta

closedf = pd.DataFrame({"Close": [1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10]})
zlmadf= ta.zlma(closedf, length=21, mamode="sma")
print(zlmadf)

```
But it doesnt work on my setup (pycharm the latest version)
gives me this error:
```
Traceback (most recent call last):
  File "C:/Users/../AppData/Roaming/JetBrains/PyCharmCE2020.3/scratches/scratch_67.py", line 5, in <module>
    zlmadf= ta.zlma(closedf, length=21, mamode="sma")
  File "C:\Users\..\venv\lib\site-packages\pandas_ta\overlap\zlma.py", line 21, in zlma
    close = 2 * close - close.shift(lag)
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```
On the other hand, my code is working without any problem. However I cannot add and change the parameteres ( length=21, mamode="sma") 
```
#this is working code for me
import pandas as pd
import pandas_ta as ta

data=[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10] #etc.. 
df = DataFrame (data,columns=["Close"])
zlma_list= ta.zlma(pd.Series(df['Close']))
```

**Comment by twopirllc** [comment]
Hello @ekremus,

```python
import pandas as pd
import pandas_ta as ta

# This works
price = pd.Series([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10])
zlma_series = ta.zlma(price)
print(type(zlma_series)) # results are Series, not lists
zlma_series = ta.zlma(price, length=21)
```
> On the other hand, my code is working without any problem. However I cannot add and change the parameteres ( length=21, mamode="sma")

It seems that ```mamode="sma"``` is not working as _intended_  resulting in all ```NaN``` values. So that's a potential bug. 😞  Unfortunately, I have a few things in the pipeline to finish before I can handle this and do not have an expected time frame of when it will be fixed. I apologize for the inconvenience.

Regards,
KJ

**Comment by ekremus** [comment]
Hey,

The last code you share is working perfectly. 🥇 
I don't know the results are True or not but I want to inform you about SMA and other moving averages are working fine. 
SMA works if the series length is more than 30. You have seen all NaN values because SMA gives results after 30th line.

Thank you.
