### ISSUE TITLE
ADX problem. I guess it doesn't work correctly.

### ISSUE THREAD

**Issue by coinrazzi** [twopirllc/pandas-ta#168]
I am using pandas-ta version 0.2.28b0

I think ADX indicator is not working correctly. I am getting data from Binance ohIc data and i am using pandas-ta adx indicator. I checked returned value with Tradingview. (for Binance Bitcoin price and other cryptocurrencies). Values are very different.

**Comment by twopirllc** [comment]
Hello @coinrazzi,

In fact **adx** is more than 99% correlated with the standard _de facto_ TA Lib. I need more proof beyond a visual comparison of numbers. If you really want to convince me that _adx_ is incorrect, then please follow Issue #107 on how to Export Chart Data from TradingView and perform a correlation test. Also, please read about _stoch_ and _stochrsi_ in Issue #112.

Regards,
KJ

**Comment by coinrazzi** [comment]
I upgrade to last version Pandas-ta. It is very close now. I will follow your message. Thank you.

**Comment by twopirllc** [comment]
@coinrazzi,

Ok. But I am still interested in seeing the results of the **adx** correlation tests you get versus TradingView or other Data Sources.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @coinrazzi,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Thanks,
KJ
