### ISSUE TITLE
Heiken ashi and Pandas

### ISSUE THREAD

**Issue by coinrazzi** [twopirllc/pandas-ta#169]
I am using pandas-ta version 0.2.28b0

When i use Heiken Ashi i am getting this message :

C:\ ....... \Python\Python38\lib\site-packages\pandas_ta\candles\ha.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["HA_open"][i] = 0.5 * (df["HA_open"][i - 1] + df["HA_close"][i - 1])

**Comment by twopirllc** [comment]
Hello @coinrazzi,

Please provide sample code that led up to this error. 

```python
import pandas as pd
import pandas_ta as ta

df = # Your data...
print(df.columns) # Show the columns prior to using Pandas TA

# What is the rest of your code?
# ...

ha_df = ta.ha(df.open, df.high, df.low, df.close)
# OR ?
df.ta.ha(append=True)
print(df.columns) # Check that the 'HA_*' columns are there

# More code ...
```

In the future, please give more detail as it makes it easier for me to debug and help solve the issue.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @coinrazzi,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Thanks,
KJ
