### ISSUE TITLE
pypi repo not up-to-date?

### ISSUE THREAD

**Issue by jdevoldere** [twopirllc/pandas-ta#173]
I'm on  pandas-ta 0.2.23b and vidya does not seem to be included even though it should be according to the documentation.

**Comment by jdevoldere** [comment]
For the record, I am not talking about the documentation on pypi, I'm talking about the library itself not being up-to-date with the github repo.

**Comment by jdevoldere** [comment]
Ah my bad, I guess it isn't part of stable yet.

**Comment by twopirllc** [comment]
Hello @jdevoldere,

I know you are referring to the code base on pypi not being in sync with github. All the latest stable working (beta or not) code is on Github. I just do not push every Github update to pypi, thoughI probably should do so more often.

```python
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Anyhow, the code works on either pypi or Github. Let me know if you need help.

Thanks,
KJ
