### ISSUE TITLE
Historic Volatility indicator

### ISSUE THREAD

**Issue by BowgartField** [twopirllc/pandas-ta#174]
**Which version are you running?
```python
0.2.28b0
```

Hi,
Thanks for this very usefull library.

I have to use an indicator like [https://www.prorealcode.com/documentation/historicvolatility/](url) but i don't find it on TA.
Is there a similar indicator ? If not is it possible to add it ?

Thanks !

**Comment by twopirllc** [comment]
Hello @BowgartField,

Thanks for using Pandas TA!

There is a Historic Volatility, but it is being revamped with some other benchmark metrics. However by definition, Historic Volatility from many sources state that it is a constant times the standard deviation. Pandas TA does have rolling statistics including standard deviation. But if you want standard deviation for the whole series, that is easy as well. You can do the following:

```python
import numpy as np
import pandas as pd
import pandas_ta as ta

df = # loading your ohlcv data
hv = np.sqrt(252) * df.ta.stdev(length=df.shape[0]).iloc[-1]
print(hv)
```

Let me know if this works or if you have any other questions. Apologies for the delay.

Thanks,
KJ

**Comment by BowgartField** [comment]
Hi,
Thanks for reply ! Yup this is working as I want.

**Comment by twopirllc** [comment]
Excellent!

Also I do want to point out that you can do it Conventionally:

```python
import numpy as np
import pandas as pd
import pandas_ta as ta

df = # loading your ohlcv data
hv = np.sqrt(252) * ta.stdev(df['close'], length=df.shape[0]).iloc[-1]
print(hv)
```

Thanks for letting me know,
KJ
