### ISSUE TITLE
Column titles in dataframe change from capital letters

### ISSUE THREAD

**Issue by robert48173** [twopirllc/pandas-ta#177]
Thanks for Pandas TA!
Version: 0.2.23b0
So, I have a (cs) dataframe with sample stock historical prices showing:
Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
then I use pandas_ta to calculate some indicators:
cs['EMA50'] = ta.ema(cs['Close'], length=50)
cs.ta.bbands(length=20, std=2, mamode='ema', append=True)
cs['EMA20'] = ta.ema(cs['close'], length=20)

Notice that to calculate cs['EMA20'] I had to use cs['close'] instead of cs['Close'] in order not to generate an error.
Applying cs.ta.bbands modified titles to: date,open,high,low,close,volume,Dividends,Stock Splits, ...

**Comment by twopirllc** [comment]
Hello @robert48173,

Thanks for using Pandas TA!

## Update
First, I recommend upgrading to the latest version. It will not solve the Issue, but you will be up to date.
```python
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

<br/>

## Programming Conventions
Based on what you gave me, you are mixing two different Programming Conventions the library supports. You switch from _Conventional_ to _DataFrame Extension_ and back to _Conventional_. That's not a problem either but there is an easier way to do it. _Solution:_ stick to one Programming Convention.

> Applying cs.ta.bbands modified titles to: date,open,high,low,close,volume,Dividends,Stock Splits, ...

That is correct.

This is explained in the **Programming Conventions** Section of the [README](https://github.com/twopirllc/pandas-ta/blob/master/README.md#programming-conventions). When applying TA with the _DataFrame Extension_: "Calling df.ta will **automatically lowercase** OHLCVA to ohlcva: open, high, low, close, volume, adj_close." Whereas the _Conventional_ way requires you to **explicitly** specify the column names from the DataFrame.

<br/>

## Possible Solutions
Here are three ways to accomplish the same result.

```python
import pandas as pd
import pandas_ta as ta

# Setup
cs = # Columns: Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
org_cols = {"date": "Date", "open": "Open", "high": "High", "low": "Low", "close": "Close", "volume": "Volume"}
```

<br/>

### _Conventional_
```python
cs['EMA20'] = ta.ema(cs['close'], length=20)
cs['EMA50'] = ta.ema(cs['Close'], length=50)
cs.ta.bbands(length=20, std=2, mamode='ema', append=True)
cs.rename(columns=org_cols, errors="ignore", inplace=True) # To rename the columns back
```

<br/>

### _DataFrame Extension_
```python
cs.ta.ema(length=50, append=True)
cs.ta.ema(length=150, append=True)
cs.ta.bbands(length=20, std=2, mamode="ema", append=True)
cs.rename(columns=org_cols, errors="ignore", inplace=True) # To rename the columns back
```

<br/>

### _Strategy_
```python
# (1) Create the Strategy
myTA = ta.Strategy(
    name="My Strat",
    ta=[
        {"kind": "ema", "length": 20},
        {"kind": "ema", "length": 50},
        {"kind": "bbands", "length": 20, "std": 2, "mamode": "ema"}
    ]
)

# (2) Run the Strategy
cs.ta.strategy(myTA, verbose=True)
cs.rename(columns=org_cols, errors="ignore", inplace=True) # To rename the columns back
```

<br/>

Let me know if these work for you.

Thanks,
KJ

**Comment by robert48173** [comment]
I am too new to pandas-ta and python to let you know now if these work for me or not, but appreciate very much your explanations.
I am glad it is not an error, now I am just curious what is the reason or benefit of changing OHLCVA to ohlcva.

**Comment by twopirllc** [comment]
@robert48173,

> I am too new to pandas-ta and python to let you know now if these work for me or not, but appreciate very much your explanations.

No worries and welcome! Thanks for sharing your skill level so I can tailor my responses to help you.

> I am glad it is not an error, now I am just curious what is the reason or benefit of changing OHLCVA to ohlcva.

Yeah. It is by design and unfortunately their case is not standardized as far as I know. I chose _lowercase_ to distinguish between **inputs** (_ohlcva_) and **outputs**  (_SMA_10_) from the column. But I also have not spent time to handle ignoring case and there likely an any easy solution 🤷🏼‍♂️.  Anyhow as you can see, renaming columns is one line if you ever need to recase them.

Regards,
KJ
