### ISSUE TITLE
Installation on Databricks

### ISSUE THREAD

**Issue by akshata29** [twopirllc/pandas-ta#178]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
Latest PIP version

**Describe the bug**
ImportError: cannot import name 'version' from 'pandas_ta' (/databricks/python/lib/python3.7/site-packages/pandas_ta/__init__.py)

Unable to install the package from PIP (even the latest one).  Following is the error 

```sh
/databricks/python/lib/python3.7/site-packages/pandas_ta/__init__.py in <module>
     94 }
     95 
---> 96 from pandas_ta.core import *

/databricks/python/lib/python3.7/site-packages/pandas_ta/core.py in <module>
     10 from pandas.core.base import PandasObject
     11 
---> 12 from pandas_ta import version, Category
     13 from pandas_ta.candles import *
     14 from pandas_ta.momentum import *
```

**To Reproduce**
Create the cluster on databricks and add new library at cluster to install the pandas-ta package

**Expected behavior**
Package correctly installed

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @akshata29,

If you are on version ```0.2.23b```, I suggest updating to the latest version: ```0.2.28b``` by:

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Let me know if that solves the issue.

Thanks,
KJ

**Comment by akshata29** [comment]
Thank you @twopirllc.   Databricks doesn't allow installation from github (except creating Python egg file).  I ended up modifying setup.py to import setup from (from setuptools import setup) and temporarily had to hardcode version# in init.py.  Will work to fix the issue and create pull request

**Comment by twopirllc** [comment]
@akshata29,

>  Databricks doesn't allow installation from github (except creating Python egg file). I ended up modifying setup.py to import setup from (from setuptools import setup) and temporarily had to hardcode version# in init.py. Will work to fix the issue and create pull request

That sucks that Databricks doesn't do that. I have some pending code I need to finish before updating the Github version and then pypi. But if you have some workable code via PR, that would be appreciative also.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @akshata29,

I have update Pandas TA as well as the ```pip``` version on pypi to version *0.2.45b*.

```sh
$ pip install -U pandas_ta
```

Please let me know if that works better with Databricks.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @akshata29,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
