### ISSUE TITLE
ImportError: cannot import name 'version' from partially initialized module 'pandas_ta'

### ISSUE THREAD

**Issue by Tjorriemorrie** [twopirllc/pandas-ta#179]
pandas_ta-0.2.23b

```python
    import pandas_ta as ta
```

<br/>

Error:
```sh
  File "/.pyenv/versions/covesting/lib/python3.8/site-packages/pandas_ta/__init__.py", line 96, in <module>
    from pandas_ta.core import *
  File "/.pyenv/versions/covesting/lib/python3.8/site-packages/pandas_ta/core.py", line 12, in <module>
    from pandas_ta import version, Category
ImportError: cannot import name 'version' from partially initialized module 'pandas_ta' (most likely due to a circular import) (/.pyenv/versions/covesting/lib/python3.8/site-packages/pandas_ta/__init__.py)
```

Using Python 3.8.5 (default, Sep 11 2020, 11:13:06) on mac

I can use the git repo version directly, which 28 I think, but then using `.ta.<anything>` does not work and does not add anything onto the dataframe.

**Comment by twopirllc** [comment]
Hello @Tjorriemorrie,

Weird. I would fully uninstall pandas-ta and try again with the latest Github version ```0.2.28b```.
```sh
$ pip uninstall pandas_ta
$ pip install git+https://github.com/twopirllc/pandas-ta
```

If that does not work, then perhaps it may be an issue with ```pyenv```. Would it be possible to test with ```virtualenv``` so we can see if it is ```pyenv```?

Keep me posted.

Thanks,
KJ

**Comment by fshsweden** [comment]
I had the same problem and it was solved by installing from Github per your suggestion

**Comment by twopirllc** [comment]
Hello @Tjorriemorrie,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @fshsweden,

Excellent! Glad you were able to resolve the Issue.

Thanks,
KJ
