### ISSUE TITLE
VP indicator how width works?

### ISSUE THREAD

**Issue by casterock** [twopirllc/pandas-ta#185]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python3.7
import pandas_ta as ta
print(ta.version)
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

I'm calculating VP over 50 candles of 1h.

I don't understand how width works in VP indicator. I run a test with different width values (1,2,3 and 10). Check my output and pay attention to "close high". Are this VP values right?

**To Reproduce**
vp1=df.ta.vp(width=1)
vp2=df.ta.vp(width=2)
vp3=df.ta.vp(width=3)
vp10=df.ta.vp(width=10)

print(df)
print(vp1)
print(vp2)
print(vp3)
print(vp10)

**OUTPUT**
                     **timestamp    open    high     low   close        volume** 
0   2020-12-31 16:00:00.000000  739.88  742.00  737.36  738.83   14810.28022
1   2020-12-31 17:00:00.000000  738.76  744.50  737.61  743.96   14700.26345
2   2020-12-31 18:00:00.000000  743.96  745.00  736.52  738.24   18490.32151
3   2020-12-31 19:00:00.000000  738.23  742.50  735.88  740.48   11375.60510
4   2020-12-31 20:00:00.000000  740.46  741.70  731.83  736.42   19450.08215
5   2020-12-31 21:00:00.000000  736.42  739.00  729.33  734.07   27932.69884
6   2020-12-31 22:00:00.000000  734.08  749.00  733.37  748.28   52336.18779
7   2020-12-31 23:00:00.000000  748.27  749.00  742.27  744.06   33019.50100
8   2021-01-01 00:00:00.000000  744.06  747.23  743.10  744.82   17604.80859
9   2021-01-01 01:00:00.000000  744.87  747.09  739.30  742.29   18794.15424
10  2021-01-01 02:00:00.000000  742.34  743.23  739.50  740.65   14948.26447
11  2021-01-01 03:00:00.000000  740.72  743.25  737.04  739.97   17106.99495
12  2021-01-01 04:00:00.000000  739.87  740.51  734.40  737.38   21624.68945
13  2021-01-01 05:00:00.000000  737.37  738.48  725.10  730.07   52992.04892
14  2021-01-01 06:00:00.000000  730.07  734.77  728.77  733.68   22836.46973
15  2021-01-01 07:00:00.000000  733.69  738.87  733.27  736.81   22895.59711
16  2021-01-01 08:00:00.000000  736.82  741.76  736.11  738.85   29384.09871
17  2021-01-01 09:00:00.000000  738.85  743.33  732.12  733.19   50190.47228
18  2021-01-01 10:00:00.000000  733.19  741.99  733.00  740.08   23543.56362
19  2021-01-01 11:00:00.000000  740.08  742.67  736.46  738.00   22098.37395
20  2021-01-01 12:00:00.000000  738.01  740.00  733.50  735.39   25671.61199
21  2021-01-01 13:00:00.000000  735.39  737.73  733.01  735.83   22249.34205
22  2021-01-01 14:00:00.000000  735.76  736.45  726.57  727.94   40914.26505
23  2021-01-01 15:00:00.000000  727.94  731.80  714.29  724.60   66427.75355
24  2021-01-01 16:00:00.000000  724.57  728.28  720.95  725.34   26866.35862
25  2021-01-01 17:00:00.000000  725.34  730.71  722.50  729.48   22422.29118
26  2021-01-01 18:00:00.000000  729.48  730.61  726.69  728.23   14582.15316
27  2021-01-01 19:00:00.000000  728.23  731.97  725.65  728.90   14614.20353
28  2021-01-01 20:00:00.000000  728.97  730.58  727.65  728.91   14058.19051
29  2021-01-01 21:00:00.000000  728.91  730.66  716.26  719.90   46190.17553
30  2021-01-01 22:00:00.000000  719.90  731.75  714.91  729.38   37985.46001
31  2021-01-01 23:00:00.000000  729.39  734.40  729.05  729.44   21870.25220
32  2021-01-02 00:00:00.000000  729.45  731.96  728.40  730.39   13138.56186
33  2021-01-02 01:00:00.000000  730.39  730.67  726.26  729.45   13117.64933
34  2021-01-02 02:00:00.000000  729.45  733.40  729.22  731.99   19342.91315
35  2021-01-02 03:00:00.000000  731.99  740.49  730.53  737.04   41590.31856
36  2021-01-02 04:00:00.000000  737.08  738.66  733.07  735.12   23887.39609
37  2021-01-02 05:00:00.000000  735.12  738.35  728.21  733.84   32631.45363
38  2021-01-02 06:00:00.000000  733.84  734.64  723.06  725.41   38970.42653
39  2021-01-02 07:00:00.000000  725.24  733.93  723.01  728.47   34642.76548
40  2021-01-02 08:00:00.000000  728.55  731.10  727.17  729.70   14020.08545
41  2021-01-02 09:00:00.000000  729.70  757.00  728.25  752.38  134011.47560
42  2021-01-02 10:00:00.000000  752.39  772.80  749.11  770.77  154115.10137
43  2021-01-02 11:00:00.000000  770.77  771.28  753.00  760.94   88376.02018
44  2021-01-02 12:00:00.000000  760.99  768.99  760.86  768.43   51945.86127
45  2021-01-02 13:00:00.000000  768.45  782.98  764.50  781.94  145618.23911
46  2021-01-02 14:00:00.000000  781.94  784.66  774.04  778.84   74461.65986
47  2021-01-02 15:00:00.000000  778.77  784.39  772.00  780.01   57755.77853
48  2021-01-02 16:00:00.000000  780.00  787.69  776.77  784.79   56561.31490
49  2021-01-02 17:00:00.000000  784.79  785.48  750.12  756.55  122647.19925

   **low_close  mean_close  high_close    pos_volume    neg_volume  total_volume**
0      719.9    740.7906      784.79  1.228753e+06  748067.99059  1.976821e+06

   **low_close  mean_close  high_close    pos_volume    neg_volume  total_volume**
0      724.6    737.1692      748.28  479021.25676  209242.55058  6.882638e+05
1      719.9    744.4120      784.79  749731.50626  538825.44001  1.288557e+06

   **low_close  mean_close  high_close    pos_volume    neg_volume  total_volume**
0     730.07  739.344706      748.28  295817.15389  114484.91234  4.103021e+05
1     719.90  730.261765      740.08  244008.48193  231932.19649  4.759407e+05
2     725.41  753.513750      784.79  688927.12720  401650.88176  1.090578e+06

 **low_close  mean_close  high_close    pos_volume    neg_volume  total_volume**
0     736.42     739.586      743.96   52750.68388   26075.86855   78826.55243
1     734.07     742.704      748.28   99063.04087   50624.30959  149687.35046
2     730.07     736.350      740.65   91723.73332   37784.73420  129508.46752
3     733.19     737.386      740.08  102470.16810   45641.93757  148112.10567
4     724.60     729.820      735.83  133013.63059   49115.70067  182129.33126
5     719.90     727.084      729.48   60804.37906   51062.63485  111867.01391
6     729.38     730.130      731.99   19342.91315   86111.92340  105454.83655
7     725.41     731.976      737.04  113192.19872   58530.16157  171722.36029
8     729.70     756.444      770.77  288126.57697  154341.96690  442468.54387
9     756.55     776.426      784.79  268265.43836  188778.75329  457044.19165

**Comment by casterock** [comment]
Check that total total volume is diferent with each width, for example with width=1 for high_close=784.79 total_volume=  1.976821e+06 and with width=2 total_volume=1.288557e+06.

I think this issue is relationated with the array_sort() by close

**Comment by twopirllc** [comment]
Hello @casterock,

Thanks for trying Pandas TA.

When you have some time, please check out **How to plot Volume Profile?** Issue #74. Hopefully that may address your question. If not, we can go from there. If it is inaccurate and you know how to make it better, I would greatly appreciate a PR.

Hope this helps.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @casterock,

I assume the suggestion in Issue #74 was sufficient. Thus I will be closing this Issue in a few days. If you are still having Issues, reopen it and we can go from there.

Thanks,
KJ
