### ISSUE TITLE
How to align RMA with TradingView

### ISSUE THREAD

**Issue by 2W-12** [twopirllc/pandas-ta#186]
Hi,
how to align RMA with tradingview ?
I'm getting completely different results :(

This is TV formula:

**Moving average used in RSI. It is the exponentially weighted moving average with alpha = 1 / length.**
```
plot(rma(close, 15))

//the same on pine
pine_rma(src, length) =>
	alpha = 1/length
	sum = 0.0
	sum := na(sum[1]) ? sma(src, length) : alpha * src + (1 - alpha) * nz(sum[1])
plot(pine_rma(close, 15))
```

**Comment by twopirllc** [comment]
Hello @2W-12,

Thanks for using Pandas TA.

> how to align RMA with tradingview ?

It passes the Visual (Smell) Test. But I recommend reading and following Issue #187 on providing a correlation test.

### TradingView

<img width="720" alt="Screen Shot 2021-01-07 at 10 04 50 AM" src="https://user-images.githubusercontent.com/18198392/103928115-39519680-50d0-11eb-9292-197a2b039930.png">

### Matplotlib

<img width="686" alt="Screen Shot 2021-01-07 at 10 05 11 AM" src="https://user-images.githubusercontent.com/18198392/103928154-479fb280-50d0-11eb-89c7-5d3f4d3fdc80.png">


Regards,
KJ

**Comment by 2W-12** [comment]
Complete issue with tests: https://github.com/twopirllc/pandas-ta/issues/189
