### ISSUE TITLE
ATR/RMA differences with TradingView

### ISSUE THREAD

**Issue by 2W-12** [twopirllc/pandas-ta#189]
Let's take weekly BINANCE:BTCUSDT indicator since beginning (14.08.2017) and do ATR with period=7 and RMA with period=7.

Python results:
```python
import pandas as pd
import numpy as np
import pandas_ta as ta

df = pd.DataFrame({'datetime': {0: '2017-08-14 00:00:00', 1: '2017-08-21 00:00:00', 2: '2017-08-28 00:00:00', 3: '2017-09-04 00:00:00', 4: '2017-09-11 00:00:00', 5: '2017-09-18 00:00:00', 6: '2017-09-25 00:00:00', 7: '2017-10-02 00:00:00', 8: '2017-10-09 00:00:00', 9: '2017-10-16 00:00:00', 10: '2017-10-23 00:00:00', 11: '2017-10-30 00:00:00', 12: '2017-11-06 00:00:00', 13: '2017-11-13 00:00:00'}, 'open': {0: 4261.48, 1: 4069.13, 2: 4310.01, 3: 4505.0, 4: 4153.62, 5: 3690.0, 6: 3660.02, 7: 4400.0, 8: 4640.0, 9: 5710.0, 10: 5975.0, 11: 6133.01, 12: 7345.1, 13: 5839.94}, 'high': {0: 4485.39, 1: 4453.91, 2: 4939.19, 3: 4788.59, 4: 4394.59, 5: 4123.2, 6: 4406.52, 7: 4658.0, 8: 5922.3, 9: 6171.0, 10: 6189.88, 11: 7590.25, 12: 7770.02, 13: 8123.15}, 'low': {0: 3850.0, 1: 3400.0, 2: 4124.54, 3: 3603.0, 4: 2817.0, 5: 3505.55, 6: 3653.69, 7: 4110.0, 8: 4550.0, 9: 5037.95, 10: 5286.98, 11: 6030.0, 12: 5325.01, 13: 5699.99}, 'close': {0: 4086.29, 1: 4310.01, 2: 4509.08, 3: 4130.37, 4: 3699.99, 5: 3660.02, 6: 4378.48, 7: 4640.0, 8: 5709.99, 9: 5950.02, 10: 6169.98, 11: 7345.01, 12: 5811.03, 13: 8038.0}})
atr = df.ta.atr(length=7)
rma = df.ta.rma(length=7)

print(atr)
0      635.390000
1      860.746923
2      842.961496
3      949.315864
4     1116.350102
5      998.287017
6      945.164499
7      865.099081
8      961.674618
9      992.824763
10     977.091686
11    1075.946678
12    1301.999156
13    1483.088680
Name: ATR_7, dtype: float64

print(rma)
0     4086.290000
1     4206.754615
2     4323.399843
3     4263.481982
4     4113.670859
5     4006.272806
6     4086.826964
7     4198.342546
8     4486.173579
9     4752.250467
10    5000.293910
11    5397.762117
12    5465.998719
13    5881.427506
Name: RMA_7, dtype: float64
```

Now compare to TradingView built-in ATR (its using RMA)
Here is pine script
```
//@version=4
study("My Script")
plot(atr(7), title="ATR")
plot(rma(close, 7), title="RMA")
```
**TradingView results are:
ATR:**
NaN
NaN
NaN
NaN
NaN
NaN
NaN
948.2300000000000
891.0542857142860
959.8036734693880
984.5531486880470
972.8884131611830
1056.797211281010
1255.1133239551500

**RMA:**
NaN
NaN
NaN
NaN
NaN
NaN
NaN
4110.605714285710
4186.233469387760
4403.912973760930
4624.7854060808000
4845.527490926400
5202.596420794060
5289.515503537760

To be honest I'm little bit lost and can't find issue cause.

P.S. sorry for incorrectly previously opened issue, i clicked "bug" occasionally and topic was like a discussion with other users if anyone seen this.

**Comment by twopirllc** [comment]
@2W-12,

Thanks. This I can work with.

```python
import pandas as pd
import numpy as np
import pandas_ta as ta

df = pd.DataFrame({'datetime': {0: '2017-08-14 00:00:00', 1: '2017-08-21 00:00:00', 2: '2017-08-28 00:00:00', 3: '2017-09-04 00:00:00', 4: '2017-09-11 00:00:00', 5: '2017-09-18 00:00:00', 6: '2017-09-25 00:00:00', 7: '2017-10-02 00:00:00', 8: '2017-10-09 00:00:00', 9: '2017-10-16 00:00:00', 10: '2017-10-23 00:00:00', 11: '2017-10-30 00:00:00', 12: '2017-11-06 00:00:00', 13: '2017-11-13 00:00:00'}, 'open': {0: 4261.48, 1: 4069.13, 2: 4310.01, 3: 4505.0, 4: 4153.62, 5: 3690.0, 6: 3660.02, 7: 4400.0, 8: 4640.0, 9: 5710.0, 10: 5975.0, 11: 6133.01, 12: 7345.1, 13: 5839.94}, 'high': {0: 4485.39, 1: 4453.91, 2: 4939.19, 3: 4788.59, 4: 4394.59, 5: 4123.2, 6: 4406.52, 7: 4658.0, 8: 5922.3, 9: 6171.0, 10: 6189.88, 11: 7590.25, 12: 7770.02, 13: 8123.15}, 'low': {0: 3850.0, 1: 3400.0, 2: 4124.54, 3: 3603.0, 4: 2817.0, 5: 3505.55, 6: 3653.69, 7: 4110.0, 8: 4550.0, 9: 5037.95, 10: 5286.98, 11: 6030.0, 12: 5325.01, 13: 5699.99}, 'close': {0: 4086.29, 1: 4310.01, 2: 4509.08, 3: 4130.37, 4: 3699.99, 5: 3660.02, 6: 4378.48, 7: 4640.0, 8: 5709.99, 9: 5950.02, 10: 6169.98, 11: 7345.01, 12: 5811.03, 13: 8038.0}})
```

Seems like you are comparing two different sources. BINANCE:BTCUSDT and TradingView. Correct?

</br>

> To be honest I'm little bit lost and can't find issue cause.
> P.S. sorry for incorrectly previously opened issue, i clicked "bug" occasionally and topic was like a discussion with other users if anyone seen this.

No problem. I know you recently joined GitHub. It took me time as well to become comfortable using the platform.

Thanks,
KJ

**Comment by 2W-12** [comment]
> Seems like you are comparing two different sources. BINANCE:BTCUSDT and TradingView. Correct?

No no, source is same, in tradingview in Ticker field type **BINANCE:BTCUSDT** and you gonna get same values. Don't forget to choose 1W timeframe (based on my example)

**Comment by twopirllc** [comment]
@2W-12,

Ok. I will add to the list. Unfortunately, I do not have a time frame on deciding on whether this is an issue or not. I still have other Issues in the queue to resolve as well as other PRs to merge into _development_. If you want to expedite the problems with **rma** and **atr** (or any other indicator for that matter), please fork, edit and submit a PR. (_Don't forget the Unit Tests_) I and the user base would greatly appreciate your contribution to maintain the accuracy of the library. Everyone wins. 😎 

Also you still not have provided me with which version of Pandas TA you are using. Anyhow, no need to tell me. Just upgrade to the latest **Latest Version** if you have not done so already.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Best Regards,
KJ

**Comment by 2W-12** [comment]
I have latest version from git.
I wish to do it myself and would if I was good with numpy/pandas.... Please keep issue open maybe one day someone will find it and help community :)

**Comment by twopirllc** [comment]
@2W-12,

> I have latest version from git.
> I wish to do it myself and would if I was good with numpy/pandas....

Excellent. I look forward to your contribution.

> I wish to do it myself and would if I was good with numpy/pandas.... Please keep issue open maybe one day someone will find it and help community :)

No problem. 😄 Thanks for helping to keep this library accurate with so many variations out in the wild.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @2W-12,

Reopen when you are making some progress. 😎 

Thanks,
KJ

**Comment by Katebsaber** [comment]
Checkout my explanation here:
[https://github.com/mrjbq7/ta-lib/issues/379#issuecomment-1107817993](https://github.com/mrjbq7/ta-lib/issues/379#issuecomment-1107817993)

**Comment by twopirllc** [comment]
@2W-12, @Katebsaber,

Well the good news is, @mihakralj provided what I missed in #402 and a few days ago I have updated: **atr**, **rma**, and **true_range**. These changes are on the _development_ branch:

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Please install that branch and let me know if it's working as intended.

Kind Regards,
KJ
