### ISSUE TITLE
RSI is being wrongly calculated

### ISSUE THREAD

**Issue by prateekdaniels** [twopirllc/pandas-ta#191]
I am using the 0.2.23b0 version of pandas_ta and using it as follows:
```
import pandas_ta as pta
check['RSI'] = pta.rsi(close=check['Close_NAVI.O'], length=10)

```
and the output is shown in the RSI column of the below screenshot :
![image](https://user-images.githubusercontent.com/37053891/104465016-b49ed500-5607-11eb-96a3-64b65d2109a7.png)

But the calculating should have been starting from the 9th row, but erroneously starts from the 1st row. This could be seen irrespective of any window length I chose.

**Comment by twopirllc** [comment]
Hello @prateekdaniels,

I see what you mean. Thanks for noticing it and pointing it out. Even though the first nine values are non ```NaN```s, _which will be fixed_, it does not effect the accuracy of the **rsi** indicator; it is still 99.98% correlated with TA Lib. It is an easy fix if you want to submit a PR. You would only need to modify **rma** and not **rsi**.

Thanks,
KJ
