### ISSUE TITLE
Calculating an indicator value for a particular date

### ISSUE THREAD

**Issue by prateekdaniels** [twopirllc/pandas-ta#192]
The below  code calculates the values for an indicator ( for example, say SMA) for all the values of the close price in a dataframe:

```python
import pandas_ta as pta
df['SMA']= pta.sma(close=df['Close_NAVI.O'], length=10)
```

My query is that, is there a way to say calculate the value of SMA for a new close value that gets appended to the data frame ?

I know that we could re-run `df['SMA']= pta.sma(close=df['Close_NAVI.O'], length=10)` to get the SMA values for all close prices, but let's say I have a big dataframe which runs into thousands of rows and I don't want to waste my computing resources to keep re-calculating the values for all the row.  

To give you a pictorial idea of what I said above, let's assume that the I know have a new close value of "16.6000" on "2014-05-07 00:00:00" of the below dataframe and I would like to calculate the value of SMA for that particular close only.

![image](https://user-images.githubusercontent.com/37053891/104534436-65d55780-5668-11eb-94a7-60cae555bc3c.png)

I tried by using the below code,

`df.loc[14, 'SMA']= pta.sma(close=df['Close_NAVI.O'], length=10)
`

but I get the following error:

```sh
df.loc[14, 'SMA']= pta.sma(close=df['Close_NAVI.O'], length=10)
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-64-3b6dc5d213d8>", line 1, in <module>
    df.loc[14, 'SMA']= pta.sma(close=df['Close_NAVI.O'], length=10)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 1642, in _setitem_with_indexer
    value = self._align_series(indexer, value)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 1952, in _align_series
    raise ValueError("Incompatible indexer with Series")
ValueError: Incompatible indexer with Series
df.loc[13, 'SMA']= pta.sma(close=df['Close_NAVI.O'], length=10)
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-65-f0f4255ec13c>", line 1, in <module>
    df.loc[13, 'SMA']= pta.sma(close=df['Close_NAVI.O'], length=10)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 1642, in _setitem_with_indexer
    value = self._align_series(indexer, value)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 1952, in _align_series
    raise ValueError("Incompatible indexer with Series")
ValueError: Incompatible indexer with Series
```

Could someone suggest a way to do this ?

**Comment by YuvalWein** [comment]
Hi @prateekdaniels,
If I get you right, what you are trying to do is to calculate the sma value, of the **last row only**.
To do so, you can use [slicing](https://stackoverflow.com/questions/509211/understanding-slice-notation):
```python
period = 14
calculate_from = -1 * period 
last_cell_value = pta.sma(close= df['Close'][calculate_from:], length=period)[-1]
last_cell_value
```

Is that what you were looking for?

**Comment by twopirllc** [comment]
Hello @prateekdaniels,

Thanks @YuvalWein for providing a potential remedy. I have not thought of that. 😎 

Furthermore, I recommend reading Issue #87 - _How to utilize this Framework for live ticks_. (It is the 1st pinned Issue). It covers essentially what you are interested in. On top of that, I also recommend reading how TradingView handles [_Pine Script Execution_](https://www.tradingview.com/pine-script-docs/en/v4/Quickstart_guide.html#study-vs-strategy). Perhaps that may give you idea how to handle streaming data. 

Note this is not a full service library, nor is any TA library that I have seen. It's primary purpose is to return accurate indicators correlated primarily with TA Lib and TradingView if possible. However to this end, I try to answer application Issues of the library have shared [example notebooks](https://github.com/twopirllc/pandas-ta/tree/master/examples) to help spark ideas.

Hope this helps!

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @prateekdaniels,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
