### ISSUE TITLE
Bill Williams Fractals with Alligator Indicators

### ISSUE THREAD

**Issue by rahulmr** [twopirllc/pandas-ta#194]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.2.23b0

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```
0.2.28b0

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implementation of Bill Williams Alligator and Fractals indicators

**Describe alternatives you've considered**
See below links
https://pandastechindicators.readthedocs.io/en/latest/#alligator
https://pandastechindicators.readthedocs.io/en/latest/#fractals
https://www.tradingview.com/script/lLgCdjag-Bill-Williams-Divergent-Bars/

**Additional context**
Some good code already available.
https://github.com/Tolkoton/WilliamsIndicators/blob/master/WilliamsIndicators.py
https://github.com/dmitriiweb/tapy

Also if possible implement crossover like in this => https://tulipindicators.org/list

**Comment by twopirllc** [comment]
Hello @rahulmr,

I have implemented Williams Alligator (**alligator**) and it's required Smoothed Moving Average (**smma**). However, I still have to look and attempt his Fractal indicator. If you can test it out on the _development_ branch and let me know, that would be great.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

I apologize for the delay. I was hoping others might help, but that seems unlikely most of the time sadly.

Thanks
KJ

**Comment by rokups** [comment]
Many places implement alligator by shifting it into the future.

For example (https://www.ifcmarkets.co.in/en/ntx-indicators/alligator):
```
    The Alligator’s jaw or the blue line is a 13-period smoothed moving average shifted into the future by 8 bars;
    The Alligator’s teeth or the red line is an 8-period smoothed moving average shifted into the future by 5 bars;
    The Alligator’s lips or the green line is a 5-period smoothed moving average shifted into the future by 3 bars.
```

Same is done in tradingview implementation. There is no shifting in pandas-ta version. It is only possible to apply a single offset to all three moving averages. I believe it is incorrect.

**Comment by twopirllc** [comment]
Hello @rokups,

> Many places implement alligator by shifting it into the future. ... Same is done in tradingview implementation. There is no shifting in pandas-ta version. 

That is true and I am aware of it.

> It is only possible to apply a single offset to all three moving averages.

Yes, one should add arguments to ```alligator``` to individually offset each ```smma```. It would be great, if you're willing, to make that contribution. 😎

> I believe it is incorrect.

Despite the lack of future offset, the individual values should be correct and I was hoping someone other than myself could/would corroborate it. Adding individual shifting arguments is trivial.

However actually extending the DataFrame for future offsets is not trivial, consider ```ichimoku```'s span future offset as an example. This is the current implementation, but there is probably a better way... 🤷🏼‍♂️. For instance, ```freq="B"``` is assumed and should either be a method argument or somehow easily determined from the Series index better than what I hacked together. If you have knowledge or experience to improve ```alligator``` and ```ichimoku```, that would be greatly appreciated. 😎 

https://github.com/twopirllc/pandas-ta/blob/bc3b292bf1cc1d5f2aba50bb750a75209d655b37/pandas_ta/overlap/ichimoku.py#L78-L89

<br/>

Additionally, I would like to figure out how to concat the new future offsets of ```alligator``` and ```ichimoku``` when running ```df.ta.strategy()``` and thus help make it easy to use like many full featured trading platforms like Trading View, TradeStation, et al.

https://github.com/twopirllc/pandas-ta/blob/bc3b292bf1cc1d5f2aba50bb750a75209d655b37/pandas_ta/core.py#L462-L469

<br/>

Anyhow if you have some ideas or can help contribute, even just a little, that would be great! 😎

Kind Regards,
KJ

**Comment by rokups** [comment]
Ehm i do not believe there is a need to extend dataframe into a future. If we wanted to see future values we could avoid shifting altogether, but that is hardly ever a case with this indicator.
