### ISSUE TITLE
Possible to use pandas-ta with backtrader 

### ISSUE THREAD

**Issue by vijay-r** [twopirllc/pandas-ta#195]
Please share an example - how to use pandas-ta with [backtrader](https://github.com/mementum/backtrader)

**Comment by twopirllc** [comment]
Hello @vijay-r,

I do not know. Perhaps someone has already done it. If so, I hope that they would share as well for everyone's benefit.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @vijay-r,

Any success with **backtrader**? If not, perhaps [**vectorbt**](https://github.com/polakowo/vectorbt) might be simpler.

Recently **vectorbt** has made it _easy_ to support for Pandas TA. To help streamline the process, I am updating ```ta.trend_return``` to make it easy to return __entries__ and __exits__ columns so **vectorbt** can backtest using those [signals](https://polakowo.io/vectorbt/docs/portfolio/base.html#vectorbt.portfolio.base.Portfolio.from_signals). Once ```ta.trend_return``` is updated, I plan to create a Jupyter Notebook Backtesting Example. I will keep you posted.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @vijay-r,

So ```ta.trend_return``` has been depreciated in favor of ```ta.tsignals``` which works similarly. However ```ta.tsignals``` does not return returns, it does return columns: Trend, Trades, Entries and Exits. The latter two columns Entries and Exits can used to feed into VectorBT's ```from_signals()``` method to generate Portfolio results. There is an example [Notebook](https://github.com/twopirllc/pandas-ta/blob/main/examples/VectorBT_Backtest_with_Pandas_TA.ipynb) detailing the process for both a Buy and Hold Strategy and a Trend Signal Strategy.

When you get a chance, let me know if it helps. Thanks for your patience.

Kind Regards,
KJ
