### ISSUE TITLE
Pandas-ta multiprocessing not working

### ISSUE THREAD

**Issue by myilmazhaubtech** [twopirllc/pandas-ta#198]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)

0.2.28b0
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**

The following line is not using any multiprocessing. Instead the whole calculation takes place on a single core although the message output says that it is using 128 CPUs. Please see the screen snapshot showing that this is clearly not happening. I couldn't get it to use all of my CPUs.

`inputs.ta.strategy(exclude=["tema", "t3", "supertrend", "natr", "percent_return", "ichimoku", "ppo", "roc", "dpo", "vwma", "wma", "zlma", "hilo", "nvi","qqe", "pvi" , "qstick", "squeeze", "ttm_trend","rvgi", "log_return", "psar", "pvt", "cdl_doji", "cdl_inside", "bop", "adosc", "cksp", "decay", "kc", "hl2", "hlc3", "ha", "donchian", "accbands", "massi"], verbose=True, timed=True)`

**To Reproduce**
```python
import pandas_ta as ta

def talib_new(input_ds,symbol_list,window_size):
  
    critical_columns_index=len(input_ds.columns) # do not remove these initial set of columns since they contain pricing information
  

    for symboll in symbol_list:
    
        print(symboll)
    
        print('Adding columns for subsymbol ',symboll)
        inputs = pd.DataFrame()
    
        inputs['open'] = input_ds[f'OpenPrice{str("_")+symboll}'].astype(float)
        inputs['high'] = input_ds[f'OpenPrice{str("_")+symboll}'].astype(float)
        inputs['low'] = input_ds[f'OpenPrice{str("_")+symboll}'].astype(float)
        inputs['close'] = input_ds[f'OpenPrice{str("_")+symboll}'].astype(float)
        inputs['volume'] = input_ds[f'OpenPrice{str("_")+symboll}'].astype(float)
    
        inputs.ta.mp = True

        inputs.ta.strategy(exclude=["tema", "t3", "supertrend", "natr", "percent_return", "ichimoku", "ppo", "roc", "dpo", "vwma", "wma", "zlma", "hilo", "nvi","qqe", "pvi" , "qstick", "squeeze", "ttm_trend","rvgi", "log_return", "psar", "pvt", "cdl_doji", "cdl_inside", "bop", "adosc", "cksp", "decay", "kc", "hl2", "hlc3", "ha", "donchian", "accbands", "massi"], verbose=True, timed=True)
        
        
        
        smoothing_features = ['MIDPRICE_2', 'DEMA_10', 'EMA_10', 'FWMA_10', 'HMA_10', 'KAMA_10_2_30', "WCP"]
        
        for name in smoothing_features:
            inputs[name] = (inputs[name]-inputs['close'])/inputs['close']*100
        
        
        #inputs['AD'] = inputs['AD'].pct_change(periods=window_size)
        inputs['OBV'] = inputs['OBV'].pct_change(periods=window_size)
        inputs['LOGRET'] = inputs.ta.log_return()
        inputs['PCTRET'] = inputs.ta.percent_return()
        inputs['ROC'] = inputs.ta.roc()
        inputs['NATR'] = inputs.ta.natr()
        inputs = inputs.drop(columns = ['open', 'high', 'low', 'volume', 'close', 'AR_26', 'AD','OBV_min_2', 'OBV_max_2', 'OBV_EMA_4', 'OBV_EMA_12', 'ABER_ZG_5_15', 'ABER_SG_5_15', 'ABER_XG_5_15', 'BBL_5_2.0', 'BBM_5_2.0', 'BBU_5_2.0'])
        
        
        
        
        
        for i in inputs.columns:
            
            input_ds[i+f'{str("_")+symboll}'] = inputs[i]
    
        input_ds=input_ds.drop(columns = [f'OpenPrice{str("_")+symboll}',f'HighPrice{str("_")+symboll}',f'LowPrice{str("_")+symboll}',f'ClosePrice{str("_")+symboll}',f'TotalVolume{str("_")+symboll}'], axis=1)

    input_ds.dropna(inplace=True)  
    
    return input_ds
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77806252/105742454-870c3280-5f09-11eb-9efe-df8c6fe89bd6.png)

![image](https://user-images.githubusercontent.com/77806252/105742505-98edd580-5f09-11eb-8cf2-39e4aba158cd.png)

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @myilmazhaubtech,

> The following line is not using any multiprocessing. Instead the whole calculation takes place on a single core although the message output says that it is using 128 CPUs. Please see the screen snapshot showing that this is clearly not happening. I couldn't get it to use all of my CPUs.

That is weird. I do not know why it is not utilizing all the CPUs available despite what Pandas TA says. With your hardware and software specs found at [scikit-learn Issue](https://github.com/scikit-learn/scikit-learn/issues/19259#issue-792634155), hopefully someone else has encountered an Issue with Python not utilizing all the core on Ubuntu.

First, I would check out the following [Linux Python Multiprocessing Issue](https://www.wikitechy.com/tutorials/linux/why-does-multiprocessing-use-only-a-single-core-after-i-import-numpy) and see if that may resolve the Issue. I would also continue trying other solutions listed from the following [Google Search](https://www.google.com/search?client=firefox-b-1-d&ei=oWgQYPOyMpas0PEPyrSW0As&q=ubuntu+python+multiprocessing+not+using+all+cores&oq=ubuntu+python+multiprocessing+not+&gs_lcp=CgZwc3ktYWIQAxgBMggIIRAWEB0QHjIICCEQFhAdEB4yCAghEBYQHRAeMggIIRAWEB0QHjIICCEQFhAdEB4yCAghEBYQHRAeMggIIRAWEB0QHjIICCEQFhAdEB4yCAghEBYQHRAeMggIIRAWEB0QHjoECAAQRzoGCAAQFhAeULsiWOQoYNg2aABwAngAgAF5iAH-A5IBAzMuMpgBAKABAaoBB2d3cy13aXrIAQjAAQE&sclient=psy-ab) that are Linux specific and try it out. Unfortunately, I do not have a high powered Linux machine to test with so you will need to help out and give me details.

Should the provided Linux specific solutions, from the links above, not work nor improve performance, I will look into it. At that point I will need your assistance to test development code, with you testing on your system.

Unfortunately, I do not have an expected time frame on resolving this Issue as I am backlogged on outstanding Issues and package enhancements. However, this can be expedited with your help as I can not do this alone nor do I have a similar machine to test on. Your assistance would be greatly appreciated.

Kind Regards,
KJ

**Comment by Qiu-INJ** [comment]
meet the same problem...

**Comment by Qiu-INJ** [comment]
> @Qiu-INJ,
> 
> I can not help you with such a minimal description of your issue.
> 
> So what version of Pandas TA are you running? Where is your reproducible code and applicable screenshots? What time of system are you running on? Have you tried code from the links in the prior comment?
> 
> Kind Regards, KJ

Sorry!!! my fault!
pandas ta: 0.3.14b0
system: ubuntu 18.04
code :
```
TestStrategy = ta.Strategy(
    name = "test",
    ta = [
        {'kind':'td_seq'}
    ]
)
data.ta.strategy(TestStrategy, cores=0, timed=True)
```

data.tail()
```
![2021-10-14 21-57-13 的屏幕截图](https://user-images.githubusercontent.com/85727393/137332168-bd85ed0b-e5ce-4c1a-bd60-11aea0910f6a.png)

```

**Comment by Qiu-INJ** [comment]
![Uploading 2021-10-14 22-02-11 的屏幕截图.png…]()
