### ISSUE TITLE
df_test.ta.stoch seems to be hardcoded to 14 3 3

### ISSUE THREAD

**Issue by replyxf** [twopirllc/pandas-ta#200]
df_test.ta.stoch(fast_k=7, slow_k=7, slow_d=3,append=True)
is the same as
df_test.ta.stoch(fast_k=14, slow_k=14, slow_d=3,append=True)

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**

**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @replyxf,

What version are you running? You did not post it as asked on the Issue Form.

You need to update to the latest version as described on the Issue Form like so:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Please upgrade and use ```help(ta.stoch)``` for the help on the correct parameters and then retest the different values **and** get back to me.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @replyxf 

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by replyxf** [comment]
I use the default version, pip install ..., last week

**Comment by twopirllc** [comment]
Hello @replyxf,

**Again** You are running an out of date version.

> You need to update to the latest version as described on the Issue Form like so:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```
> Please upgrade and use help(ta.stoch) for the help on the correct parameters and then retest the different values and get back to me.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @replyxf,

Reopen if you still have an Issue.

Thanks,
KJ

**Comment by codesutras** [comment]
This issue seems to exist with Strategy implementation with params dict. it's working fine when we are passing keyword argument in Custom strategy. eg #{'kind': 'stoch',"k":15,"d":25,"smooth_k":10}
`
CustomStrategy = ta_p.Strategy(
    name="Testing Strategy Calculation",
    description="Testing",
    ta=[
        {"kind": "atr"},
        #{"kind": "sma", "length":13},
        #{"kind": "rsi","length":14},
        {"kind": "macd", "fast":15, "slow": 25,"signal":10},
        {'kind': 'stoch', 'params': (15, 25, 5)}
        #{'kind': 'stoch',"k":15,"d":25,"smooth_k":10}
    ]
)

`
### Expected behaviour 
Stoch kind should work in custom strategy with   {'kind': 'stoch', 'params': (15, 25, 5)} also.
