### ISSUE TITLE
trend_return doesn't accumulate either of return types

### ISSUE THREAD

**Issue by AlexStox** [twopirllc/pandas-ta#204]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python 3.8
pandas_ta 0.2.23b0
```
**Describe the bug**
I tried `log=False, cumulative = True` and in another case `log=True, cumulative = True`, but there are no cumulative returns in returns column for log returns or percent returns

**To Reproduce**
I can't attach my CSV here because couldn't find any option in this bug report, but I think this will work the same way for any SP500 daily data you have
```
import pandas as pd
import pandas_ta as ta
df = pd.read_csv("E:\Dropbox\Trading\Quotes\^spx_d.csv", sep=",")
df.set_index(pd.DatetimeIndex(df["Date"]), inplace=True)
MAstr = ta.trend_return(df['Close'], trend= df['Close'] > ta.sma(df['Close'], 50), log=False, cumulative = True)
print('\n MAstr \n',MAstr)
print('\n MAstr > 0 \n',MAstr[MAstr.CPTR_Trades>0])
print('\n MAstr <0 \n', MAstr[MAstr.CPTR_Trades<0])
```
OUTPUT:
```
 MAstr 
             CPTR  TR_PCTRET  CPTR_Trends  CPTR_Trades
Date                                                 
1920-01-02   0.0        NaN            0            0
1920-01-03   0.0        0.0            0            0
1920-01-05   0.0        0.0            0            0
1920-01-06   0.0        0.0            0            0
1920-01-07   0.0        0.0            0            0
         ...        ...          ...          ...
2020-10-26   0.0        0.0            0            0
2020-10-27   0.0        0.0            0            0
2020-10-28   0.0        0.0            0            0
2020-10-29   0.0        0.0            0            0
2020-10-30   0.0        0.0            0            0

[26803 rows x 4 columns]

 MAstr > 0 
             CPTR  TR_PCTRET  CPTR_Trends  CPTR_Trades
Date                                                 
1920-03-06   0.0        0.0            0            1
1920-07-01   0.0        0.0            0            1
1920-07-16   0.0        0.0            0            1
1920-08-20   0.0        0.0            0            1
1920-08-23   0.0        0.0            0            1
         ...        ...          ...          ...
2020-04-16   0.0        0.0            0            1
2020-04-23   0.0        0.0            0            1
2020-09-29   0.0        0.0            0            1
2020-10-02   0.0        0.0            0            1
2020-10-06   0.0        0.0            0            1

[814 rows x 4 columns]

 MAstr <0 
                 CPTR  TR_PCTRET  CPTR_Trends  CPTR_Trades
Date                                                     
1920-04-19  0.045541  -0.018319            1           -1
1920-07-15  0.007444  -0.009390            1           -1
1920-07-22  0.009505   0.004739            1           -1
1920-08-21  0.004813   0.004813            1           -1
1920-10-27  0.040070  -0.006881            1           -1
             ...        ...          ...          ...
2020-04-17  0.026794   0.026794            1           -1
2020-09-17  0.191401  -0.008412            1           -1
2020-10-01  0.013547   0.005293            1           -1
2020-10-05  0.017976   0.017976            1           -1
2020-10-23  0.031166   0.003446            1           -1

[814 rows x 4 columns]
```

**Expected behavior**
As MAstr  shows, no cumulative data, because 0 in the end, although there are trades

**Comment by twopirllc** [comment]
Hello @AlexStox,

Interesting. I'll take a look today, do you have a sample of the csv I can use? Otherwise I will use TradingView SPX data for this case.

Thanks,
KJ

**Comment by AlexStox** [comment]
> 
> 
> Hello @AlexStox,
> 
> Interesting. I'll take a look today, do you have a sample of the csv I can use? Otherwise I will use TradingView SPX data for this case.
> 
> Thanks,
> KJ

I would gladly share my file with you, but there is no option here. But you can download it using the [Pandas Stooq](https://pandas-datareader.readthedocs.io/en/latest/readers/stooq.html) or manually [on the Stooq website](https://stooq.com/q/d/?s=%5Espx&c=0&d1=19200101&d2=20200931)

**Comment by twopirllc** [comment]
@AlexStox,

Ok, this is what I have done. I have basically reiterated sample code in the [AIExample Notebook](https://github.com/twopirllc/pandas-ta/blob/master/examples/AIExample.ipynb). Sorry if it is all screenshots for now.

# Fetch Data and apply **SMA50**
<img width="398" alt="Screen Shot 2021-02-01 at 2 30 34 PM" src="https://user-images.githubusercontent.com/18198392/106526403-63f9f980-649a-11eb-9fe7-155af514c71a.png">

# Apply **trend_return()**
<img width="638" alt="Screen Shot 2021-02-01 at 2 30 51 PM" src="https://user-images.githubusercontent.com/18198392/106526465-868c1280-649a-11eb-9951-60136da2b4a7.png">

In fact, you could also append **trend_return()** to _df_ if you want. Up to you.

# Your Filters
<img width="418" alt="Screen Shot 2021-02-01 at 2 31 03 PM" src="https://user-images.githubusercontent.com/18198392/106526548-ade2df80-649a-11eb-890d-d1c673e0f97b.png">
<img width="410" alt="Screen Shot 2021-02-01 at 2 31 12 PM" src="https://user-images.githubusercontent.com/18198392/106526556-b20efd00-649a-11eb-91c0-cf2ae6dabcfc.png">

# Plot of Cumulative PCTRET (black) and PCTRET for the trend (blue)
<img width="682" alt="Screen Shot 2021-02-01 at 2 31 28 PM" src="https://user-images.githubusercontent.com/18198392/106526635-d36fe900-649a-11eb-950d-5abf442821d8.png">

# Entries, Exits, All Trades and Trade Log
<img width="672" alt="Screen Shot 2021-02-01 at 2 32 13 PM" src="https://user-images.githubusercontent.com/18198392/106527110-98ba8080-649b-11eb-8ac8-fc4d1f93dec5.png">

# Chart with Entries (lime) and Exits (fuchsia)
<img width="680" alt="Screen Shot 2021-02-01 at 2 32 23 PM" src="https://user-images.githubusercontent.com/18198392/106527100-91937280-649b-11eb-8ae3-09746bbc99ea.png">

# Long_Trend (green) and Short_Trend (red)
<img width="672" alt="Screen Shot 2021-02-01 at 2 31 34 PM" src="https://user-images.githubusercontent.com/18198392/106527120-9bb57100-649b-11eb-9e38-2d0659ecf804.png">

<br/>

Hope this helps! Let me know if you have any questions or something is still not working.

Kind Regards,
KJ

**Comment by AlexStox** [comment]
As I understood, I just have to use methods differently. 

1) What type of method would you recommend to use by default to avoid such errors? 

2) You can try this light but very powerful charting lib @highfestiva [finplot](https://github.com/highfestiva/finplot.git)

**Comment by twopirllc** [comment]
Hello @AlexStox,

> What type of method would you recommend to use by default to avoid such errors?

If you have a set of indicators you like, I recommend building your DataFrame using a . Check out the [Strategy Notebook](https://github.com/twopirllc/pandas-ta/blob/master/examples/PandasTA_Strategy_Examples.ipynb) for examples and don't hesitate to ask if you get stuck. However *trend_return()* does not run in _ta.strategy()_, so it would have to be run after _ta.strategy()_.

**Note:** Don't forget to check that your index is Datetime Ordered and preferably an index so you can take advantage of VWAP if you use it.

For example:
```python
import pandas as pd
import pandas_ta as ta

my_ta = [
    {"kind":"sma", "close": "close", "length": 50}, # "SMA_50"
    {"kind":"ema", "close": "volume", "length": 10, "prefix": "VOLUME"}, # "VOLUME_EMA_10"
]
my_system = ta.Strategy("Volume EMA and Price SMA50", my_ta)

# Long Logic for the strategy
long_condition = df.close > df["SMA_50"]

df = # your ohlcv data
df.ta.strategy(my_system)
df.ta.trend_return(trend=long_condition, append=True)

# Then some post trend_return analysis like above
# Some plotting ...
# Some AI/ML if that's what you also do ...
```

# You can try this light but very powerful charting lib @highfestiva finplot

Thanks! Will check it out. For fast charts, I use _matplotlib_ and I use _mplfinance_ for more sophisticated ones.

Hope this helps!

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @AlexStox,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by AlexStox** [comment]
Thank you. To be honest I've not checked that yet, because I stacked with other part of the code not related to yours :) But if it worked on your side, it should work on my side :) 

Thank you.
