### ISSUE TITLE
Unable to Use in GCP

### ISSUE THREAD

**Issue by jboshers1** [twopirllc/pandas-ta#207]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
pandas-ta>=0.2.23b
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
Fails on Import
**To Reproduce**
import pandas_ta as ta
ImportError: cannot import name 'version' from 'pandas_ta' (/env/local/lib/python3.7/site-packages/pandas_ta/__init__.py)

**Expected behavior**
The Module to Load

**Screenshots**
<img width="738" alt="Screen Shot 2021-02-01 at 10 00 40 PM" src="https://user-images.githubusercontent.com/50243740/106558818-45672300-64d9-11eb-87b2-61387c69e7b0.png">
<img width="1144" alt="Screen Shot 2021-02-01 at 10 00 24 PM" src="https://user-images.githubusercontent.com/50243740/106558820-45ffb980-64d9-11eb-8f9b-fa585fd70f6c.png">

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @jboshers1,

Try upgrading.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Then let me know.

Thanks,
KJ

**Comment by jboshers1** [comment]
Hi KJ, that didn't seem to work either. Am I missing something obvious? 
<img width="1280" alt="Screen Shot 2021-02-02 at 12 14 43 AM" src="https://user-images.githubusercontent.com/50243740/106579152-32624c00-64f5-11eb-9a65-621abfa64bd4.png">

**Comment by twopirllc** [comment]
Hello @jboshers1,

Unfortunately, I do not use GCP so I flagged this Issue for **Help Wanted** in case someone else has this Issue or knows of a solution.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @jboshers1,

Were you ever able to find a fix? Have you tried downloading the zip from Github and doing a manual ```pip install```?

Thanks,
KJ

**Comment by jboshers1** [comment]
Hi @twopirllc  - Yes! I had to upgrade the Python runtime to 3.8 and it worked without issue

**Comment by twopirllc** [comment]
@jboshers1,

Great! Glad to hear it was a simple fix.

Thanks,
KJ
