### ISSUE TITLE
Issue with SMA

### ISSUE THREAD

**Issue by chaudhary-v** [twopirllc/pandas-ta#208]
![image](https://user-images.githubusercontent.com/20244638/106646949-4b7e0200-65b4-11eb-8fe4-384ccaa9703e.png)

While I am trying to do a SMA crossover with SMA 5 and 15, it's giving me SMA 10 no matter what

**Comment by twopirllc** [comment]
Hello @chaudhary-v,

Upgrade to the latest version:
```sh
pip install -U git+https://github.com/twopirllc/pandas-ta
```

Then I will check it out as soon as I can.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @chaudhary-v,

Just noticed you misspelled "length" for your second **sma**.

Thanks,
KJ

**Comment by chaudhary-v** [comment]
Thanks, it was a silly mistake from my end.

**Comment by twopirllc** [comment]
Hi @chaudhary-v,

Still happens to me too.

Kind Regards,
KJ

**Comment by shikharvaish28** [comment]
Hello @chaudhary-v @twopirllc ,

I am trying to implement SMA crossover but am unable to do it. Can you please share the approach?
