### ISSUE TITLE
TD Seq strategy/indicator

### ISSUE THREAD

**Issue by rylos** [twopirllc/pandas-ta#209]
Hi! First of all, thank you for this fantastic library.
Just a request to add this indicator that works in a fantastic way for crypto markets:
[TD Sequential by probear](https://www.tradingview.com/script/t08BkTIg-TD-Sequential/)

What do you think? 
Thank you in advance.
Regards
Marco

**Comment by twopirllc** [comment]
Hello @rylos,

This has been requested, Issue #156, so near the top to be implemented. However I do not have an adequate time frame for completion. You are welcome to _fork_, _add_, and submit a _PR_ to get the process moving quicker as well as get contribution credit 😎 . I am closing the Issue as it is a duplicate. But the _probear_ version will also be considered when it gets implemented.

Thanks for using Pandas TA!

Kind Regards,
KJ
