### ISSUE TITLE
Separate features that take future time info into account

### ISSUE THREAD

**Issue by dorienh** [twopirllc/pandas-ta#210]
This library is great. I especially like that one can calculate all indicators in one nice command. I imagine that many folks, like me, use this as an input to a machine learning algorithm. 

However! (and correct me as I am wrong) Some indicators use future time information. E.g. zscore standardizes over the entire time series. In machine learning one is not supposed to do this (but we standardize on training and test set separately). 

This makes me wonder if other indicators, which I may not all be familiar with, use any future data as input. So far I hope it's just the statistical ones I should not include? 

Happy for any information on which are not calculated iteratively but already fed some future info (e.g. overall average, max etc. ).

**Comment by twopirllc** [comment]
Hello @dorienh,

> This library is great. I especially like that one can calculate all indicators in one nice command. I imagine that many folks, like me, use this as an input to a machine learning algorithm.

Thank you! It sure keeps me busy 🤣. Yes ```df.ta.strategy()``` anecdotally is popular for AI/ML practitioners. In my experience porting indicators and developing indicators, that is akin to throwing spaghetti at the wall hoping some thing sticks and still has value. Also there are indicators, different in some degree, have similar resultants like _Awesome Osc._, _Abosolute Price Osc._, _Bias_, et al. If they are normalized, are they really that much different?

<img width="764" alt="Screen Shot 2021-02-03 at 10 20 54 AM" src="https://user-images.githubusercontent.com/18198392/106791315-99712500-6609-11eb-9001-34dd85808c15.png">

If not, pick the best one. Try to reduce dimensions prior to applying TA features.

> However! (and correct me as I am wrong) Some indicators use future time information. E.g. zscore standardizes over the entire time series. In machine learning one is not supposed to do this (but we standardize on training and test set separately).

> This makes me wonder if other indicators, which I may not all be familiar with, use any future data as input. So far I hope it's just the statistical ones I should not include?

Yes. [Data Leaks](https://github.com/twopirllc/pandas-ta/issues?q=is%3Aissue+leak) have been brought up before and the concern has been addressed. In short, there are two indicators with [Potential Data Leaks](https://github.com/twopirllc/pandas-ta#features), **ichimoku** and **dpo** do. The README addresses how what to do with them. All of the statistical indicators are rolling window based calculations, they do not Data Leak. 
> Happy for any information on which are not calculated iteratively but already fed some future info (e.g. overall average, max etc. ).

Open Source, take a look 😎 . 

Hope this clarifies any questions. Thanks for using Pandas TA!

Kind Regards,
KJ

**Comment by dorienh** [comment]
Great answer, yes the data leaks is what I was looking for, perfect if most use rolling windows. 

As for the ML, yes many do seem correlated. In the initial big data approach we would do some feature selection which would probably remove highly correlated features, so using all of them works fine for now. When digging deeper we try to add indicators that would capture when our predictions go wrong :) Still working on that :)

**Comment by twopirllc** [comment]
> Great answer, yes the data leaks is what I was looking for, perfect if most use rolling windows.

No worries.

> As for the ML, yes many do seem correlated. In the initial big data approach we would do some feature selection which would probably remove highly correlated features, so using all of them works fine for now.

True

> When digging deeper we try to add indicators that would capture when our predictions go wrong :) Still working on that :)

Yeah. We all are. 😄 

KJ
