### ISSUE TITLE
Golden cross

### ISSUE THREAD

**Issue by dorienh** [twopirllc/pandas-ta#211]
A quite nice and often useful feature is the [golden cross and death cross](https://www.tradingview.com/scripts/goldencross/). From [Investopedia](https://www.investopedia.com/terms/s/sma.asp): 

_Two popular trading patterns that use simple moving averages include the death cross and a golden cross. A death cross occurs when the 50-day SMA crosses below the 200-day SMA. This is considered a bearish signal, that further losses are in store. The golden cross occurs when a short-term SMA breaks above a long-term SMA._ 

I've seen it defined slightly different as well: 

 _In the current version, the code can be run to test a strategy to go long when the 50-day moving average breaks above and stays above the 200-day moving by at least 15 points, go short when the 50-day moving average falls and stays below the 200-day moving average by at least 15 points, and hold the cash value on all other days. Interest on cash and transaction costs are ignored._

It's seems like that 15 point  buffer may be a setting. It's not super complex to calculate, as you can see [here](https://github.com/rtuhin/Golden-Cross).

**Comment by twopirllc** [comment]
Hello @dorienh,

I am unclear what you would like added to the library. I am familiar with the Golden Cross Strategy; trivial like Hello World.

> In the current version, the code can be run to test a strategy to go long when the 50-day moving average breaks above and stays above the 200-day moving by at least 15 points, go short when the 50-day moving average falls and stays below the 200-day moving average by at least 15 points, and hold the cash value on all other days. Interest on cash and transaction costs are ignored.

Do you need help building this Golden Cross variant?

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @dorienh,

Hope all is well. I am closing this Issue in a couple of days if I do not hear back from you regarding this enhancement and what you would like accomplished.

Kind Regards,
KJ

**Comment by dorienh** [comment]
Apologies for the late reply. I guess this boil down to if you want to include clear buy/sell signals as part of a strategy, or if you'll let people make those buy/sell signals themselves. The latter is not bad as it gives us more to think about :) I think we can close this for now.

**Comment by twopirllc** [comment]
Hello @dorienh,

No worries.

Thanks to contributions by @lluissalord and @rengel8, some indicators have built in signals. Current indicators with signals include: **er**, **macd**, **rsi** and **rsx** found when searching [if signal_indicators](https://github.com/twopirllc/pandas-ta/search?q=if+signal_indicators) in the source of this repo. They are keyword arguments.

For example:
```python
import pandas as pd
import pandas_ta as ta

df = pd.<your datasource>
# Cross above 80 and Cross below 20
lower, upper = 20, 80
df.ta.rsi(signal_indicators=True, cross_values=True, xa=upper, xb=lower, append=True)
print(df)
```

I would also check the source and play with the keyword arguments to get the signals you want.

### Signals for Indicators

Pandas TA has primarily been an indicator library with a few extra features for making it easy to append new features to a DataFrame. Moving forward, I think it is a good idea to add ```signal_indicators``` to more common indicators.

Kind Regards,
KJ
