### ISSUE TITLE
need help build RVI indicator

### ISSUE THREAD

**Issue by cbogithub** [twopirllc/pandas-ta#22]
hi , i  interested with pandas-ta , today i need help to build RVI indicator
i saw  how calc RVI on tradingview
```
rvgi = sum(swma(close - open), length) / sum(swma(high - low), length)
signal = swma(rvgi)
```
what i can replace sum func on tradingview with ?

i think i can do : 
x = swma(close - open).rolling(length)

y = swma(high - low).rolling(lenght)

rvi= x.sum() / y.sum()

**Comment by twopirllc** [comment]
Hi.  Thanks.

I can add it in.  But if you are using pandas_ta swma, you should pass in the proper length of it as it defaults to 10.  My preliminary test below was able to capture the RVGI.

import pandas_ta as ta
swma_length=4, length=14
num = ta.swma(close - open_, length=swma_length).rolling(length)
den = ta.swma(high - low, length=swma_length).rolling(length)
rvgi = num.sum() / den.sum()

Hope this helps.

**Comment by cbogithub** [comment]
thanks, so much

**Comment by twopirllc** [comment]
On TradingView, there is in fact multiple versions of swma. [TV User SWMAs](https://www.tradingview.com/scripts/swma/) as well as the built in [TV SWMA](https://www.tradingview.com/pine-script-reference/v3/) which is implemented in pandas_ta as swma.
<img width="730" alt="TV SWMA" src="https://user-images.githubusercontent.com/18198392/60772810-5f980f80-a0b0-11e9-9f1a-f0081c52558c.png">

Is the RVI indicator you originally posted above using TV's Symmetric Weighted Moving Average or Everget's Sine Weighted Moving Average that you just posted?  If using Everget's please provide a link so I have a reference to work with like you did with his Sine Weighted Moving Average.

**Comment by cbogithub** [comment]
Hi, thanks for answers. they are same. But i usually  found many different ways to work . Sorry if above question is stupid

**Comment by twopirllc** [comment]
Sure.

But I still do not understand which SWMA to use for RVI?  Everget's or TradingView's?

Thanks

**Comment by cbogithub** [comment]
I use Swma tradingview's to calc RVI

**Comment by cbogithub** [comment]
hi, but RVI indicator which your build lost a rvi signal : signal = swma(rvgi)
please  update
