### ISSUE TITLE
warning in running watchlist that ticker and function were mixed up

### ISSUE THREAD

**Issue by karenjh2** [twopirllc/pandas-ta#220]
I just downloaded this so must be latest version.

line 181
               # KJH change
                #df = self.ds.data(ticker, tf)
                df = self.ds.data(tf,ticker)
                # end of KJH change

I made the above change and I stopped getting the warning

**Comment by twopirllc** [comment]
Hello @karenjh2,

What version are you running of Pandas TA (as asked on the Bug Report)?

This installs the latest version which _normally_ solves most Issues. (Also requested to do in the Bug Report)
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

If your upgrade does not solve the Issue, please let me know.

Kind Regards,
KJ

**Comment by karenjh2** [comment]
I downloaded pandas-ta this morning, as I mentioned on one of the bug reports. I doubt there has been a version update since then. So it is the latest version.

 

 

Karen Higgins

**Comment by karenjh2** [comment]
I downloaded pandas-ta this morning, as I mentioned on one of the bug reports. I doubt there has been a version update since then. So it is the latest version.

 

 

 

Karen Higgins

**Comment by twopirllc** [comment]
Hello @karenjh2,

If you could _simply_ print the version and let me know, then I can be of more assistance. All you have to do is:
```python
import pandas_ta as ta
print(ta.version)
```

<br/>

> I downloaded pandas-ta this morning, as I mentioned on one of the bug reports. I doubt there has been a version update since then. So it is the latest version.

How did you download it? Saying you downloaded it this morning does not imply how you downloaded it. Which one you install _determines_ which version you are on.  

The Last stable version (_pypi_): _0.2.23b_
The Lastest version _(GitHub):_ _0.2.42b_

<br/>
As noted on the README:
<br/>

![Screen Shot 2021-02-08 at 5 26 20 PM](https://user-images.githubusercontent.com/18198392/107302801-cde24800-6a32-11eb-9925-976f5d0ce2f1.png)

Kind Regards,
KJ

**Comment by karenjh2** [comment]
0.2.23b0

 

 

Karen Higgins

**Comment by twopirllc** [comment]
Great! Please use the Latest versions moving forward.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Thanks,
KJ
