### ISSUE TITLE
yfinance not found in watchlist

### ISSUE THREAD

**Issue by karenjh2** [twopirllc/pandas-ta#221]
line 187

           # KJH start
            #elif isinstance(self.ds, yfinance):
            elif isinstance(self.ds,yf):
            # KJH end

This resolved it. The error was noted in editor. I did not get the error when running watchlist.

**Comment by twopirllc** [comment]
Hello @karenjh2,


What version are you running of Pandas TA (as asked on the Bug Report)? 

This installs the latest version which _normally_ solves most Issues. (Also requested to do in the Bug Report)
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Also please feel free to _fork_, _edit_ and submit _PRs_ to expedite bugs you have found. Everyone benefits and you get contribution credit 😎 .

Kind Regards,
KJ

**Comment by karenjh2** [comment]
Karen Higgins

**Comment by twopirllc** [comment]
Hello @karenjh2,

I have updated the ```watchlist.py``` to get yahoo finance working as well as update the notebooks.

Please upgrade to the latest version _0.2.45b_ and let me know if it is working better.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Thanks,
KJ

**Comment by karenjh2** [comment]
Thanks for the notice. I will do that.

 

And thanks for doing this. It is an impressive effort.

 

 

Karen Higgins

**Comment by twopirllc** [comment]
@karenjh2,

Thank you for your patience and using Pandas TA.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @karenjh2,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
