### ISSUE TITLE
watchlist error spawn_main - resolved, need if __name__ == '__main__':

### ISSUE THREAD

**Issue by karenjh2** [twopirllc/pandas-ta#222]
I use Pycharm, not Juypter.

I ran your example.
![image](https://user-images.githubusercontent.com/46858944/107282162-5a7a1e00-6aa6-11eb-9f34-083c311064bf.png)

![image](https://user-images.githubusercontent.com/46858944/107282223-6bc32a80-6aa6-11eb-8387-debb23d8c9b4.png)

**Comment by twopirllc** [comment]
Hello @karenjh2,

What version are you running of Pandas TA (as asked on the Bug Report)? 

This installs the latest version which _normally_ solves most Issues. (Also requested to do in the Bug Report)
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

This is **not** a Pandas TA bug. In fact, it is a Python multiprocessing Issue and the error message provides a solution. Furthermore, the _third_ pinned Issue, #181, addresses this. In the future, please look through the Issues before posting duplicates.

Kind Regards,
KJ
