### ISSUE TITLE
Long runtime when using df.ta.strategy

### ISSUE THREAD

**Issue by xqpoo9** [twopirllc/pandas-ta#223]
When using df.ta.strategy(), the run time is un usually high for me (around 500ms). This is compared to the runtime of creating the indicator directly using df.ta.sma which only takes a few ms total. I'm wondering if there's a way to improve the performance of the indicator generation.

```python
df = pd.DataFrame(CANDLES)

CustomStrategy = ta.Strategy(
    name="Test1",
    description="test1",
    ta=[
        {"kind": "sma", "length": 7, "close":"c"},
        {"kind": "sma", "length": 25, "close":"c"}
    ]
)
# To run your "Custom Strategy"
df.ta.strategy(CustomStrategy, timed=True, verbose=True)
```

```sh
      [+] Strategy: Test1. 
      [i] Indicator arguments: {'timed': True, 'append': True}. 
      [i] Multiprocessing: 4 of 4 cores. 
      [i] Total indicators: 2. 
      [i] Columns added: 2. 
      [i] Runtime: 555.9425 ms (0.5559 s). 
```

**Comment by twopirllc** [comment]
Hello @xqpoo9,

That is weird.

**Upgrade.** The **current** version is: ```v0.2.42b```
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

It would be great if you could run the following:
```python
import pandas as pd
import pandas_ta as ta

print(f"Pandas TA v{ta.version}")
CANDLES = # Your ohlcv source

print(f"CANDLES[{type(CANDLES)}]:\n{CANDLES}")
df = pd.DataFrame(CANDLES)
print(list(df.columns))

CustomStrategy = ta.Strategy(
    name="Test1",
    description="test1",
    ta=[
        {"kind": "sma", "length": 7, "close":"c"},
        {"kind": "sma", "length": 25, "close":"c"}
    ]
)
# To run your "Custom Strategy"
df.ta.strategy(CustomStrategy, timed=True, verbose=True)
print(df.head(15))
print(df.tail())
```

When you provide the above output, I will be able to help you more.

Kind Regards,
KJ

**Comment by xqpoo9** [comment]
Thanks KJ, 

<img width="1165" alt="Screen Shot 2021-02-08 at 10 47 53 PM" src="https://user-images.githubusercontent.com/63019253/107313030-bff6ec00-6a5f-11eb-8385-e230516bdf1e.png">

<img width="1161" alt="Screen Shot 2021-02-08 at 10 48 57 PM" src="https://user-images.githubusercontent.com/63019253/107313094-d8ff9d00-6a5f-11eb-80df-211241427e04.png">

By the way this is with python3, and pandas-ta was installed with pip3 install -U git+https://github.com/twopirllc/pandas-ta. I've also tried renaming the columns to the full text versions, eg "open" instead of "o".

**Comment by twopirllc** [comment]
Hi @xqpoo9,

So, good? Run time was 0.7329 secs. Or are you using a smaller data set from the original post?

<br/>

Also regarding default columns:
<img width="856" alt="Screen Shot 2021-02-08 at 8 25 38 PM" src="https://user-images.githubusercontent.com/18198392/107315689-0cd0c780-6a4c-11eb-8198-1ab767d7b09c.png">

<br/>

Also you might want to use a Pandas DatetimeIndex. For instance, **VWAP** requires it.

Thanks,
KJ

**Comment by xqpoo9** [comment]
Hi KJ,

Actually to clarify, if I generate indicators individually like below, they only take a few ms each (eg 3ms) compared to ta.strategy which took 732ms in the second case and 555ms in the first case with the same data set sizes. I was hoping to utilize the multiprocessing of ta.strategy to speed things up because even a few ms adds up when doing a few thousand generations of indicators.

        for interval in intervals:
            # Load the candles into pandas

            lastTime = (time.time_ns() // 1_000_000 )

            df = pd.DataFrame(combined)
            df.ta.sma(close="c", length=interval, append=True)

            print(
                f'Generating sma, length {interval}, Total time {(time.time_ns() // 1_000_000 ) - lastTime} ms'
            )

            // Generating sma, length 7, Total time 4 ms
            // Generating sma, length 25, Total time 2 ms
            // Generating sma, length 99, Total time 3 ms

**Comment by twopirllc** [comment]
@xqpoo9,

> Actually to clarify, if I generate indicators individually like below, they only take a few ms each (eg 3ms) compared to ta.strategy which took 732ms in the second case and 555ms in the first case with the same data set sizes.

Python multiprocessing is not as good as other languages. It's good for some cases but not all. 

> ... because even a few ms adds up when doing a few thousand generations of indicators.

I know.

### _development_ version

There is a _development_ version you can try that allows you to disable multiprocessing while using ```df.ta.strategy()```. _This_ is the perfect use case which _should_ solve what you discovered. If you are willing to test it out before I update GitHub, that would be great!

First uninstall pandas_ta and then run:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Then in the code, add ```df.ta.cores = 0``` **before** ```df.ta.strategy(CustomStrategy, timed=True, verbose=True)``` like below.

<br/>

### Updated Sample
```python
import pandas as pd
import pandas_ta as ta

print(f"Pandas TA v{ta.version}")
CANDLES = # Your ohlcv source

df = pd.DataFrame(CANDLES)
print(df.shape)
print(list(df.columns))

CustomStrategy = ta.Strategy(
    name="Test1",
    description="test1",
    ta=[
        {"kind": "sma", "length": 7, "close":"c"},
        {"kind": "sma", "length": 25, "close":"c"}
    ]
)
# Disable multiprocessing for df.ta.strategy()
df.ta.cores = 0
# To run your "Custom Strategy"
df.ta.strategy(CustomStrategy, timed=True, verbose=True)
print(df.head())
print(df.tail())
```

Would you mind testing it out to see if the performance improves?

Thanks,
KJ

**Comment by xqpoo9** [comment]
That's quite useful, thanks KJ.

With this I could get some speed improvements because pd.DataFrame only needs to be called once, and ta.strategy is overall a nice way to organize strategies. 

<img width="1149" alt="Screen Shot 2021-02-09 at 12 35 21 AM" src="https://user-images.githubusercontent.com/63019253/107320505-cfc9fc80-6a6e-11eb-8b55-25c9dae6d5eb.png">

After reading a bit more on the [multiprocessing](https://github.com/twopirllc/pandas-ta/blob/98478f8bf049a4c8748d6f3c795f4f335ced05ca/pandas_ta/core.py#L669), it's likely due to the overhead of creating processes. I dont know enough about it, but would be cool if there was a way to keep these processes alive and feed new candles into them or somehow utilize multi processes. I tried running these in threads earlier and had a similar result

**Comment by twopirllc** [comment]
@xqpoo9,

> That's quite useful, thanks KJ.

You're welcome. No worries. Thanks for testing it out!

> With this I could get some speed improvements because pd.DataFrame only needs to be called once, and ta.strategy is overall a nice way to organize strategies.

Yeah. Essentially, you can pass _json_ into the ```ta``` parameter of ```ta.Strategy(ta=indicators_json)```.

> After reading a bit more on the multiprocessing, it's likely due to the overhead of creating processes.

Yup, plus a basic loop is fine for a small subset of indicators... but not all the indicators.

> I dont know enough about it, but would be cool if there was a way to keep these processes alive and feed new candles into them or somehow utilize multi processes. I tried running these in threads earlier and had a similar result.

That would be pretty cool. I wish I had more time to play around with it and get something potentially working.

I will try this week and push the development build to GitHub; I'll let you know. But thanks for testing the _development_ build. I appreciate it!

Thanks,
KJ
