### ISSUE TITLE
class diagrams and uses cases 

### ISSUE THREAD

**Issue by ALT-KIK** [twopirllc/pandas-ta#225]
I am University student and my job is to make class diagrams and uses cases for some project. I chose this project and can make it. Ofc if you need it

**Comment by twopirllc** [comment]
Hello @ALT-KIK,

Feel free. I would be interested in seeing what you come up with. However, I am curious why you chose this repo even though you have never ⭐ ed it nor interacted with me beforehand? Do you even know what this library is and what it does?

Kind Regards,
KJ

**Comment by ALT-KIK** [comment]
I haven't dived into code yet. But as I understood it is library for tech analysis?

**Comment by twopirllc** [comment]
Basically
