### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'name'

### ISSUE THREAD

**Issue by franson-git** [twopirllc/pandas-ta#226]
Hi,
I am using pandas_ta 0.2.23b0 version
when I request a sma length higher than my data I get an error : 

AttributeError: 'DataFrame' object has no attribute 'name'

For example : 

CODE:

```python
df = some_very_large_pandas_dataframe

print(df.shape)

MyStrategy = ta.Strategy(
    name="my strategy",
 description="SMA 2000, BBANDS, RSI, MACD and Volume SMA 20",
    ta=[
        {"kind": "sma", "length": 2000},
        {"kind": "bbands", "length": 20},
        {"kind": "rsi"},
        {"kind": "macd", "fast": 8, "slow": 21},
        {"kind": "sma", "close": "volume", "length": 20, "prefix": "VOLUME"},
    ]
)
df.ta.strategy(MyStrategy)
```

RESPONSE:

```sh
(1276, 11) 
[X] BBANDS_20_2.0 column(s) values are all na: SMA_2000
[X] RSI_14 column(s) values are all na: SMA_2000
[X] MACD_8_21_9 column(s) values are all na: SMA_2000

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-98-dbabdc2df15d> in <module>
     20     ]
     21 )
---> 22 df.ta.strategy(MyStrategy)
     23 

~/anaconda-installation/envs/francisco-conda-venv/lib/python3.7/site-packages/pandas_ta/core.py in strategy(self, *args, **kwargs)
    682         # Apply prefixes/suffixes and appends indicator results to the
    683         # DataFrame
--> 684         [self._post_process(r, **kwargs) for r in results]
    685 
    686         if timed:

~/anaconda-installation/envs/francisco-conda-venv/lib/python3.7/site-packages/pandas_ta/core.py in <listcomp>(.0)
    682         # Apply prefixes/suffixes and appends indicator results to the
    683         # DataFrame
--> 684         [self._post_process(r, **kwargs) for r in results]
    685 
    686         if timed:

~/anaconda-installation/envs/francisco-conda-venv/lib/python3.7/site-packages/pandas_ta/core.py in _post_process(self, result, **kwargs)
    449             # Add prefix/suffix and append to the dataframe
    450             self._add_prefix_suffix(result=result, **kwargs)
--> 451             self._append(result=result, **kwargs)
    452         return result
    453 

~/anaconda-installation/envs/francisco-conda-venv/lib/python3.7/site-packages/pandas_ta/core.py in _append(self, result, **kwargs)
    362             elif len(na_columns):
    363                 print(
--> 364                     f"[X] {result.name} column(s) values are all na: {', '.join(na_columns)}"
    365                 )
    366                 return

~/anaconda-installation/envs/francisco-conda-venv/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140 
   5141     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'name'

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Here the error is that my dataframe has 1276 rows which is less than sma length, in this case 2000, then
I would like to ignore this error when data is smaller than indicator parameter or customize the parameter. I will customize the parameter with a pythonist method but I want to know if there is a pandas_ta form of doing it.

Thanks you very much

**Comment by twopirllc** [comment]
Hello @franson-git,

First off, please use the Latest Version:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

> Here the error is that my dataframe has 1276 rows which is less than sma length, in this case 2000, then
I would like to ignore this error when data is smaller than indicator parameter or customize the parameter. I will customize the parameter with a pythonist method but I want to know if there is a pandas_ta form of doing it.

There is no immediate solution to passing in data smaller than an indicator window size. The Pandas TA ```strategy``` method would need to be modified to kick out indicators that have that case. I am curious why one would intentionally pass in less data than required for an indicator?

Kind Regards,
KJ

**Comment by franson-git** [comment]
Obviously I am not interested to passing in data smaller than an indicator window size, I am interested to kick out in these cases.
Thank you for the update link and your response.
This issue is closed.

**Comment by twopirllc** [comment]
@franson-git,

> Obviously I am not interested to passing in data smaller than an indicator window size, I am interested to kick out or make a custom method in these case.
Thank you for the update link and your response.
This issue is closed for me at the moment.

Whew! Anyhow, I revisited the code and have I think a _decent_ fix but only for "length" attribute at this time. But this should do for the **majority** of indicators.

You can test locally by adding the following code here [pandas_ta/core.py Line 628](https://github.com/twopirllc/pandas-ta/blob/98478f8bf049a4c8748d6f3c795f4f335ced05ca/pandas_ta/core.py#L628) and before the _verbose_ section.

```python
        # Remove indicators with "length" keyward when larger than the DataFrame
        removal = []
        for kwds in ta:
            _ = False
            if "length" in kwds and kwds["length"] > self._df.shape[0]:
                _ = True
            if _: removal.append(kwds)
        [ta.remove(x) for x in removal]
```

Let me know if that helps.

Kind Regards,
KJ

**Comment by franson-git** [comment]
Yes ! this is now my response when I execute this CODE:

`df = very_large_pandas_data_frame
print(df.shape)

MyStrategy = ta.Strategy(
    name="my strategy",
 description="SMA 2000, BBANDS, RSI, MACD and Volume SMA 20",
    ta=[
        {"kind": "sma", "length": 2000},
        {"kind": "bbands", "length": 20},
        {"kind": "rsi"},
        {"kind": "macd", "fast": 8, "slow": 21},
        {"kind": "sma", "close": "volume", "length": 20, "prefix": "VOLUME"},
    ]
)
df.ta.strategy(MyStrategy)`

REPONSE:

`(1278, 11)
[X] Not an available strategy.`

**Comment by twopirllc** [comment]
@franson-git,

Hmmm... ok. I'll spend more time on it and fix it up.

Thanks for the feedback!
KJ

**Comment by twopirllc** [comment]
Hello @franson-git,

The latest version, _0.2.45b_, is up:
```sh
$ pip install -U pandas_ta
```

Please update and check out the fix for this case. Your feedback would be great!

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @franson-git,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
