### ISSUE TITLE
Can't change VWAP default anchor setting 'D' to minutes 'Min'

### ISSUE THREAD

**Issue by nasser-miah** [twopirllc/pandas-ta#228]
Hi, I'm trying to change the default anchor setting on the VWAP indicator, i.e. from 'D' for Days to Minutes, but can't seem to change it. It still chooses 'D'. This is my CustomStrategy:

    # Create your own Custom Strategy
    CustomStrategy = ta.Strategy(
        name="Momo and Volatility",
        description="SMA 50,200, BBANDS, RSI, SQZ, MACD, STOCH and Volume SMA 20",
        ta=[
            {"kind": "ema", "length": 10},
            {"kind": "vwap", "anchor": "Min"},
        ]
    )

What am I doing wrong?

**Comment by twopirllc** [comment]
Hello @nasser-miah,

This sounds like an Issue with your DataFrame DatetimeIndex timeframe resolution and not Pandas TA. Since you provided nothing but sample code **and** no data, I can not assist you further. Note: **vwap** does not resample data to different timeframes and it requires the DataFrame index to be a DatetimeIndex.

As stated at the bottom of the README regarding **vwap** in _Update Indicators_: See [Timeseries Offset Aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases) for additional options. 

Also what timeframe is your DataFrame in? By wanting "Minutes", I assume your DataFrame DatetimeIndex is already in Minute resolution. Or is your DataFrame DatetimeIndex in Daily resolution and you want it in Minute Resolution?

Kind Regards,
KJ

**Comment by nasser-miah** [comment]
Hi @twopirllc, I have my dataset in minutes resolution, but looking further into what was installed from pip it seems the version pandas-ta (0.2.23b0) does not have the anchor parameter at all in vwap.py, which probably fixes the timeseries issues your saying. So I guess I am running an old version then? I also tried pip reinstalling the pandas_ta package but got back the same "old" version... when will you be releasing a new stable package?

**Comment by twopirllc** [comment]
Hello @nasser-miah,

To install the Latest Version per the README:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

> when will you be releasing a new stable package?

I will be releasing a new Stable version to PyPi when I get through some more outstanding Issues and PRs. Pandas TA is open to contributions in solving Issues as well as new creating new indicators, metrics, and features.

Kind Regards,
KJ

**Comment by nasser-miah** [comment]
Hi @twopirllc ,

I installed the latest version pandas-ta (0.2.42b0) as per your instruction and after trying to run my code am now getting this following traceback error for vwap:

line 23, in vwap
    vwap  = wp.groupby(wp.index.to_period(anchor)).cumsum()
AttributeError: 'RangeIndex' object has no attribute 'to_period'

And in addition to that I am also getting following infos:

[!] VWAP volume series is not datetime ordered. Results may not be as expected.
[!] VWAP price series is not datetime ordered. Results may not be as expected.

Mind you though that this crash exit never happened on the Stable version with vwap configured either via a custom strategy or running all strategies. As a workaround I am excluding vwap before running the strategy for the Latest version. To be honest I have no clue why or have insufficient pandas knowledge to figure this out it in near future time, ... You will probably spot my mistake before that ... 

This can be reproduced with the following code, see attachment.

[pandas_ta_vwap_issue.py.txt](https://github.com/twopirllc/pandas-ta/files/5978401/pandas_ta_vwap_issue.py.txt)

**Comment by twopirllc** [comment]
Hi @nasser-miah,

> I installed the latest version pandas-ta (0.2.42b0) as per your instruction and after trying to run my code am now getting this following traceback error for vwap:

Great! Thanks for upgrading.

> This can be reproduced with the following code, see attachment.
pandas_ta_vwap_issue.py.txt

Awesome! Thanks for providing me with reproducible code.

Please give the following code a run and let me know:
```python
import sys
import requests
import pandas as pd
import pandas_ta as ta

symbol = 'USDT-BTC'
data = requests.get(f"https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName={symbol}&tickInterval=oneMin").json()

df = pd.DataFrame(data['result'])
df.rename(columns={'T':'time', 'O':'open', 'C':'close', 'H':'high', 'L':'low', 'V':'volume'}, inplace=True)
df.set_index(pd.DatetimeIndex(df['time']), inplace=True, drop=True)
df.drop(columns="time", axis=1, inplace=True)

def custom_strategy_settings():
    # Create your own Custom Strategy
    CustomStrategy = ta.Strategy(
        name="Momo and Volatility",
        description="SMA 50,200, BBANDS, RSI, SQZ, MACD, STOCH and Volume SMA 20",
        ta=[
            {"kind": "ema", "length": 10},
            {"kind": "vwap", "anchor": "Min"},
        ]
    )
    # To run your "Custom Strategy"
    return CustomStrategy

df.ta.strategy(custom_strategy_settings())
#df.ta.strategy(exclude=["vwap"], verbose=True)
# df.ta.strategy()

print(df.columns)

df[["close", "VWAP_MIN"]].tail(100).plot(figsize=(16,10), color=["black", "blue"], grid=True)
```

> And about your contribution comment, sure, if I find anything will definitely make a PR. I just want to say that this package is awesome, gold stars to you and the team for maintaining this.

Thank you. We appreciate it. Any contribution would be great, even if it is fixing documentation or providing useful examples in a Notebook.

Thanks,
KJ

**Comment by nasser-miah** [comment]
Hi @twopirllc, thanks buddy for your help, it works great! I however changed the vwap anchor from minute scale to hourly and can now make use of it in technical analysis minute charts. Just a question though, is that last line supposed to plot something? If so, it did not work for me...

**Comment by twopirllc** [comment]
Hello @nasser-miah,

Glad you were able to get it working! Yes, the last line is for plotting. Should be able to throw the code into a Jupyter Notebook run it and it will plot it (for visual verification).

Kind Regards,
KJ

**Comment by nasser-miah** [comment]
Aha, nice, is it interactive? I was looking for such a feature for some time, and finally stumbled upon finplot for visualizing, it gives you an interactive plot window. Works great ... [https://github.com/highfestiva/finplot](https://github.com/highfestiva/finplot), check the example 2, it was in there that I tried using vwap and got stuck.

**Comment by twopirllc** [comment]
Hi @nasser-miah,

Sorry for the late reply. No it's a basic matplotlib/pandas chart to see if things look visually correct.

> I was looking for such a feature for some time, and finally stumbled upon finplot for visualizing, it gives you an interactive plot window. Works great ... https://github.com/highfestiva/finplot, check the example 2

Nice! Thanks for the reference, I will check it out. Interactive is better for trading for sure.

Thanks,
KJ
