### ISSUE TITLE
[question]why rsi value in pandas-ta not same rsi value in talib ?

### ISSUE THREAD

**Issue by cbogithub** [twopirllc/pandas-ta#23]
```
import math
import numpy as np
import pandas as pd

import talib
import pandas_ta as talib_pd





length =2
src  =   [1,2,3,5,6,9,-1,-9,3,5,6,9,9,-1,-9,3,5]
offset = 0



src_pd = pd.Series( np.array(src,dtype=float))



rsi=talib.RSI(np.array(src,dtype=float),14)


rsi_pd = talib_pd.rsi(src_pd,14)

print("rsi Talib", rsi)

print("rsi pandas-talib",rsi_pd.values)
```

and resulst: 

```
[rsi Talib [        nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan 41.93548387 51.95071869 53.39359583]

rsi pandas-talib [         nan 100.         100.         100.         100.
 100.          62.51832437  47.3167885   62.11972178  63.92955682
  64.82974757  67.44149959  67.44149959  52.51802285  44.14507698
  55.53754539  57.10006328]]
```

**Comment by twopirllc** [comment]
### Short Answer
You are absolutely correct.  They are not the same.  There are two primary reasons for the difference:
- pandas_ta is not implemented exactly like talib.  Even if it was, then it could have differences related to the next bullet point.
- There are precision differences between C++ and Python.

### pandas_ta Tests and Possible Correlation Differences with talib
In fact, RSI is not the only indicator that differs from talib.  Just run:
`> python -m unittest discover -v`
This will list all the tests and list those that have less than 0.99 correlation with talib, if there is a corresponding indicator in talib, like:
<img width="454" alt="NAT_14 talib correlation" src="https://user-images.githubusercontent.com/18198392/60772223-278cce80-a0a8-11e9-9890-38ece1e85fc7.png">

### Chart Differences
However I am not overtly concerned about the differences between talib and pandas_ta RSI at this point.  In fact, here are the charts of TradingView's built in RSI and pandas_ta RSI.
<img width="715" alt="SPY RSI14 TV" src="https://user-images.githubusercontent.com/18198392/60772313-63746380-a0a9-11e9-869d-127efbfdd6e8.png">

<img width="685" alt="SPY RSI14 pandas_ta" src="https://user-images.githubusercontent.com/18198392/60772416-e2b66700-a0aa-11e9-8841-bd749eb7f940.png">
Clearly the RSI is unequivocally highly correlated with a third party such as TradingView's Pine language as are many of pandas_ta's indicators, including those that have less than 0.99 correlation with talib.

### Conclusion
Use what works best for you, either library or both in combination to suit your purposes and desired level of precision.  Lastly, pandas_ta was not designed to be another wrapper for talib.

**Comment by cbogithub** [comment]
Thank for clear reply. I only know why they are different .and i not compare them
