### ISSUE TITLE
true_range() function are not propagating drift parameter in the inputs - NaN values.

### ISSUE THREAD

**Issue by ffhirata** [twopirllc/pandas-ta#237]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
0.2.45b0
```

**Describe the bug**
The true_range calculation is valid when its inputs ([high_low_range, high - prev_close, prev_close - low]) are valid. This assumption is not occurring in the beginning of the data series, due shift caused by drift parameter.

The true_range() function has the argument drift which is a shift in the data series. This causes introduction of NaN (depends on numbers of shifts) in the beginning of the data serie **close_prev**. So, every calculation that relies on first series are using NaN as input. The bug is that true_range() assumes NaN as a valid input, so the results are compromised to a partial calculation, which I think it is incorrect. This error propagates to subsequent calculations, for instance average.

**To Reproduce**
Inputs: [testDataframe.zip](https://github.com/twopirllc/pandas-ta/files/6076419/testDataframe.zip)

```python
if __name__ == '__main__':

    # read input data with expected results
    # columns are: close, close_prev, high, low, true_range, true_range_expected_result, ATR_SMA_20_expected_result
    filenamePath = r'D:\scripts\trade\ta_analysis_pr\testDataframe.csv'
    df = pd.read_csv(filenamePath, sep=';')

    # calculate true range for all rows
    df.ta.true_range(append=True)
    # calculate SMA_20 based on true_range
    atr = ta.sma(df.TRUERANGE_1, length=20)
    # join SMA result
    df = df.join(atr)

    print(df[['close_prev', 'true_range_expected_result', 'TRUERANGE_1']])
    # compare columns true_range_expected_result vs. TRUERANGE_1
    # check df.TRUERANGE_1[0]=0.32, true_range() is returning a partial value, because df.close_prev[0]=NaN, i.e., the function doesn´t have all valid inputs (close, close_prev, high, low) to provide a valid value.
    print(df[['TRUERANGE_1', 'ATR_SMA_20_expected_result', 'SMA_20']])
    # compare columns ATR_SMA_20_expected_result vs. SMA_20
    # check df.SMA_20[19]=0.9495, the result is partial because true_range assumed close_prev as NaN in the first cycle. Due previous error, the sma calculated incorrect.

    df.to_csv(r'D:\scripts\trade\ta_analysis_pr\testDataframe_result.csv', index=True)
```

**Expected behavior**
The attachment shows an example of calculation of arithmetic average calculation based on true_range results.
[testDataframe_result.xlsx](https://github.com/twopirllc/pandas-ta/files/6076413/testDataframe_result.xlsx)

The changes in close_prev due shift (introducing NaN) should propagate to inputs of calculation of:
`true_range = true_range.abs().max(axis=1)`
I did a proposed solution in:
https://github.com/ffhirata/pandas-ta/tree/ffhirata-patch-1

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @ffhirata,

Thank you for providing details and analysis. It helps a lot! 

Something is afoot. There is a difference in the initial value between Pandas TA and TA Lib. 

<img width="498" alt="Screen Shot 2021-03-04 at 9 29 47 AM" src="https://user-images.githubusercontent.com/18198392/110004434-481d8980-7ccc-11eb-9960-4641fa77cfea.png">

<br/>

It is a simple fix to correct it to TA Lib output (which is my baseline correlation testing library). Namely just adding the line to ```true_range.py```.

```python
def true_range(...):
    # ...
    true_range = true_range.abs().max(axis=1)
    true_range.iloc[0] = npNaN # <--- fix to match TA Lib
    # ...
```

Thus now matching. Will this work?

<img width="266" alt="Screen Shot 2021-03-04 at 10 08 14 AM" src="https://user-images.githubusercontent.com/18198392/110009294-abf68100-7cd1-11eb-8e27-85c139daa3eb.png">

Please verify on your end that if this fix works and fits the bug in question.

Kind Regards,
KJ

**Comment by ffhirata** [comment]
Hi twopirllc,

So, the code you sent will fix when drift=1.

def true_range(high, low, close, drift=None, offset=None, **kwargs):

true_range.iloc[0] = npNaN # <--- fix to match TA Lib, it fixes only
for the first item when drift=1 or None.

When I fixed in true_range() I did the same error:

    # Calculate Result
    prev_close = close.shift(drift) # first element is nan
    # changes ffh, to be compatible with prev is nan
    high_low_range[0] = float('nan')

I tried to do for n drift:

    lstNan = [float('nan')] * drift
    high_low_range = pd.Series(lstNan).append(high_low_range[drift:])

I don´t know if there is other clear solution to set NaN in the
beginning of the series according to drift argument.

Kind regards,

ffhirata


Em qui., 4 de mar. de 2021 às 15:43, Kevin Johnson <notifications@github.com>
escreveu:

**Comment by twopirllc** [comment]
@ffhirata,

Oops! You are right. Was juggling a few things and forgot the ```drift``` case of leading NaNs. I have some code elsewhere in the library to fix that. Just need to dig it up and patch. Thanks again for looking into this and helping. I appreciate it.

Kind Regards,
KJ

**Comment by ffhirata** [comment]
Happy to help!

Em qui., 4 de mar. de 2021 às 20:13, Kevin Johnson <notifications@github.com>
escreveu:

**Comment by twopirllc** [comment]
Hello @ffhirata,

This should do the trick. It would be great if you test it and make a PR so you can be added as a contributor.

```python
def true_range(...):
    # ...
    true_range = true_range.abs().max(axis=1)
    true_range.iloc[:drift] = npNaN # << fix
    # ...
```

Thanks,
KJ
