### ISSUE TITLE
cant use pool after set core zero in pandas-ta . Error : module 'multiprocessing' has no attribute 'pool'

### ISSUE THREAD

**Issue by mjheydari** [twopirllc/pandas-ta#239]

**Comment by twopirllc** [comment]
Hello @mjheydari,

I do not understand what you are trying to accomplish and how I can help you with so few details provided. (You do realize that I can not read minds and infer your context with limited to no information?)

What is the point of?
```python
pl = mp.pool.Pool()
```

Kind Regards,
KJ

**Comment by twopirllc** [comment]
??
