### ISSUE TITLE
Sine Weighted Moving Average

### ISSUE THREAD

**Issue by twopirllc** [twopirllc/pandas-ta#24]
I see on  Tradingview script calc SWMA very simple, how to convert it to python use pandas ? :  https://www.tradingview.com/script/6MWFvnPO-Sine-Weighted-Moving-Average/

PI = 2 * asin(1)
sum = 0.0
weightSum = 0.0

for i = 0 to length - 1
    weight = sin((i + 1) * PI / (length + 1))
    sum := sum + nz(src[i]) * weight
    weightSum := weightSum + weight

swma = sum / weightSum
```

_Originally posted by @cbogithub in https://github.com/twopirllc/pandas-ta/issues/22#issuecomment-508996474_

**Comment by twopirllc** [comment]
Everget the author of Sine Weighted Moving Average has approved publishing it.  I will push it out in the next day or so.

**Comment by cbogithub** [comment]
I hope soon.
Thanks
