### ISSUE TITLE
are the indicators always in a different order in the dataframe?

### ISSUE THREAD

**Issue by copypasteearth** [twopirllc/pandas-ta#241]
hello I am using this

```python
def get_data():
    """
    Gets data from CSV (0 - AAPL, 1 - MSI, 2 - SBUX).
    :return: T x 3 Stock Prices
    """
    ticker = yf.Ticker("AAPL")
    df = ticker.history(period='1y',interval='1d')

    df = df.dropna()
    df.ta.strategy()
    df = df.fillna(0)
    with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
        print(df[0:10][0:10])
    exit()
    indexess = df.index
    retdats = df.copy(deep=True)
 
    return df, indexess, retdats
```

and everytime i use it the indicators are in different columns, is there a way for the indicators to persist their order in the dataframe on every run. sorry this is probably not a bug but i need a way for the indicators to stay in the same column every run. thank you for your time

**Comment by copypasteearth** [comment]
i actually just sorted the columns, i think that will work

**Comment by twopirllc** [comment]
Hello @copypasteearth,

That is correct, by default ```df.ta.strategy()``` uses ```imap_unordered()``` for it's [Process Pool](https://docs.python.org/3/library/multiprocessing.html). Users had wanted speed versus order; especially with so many indicators.

I can optionally added an ordered version of ```df.ta.strategy()``` using ```imap()``` with a keyword argument but it seems sorting the columns post-processing works as well.

Kind Regards,
KJ

**Comment by copypasteearth** [comment]
Yeah, thanks for the info. Now that I sorted it I am getting the expected output.

Thanks again.

**Comment by twopirllc** [comment]
@copypasteearth,

No worries. Thanks for using Pandas TA!

KJ
