### ISSUE TITLE
Question about trade_offset parameter in trend_return()

### ISSUE THREAD

**Issue by edwardwang1** [twopirllc/pandas-ta#242]
Hi,

First off, I wanted to thank you for your work on this project. It's been a blast using it so far. I have a question related to trend_return(). When I specify the trade_offset parameter as 0, the trade column is shifted as would be the case if trade_offset was equal to -1.  I hope the tables below will better illustrate the behaviour.

From looking at the source code, it seems that this behaviour is intentional because the following line returns -1 if trade_offset=0. 

For my own understanding, why is the default trade_offset -1? It would seem to me that by shifting the trade backwards by 1, you are incorporating future information in the the previous timepoint. 

`trade_offset = int(trade_offset) if trade_offset and isinstance(trade_offset, int) else -1`

trade_offset = -1
| Time |CPTR_Trends|CPTR_Trades|
| ------------- | ------------- | ------------- |
| 2021-02-12 14:00:00  | 0  | 0 |
| 2021-02-12 15:00:00  | 0  | 1  |
| 2021-02-12 16:00:00  | 1  | 0  |
| 2021-02-12 17:00:00  | 1  | 0  |
| 2021-02-12 18:00:00  | 1  | 0  |

trade_offset = 0
| Time |CPTR_Trends|CPTR_Trades|
| ------------- | ------------- | ------------- |
| 2021-02-12 14:00:00  | 0  | 0 |
| 2021-02-12 15:00:00  | 0  | 1  |
| 2021-02-12 16:00:00  | 1  | 0  |
| 2021-02-12 17:00:00  | 1  | 0  |
| 2021-02-12 18:00:00  | 1  | 0  |

trade_offset = 1
| Time |CPTR_Trends|CPTR_Trades|
| ------------- | ------------- | ------------- |
| 2021-02-12 14:00:00  | 0  | 0 |
| 2021-02-12 15:00:00  | 0  | 0  |
| 2021-02-12 16:00:00  | 1  | 0  |
| 2021-02-12 17:00:00  | 1  | 1  |
| 2021-02-12 18:00:00  | 1  | 0  |

**Comment by edwardwang1** [comment]
Hi @twopirllc 

Thanks for the quick response, and for pointing me to the discussion. Regarding the issue above, I forked pandas-ta and made a change to the trend_return() that seemed to do the trick.

Replace
` trade_offset = int(trade_offset) if trade_offset and isinstance(trade_offset, int) else -1` 

With
`    if trade_offset !=0:
 trade_offset = int(trade_offset) if trade_offset and isinstance(trade_offset, int) else -1`


Thank you!

**Comment by twopirllc** [comment]
@edwardwang1,

Excellent! Submit a PR for contribution 😎 .
 
Thanks,
KJ

**Comment by edwardwang1** [comment]
Submitted!
