### ISSUE TITLE
How to apply all indicators using one line ?

### ISSUE THREAD

**Issue by rushidarge** [twopirllc/pandas-ta#245]
**Which version are you running? The lastest version is Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @rushidarge,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by rushidarge** [comment]
Thank you so much....
