### ISSUE TITLE
RVI indicator

### ISSUE THREAD

**Issue by cbogithub** [twopirllc/pandas-ta#25]
https://github.com/twopirllc/pandas-ta/issues/22.

thanks for build it in pandas-ta , but RVI indicator which your build was lost " `rvi signal" :signal = swma(rvgi) `  ( RVI indicator have 2 line rvi and rvi signal)

**Comment by twopirllc** [comment]
You mean it is missing the signal component?  Oops!  I'll add that in.  Thanks for spotting the issue.

In the mean time, you can do:

```python
rvi = ta.rvi(close)
rvi_signal = ta.swma(rvi, length=14)
```
