### ISSUE TITLE
Add Progress bars!

### ISSUE THREAD

**Issue by sweg44** [twopirllc/pandas-ta#254]
Hi guys,

I think that a progress bar when running a strategy on a df would be a great feature because I am always frustrated when I have to keep checking back on the progress of my strategies (most of the data I use is >1Mn rows) and so a progress bar - like those you see in the package "tqdm" would be great,

`Simple Example of Progress Bars when running a for loop`
`from tqdm import tqdm`
`direction = []`
`for i in tqdm(range(len(df))):`
    `if df.iloc[i, 0] > df.iloc[i+1, 1]:`
        `direction.append(0)`
    `else:`
        `direction.append(1)`

**Comment by twopirllc** [comment]
Hello @sweg44,

Thanks for using Pandas TA!

That sounds like a good idea. By default it will be off, as I want to keep Pandas TA as headless as possible. Unfortunately I do not have an ETA but will try and work it in as soon as I can. Or someone else if they want to get it incorporated sooner.

Kind Regards,
KJ
