### ISSUE TITLE
Unexpected results on Chande-Kroll stop indicator

### ISSUE THREAD

**Issue by luisbarrancos** [twopirllc/pandas-ta#256]
Hi. I couldn't find a mailing list to ask this directly.

According to the book *"The New Technical Trader"* by Chande & Kroll (1st ed, Wiley, ISBN 9780471597803), on page 95, the CK **long** stop is calculated by computing a 10 day simple moving average of the ATR, which they name *ATR_10*, to which we subtract 3*ATR_10 from highest high of the last 10 days. This quantity will be the preliminary long stop. The final long stop will be the highest value of the preliminary long stop over a 20 day period.

There seem to be some discrepancies however. According to the book then, the p value is 10, x = 3, q = 20, and the MA mode is a simple moving average.
However https://github.com/twopirllc/pandas-ta/blob/a31489af18f8a23f36a1831d1f3c5bbd37a930c9/pandas_ta/trend/cksp.py#L19 has the ATR call without specifying a MA mode, which defaults to the Wilder moving average. This and the 1st step only would be similar to the Donchian channels if i'm not mistaken. The defaults aren't matching the defaults from the book either at https://github.com/twopirllc/pandas-ta/blob/a31489af18f8a23f36a1831d1f3c5bbd37a930c9/pandas_ta/trend/cksp.py#L13
The implementation sketch from the reference at https://github.com/twopirllc/pandas-ta/blob/a31489af18f8a23f36a1831d1f3c5bbd37a930c9/pandas_ta/trend/cksp.py#L63 , namely [here](https://www.multicharts.com/discussion/viewtopic.php?t=48914)
seems to be in conflict with the idea expressed in the book as well:

> first high stop = HIGHEST[p](high) - x * Average True Range[p]
> first low stop = LOWEST[p](high) + x * Average True Range[p]
> stop short = HIGHEST[q](first high stop)
> top long = LOWEST[q](first low stop)

here the short and long stop seem swapped.
Which exact implementation is provided in Pandas-TA? Is Pandas-TA trying to follow the behavior of another application or service (i.e, tradingview), hence the different defaults and behaviour?
Thank you.

**Comment by twopirllc** [comment]
Hello @luisbarrancos,

> Which exact implementation is provided in Pandas-TA? Is Pandas-TA trying to follow the behavior of another application or service (i.e, tradingview), hence the different defaults and behaviour?

That is correct. I am using the TradingView implementation where **atr** uses **rma** because the TA Lib source I have do not include Chande-Kroll Stop.

<br/>

<img width="1248" alt="Screen Shot 2021-03-24 at 1 12 14 PM" src="https://user-images.githubusercontent.com/18198392/112377558-25670b00-8ca3-11eb-9c38-72863042c1b9.png">

<br/><br/>

> According to the book "The New Technical Trader" by Chande & Kroll (1st ed, Wiley, ISBN 9780471597803), on page 95, the CK long stop is calculated by computing a 10 day simple moving average of the ATR, which they name ATR_10, to which we subtract 3*ATR_10 from highest high of the last 10 days. This quantity will be the preliminary long stop. The final long stop will be the highest value of the preliminary long stop over a 20 day period.

I am open to this calculation being included. Would you like to fork, edit and submit a PR? If so, that would be greatly appreciated. 😎 

Kind Regards,
KJ

**Comment by luisbarrancos** [comment]
@twopirllc i understand. I'll be working on test cases to fully verify this, followed shortly by a PR. I suppose you want unit tests as well. For the book implementation we can use the actual YENUSD (1993) historic data. Thank you for the swift reply.

**Comment by twopirllc** [comment]
@luisbarrancos,

Sounds great! I would appreciate it. 😎 

Thanks,
KJ

**Comment by luisbarrancos** [comment]
@twopirllc there are a couple of decisions to make here. A parameter controlling the behaviour between the tradingview implementation and the book implementation has the advantage of having a single cksp indicator, however the default periods also change. Having two indicators is perhaps opening a can of worms. What do you think would be the most sensible course of action here?
Furthermore wrt to unit tests, TAlib lacks as you mentioned earlier, a Chande-Kroll stop implementation to compare with. Unit tests notwithstanding i can provide you a small jupyter notebook with the JPY futures contract data used in the book for verification.
