### ISSUE TITLE
Chande Kroll Stop bug (and the fix)

### ISSUE THREAD

**Issue by rylos** [twopirllc/pandas-ta#257]
I'm using latest dev version.
As title says, this:
`short_stop_ = high.rolling(p).min() + x * atr_
 short_stop = short_stop_.rolling(q).min()`
is wrong, the correct short_stop must use the low series, so the correct one is:
`short_stop_ = low.rolling(p).min() + x * atr_
    short_stop = short_stop_.rolling(q).min()`

Ciao!

**Comment by twopirllc** [comment]
Hello @rylos,

Good eye! I would like for you to get contribution credit. Would you like to fork, edit and submit a PR?

Kind Regards,
KJ
