### ISSUE TITLE
Noob question here - "[X] Ooops!!!: It's True, the series 'close' was not found in time"

### ISSUE THREAD

**Issue by mcpeixoto** [twopirllc/pandas-ta#259]
Hi there,
First of all sorry for my ignorance.

I have this dataframe:
![image](https://user-images.githubusercontent.com/30632902/112894417-bc80f800-90d3-11eb-950e-6c3042642db0.png)

I want to plot it along side with it alot of indicators.
I can do this manually for example:
![image](https://user-images.githubusercontent.com/30632902/112894596-f3efa480-90d3-11eb-9011-aa2f51bfc99b.png)

But I'm not able to use a strategy..
![image](https://user-images.githubusercontent.com/30632902/112894662-0b2e9200-90d4-11eb-8586-c644e0df66a7.png)

How do I specify which one is my "target" column. I seems it defaults to "close".

**Comment by twopirllc** [comment]
Hello @mcpeixoto,

No worries. You need to specify the replacement column to use for _close_.

<br/>

<img width="512" alt="Screen Shot 2021-03-29 at 2 47 59 PM" src="https://user-images.githubusercontent.com/18198392/112904567-fb945680-909d-11eb-93ae-05cd57fe4dd2.png">

<br/>

Let me know if this works for you. Thanks for trying Pandas TA!

Kind Regards,
KJ

**Comment by mcpeixoto** [comment]
Thank you so much for the patience and kind response. It works :)

**Comment by twopirllc** [comment]
@mcpeixoto,

No worries. Thanks for prompt response that the solution works for you. 😎 

Thanks,
KJ
