### ISSUE TITLE
df.ta.strategy() returning None

### ISSUE THREAD

**Issue by danwatson16** [twopirllc/pandas-ta#263]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**

**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @danwatson16,

I would like to help you, however you did not fill any information requested of you. When you have the time, please fill out the Issue contents listed above; the more the merrier.

Kind Regards,
KJ

**Comment by M6stafa** [comment]
`df.ta.strategy()` doesn't supposed to return anything. It adds new columns to `df`.

**Comment by twopirllc** [comment]
Hello @danwatson16,

I assume by no response that you have resolved this Issue on your own and I will be closing this issue in a few days. However if that is not the case, please fill out the Issue contents listed above. Make sure you have tested with the Latest Version of Pandas TA:

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Also** provide reproducible code.

Kind Regards,
KJ
