### ISSUE TITLE
Standard Deviation feature request

### ISSUE THREAD

**Issue by manojjenago** [twopirllc/pandas-ta#268]
Hi ,
Thanks for a beutiful peice of code, it helps a lot.
I was looking for a Standard deviation indicator . Please guide how I can only add standard deviation 1,2,3 on a daily chart.
Again thanks for a beutiful peice of package ..... Very very good job here ..

Thanks,
Manoj

**Comment by twopirllc** [comment]
Hello @manojjenago,

Thanks!

> I was looking for a Standard deviation indicator .

There is a standard deviation (**stdev**) indicator. 

```python
import pandas as pd
import pandas_ta as ta

df =  # your ohlcv data

# By default this calculates a rolling standard deviation of length 30 bars
# The append kwarg will append stdev to the DataFrame df when done
df.ta.stdev(append=True) # = ta.stdev(df['close'], length=30, ddof=1)

# Sanity check
print(df)
```

> Please guide how I can only add standard deviation 1,2,3 on a daily chart.

I am uncertain what you mean by 1,2,3... Do you mean how to plot **stdev** with horizontal lines 1,2,3?

Kind Regards,
KJ

**Comment by manojjenago** [comment]
> Hello @manojjenago,
> 
> Thanks!
> 
> > I was looking for a Standard deviation indicator .
> 
> There is a standard deviation (**stdev**) indicator. All the indicators are listed on the README.
> 
> ```python
> import pandas as pd
> import pandas_ta as ta
> 
> df =  # your ohlcv data
> 
> # By default this calculates a rolling standard deviation of length 30 bars
> # The append kwarg will append stdev to the DataFrame df when done
> df.ta.stdev(append=True) # = ta.stdev(df['close'], length=30, ddof=1)
> 
> # Sanity check
> print(df)
> ```
> 
> > Please guide how I can only add standard deviation 1,2,3 on a daily chart.
> 
> I am uncertain what you mean by 1,2,3... Do you mean how to plot **stdev** with horizontal lines 1,2,3?
> 
> Kind Regards,
> KJ

Thanks for your quick reply, I did see that , but I was refering 1,2,3 in terms of the Thinkerswim terminology , where you you can add Standard Deviation for 1 , Standard Deviation for 2 and so on.
you can find the details on the learning center of Thinkerswim.  If you can guide how to covert the euations to a python file that will be great ..

https://tlc.thinkorswim.com/center/reference/thinkScript/Functions/Statistical/StDevAll

**Comment by twopirllc** [comment]
@manojjenago,

Like the example code below in the link? Or creating a new indicator? If so check out Issue #264 **Creating a Custom Indicator**?

<img width="425" alt="Screen Shot 2021-04-09 at 11 58 23 AM" src="https://user-images.githubusercontent.com/18198392/114228228-fb604a80-992a-11eb-9791-9bb94471b878.png">

where you want to use the results of **stdev**?

Thanks,
KJ

**Comment by manojjenago** [comment]
> @manojjenago,
> 
> Like the example code below in the link? Or creating a new indicator? If so check out Issue #264 **Creating a Custom Indicator**?
> 
> <img alt="Screen Shot 2021-04-09 at 11 58 23 AM" width="425" src="https://user-images.githubusercontent.com/18198392/114228228-fb604a80-992a-11eb-9791-9bb94471b878.png">
> 
> where you want to use the results of **stdev**?
> 
> Thanks,
> KJ

Thanks , I want to use the indicator values to Enter or Exit a Stock based on the signal .. Or if you can create a new indicator that will be greatly helpful. 

![image](https://user-images.githubusercontent.com/20192908/114229888-6d925880-9946-11eb-91ad-45b3d5a66e1f.png)


Thanks,
Manoj

**Comment by twopirllc** [comment]
@manojjenago,

Which plotting library do you use? matplotlib? mplfinance? other?

Thanks for the chart image. It is more insightful. In that image you posted, it looks like each candle component (open, high, low, close) are being processed by **stdev**. Then horizontal chart lines of -2, -1, 0, 1, 2 **stdev**s are applied to the chart. Is this correct?

> I want to use the indicator values to Enter or Exit a Stock based on the signal

I am still unclear what the _signal_ or _indicator_ is. I ask because a _signal_, to me, results in a _trend_ that converts prices to binary (long: 1, short: 0) _signal_. So is the _signal_ something like buy when _close_ crosses above -1 **stdev**s and sell when it _close_ crosses above +1 **stdev**s? If so, there will be a solution soon to generate those _Enter_ and _Exit_ values.

Thanks,
KJ

**Comment by manojjenago** [comment]
> @manojjenago,
> 
> Which plotting library do you use? matplotlib? mplfinance? other?
> 
> Thanks for the chart image. It is more insightful. In that image you posted, it looks like each candle component (open, high, low, close) are being processed by **stdev**. Then horizontal chart lines of -2, -1, 0, 1, 2 **stdev**s are applied to the chart. Is this correct?
> 
> > I want to use the indicator values to Enter or Exit a Stock based on the signal
> 
> I am still unclear what the _signal_ or _indicator_ is. I ask because a _signal_, to me, results in a _trend_ that converts prices to binary (long: 1, short: 0) _signal_. So is the _signal_ something like buy when _close_ crosses above -1 **stdev**s and sell when it _close_ crosses above +1 **stdev**s? If so, there will be a solution soon to generate those _Enter_ and _Exit_ values.
> 
> Thanks,
> KJ

Thanks , for your quick reply.  I am using both matplotlib? mplfinance. So anything will work ...matplotlib is preferred..

Yes , the standard devs are applied to the chart.  When I metnioned about signal , mean like the last candelstick  crossing over the standard dev (-1,-2 ..etc) then Buy if the  last candelstick  crossing below the standard dev (1, 2 ..etc) then sell.  

You got it correctly , if the indicator can match what ever  from thinkerswim then it will be a great help ...Thanks for taking the request , you are the best ..and I have not seen anyone in git hub who replies to each and every message .... Thanks a ton for that .. 
Below is the folrmula as metioned in Learning Center ... 
Example
```
input price = close;

def regression = InertiaAll(price, 30);
def stdDeviation = StDevAll(price, 30);

plot UpperLine = regression + stdDeviation;
plot LowerLine = regression - stdDeviation;
```

**Comment by twopirllc** [comment]
Hello @manojjenago,

Could you please indulge me with a better pic of the chart above with the stdev lines that include scales? Also, is it a custom indicator to create that **stdevall** for the candles? Because the code posted in the prior response accounts for one price series and not four (ohlc). Even a whole screen shot of your ToS layout would help.

Thanks,
KJ

**Comment by manojjenago** [comment]
> Hello @manojjenago,
> 
> Could you please indulge me with a better pic of the chart above with the stdev lines that include scales? Also, is it a custom indicator to create that **stdevall** for the candles? Because the code posted in the prior response accounts for one price series and not four (ohlc). Even a whole screen shot of your ToS layout would help.
> 
> Thanks,
> KJ

Hi Kevin,
Thanks for your reply. 
Please find the updated screenshot. I think we are only using close from OHLC , I guess here. 
The indicator is a part of ThinkerSwim (out Of box)  not a custom indicator. The way the indicator is calculated i guess , 
regression + stdDeviation * 1 
regression + stdDeviation * 2
... and so on. 
So I guess the thing is to find the regression or the Inertia that is being used in regression. Please let me know if you need some other inputs ..

```
input price = close;

def regression = InertiaAll(price, 30);
def stdDeviation = StDevAll(price, 30);

plot UpperLine = regression + stdDeviation;
plot LowerLine = regression - stdDeviation;
```
Please have the below links that might help for getting some more details ..

https://tlc.thinkorswim.com/center/reference/thinkScript/Functions/Statistical/StDevAll

https://tlc.thinkorswim.com/center/reference/thinkScript/Functions/Statistical/Inertia
(Draws the linear regression curve using the least-squares method to approximate data for each set of bars defined by the length parameter)

https://tlc.thinkorswim.com/center/reference/thinkScript/Functions/Statistical/InertiaAll

![StandardDeveiaion](https://user-images.githubusercontent.com/20192908/114713068-c1ae8b80-9cfe-11eb-812c-2324795a6873.jpg)

**Comment by twopirllc** [comment]
@manojjenago,

Awesome! Thanks for the full image. It makes more sense now. I made something else instead. A two for one. 😄

Thanks,
KJ

**Comment by manojjenago** [comment]
> @manojjenago,
> 
> Awesome! Thanks for the full image. It makes more sense now. I made something else instead. A two for one. 😄
> 
> Thanks,
> KJ

Ohh Sorry My bad , I should have given you the full image at first.
But if you can try to get Thinkerwhim Desktop version and try to add the Standard deviation channlel, It will give you some more details , and please feel free to ask the details as requied to me. I can provide them asap. I have seen this indicator kind of works and the lines are permanent so it gives a better indication where the price can breakout either way. If we can mimic the same behavior of Thinkerswim, I guess this will be a better indicator ..

Thanks again for all your support and help...Looking forward to get some good news soon ...
Thanks,
MJ

**Comment by twopirllc** [comment]
@manojjenago,

> Ohh Sorry My bad , I should have given you the full image at first.

No worries. I needed to test something else out anyhow. 😄 

I just need to figure out how to do the lines for the full chart. The code is trivial.

I'll keep you posted or if I need more clarification.

Thanks,
KJ

**Comment by twopirllc** [comment]
@manojjenago,

Bad news! It will not be ready for the upcoming update. I still have to clean it up & add some tests. But I will keep you posted.

Good news! I have beta code that's promising.

<img width="736" alt="Screen Shot 2021-04-15 at 11 30 29 AM" src="https://user-images.githubusercontent.com/18198392/114920188-078e5100-9dde-11eb-9bfd-1a0ff6417379.png">

Thanks,
KJ

**Comment by manojjenago** [comment]
> @manojjenago,
> 
> Bad news! It will not be ready for the upcoming update. I still have to clean it up & add some tests. But I will keep you posted.
> 
> Good news! I have beta code that's promising.
> 
> <img alt="Screen Shot 2021-04-15 at 11 30 29 AM" width="736" src="https://user-images.githubusercontent.com/18198392/114920188-078e5100-9dde-11eb-9bfd-1a0ff6417379.png">
> 
> Thanks,
> KJ

Wow nice , you have made it ... Thanks for putting time and effort for this.
Can not wait for the release , but if you want just share the bita version of code so I can test and give some inputs if we need anything in final version. My id is jenaman@gmail.com

Thanks so much again .... 
Thanks ,
Manoj

**Comment by twopirllc** [comment]
Hello @manojjenago,

I have added ```ta.tos_stdevall``` to the library. It is available under the _development_ branch if you want to test it out before I update the _main_ branch.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks for your patience.
KJ

**Comment by manojjenago** [comment]
Thanks, Kevin. So nice of you.

You are really great. Luckey go have this indicator.
 I will check it out. Sorry was too much busy in my work forgot to send you
some screenshots that you had asked for earlier.

Thanks,
Manoj

**Comment by twopirllc** [comment]
@manojjenago,

No worries. I appreciate your patience.

KJ

**Comment by twopirllc** [comment]
@manojjenago,

It's available now on the main branch or pypi. Please let me know if there are any issues.

Thanks,
KJ

**Comment by manojjenago** [comment]
Thanks Kevin.

I will check it out. Right now lot of workload, so bit diverted from
trading.
But soon will check and let you know, if I have any questions.
Thanks again for all your effort to make this happen.
Thanks & Regards,
Manoj

**Comment by manojjenago** [comment]
Hi Kevin,
I am really enjoying the indicator and your cool library... Thank you so
much for all your hard work.

Do you have any plans to have renko style chart too ?? Else please take a
request for it.

Thanks,
Manoj

**Comment by twopirllc** [comment]
Hello @manojjenago,

Thanks! Coffees are welcome! 😎 

> Do you have any plans to have renko style chart too ?? Else please take a
request for it.

Yes. Someone (#152) has already requested it as well. Been slammed with Issues and improving the internals to work on new features on top of that. Contributions are welcome if you want a feature added sooner to the package. 😎 

Kind Regards,
KJ

**Comment by kaanguven** [comment]
> Hello @manojjenago,
> 
> Thanks! Coffees are welcome! 😎
> 
> > Do you have any plans to have renko style chart too ?? Else please take a
> > request for it.
> 
> Yes. Someone (#152) has already requested it as well. Been slammed with Issues and improving the internals to work on new features on top of that. Contributions are welcome if you want a feature added sooner to the package. 😎
> 
> Kind Regards, KJ

I tried ta.tos_stdevall but values are wrong i guess. just check results and my code below :

`             src = dfLB["close"]
            
              length = 100
           
              dev = ta.tos_stdevall(src,40)
              print(dev)
`
TV results :
![ek](https://user-images.githubusercontent.com/83061705/197331373-6d85f88d-b361-4acf-a070-e76b857ebf7d.PNG)

my results for U_2 and L_2

![we](https://user-images.githubusercontent.com/83061705/197331391-5e702168-9690-43a1-bbab-f1757937d451.PNG)
