### ISSUE TITLE
Minor issue in the example notebook

### ISSUE THREAD

**Issue by bdowling** [twopirllc/pandas-ta#27]
The example notebook shows

`e.ta.indicators()`

but I think this needs to be

`e().ta.indicators()`

Or you need to assign `e = pd.DataFrame()` ... coders choice. :)

**Comment by thedatadavis** [comment]
e is set in the first code block beneath the imports

**Comment by twopirllc** [comment]
Thanks @thedatadavis !
Yeah, it is set in the first code block. Or just set it as:
`e = pd.DataFrame()`

**Comment by bdowling** [comment]
Not sure if my point was missed.. the example first block is missing the `()` to call the function...

**Comment by twopirllc** [comment]
Weird.  To clarify, your first cell was missing the parenthesis with `e = pd.DataFrame`?

**Comment by twopirllc** [comment]
Anyhow, updated the example notebook as it was a bit stale.
