### ISSUE TITLE
ADX indicator not working

### ISSUE THREAD

**Issue by mwpwalshe** [twopirllc/pandas-ta#270]

**Comment by twopirllc** [comment]
Hello @mwpwalshe,

Thanks for using Pandas TA. For clarification, did you resolve the Issue yourself? If so, what did you do to correct it? If not, please let me know.

Kind Regards,
KJ

**Comment by mwpwalshe** [comment]
Hi,
Sorry, was my own code error, just implementing all the indicators, great
to have this resource in pandas.
Thanks,
Michael
