### ISSUE TITLE
Cumulative Percent Return (percent_return(cumulative=True)) is calculated incorrectly

### ISSUE THREAD

**Issue by rcdodds** [twopirllc/pandas-ta#271]
**Which version are you running? The latest version is on Github. Pip is for major releases.**
0.2.45b0

**Describe the bug**
ta.percent_return(cumulative=True) is calculating incorrectly. It is simply adding up the consecutive returns from each period, which does not equal the cumulative percentage return algebraically.

**To Reproduce**
```python
import pandas as pd
import pandas_ta as ta
df = pd.DataFrame(data={'close': [100, 110, 121, 110]})
df.ta.percent_return(cumulative=True, append=True)     # This returns incorrect values.
df['pct_gain'] = (df['close'] / df['close'][0]) - 1                  # This returns correct values.
df
```

```sh
   close  CUMPCTRET_1  pct_gain
0    100          NaN      0.00
1    110     0.100000      0.10
2    121     0.200000      0.21
3    110     0.109091      0.10
```

In the above example, CUMPCTRET_1 states that 100 >> 121 is a 20% gain and 100 >> 110 is a 10.9091% gain.
This simple example is not very far off from the correct values, but it becomes more drastic when using real data over time.
For instance, as of 4/16/2021 the 3-month performance of BTC-USD should return about 500% but instead returns 184%

**Expected behavior**
I expect percent_return with cumulative=True to return the cumulative percentage gain.
Instead, it returns the sum of the prior, individual percentage gains.

**Comment by twopirllc** [comment]
Hello @rcdodds,

Thanks for looking into this. It does look like something doesn't add up.

> For instance, as of 4/16/2021 the 3-month performance of BTC-USD should return about 500% but instead returns 184%

For which dates and prices are you determining this?

This is what I see for returns from 1/16/2021 to 4/16/2021 (90 days).

![BTCUSD D 2018 2021-04-19](https://user-images.githubusercontent.com/18198392/115278163-ff922200-a0f9-11eb-8b08-a74e6f315785.png)

Or are the dates and prices above incorrect? I just want to make sure the numbers add up. Do you also see anything wrong with ```log_return()``` and it's cumulative values?

I will have a revised _development_ version of *percent_return()* and *log_return()* in another day or so. I'll keep you posted.

Kind Regards,
KJ

**Comment by rcdodds** [comment]
No problem! Huge fan of the library so far and I can't thank you enough for
all the work you put into it.

Taking another look, I was actually using 6-month data, not 3-month. I'm
pulling the OHLCV data from Yahoo! Finance (yfinance).

On 10/20/2020, BTC-USD closed at $11,916
Now, BTC-USD is above $55,000

Rough math of 11k to 55k is x5 which is a 400% gain
However, with percent_return(cumulative=True) I get just around 170%
(1.7ish)

Thank you,
Ryan Dodds
***@***.***
(484) 723-3363

**Comment by twopirllc** [comment]
Hello @rcdodds,

> Taking another look, I was actually using 6-month data, not 3-month.

No worries.

When you get a chance, please install the _development_ version and test out ```ta.percent_return``` and ```ta.log_return``` and their cumulative values. I would like to push it out to _main_ as soon as possible. To install the _development_ version:

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Sample Code:

```python
import datetime
import pandas as pd
import pandas_ta as ta

dt_to = datetime.datetime.now()
dt_from = dt_to - datetime.timedelta(days=180)

df = pd.DataFrame().ta.ticker("BTC-USD", kind="info") # This wraps 'yfinance' 
df = df.loc[dt_from:dt_to].copy()
del df["volume"]

df.ta.percent_return(cumulative=False, append=True)
df.ta.percent_return(cumulative=True, append=True)
df.ta.log_return(cumulative=False, append=True)
df.ta.log_return(cumulative=True, append=True)

df[df.columns[3:]]
```

Should print:

<img width="429" alt="Screen Shot 2021-04-22 at 10 47 08 AM" src="https://user-images.githubusercontent.com/18198392/115763588-75e08f80-a359-11eb-86ba-c5d493f90be9.png">

Are these correct and inline with expectations?

> No problem! Huge fan of the library so far and I can't thank you enough for
all the work you put into it.

Thank you!
KJ

**Comment by twopirllc** [comment]
@rcdodds,

It is now available on the Latest Version _0.275b_:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Please let me know if it still is incorrect.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @rcdodds,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
