### ISSUE TITLE
is there any way to calculate atr trailing stops via python for historical ohlc data

### ISSUE THREAD

**Issue by mahesh-solanke** [twopirllc/pandas-ta#272]
@twopirllc Thanks for such a beautiful library for technical indicators, it helps me a lot in many ways.
I am stuck on one point, didn't find any relevant python indicator library or calculation for getting values of ATR Trailing Stops, is there any way please help me out.

Thanks in advance.

**Comment by twopirllc** [comment]
Hello @mahesh-solanke,

Thanks.

I found Motive Wave's [ATR Trailing Stop](https://www.motivewave.com/studies/atr_trailing_stops.htm) has an algorithm for it. 

Currently I am backlogged on Issues and Features and unfortunately do not have a time frame on when it can be implemented in Pandas TA. But if you are willing to give it a shot, we all would appreciate the contribution to see it in Pandas TA sooner. If so, feel free to _fork_, _edit_ and submit a _PR_ when ready.

Kind Regards,
KJ

**Comment by koonom1985** [comment]
May I know any update on this features so far?

**Comment by twopirllc** [comment]
Hello @mahesh-solanke,

So _atrts_ has been implemented with the assistance of @koonom1985. 😎 It is available on the _development_ branch if you want to check it out.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by mahesh-solanke** [comment]
@twopirllc, Thank you so much for this.
It really means a lot. that you guys have implemented
Thanks, @koonom1985 for your help.

Regards,
Mahesh Solanke

**Comment by twopirllc** [comment]
@mahesh-solanke,

You're welcome.

Regards,
KJ
