### ISSUE TITLE
cmf indicator doesn't change with length

### ISSUE THREAD

**Issue by CacheKatch** [twopirllc/pandas-ta#273]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
I am using pandas-ta==0.2.45b0
```python
import pandas_ta as ta
print(ta.version)
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
cmf function gives the same results regardless of the length. It seems that the length of 20 is hard coded. 

**To Reproduce**
this is the data source: [GC.txt](https://github.com/twopirllc/pandas-ta/files/6333257/GC.txt)
```python
gc_data_file = 'Resources_data/GC.txt'
gc_df = pd.read_csv(gc_data_file, parse_dates=[[0,1]], index_col='Date_Time')
gc_df['tot_vol'] = (gc_df.Vol + gc_df.OI)
gc_df.drop(columns=['Vol', 'OI'])
gc_df.rename(columns={'Open':'open', 'High': 'high','Low': 'low','Close': 'close', 'tot_vol': 'volume'}, inplace=True)
gc_df['cmf'] = ta.cmf(gc_df.high, gc_df.low,gc_df.close, gc_df.volume, Length=20)
gc_df['cmf21'] = ta.cmf(gc_df.high, gc_df.low,gc_df.close, gc_df.volume, Length=21)
```

**Expected behavior**
The results of cmf function are expected to change when different lengths are specified.

**Screenshots**
![cmf20_cmf21_are_same](https://user-images.githubusercontent.com/70239124/115181357-5e757e00-a09d-11eb-941b-d8d226c8a758.png)

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @CacheKatch,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by CacheKatch** [comment]
yes,
Thank you for the follow up. It did work.
So, please close the the issue

Again,
Many thanks,
I love the library
very comprenhensive

**Comment by twopirllc** [comment]
@CacheKatch,

Awesome! Glad it's working for you.

> I love the library; very comprenhensive

Thank you!
Kevin Johnson
