### ISSUE TITLE
bbands reporting inaccurate Upper/Lower band data

### ISSUE THREAD

**Issue by jrcart** [twopirllc/pandas-ta#276]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.2.23b0

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```
This did not work in terminal and also tried upgrading via Jupyter notebook to no avail.

**Describe the bug**
Trying to run bbands and the Lower and Upper bands are not matching TradingView nor TOS (both are spot on against each other). Mid-line is spot on. I have quadruple checked all the inputs and cannot find anything in the pandas_ta script that would cause any numbers to be different than the calculations in other platforms.

**To Reproduce**
Provide sample code.
Tried the all of the following variations:
```python
my_df.ta.bbands(close='close', std=2, mamode='sma', length=21 , ddof=0, offset=0, append=True)
my_df.ta.bbands(close='close', std=2, mamode=None, length=21 , ddof=0, offset=0, append=True)
my_df.ta.bbands(close='close', std=2, mamode='sma', length=21 , offset=0, append=True)
my_df.ta.bbands(close='close', std=2, mamode=None, length=21 ,offset=0, append=True)
my_df.ta.bbands(close='close', std=None, mamode='sma', length=21 , offset=0, append=True)
my_df.ta.bbands(close='close', std=None, mamode=None, length=21 ,offset=0, append=True)
```

**Expected behavior**
Data for SPY 4/8/21
-TOS & TV report identical numbers:
--Lower: 383.89
--Upper: 408.31
--Mid: 396.10

-pandas_ta reports: (note: being exactly 0.30 off on both bands is coincidental as other days off by more/less)
--Lower:   383.59 
--Upper:  408.61 
--Mid:  396.10 

**Screenshots**
Nothing to really show, other than the Upper and Lower bands are off every day.

**Additional context**
I have used ADX and some Moving Averages in the same program and they are spot on, as is the BBands Mid-Line. It is only the Upper and Lower bands of the BBands that are off. I'm hoping I just have some sort of configuration error that I'm messing up. I sifted through every help document I could find before posting, any help would be appreciated. Thank you!

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @jrcart,

> I sifted through every help document I could find before posting, any help would be appreciated.

Great! I assume you read Issue #202 about Standard Deviation ddof. If not, please read it to understand part of the history of this library and how this library is tested and why.

### Upgrading Pandas TA

> This did not work in terminal and also tried upgrading via Jupyter notebook to no avail.

I would like to recommend the latest pypi version _0.2.45b_, but unfortunately it doesn't have the fix. Eventually, you will **need** to _upgrade_ to get it to work and there is _unfortunately_ there is no way around that. 

If you were unable to install using:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```
What version of Python and OS are you using? What were the errors? Screenshots?

Also did you try manually downloading the zip from Github and doing a local [pip install](https://packaging.python.org/tutorials/installing-packages/)?

<img width="360" alt="Screen Shot 2021-04-21 at 10 27 22 AM" src="https://user-images.githubusercontent.com/18198392/115596838-68f66a00-a28d-11eb-9e60-3d8780faf2ff.png">

<br/>

### Bollinger Bands and ddof

Once you are able to upgrade, you will need to set ```ddof=0```.

```python
my_df = # ohlcv data
my_df.ta.bbands(ddof=0, append=True)
print(my_df)
```

Once you get this far, please let me know if it is still "way off" from expected. If so, then you will **need** to export historical data from ToS for more in depth analysis.

### Exporting ToS Data for External Testing

Lastly to ensure there are no differences in data, I recommend [exporting data from ToS](https://usethinkscript.com/threads/exporting-historical-data-from-thinkorswim-for-external-analysis.507/) and using their data to test differences between indicators. Make sure you **also** export it with the indicator in question you want to compare with, **bbands** in this case. Then share the exported data with the default ToS **bbands ** parameters here so I can check as well.

<br/>

#### Misc.
The ```close=pd.Series``` is only needed if you want to use something other than "close" or using some weird cased name for "close".

```python
my_df.ta.bbands(close='close', std=2, mamode=None, length=21 ,offset=0, append=True)
# are equivalent
my_df.ta.bbands(std=2, mamode=None, length=21 ,offset=0, append=True)
```

Hope this helps! Keep me posted.

Kind Regards,
KJ

**Comment by jrcart** [comment]
Hi KJ, thanks for the quick response. I was indeed able to upgrade to 0.2.45b0 thanks to your guidance. However I am still seeing the same issue when using ddof=0. "Way off" is probably not the right characterization (as I'm really only seeing ~0.11% difference in both the Upper / Lower bands on both QQQ and SPY L~250 trading days), but every other one of the indicators is always spot on, so it threw me for a bit of a loop. I can export BBands separately, so no big deal, just thought perhaps I was doing something incorrectly. Thanks again for the great package and your help!!

**Comment by twopirllc** [comment]
@jrcart,

>  I was indeed able to upgrade to 0.2.45b0 thanks to your guidance.

Great! 

> However I am still seeing the same issue when using ddof=0.

Right. That's because you need version _0.2.67b_ or later to use ```ddof=0``` which is available on Github and can be downloaded from there as described above.

> every other one of the indicators is always spot on, so it threw me for a bit of a loop.

Tell me about it. :laughing:

> I can export BBands separately, so no big deal, just thought perhaps I was doing something incorrectly.

Nice! That makes it easier (though more tedious) to cross test indicators among the many platforms.

> Thanks again for the great package and your help!!

No worries. Thank you.
KJ

**Comment by twopirllc** [comment]
Hello @jrcart,

A new version is up:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

or do the download thing I described before.

Let me know how it goes. Thanks!

KJ

**Comment by jrcart** [comment]
Hey @twopirllc,
So I did the upgrade and re-ran the program using: 
`my_df.ta.bbands(close='close', std=2, mamode='sma', length=21 , ddof=0, offset=0, append=True)`
... But I am still seeing issues. Below is an excerpt on ticker BP using TradingView (I triple-checked it's a 21 length) data vs. the pandas_ta outputs (Upper Diff and Lower Diff just showing the difference between the numbers):

time | open | high | low | close | Basis | Upper | Lower | BBL_21_2.0 | BBM_21_2.0 | BBU_21_2.0 | BBB_21_2.0 | Upper Diff | Lower Diff
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1619184600 | 24.35 | 24.55 | 24.225 | 24.52 | 24.8428571 | 25.5956081 | 24.0901062 | 24.0715169 | 24.8428571 | 25.6141973 | 6.20975439 | 0.07% | -0.08%
1619443800 | 24.67 | 24.96 | 24.65 | 24.92 | 24.8595238 | 25.6028106 | 24.116237 | 24.0978815 | 24.8595238 | 25.6211661 | 6.12756979 | 0.07% | -0.08%
1619530200 | 25.14 | 25.31 | 24.73 | 24.94 | 24.8457143 | 25.5715261 | 24.1199025 | 24.1019785 | 24.8457143 | 25.58945 | 5.98683327 | 0.07% | -0.07%
1619616600 | 25.3 | 25.73 | 25.29 | 25.64 | 24.867619 | 25.6574088 | 24.0778293 | 24.0583254 | 24.867619 | 25.6769127 | 6.50881482 | 0.08% | -0.08%
1619703000 | 25.83 | 25.95 | 25.3 | 25.47 | 24.8957143 | 25.7261948 | 24.0652337 | 24.0447249 | 24.8957143 | 25.7467036 | 6.83643241 | 0.08% | -0.09%

**Comment by twopirllc** [comment]
@jrcart,

Again

> I use [_TA Lib_ Source](https://www.ta-lib.org/hdr_dw.html) to test the accuracy of indicators where the majority of common indicators are >99% correlated including **bbands**, **stdev**, and **variance** which **bbands** also invokes. So **bbands** are not technically off even if ```ddof=1 or 0```.

> I wish there was a Common Standard of Technical Analysis defaults. There are many libraries, platforms et al that have one off variations in one way or another. I chose TA Lib to be the base since it is the de facto TA Library that many other libraries, frameworks, platforms use. Also it helps having TA Lib code.

Here are some Correlation results. 

<img width="717" alt="Screen Shot 2021-04-29 at 12 57 30 PM" src="https://user-images.githubusercontent.com/18198392/116610870-8ad59980-a8ea-11eb-87f1-2ee06d55b965.png">

More Correlation results but using TradingView's Data and TradingView's **default** **bbands(close, 20, 2.0)** using ticker BP.

<img width="700" alt="Screen Shot 2021-04-29 at 1 00 05 PM" src="https://user-images.githubusercontent.com/18198392/116611133-e011ab00-a8ea-11eb-9e4b-1061eaae1882.png">

More Correlation results but using TradingView's Data and TradingView's **default** **bbands(close, 20, 2.0)** using ticker SPY as well as a comparison to SPY's values in your original post.

<img width="708" alt="Screen Shot 2021-04-29 at 1 26 08 PM" src="https://user-images.githubusercontent.com/18198392/116614362-b35f9280-a8ee-11eb-9068-7351d1b4d73d.png">
<img width="725" alt="Screen Shot 2021-04-29 at 1 26 23 PM" src="https://user-images.githubusercontent.com/18198392/116614382-b8bcdd00-a8ee-11eb-82ff-cf69f4412a76.png">

<br/>

I am open to contributions to bridge these correlation gaps of less than 1%. If you are willing to help out and get this fix in, all users will be grateful. 😎 

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @jrcart,

The Latest Version is available. If you have TA Lib installed, it will use that otherwise it will use the built in Pandas TA one.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Kind Regards,
KJ
