### ISSUE TITLE
Creating exe-file with pyinstaller not possible

### ISSUE THREAD

**Issue by Rapid1898-code** [twopirllc/pandas-ta#279]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
pandas-ta                 0.2.75b0
pyinstaller               4.3
pyinstaller-hooks-contrib 2021.1

**Upgrade.**
allready done - see above

**Describe the bug**
I want to create an exe-file using pyinstaller

The py-file is very-simple (and runs when i start it in vscode or from the terminal)
`import pandas_ta as ta
print("It works!")`

I create the exe-file with:
```sh
pyinstaller --onefile temp5.py
```
also tried:
```sh
pyinstaller --onefile --hidden-import pandas_ta temp5.py
```
(with the same result)
(the building of the the exe-file works fine without errors)

But when i start the exe-file it get this error message:
```sh
Traceback (most recent call last):
  File "temp5.py", line 3, in <module>
    import pandas_ta as ta
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pandas_ta\__init__.py", line 10, in <module>
  File "pkg_resources\__init__.py", line 466, in get_distribution
  File "pkg_resources\__init__.py", line 342, in get_provider
  File "pkg_resources\__init__.py", line 886, in require
  File "pkg_resources\__init__.py", line 772, in resolve
pkg_resources.DistributionNotFound: The 'pandas_ta' distribution was not found and is required by the application
[17468] Failed to execute script temp5
````

**To Reproduce**
py-file: 
```python
import pandas_ta as ta
print("It works!")`
```

compiling with pyinstaller:
```sh
pyinstaller --onefile temp5.py
```
or:
```sh
pyinstaller --onefile --hidden-import pandas_ta temp5.py
```

**Expected behavior**
Working exe-file without error when running

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @Rapid1898-code,

Pandas TA uses multiprocessing, "frozen" issue... then you need to fix your ```temp5.py``` to include:
```python
import pandas_ta as ta
if __name__ == '__main__':
    freeze_support()
    print(f"executable created")
```

```The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable.```

This might help also: [Freezing your Code](https://python-guide-es.readthedocs.io/es/latest/shipping/freezing.html)
Google Search of [pyinstaller frozen importlib](https://www.google.com/search?q=pyinstaller+frozen+importlib&client=firefox-b-1-d&ei=xMiKYIiRLOHi9APA_YbgBg&oq=pyinstaller+froz&gs_lcp=Cgdnd3Mtd2l6EAMYAjICCAAyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjoHCAAQRxCwAzoFCAAQkQJQyh1Y3iFgmztoAXACeACAAXCIAbwDkgEDNC4xmAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=gws-wiz)

Have also you tried [this](https://stackoverflow.com/questions/28349359/pyinstaller-single-file-executable-doesnt-run)?

Please let me know if any works so we can help others with this issue.

Kind Regards,
KJ
