### ISSUE TITLE
Apply TA Strategy is Slow over 7 Seconds.

### ISSUE THREAD

**Issue by phicha20224** [twopirllc/pandas-ta#281]
```python
    jays_ta = [
            {"prefix":"stochrsi","kind": "stochrsi"} #,{"prefix":"stochrsi","kind": "stochrsi"}
    ]
        start_time = time.time()
        my_strategy = ta.Strategy(name="jay's strategy", ta=jays_ta.copy())
        dframe.ta.strategy(my_strategy)
        print("--- %s seconds ---" % (time.time() - start_time))
```
It is print out over 7 seconds
Dataframe is only 25 row.
I do repeat my ticker so over 750 tickers x 7 second = 5.250 seconds = 87 Minute..

Please help, how to speed up ? 
Thank You,

**Comment by twopirllc** [comment]
Hello @phicha20224,

What version Pandas TA are you using? 

If you are not using the Latest Version (_0.2.75b_), **upgrade**:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Also give me some of your data.

Kind Regards,
KJ

**Comment by phicha20224** [comment]
C:\Temp>pip show pandas-ta
Name: pandas-ta
Version: 0.2.67b0
Summary: An easy to use Python 3 Pandas Extension with 130+ Technical Analysis Indicators. Can be called from a Pandas DataFrame or standalone like TA-Lib. Correlation tested with TA-Lib.
Home-page: https://github.com/twopirllc/pandas-ta
Author: Kevin Johnson
Author-email: appliedmathkj@gmail.com
License: The MIT License (MIT)
Location: c:\users\philip\appdata\local\programs\python\python37-32\lib\site-packages
Requires: pandas
Required-by:

Mr Twopirllc,
I try on different device which have ubuntu and run inside docke
and ir run fastest 
--- 0.08880496025085449 seconds ---                                                                                     
/usr/local/lib/python3.9/site-packages/pandas/core/frame.py:4441: SettingWithCopyWarning:                               A value is trying to be set on a copy of a slice from a DataFrame

**Comment by twopirllc** [comment]
@phicha20224,

Ok.

But still Upgrade to the Latest Version (_0.2.75b_):
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

This is still **beta** software and still ironing out **bugs** and extending with new features.

I also recommend doing:
```python
import pandas as pd
import pandas_ta as ta
import time

jays_ta = [
    {"kind": "stochrsi"},
]
start_time = time.time()

dframe = # ohlcv data
my_strategy = ta.Strategy(name="jay's strategy", ta=jays_ta)
#dframe.ta.cores = 0  # You might need to set this to zero to get a speed boost
dframe.ta.strategy(my_strategy, verbose=True)
print(f"--- {time.time() - start_time} seconds ---")
```

Anyhow. Is there a speed issue still?

Thanks,
KJ

**Comment by phicha20224** [comment]
D:\>pip show pandas_ta
Name: pandas-ta
Version: 0.2.75b0
Summary: An easy to use Python 3 Pandas Extension with 130+ Technical Analysis Indicators. Can be called from a Pandas DataFrame or standalone like TA-Lib. Correlation tested with TA-Lib.
Home-page: https://github.com/twopirllc/pandas-ta
Author: Kevin Johnson
Author-email: appliedmathkj@gmail.com
License: The MIT License (MIT)
Location: c:\users\philip\appdata\local\programs\python\python37-32\lib\site-packages
Requires: pandas
Required-by:

[+] Strategy: jay's strategy
[i] Indicator arguments: {'append': True}
[i] Multiprocessing 4 indicators with 7 chunks and 8/8 cpus.
********************** it slow here *********************
[i] Total indicators: 4
[i] Columns added: 10
[i] Last Run: Saturday May 1, 2021, NYSE: 8:20:16, Local: 12:20:16 SE Asia Standard Time, Day 121/365 (33.00%)
--- 4.706642150878906 seconds ---


put this
dframe.ta.cores = 0  # You might need to set this to zero to get a speed boost
and its fastest. Thank You..

[+] Strategy: jay's strategy
[i] Indicator arguments: {'append': True}
[i] No mulitproccessing (cores = 0).
[i] Progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 109.05it/s]
[i] Total indicators: 4
[i] Columns added: 10
[i] Last Run: Saturday May 1, 2021, NYSE: 8:21:55, Local: 12:21:55 SE Asia Standard Time, Day 121/365 (33.00%)
--- 0.043682098388671875 seconds ---

**Comment by twopirllc** [comment]
@phicha20224,

You need this
```python
dframe.ta.cores = 0  # You might need to set this to zero to get a speed boost
```
because you have a few indicators (4) and it takes longer to start up multiprocessing for just a small number of indicators.

KJ

**Comment by phicha20224** [comment]
I run on another, notebook which only have 2 core/4thread lower than this pc which 4 core/8thread, but it faster..
Thank You. 
I just read the docs,  latest version have so many upgrade. its cool.
