### ISSUE TITLE
"strict" Increasing/decreasing is slow

### ISSUE THREAD

**Issue by ben1628** [twopirllc/pandas-ta#284]
Increasing/decreasing is very slow.

Once you use ```strict=True```, it is using rolling.apply which turns each row of the df into a series and then pass it to a custom function for transformation.  In my case, I have a six month 1 minute OHLC, a 95000 record, which takes 16 seconds to run.

Moreover, it is a strict comparison, in a typical scenario, you want it to return true if current close is a percentage above previous close.

I'm working on a new function to fix the problem, my initial test shows it is less than a second to run the same test.

**Comment by twopirllc** [comment]
Hello @ben1628,

> Increasing/decreasing is very slow.

The default case, ```strict=False```, it is not.

> Once you use strict=True, it is using rolling.apply which turns each row of the df into a series and then pass it to a custom function for transformation. In my case, I have a six month 1 minute OHLC, a 95000 record, which takes 16 seconds to run.

Understandable.

> Moreover, it is a strict comparison, in a typical scenario, you want it to return true if current close is a percentage above previous close.

Increasing/Decreasing are based off of TradingView's Rising/Falling builtin functions. They are not percentage based. However we can easily add a ```percentage``` argument option to account for that scenario. 

<img width="787" alt="Screen Shot 2021-05-06 at 8 49 40 AM" src="https://user-images.githubusercontent.com/18198392/117328376-6e84b000-ae48-11eb-83be-8ee7537a7e36.png">

<br/>

> I'm working on a new function to fix the problem, my initial test shows it is less than a second to run the same test.

**Excellent!** I welcome _any_ contribution that is at a minimum accurate and optimally fast. Fork, edit, and submit a PR whenever you develop a satisfying solution. 😎 

Kind Regards,
KJ

**Comment by ben1628** [comment]
Instead of trying to Fork, edit and submit, Here is the version I have that seems to do what is expected with good speed.

def increasing(close, length=None, pct=None, strict=None, asint=None,  offset=None, **kwargs):
    """Indicator: Increasing"""
    # Validate Arguments
    length = int(length) if length and length > 0 else 1
    strict = strict if isinstance(strict, bool) else False
    asint = asint if isinstance(asint, bool) else True
    close = verify_series(close, length)
    offset =get_offset(offset)
    if close is None: return

    def stricly_increasing(close, adj_close, n):
       if (n >= 1) :
          ret = close > adj_close.shift(1)

       for x in range(3, n + 1) :
          ret = ret & (close.shift(x-2) > adj_close.shift(x-1))
       return ret

    if (pct) :
        adj_close = close + close * pct * 0.01
    else :
        adj_close = close
    # Calculate Result
    if strict :
        # Returns value as float64? Have to cast to bool
        increasing =  stricly_increasing(close, adj_close, length)
        increasing.fillna(0, inplace=True)
        increasing = increasing.astype(bool)
    else:
        increasing = close > adj_close.shift(length)

    if asint:
        increasing = increasing.astype(int)

    # Offset
    if offset != 0:
        increasing = increasing.shift(offset)

    # Handle fills
    if "fillna" in kwargs:
        increasing.fillna(kwargs["fillna"], inplace=True)
    if "fill_method" in kwargs:
        increasing.fillna(method=kwargs["fill_method"], inplace=True)

    # Name and Categorize it
    increasing.name = f"{'S' if strict else ''}INC_{length}"
    increasing.category = "trend"

    return increasing

**Comment by ben1628** [comment]
And similar version for increasing

def increasing(close, length=None, pct=None, strict=None, asint=None,  offset=None, **kwargs):
    """Indicator: Increasing"""
    # Validate Arguments
    length = int(length) if length and length > 0 else 1
    strict = strict if isinstance(strict, bool) else False
    asint = asint if isinstance(asint, bool) else True
    close = ta.verify_series(close, length)
    offset = ta.get_offset(offset)
    if close is None: return

    def stricly_increasing(close, adj_close, n):
       if (n >= 1) :
          ret = close > adj_close.shift(1)

       for x in range(3, n + 1) :
          ret = ret & (close.shift(x-2) > adj_close.shift(x-1))
       return ret

    if (pct) :
        adj_close = close + close * pct * 0.01
    else :
        adj_close = close
    # Calculate Result
    if strict :
        # Returns value as float64? Have to cast to bool
        increasing =  stricly_increasing(close, adj_close, length)
        increasing.fillna(0, inplace=True)
        increasing = increasing.astype(bool)
    else:
        increasing = close > adj_close.shift(length)

    if asint:
        increasing = increasing.astype(int)

    # Offset
    if offset != 0:
        increasing = increasing.shift(offset)

    # Handle fills
    if "fillna" in kwargs:
        increasing.fillna(kwargs["fillna"], inplace=True)
    if "fill_method" in kwargs:
        increasing.fillna(method=kwargs["fill_method"], inplace=True)

    # Name and Categorize it
    increasing.name = f"{'S' if strict else ''}INC_{length}"
    increasing.category = "trend"

    return increasing

**Comment by twopirllc** [comment]
@ben1628,

> Instead of trying to Fork, edit and submit, which I'm not too familiar with. Here is the version I have that seems to do what is expected with good speed.

I hear you. We all start somewhere. I will modify them as soon as I can and let you know when it is up on the _development_ branch to check out and make sure that it is working as intended. I'll also add you to the contribution list.

Thanks,
KJ

**Comment by ben1628** [comment]
Thanks

**Comment by twopirllc** [comment]
Hey @ben1628,

The improvements in speed are great! One question regarding ```pct``` between ```increasing``` and ```decreasing```.  Are they both supposed to be the same:  ```adj_close = close + close * pct * 0.01```?  Or should the ```decreasing``` one be ```adj_close = close - close * pct * 0.01```?

Thanks,
KJ

**Comment by twopirllc** [comment]
Hey @ben1628,

It is available on the _development_ branch for testing. Would be nice if you can verify _before_ I post to main.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by twopirllc** [comment]
Welp @ben1628,

I have pushed it to the __main__ branch now:

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Please let me know how it works out when you get a chance.

Thanks,
KJ
