### ISSUE TITLE
Drop the pre-release flag in the next release

### ISSUE THREAD

**Issue by carlogrisetti** [twopirllc/pandas-ta#286]
Hello,
I am using your library to get TA for a trading bot project. The only thing that annoys me is that my IDE is not able to parse the requirements.txt because of the pre-release tag that is propagated towards PyPI.

Please consider in dropping the pre-release flag for the next release, unless you have any major stopping points.

Thanks!

**Comment by carlogrisetti** [comment]
PyCharm, I mean removing the pre-release flag on the release management on GitHub web interface when defining a new release (it's not in the setup.py). All your releases are marked as pre-release and the default package resolver in pycharm looks for a stable one.

**Comment by twopirllc** [comment]
@carlogrisetti

Thanks for the prompt reply and clarification. I will make this happen.

Thank you,
KJ

**Comment by carlogrisetti** [comment]
Nice, thanks!
