### ISSUE TITLE
list of indicators which return dataframe

### ISSUE THREAD

**Issue by codesutras** [twopirllc/pandas-ta#287]
@twopirllc , Is there a way in the current code to find out a list of indicators, which return dataframe ? Or do we have a list of indicators that return dataframe ?

I know, had mentioned a few of the indicators names which returns dataframe. But, it would be great, if you could share the list of all those such indicators. I want to handle those indicators separately. 

Thanks in advance !!

**Comment by twopirllc** [comment]
Hi @codesutras,

Currently, there is not. Though you could probably make a shell script to go through the sub directories in the [pandas_ta/](https://github.com/twopirllc/pandas-ta/tree/master/pandas_ta) and see which indicators have: ```from pandas import DataFrame```. This would probably be the easiest and fastest solution.

Hope this helps!

Kind Regards,
KJ

**Comment by codesutras** [comment]
Thanks for the reply kevin.

After running a grep command in pandas_ta folder, I've got the below references. 

` grep -l -r -x "from pandas import DataFrame"  `

overlap/supertrend.py
utils/_data.py
candles/ha.py
candles/cdl_z.py
trend/vortex.py
trend/ttm_trend.py
trend/tsignals.py
trend/cksp.py
trend/amat.py
trend/aroon.py
trend/adx.py
trend/decay.py
volume/aobv.py
volume/mfi.py
volatility/kc.py
volatility/accbands.py
volatility/aberration.py
volatility/donchian.py
volatility/bbands.py
volatility/thermo.py
momentum/uo.py
momentum/pvo.py
momentum/kst.py
momentum/kdj.py
momentum/trix.py
momentum/eri.py
momentum/rvgi.py
momentum/ppo.py
momentum/stochrsi.py
momentum/squeeze.py
momentum/stoch.py
momentum/smi.py
momentum/brar.py
performance/drawdown.py

`  grep -l -r -x "from pandas import concat, DataFrame"  `

volume/vp.py
momentum/macd.py

**Comment by twopirllc** [comment]
@codesutras,

Looks good! You can add it to the Makefile if you want.
