### ISSUE TITLE
Value variation in supertrend

### ISSUE THREAD

**Issue by karthiceaswar** [twopirllc/pandas-ta#289]
Using the latest version of pandas-ta through git.
i am calculating supertrend using it.Getting values with slight variations
![image](https://user-images.githubusercontent.com/74752653/118488350-44c96400-b739-11eb-803f-f5bd9685369a.png)
These values i got from pandas ta
Actual values from chart : 33395.17,33395.17,33395.17,33395.17,333426.78
![image](https://user-images.githubusercontent.com/74752653/118488863-cf11c800-b739-11eb-980a-2141af97ed32.png)
![image](https://user-images.githubusercontent.com/74752653/118488909-d933c680-b739-11eb-9825-ef2f59a09a49.png)
both using same lenght and multiplier
![image](https://user-images.githubusercontent.com/74752653/118489149-20ba5280-b73a-11eb-94ab-543313b3c599.png)
The first value in 0 in supertrend, maybe thats giving an error

**Comment by twopirllc** [comment]
Hello @karthiceaswar,

> Using the latest version of pandas-ta through git.

You could have just written _0.2.75b_.

> Actual values from chart : 33395.17,33395.17,33395.17,33395.17,333426.78

Actual values from what chart and what platform or library?

It is convenient to for me or anyone else who may have a solution when you provide more details than arbitrary data. I have no idea what ticker you are using, what exchange it is from, what platform you are comparing against, etc.... You provide no data to verify either your own or from the platform you are comparing against.

> The first value in 0 in supertrend, maybe thats giving an error

Perhaps. 🤷🏼‍♂️ You can easily modify your local copy and test it out.

<br/>

Again I am having to retype the same questions that I typed in the Bug Form.

<img width="675" alt="Screen Shot 2021-05-18 at 7 44 10 PM" src="https://user-images.githubusercontent.com/18198392/118749031-95ac8b80-b811-11eb-8281-1a8b8bbdbc39.png">

<br/>

I have also outlined this in the README.

<img width="666" alt="Screen Shot 2021-05-18 at 7 41 03 PM" src="https://user-images.githubusercontent.com/18198392/118749143-ca204780-b811-11eb-824f-0c3c18bbb880.png">

<br/>

Looking forward for more information so I can _properly_ address the Issue.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @karthiceaswar,

Feel free to reopen the Issue when you are ready to provide data and reproducible code so I can _properly_ assist you with this Issue.

Thanks,
KJ
