### ISSUE TITLE
join ?

### ISSUE THREAD

**Issue by asmodehn** [twopirllc/pandas-ta#29]
Hi,

I am discovering pandas_ta, and I was wondering why 'append' is an option in the API, but not join ?
It seems to me, naively, that join would be a useful option, especially to link an indicator with the time of the current dataframe...

**Comment by asmodehn** [comment]
Or maybe I am just not understanding something... I had a bunch of NaN in my dataframe head(), but it was not because the indicator didnt had value for the first rows, and not because of the append like i assumed at first.

**Comment by twopirllc** [comment]
Hello @asmodehn ,

All append does when using ```df.ta.indicator(*, append=True)``` is put the resultant columns at the end of the current dataframe ```df```.  So ```df.ta.macd(fast=3, slow=10, append=True)``` will three new columns to ```df```.  I think ```df.join``` may be useful, but at the time I thought normal column assignment was the easiest and quickest way to apply the columns to the current dataframe.

Is the current implementation of 'append' not working correctly in regards to your second post?  Do you have a specific example and output I can look at to get a better understanding?

Thanks
