### ISSUE TITLE
Help Not Showing Up In The Terminal!!

### ISSUE THREAD

**Issue by xcoderrrrr** [twopirllc/pandas-ta#290]
# For Some Reason Help Option Is Not Showing Up In The Terminal!
Here is my code:
```
import pandas-ta as ta
import pandas as pd

df = pd.DataFrame
help(df.ta)
df.ta.indicators()
help(pandas_ta.atr)
```
Please help!

**Comment by dopevog** [comment]
There is no bug at all. The Only thing is that you have forgotten to add ```()``` at the end of ```pd = pd.DataFrame```.
Your code should look like this:
```
import pandas-ta as ta
import pandas as pd

df = pd.DataFrame()
help(df.ta)
df.ta.indicators()
help(pandas_ta.atr)
```
This should work!

**Comment by xcoderrrrr** [comment]
Thanks! It works now.....

**Comment by twopirllc** [comment]
Great! Thanks for helping @dopevog!

KJ
