### ISSUE TITLE
New indicators issue

### ISSUE THREAD

**Issue by satishchaudhary382** [twopirllc/pandas-ta#291]
**Expected behavior**
I was keen to try new indicators add into this beautiful library however, the list of new indicators shows attribute error

AttributeError: module 'pandas_ta' has no attribute 'stc'

**Screenshots**
![image](https://user-images.githubusercontent.com/39291322/118910969-1a4bf680-b945-11eb-9bd0-3f3b07e83a1a.png)

**Comment by twopirllc** [comment]
Hello @satishchaudhary382,

Please fill out the Bug Report as requested. You have **not** provided enough information for me or anyone else to assist your with this Issue.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @satishchaudhary382,

I assume by no response you have figured it out. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
