### ISSUE TITLE
What are long_run and short_run trend indicators?

### ISSUE THREAD

**Issue by coinrazzi** [twopirllc/pandas-ta#296]
Hi,
What are long_run and short_run trend indicators?
I use it. And print results gor long_run and short_run as DataFrame. But i did not difference between results. I did not understand what is benefits those indicators?

long_run results Bitcoin 5 minute data
    close
0   37056
1   37056
2   37075
3   36883
4   37144
..    ...
75  35389
76  35097
77  35173
78  35340
79  35458

[80 rows x 1 columns]    

long_run results Bitcoin 5 minute data
 close
0   37056
1   37056
2   37075
3   36883
4   37144
..    ...
75  35389
76  35097
77  35173
78  35340
79  35458

[80 rows x 1 columns]

**Comment by twopirllc** [comment]
Hello @coinrazzi,

They are part of _my_ custom indicators along with [**amat**](https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/trend/amat.py) and [**aobv**](https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/volume/aobv.py). In fact **long_run** and **short_run** are _required_ for **amat** and **abov**. I ported _Archer Moving Average Trend_ (**amat**) from my Trading View Pine Script [**Trade Archer - Moving Averages - v1.4F**](https://www.tradingview.com/script/Z2mq63fE-Trade-Archer-Moving-Averages-v1-4F/)).

Regarding **long_run** (and conversely **short_run**), their ```fast``` and ```slow``` parameters work best with smoothed series. It makes it easier to tell if they are **increasing** and **decreasing**. Long Run then checks if ```fast``` and ```slow``` are potentially crossing _or_ both increasing (think parallel):

```python
def long_run(fast, slow, length=None, offset=None, **kwargs):
    """Indicator: Long Run"""
    # ...

    # Calculate Result
    pb = increasing(fast, length) & decreasing(slow, length)  # potential bottom or bottom
    bi = increasing(fast, length) & increasing(slow, length)  # fast and slow are increasing
    long_run = pb | bi  # more signals with or, less with and (&)

    return long_run # Returns binary series 1 if long trend, 0 otherwise
```

_Archer Moving Average Trend_ (**amat**) just uses Moving Averages for their ```fast``` and ```slow``` parameters. But you are not limited to just Moving Averages as ```fast``` and ```slow``` parameters of course, preferably smoothed series. For instance, you can pass in two different Moving Averages like ```HMA_10``` and ```SMA_50``` for ```fast``` and ```slow``` or even ```macd``` and ```macd signal``` for ```fast``` and ```slow```. Experiment.

Long Run and Short Run return binary series (```0001111010111...```), _1_ or a trend and _0_ not a trend.

Example:
```python
import pandas_ta as ta

df = # ohlcv
closedf = df["close"]
# This is literally **amat**
lrun = df.ta.long_run(ta.ema(closedf, 8), ta.ema(closedf, 21), append=False)
srun = df.ta.short_run(ta.ema(closedf, 8), ta.ema(closedf, 21), append=False)
srun.tail(50).plot(kind='bar', figsize=(16,0.5), color=['red'], linewidth=1, alpha=0.45)
lrun.tail(50).plot(kind='bar', figsize=(16,0.5), color=['green'], linewidth=1, alpha=0.45, title=f"{lrun.name}(green) & {srun.name}(red)")
```

<img width="756" alt="Screen Shot 2021-05-23 at 12 48 11 PM" src="https://user-images.githubusercontent.com/18198392/119274563-5e4d2e80-bbc5-11eb-8dfc-192364aff2a0.png">

<br/>

Hope this makes more sense.

Kind Regards,
KJ

**Comment by coinrazzi** [comment]
Great information. thank you :)
