### ISSUE TITLE
AttributeError: module 'pandas_ta' has no attribute 'ticker'

### ISSUE THREAD

**Issue by wenny0501** [twopirllc/pandas-ta#309]
Hi, I like pandas_ta. it is very useful.
but i meet un problem.
is it a bug?

**Which version are you running? The lastest version is on Github. Pip is for major releases.**

ta.version
0.2.45b0

**Describe the bug**

help(ta.sma)
ok
help(ta.ticker)
AttributeError: module 'pandas_ta' has no attribute 'ticker'
help(ta.yf)
AttributeError: module 'pandas_ta' has no attribute 'yf'
**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/68882045/121597162-5e935980-ca0e-11eb-87f2-753f90971621.png)

Thanks

**Comment by twopirllc** [comment]
Hello @wenny0501,

This is **not** a bug. You are just running an older version of the library. Thus to use ```ta.yf()``` or ```df.ta.ticker()``` as mentioned on the README, you need to upgrade to the _Latest Version_. Using the Latest Version ensures you get bug fixes and newer features.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

<br/>

> is only daily historical data acceptable?
can we use hourly (30 min, 5 min, etc.) historical data?

You are _not_ limited to Daily data. You are _largely_ limited to what **yfinance** is capable of. For more information, please see the README or use ```help(ta.yf)``` for it's capabilities.

<img width="792" alt="Screen Shot 2021-06-10 at 2 26 08 PM" src="https://user-images.githubusercontent.com/18198392/121599484-f5085080-c9f7-11eb-8837-c8bb7eb35061.png">


Please let me know when you install the Latest Version and able to get data.

Thanks,
KJ

**Comment by wenny0501** [comment]
thanks

**Comment by twopirllc** [comment]
Hello @wenny0501,

Were you able to install the Latest Version and get data?

Thanks,
KJ

**Comment by wenny0501** [comment]
yes, it works well.
thanks.

**Comment by twopirllc** [comment]
@wenny0501 

Thanks for confirming.

Happy trading/investing!
KJ
