### ISSUE TITLE
[Enhancement] Consider Vectorize Algorithms 

### ISSUE THREAD

**Issue by MichaelHelmers** [twopirllc/pandas-ta#31]
I recently stumbled upon your project (literally about 2 hours ago) and I've only had a chance to go through a few of your tools but I noticed a few of them that are ripe for vectorization.  For example, looking at the WMA implementation you have (I've removed some fluff to conserve space since this is already a long post):

```python
from pandas import Series
from numpy import arange

def wma(close, length):
    total_weight = 0.5 * length * (length + 1)
    weights_ = Series(arange(1, length + 1))
    def linear(w):
        def _compute(x):
            return (w * x).sum() / total_weight
        return _compute
    close_ = close.rolling(length, min_periods=length)
    wma = close_.apply(linear(weights), raw=True)
    return wma
```

Using convolution and Numpy's ability to operate on an entire array at the same time we can get a massive speedup over you method, albeit at the expense of ease of understanding.  Here's what I came up with:

```python
from numpy import arange
from scipy.ndimage import convolve1d as conv

def wma(close, length):
    weights = arange(1, length) / arange(1, length).sum()
    return conv(close, weights=weights, axis=0, mode='nearest')
```

Just as a quick test I pulled in the last 1000 5 minute time-frame tick marks from an exchange, then created a length 10, 100, and 1000 DataFrame on the closes.  Here is the code:

```python
import numpy as np, timeit
setup = '''
import pandas as pd
from numpy import arange
from pandas import Series
from scipy.ndimage import convolve1d as conv
def my_wma(dr, length):
    wts = arange(1, length) / arange(1, length).sum()
    return conv(dr, weights=wts, axis=0, mode='nearest')
def your_wma(close, length):
    total_weight = 0.5 * length * (length + 1)
    weights = Series(arange(1, length + 1))
    def linear(w):
        def _compute(x):
            return (w * x).sum() / total_weight
        return _compute
    close_ = close.rolling(length, min_periods=length)
    wma = close_.apply(linear(weights), raw=True)
    return wma
    
df = READ IN FROM CSV
df1 = df['close'].tail(10)
df2 = df['close'].tail(100)
df3 = df['close'].tail(1000)
'''
myt1 = timeit.repeat('my_wma(df1.values, 9)', setup=setup, number=100, repeat=10)
myt2 = timeit.repeat('my_wma(df2.values, 9)', setup=setup, number=100, repeat=10)
myt3 = timeit.repeat('my_wma(df3.values, 9)', setup=setup, number=100, repeat=10)
yourt1 = timeit.repeat('your_wma(df1, 9)', setup=setup, number=100, repeat=10)
yourt2 = timeit.repeat('your_wma(df2, 9)', setup=setup, number=100, repeat=10)
yourt3 = timeit.repeat('your_wma(df3, 9)', setup=setup, number=100, repeat=10)
print('Average Speed difference: {:0.01f}x'.format(np.mean(np.divide(yourt1, myt1))))
print('Average Speed difference: {:0.01f}x'.format(np.mean(np.divide(yourt2, myt2))))
print('Average Speed difference: {:0.01f}x'.format(np.mean(np.divide(yourt3, myt3))))
```
and the result was...
```
Average Speed difference: 29.2x
Average Speed difference: 613.0x
Average Speed difference: 5258.9x
```
I also ran 
```python
%timeit my_wma(df1.values, 9)
%timeit my_wma(df2.values, 9)
%timeit my_wma(df3.values, 9)
%timeit your_wma(df1, 9)
%timeit your_wma(df2, 9)
%timeit your_wma(df3, 9)
```
And got the results:
```
22.1 µs ± 58 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
22.7 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
27.9 µs ± 42.5 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

664 µs ± 3.02 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
14.2 ms ± 20.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
150 ms ± 575 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
I realize that this is speedup would really be beneficial to someone who is calculating the averages for all historical points and that real time trading that the speed would probably not make a huge impact.  However, it's clear to me that this method is much more efficient and IMO every bit of speedup helps, especially if one is back-testing.

**Comment by twopirllc** [comment]
Hello @MichaelHelmers,

Thanks for the analysis, feedback and the recommendation to optimize some of the algorithms by vectorization.  I agree that the there should be speed increases and I am not opposed to such improvements in this module..  

While developing this module, I wanted to cover as many indicators as I could as well as keep it tightly coupled with _pandas_ and it's dependent modules.  It was better to have it implemented as accurately as possible first and then find ways to speed up slower algorithms.

I know that _pandas_ does not depend on _scipy_ but _numpy_, so I am curious as to why you used _scipy_'s convolve method and not _numpy_'s?  Is there a difference in speed or accuracy between the two?

You are welcome to fork and make a pull request with your optimizations.  No doubt other users of the module would appreciate the optimizations also.

Thanks,
KJ

**Comment by goodboy** [comment]
@twopirllc the `numpy` / vectorized version is also more generalized since you can pass in a weights curve if needed.

If @MichaelHelmers doesn't address this I would happy to.

I'm actually quite interested in a lot of what you have in this repo except would much prefer it ported (where possible) to `numpy` (mostly for speed).

**Comment by twopirllc** [comment]
Hello @goodboy,

Coincidentally, today I have updated ```ema``` and ```wma```. Just finishing supplementary code before pushing it to Github. I have replaced:
```python
def wma(**kwargs):
    ...

    def linear(w):
        def _compute(x):
            return (w * x).sum() / total_weight
        return _compute
    ...
```
with ```numpy```'s ```dot``` product for a speed boost.
```python
def wma(**kwargs):
    ...

    def linear(w):
        def _compute(x):
            return np.dot(x, w) / total_weight
        return _compute
    ...
```

I am open to speed gains whether it is handled via ```pandas``` or ```numpy``` as long as the indicators return ```Series``` or ```DataFrame``` by default. We could also put in a ```numpy``` kwarg in the indicators to return ```numpy``` arrays so you can have the ```numpy``` port.

You are welcome to _fork_ and make modifications. I see that you also have some experience with ```PyTest```. I would like some help to migrate to ```PyTest``` if it makes a difference.  Thoughts?

Thanks,
KJ

**Comment by goodboy** [comment]
>with numpy's dot product for a speed boost.

:tada: 

>I am open to speed gains

:+1: 

> We could also put in a numpy kwarg in the indicators to return numpy arrays so you can have the numpy port.

This is interesting.
I'm firstly curious why you chose `pandas` for first class support [considering the well known the performance differences](https://zerowithdot.com/python-numpy-and-pandas-performance/).
Normally I would expect that *wrapping in `pandas`* data structures would be the more optional thing.
This is maybe something worth discussion in a separate issue.
 
For my immediate purposes I'm actually after a set of routines that can also handle streaming.

That is, code more along the lines of:

```python
async def wma(
    source: AsyncStream[np.ndarray],
    length: int, 
    weights: np.ndarray
) -> AsyncIterator :
    _lookback = np.zeros(length - 1)
    async for frame_len, frame in source:
        wma = np.convolve(frame, w, 'valid')
        # todo: handle case where frame_len < length - 1
        _lookback = frame[-(length-1):]
        yield wma
````
(Note, this is an untested example).

Where offline processing is actually the special (i.e. single iteration) case.

It is basically an api where the user is in control of the details of `DataFrame.rolling()` on a per frame basis like you'd expect in any real-time signal processing system.

The platform I'm about to release is built entirely on the premise of streamed real-time data, however, offline processing should also be a special case that occurs every time a new historical sequence is loaded.
 
Maybe this is something we can talk more about :smile_cat: 

>I see that you also have some experience with PyTest

Heh, just a bit :wink:.
I'm definitely down to help with this port; it would help get my head in all these routines.

I'm currently attempting to get a first draft of a real-time charting system out the door.
Once that's complete and I have an API more finalized for that I think we can actually be of good use to one another :surfer:.

**Comment by twopirllc** [comment]
@goodboy,

> I'm firstly curious why you chose pandas for first class support considering the well known the performance differences.

> > I am open to speed gains

Funny, I reread that link prior to responding to your original post. Simple answer, I have more direct experience with ```pandas``` versus ```numpy``` and I have little time to learn another API and it's nuances while developing supplemental components for my Quant/Algo Trading Platform. Furthermore:

> > While developing this module, I wanted to cover as many indicators as I could as well as keep it tightly coupled with pandas and it's dependent modules. It was better to have it implemented as accurately as possible first and then find ways to speed up slower algorithms.

> For my immediate purposes I'm actually after a set of routines that can also handle streaming.
> I'm currently attempting to get a first draft of a real-time charting system out the door.
Once that's complete and I have an API more finalized for that I think we can actually be of good use to one another 🏄.
> The platform I'm about to release is built entirely on the premise of streamed real-time data, however, offline processing should also be a special case that occurs every time a new historical sequence is loaded.

Nice! 😸 

For your case, it makes sense for your real-time charting system to utilize streaming. What time frames do you trade in? What types of assets? What data sources do you use?

Regarding ```PyTest```, I would start with the **_Candle_** and **_Performance_** indicators since there are a few of them.

Open to new ideas, discussions and more time! 🤣 

Regards,
KJ
