### ISSUE TITLE
TTM Squeeze PRO indicator

### ISSUE THREAD

**Issue by zlpatel** [twopirllc/pandas-ta#313]
First of all, I use squeeze indicator (ttm squeeze) and I love it. But I was wondering if someone can create john carter's new squeeze indicator called "ttm squeeze pro".

Here are some links:

https://usethinkscript.com/threads/john-carters-squeeze-pro-indicator-for-thinkorswim-free.4021/
https://www.tradingview.com/script/TAAt6eRX-Squeeze-PRO-Indicator-Makit0/

**Comment by twopirllc** [comment]
Hello @zlpatel,

Will add it to the list. Thanks for using Pandas TA.

Kind regards,
KJ

**Comment by zlpatel** [comment]
I am working on this issue.
