### ISSUE TITLE
Issue with VWMA passing in wrong parameters?

### ISSUE THREAD

**Issue by DannyMartens** [twopirllc/pandas-ta#316]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```
0.2.45b
```

**Describe the bug**
Stepping through the code I noticed that vwma has volume set to close. See: 
![image](https://user-images.githubusercontent.com/37220423/123451630-4c372500-d5a3-11eb-8ca9-ef65e399b62b.png)

**To Reproduce**
Run any code that uses vwma
```python
    def vwap(self, anchor=None, offset=None, **kwargs):
        high = self._get_column(kwargs.pop("high", "high"))
        low = self._get_column(kwargs.pop("low", "low"))
        close = self._get_column(kwargs.pop("close", "close"))
        volume = self._get_column(kwargs.pop("volume", "volume"))

        if not self.datetime_ordered:
            volume.index = self._df.index

        result = vwap(high=high, low=low, close=close, volume=volume, anchor=anchor, offset=offset, **kwargs)
        return self._post_process(result, **kwargs)

    def vwma(self, volume=None, length=None, offset=None, **kwargs):
        close = self._get_column(kwargs.pop("close", "close"))
        volume = self._get_column(kwargs.pop("volume", "volume"))

        result = vwma(close=close, volume=close, length=length, offset=offset, **kwargs)
        return self._post_process(result, **kwargs)
```
**Expected behavior**
```
volume=volume
```

Let me know if I missed something basic or I am just being dumb

**Comment by twopirllc** [comment]
Hi @DannyMartens,

Doh! The Curse of Copy/Paste sometimes. Thanks for catching it! Want to make a PR and get contribution credit?

Thanks,
KJ

**Comment by DannyMartens** [comment]
Sure, PR here: https://github.com/twopirllc/pandas-ta/pull/317
