### ISSUE TITLE
Error: Reindexing only valid with uniquely valued Index objects

### ISSUE THREAD

**Issue by justmeonthegit** [twopirllc/pandas-ta#323]
Using python 3.7.7

When calling ATR i get an error:
```sh
2021-07-03 08:01:49.416460 1 cdX9cpVr23rnQjEVnRTh4x ERROR Error from indicator.py,values line nr 115,

 Code: <class 'pandas.errors.InvalidIndexError'> with message: Reindexing only valid with uniquely valued Index objects

  File "c:\traderbot\engine\src\indicators\indicator.py", line 115, in values
    tbi.calculate()
  File "c:\traderbot\engine\src\indicators\atr.py", line 138, in calculate
    self.__calculate_atr()
  File "c:\traderbot\engine\src\indicators\atr.py", line 151, in __calculate_atr
    self.ohlc_data['value'] = pta.atr(self.ohlc_data['high'], self.ohlc_data['low'], self.ohlc_data['close'], length=self.length)
  File "C:\Users\Marcel\miniconda3\lib\site-packages\pandas_ta\volatility\atr.py", line 19, in atr
    tr = true_range(high=high, low=low, close=close, drift=drift)
  File "C:\Users\Marcel\miniconda3\lib\site-packages\pandas_ta\volatility\true_range.py", line 19, in true_range
    true_range = DataFrame(ranges).T
  File "C:\Users\Marcel\miniconda3\lib\site-packages\pandas\core\frame.py", line 509, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "C:\Users\Marcel\miniconda3\lib\site-packages\pandas\core\internals\construction.py", line 531, in to_arrays
    data, columns, coerce_float=coerce_float, dtype=dtype
  File "C:\Users\Marcel\miniconda3\lib\site-packages\pandas\core\internals\construction.py", line 593, in _list_of_series_to_arrays
    indexer = indexer_cache[id(index)] = index.get_indexer(columns)
  File "C:\Users\Marcel\miniconda3\lib\site-packages\pandas\core\indexes\base.py", line 2987, in get_indexer
    "Reindexing only valid with uniquely valued Index objects"
```

I use the following code:

```python
   self.ohlc_data['value'] = pta.atr(self.ohlc_data['high'], self.ohlc_data['low'], self.ohlc_data['close'], length=self.length)
```

The values of self.length = 14 (int)
The values of self.ohlc_data is:
```

              time      open      high       low     close    volume             utctime
568  1622668800000  31044.37  31078.11  30978.01  30995.23  6.426382 2021-06-02 21:20:00
569  1622669100000  30991.14  31010.72  30959.10  30965.50  3.925410 2021-06-02 21:25:00
570  1622669400000  30973.65  30995.46  30960.07  30969.20  2.848319 2021-06-02 21:30:00
571  1622669700000  30974.26  30974.26  30884.00  30947.30  6.709024 2021-06-02 21:35:00
572  1622670000000  30942.12  31023.78  30938.60  31005.30  6.739472 2021-06-02 21:40:00
..             ...       ...       ...       ...       ...       ...                 ...
665  1625289900000  28318.14  28393.51  28318.14  28345.29  3.075262 2021-07-03 05:25:00
666  1625290200000  28345.29  28404.71  28345.29  28391.58  5.038435 2021-07-03 05:30:00
667  1625290500000  28391.57  28430.28  28388.75  28430.28  7.276387 2021-07-03 05:35:00
668  1625290800000  28430.28  28441.98  28415.00  28433.43  5.479073 2021-07-03 05:40:00
669  1625291100000  28433.49  28439.95  28402.98  28439.95  1.732114 2021-07-03 05:45:00
[8742 rows x 7 columns]
```

I have two scenario's:
Running in production
Running in backtest

Running in production goes good.
Running in backtest (data above) is producing this error, because the index is not unique

So If i reindex the dataframe with it works well:
self.ohlc_data = self.ohlc_data.reset_index(drop=True) 

Which is a little bit strange as I pass series to the atr, so somewhere in the code is a referall to the complete df.

**Comment by twopirllc** [comment]
Hello @justmeonthegit,

For production and backtest environments, what version of Python, Pandas TA are you using? Also are you using TA Lib for either? What does the working production code look like in comparison to the one-liner you provided?

Please post a smaller subset, 500 rows, of your ohlc data.

> Which is a little bit strange as I pass series to the atr, so somewhere in the code is a referall to the complete df.

Please provide evidence of this so I can narrow down the problem.

Kind Regards,
KJ

**Comment by justmeonthegit** [comment]
Hi KJ,

The production services and backtest are for this case the same (running in
same conda env).

Version numbers see below:

-07-03 19:22:29.524981 3 YHHHmkxy6CXMFkCnzxnoE4 INFO  Information about the
running Pyhton version
2021-07-03 19:22:29.525972 2 YHHHmkxy6CXMFkCnzxnoE4 WARNI 3.7.7 (default,
May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
2021-07-03 19:22:29.525972 3 YHHHmkxy6CXMFkCnzxnoE4 INFO
2021-07-03 19:22:29.526938 3 YHHHmkxy6CXMFkCnzxnoE4 INFO  CCXT version
1.51.1
2021-07-03 19:22:29.526938 3 YHHHmkxy6CXMFkCnzxnoE4 INFO  CCXT is under
ccxt/ccxt is licensed under the MIT License
2021-07-03 19:22:29.526938 3 YHHHmkxy6CXMFkCnzxnoE4 INFO
https://github.com/ccxt/ccxt/blob/master/LICENSE.txt
2021-07-03 19:22:29.526938 3 YHHHmkxy6CXMFkCnzxnoE4 INFO
2021-07-03 19:22:29.527976 3 YHHHmkxy6CXMFkCnzxnoE4 INFO  TA-Lib version
0.4.19
2021-07-03 19:22:29.527976 3 YHHHmkxy6CXMFkCnzxnoE4 INFO  License
information at https://github.com/mrjbq7/ta-lib/blob/master/LICENSE
2021-07-03 19:22:29.527976 3 YHHHmkxy6CXMFkCnzxnoE4 INFO
2021-07-03 19:22:29.528932 3 YHHHmkxy6CXMFkCnzxnoE4 INFO  Tulipy version
0.8.4
2021-07-03 19:22:29.528932 3 YHHHmkxy6CXMFkCnzxnoE4 INFO  License
information at https://tulipindicators.org/license
2021-07-03 19:22:29.528932 3 YHHHmkxy6CXMFkCnzxnoE4 INFO
2021-07-03 19:22:29.530960 3 YHHHmkxy6CXMFkCnzxnoE4 INFO  Pandas TA 0.2.45b0
2021-07-03 19:22:29.531955 3 YHHHmkxy6CXMFkCnzxnoE4 INFO
https://github.com/twopirllc/pandas-ta

The code for production is exactly the same (for me this is a boolean in a
configuration file)
The complete code is not very usesfull in this.


I can create a unitest with a posting of 500 rows but need some time for
that. I cannot imagine that the length of a dataframe will be the issues :-)
Especially as a redindex wil solve the problem then the problem lies into
the indexation. My data index with 8742 contains with double index numbers.

I think the problem lies in the fact that I will post
self.ohlc_data['high'] which you probably recieve as a series. But in fact
in memory it will be a pointer to the complete dataframe.

**Comment by twopirllc** [comment]
@justmeonthegit,

So the _error_ has to do with ```true_range``` and **not** ```atr``` since it's the last Pandas TA call before Pandas has an Issue with it. That last call is: ```true_range = DataFrame(ranges).T```. More recent versions of Pandas TA use ```true_range = concat(ranges, axis=1)``` instead, so that may resolve the Issue.

The easiest thing to test, in my opinion, would be to upgrade from ```v0.2.45``` to ```v0.3.02b``` (released yesterday) since there have been numerous bug fixes and enhancements in the library since then.

Should you choose to upgrade and you have TA Lib installed, [35 indicators](https://github.com/twopirllc/pandas-ta/search?q=if+Imports%5B%22talib%22%5D%3A) of Pandas TA will use TA Lib's calculations instead. Based on TA Lib's C source, indexes are not considered for their computations. Also if you choose to use **vwap** from Pandas TA, the price and volume indexes must be an ordered Datetime Index.

Keep me posted on what you choose to do and if the problem gets resolved (hopefully via upgrading 😉).

Thanks,
KJ

**Comment by justmeonthegit** [comment]
Hi KJ,

I resolved it by doing a reindex in one of the data components, so then everything was fine for me. If you need test info just let me knwo.

Meanwhile : I update pandas-TA, thxs for mentioning. 

Regards,

**Comment by twopirllc** [comment]
@justmeonthegit,

No worries. Glad you have a working solution and replied in a timely manner. 😎 

GL 🍀 

KJ
