### ISSUE TITLE
KVO formula looks a bit in correct

### ISSUE THREAD

**Issue by navdeepchahal22** [twopirllc/pandas-ta#327]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
Version: 0.3.2b0

**Describe the bug**
formula used in kvo doesnt match general formual for example https://www.investopedia.com/terms/k/klingeroscillator.asp on investopedia or other sources formula for VF is, VF = V×[2×((dm/cm)−1)]×T×100, but you have used (2 * dm / cm - 1) in line 35 of kvo.py, which should be (2 * (dm / cm - 1)) to give correct values

**To Reproduce**
just run kvo.py

Thank you

**Comment by twopirllc** [comment]
Hello @navdeepchahal22,

Hmm... I will take a look and check it out. Thanks for the heads up!

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@navdeepchahal22,

I am changing it to TradingView's implementation:

```
//@version=4
study(title="Klinger Oscillator", format=format.volume, resolution="")
sv = change(hlc3) >= 0 ? volume : -volume
kvo = ema(sv, 34) - ema(sv, 55)
sig = ema(kvo, 13)
```

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @navdeepchahal22,

If you want to test out **kvo** before I update the _main_ branch, you can install the _development_ branch by installing:

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by navdeepchahal22** [comment]
hey ,
i apoligoze as i will not be able to verify now, as i have moved on a lot on my project.
thank you though for providing detailed infromation on indicators

**Comment by twopirllc** [comment]
@navdeepchahal22,

No worries. Just informing you.

KJ
