### ISSUE TITLE
problem with lenght

### ISSUE THREAD

**Issue by 1giax1** [twopirllc/pandas-ta#33]
hi mate,
i try to use your indicator but i have a problem when i use the parameter lenght:
`sma=df.ta.sma(close=df['close'],lenght=10)
print(df['close'].tail(3))
print(sma.tail(3))`

and the output:

3922    8079.54
3923    8073.16
3924    8076.36
Name: close, dtype: float64
3922    8064.433
3923    8062.750
3924    8061.351
Name: SMA_10, dtype: float64

and if i put 
sma=df.ta.sma(close=df['close'],lenght=20)

the output is
3922    8079.54
3923    8073.16
3924    8076.36
Name: close, dtype: float64
3922    8064.433
3923    8062.750
3924    8061.351
Name: SMA_10, dtype: float64

so not change anything..
where is my mistake ? because every time use the else condition

# Validate Arguments
    close = verify_series(close)
    length = int(length) if length and length > 0 else 10
    offset = get_offset(offset)

**Comment by hydroplosion** [comment]
You're spelling 'length' incorrectly.

**Comment by twopirllc** [comment]
Hello @1giax1 ,

Thanks for the post.  Have you tried @hydroplosion 's recommendation?

Thanks.

**Comment by 1giax1** [comment]
Yeah thanks you so much everybody.. you can close the issue if you want
Thanks alot
