### ISSUE TITLE
atr sometimes wrong

### ISSUE THREAD

**Issue by bonusguy** [twopirllc/pandas-ta#330]
Version: 0.3.02b

**Describe the bug**
Sometimes I get atr(14) even if I call atr(3)

<img width="507" alt="Screenshot_5" src="https://user-images.githubusercontent.com/22365509/124748196-1854eb80-df23-11eb-9d69-069009ac33df.png">

I guess the error is here in atr.py:
<img width="389" alt="Screenshot_6" src="https://user-images.githubusercontent.com/22365509/124748381-56520f80-df23-11eb-859f-26fa64cab170.png">

probably it has to be:
atr = ATR(high, low, close, length)

Thanks!

**Comment by twopirllc** [comment]
Hello @bonusguy,

Doh! 🤦🏼 Nice catch! Want to make a PR and get contribution credit? Would greatly appreciate it. 😎 If not, no worries.

Kind Regards,
KJ

**Comment by schwaa** [comment]
I'm using the latest version (0.3.2b0) my ATR is wrong and length is ignored.  It looks like its always 14 days. I assume this is the same issue? Only 10hrs old any thoughts on the fix for this? I assume there would be a new build, I would need to install/build?  Thank you

**Comment by twopirllc** [comment]
Hello @schwaa,

> I assume this is the same issue?

If you have TA Lib installed as well, then it is the same Issue.

> Only 10hrs old any thoughts on the fix for this?

It's on the near term to do list. However, there is _nothing_ to prevent you from editing your local copy to temporarily patch the Issue until the fix is in. Furthermore, I am open to contributions for Issues or additional Features to help speed the process along.

Kind Regards,
KJ

**Comment by schwaa** [comment]
I'm pretty sure I can make the change, but not sure how to commit the code. ie like I know how to commit -a and git push, but not in a project like this.

**Comment by twopirllc** [comment]
@schwaa,

You have to be authorized to do pushes. However you can try a pull request. If you can not figure it out, not worries, at least you have a fixed local version for the time being. I typically inform people when Issues have been corrected and the _main_ branch has been updated.

Thanks,
KJ

**Comment by twopirllc** [comment]
@bonusguy,

It is now available on the _development_ branch if you want to check it out before I update the _main_ branch.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks for your patience,
KJ

**Comment by bonusguy** [comment]
Hi Kevin,

thanks for notifying me and sorry that I didnt make the change. It was my
first issue and never did a pull request so far. For the next bug I promise
to provide the fix.
Thanks for sharing your nice library,

Urban

Am Sa., 10. Juli 2021 um 19:39 Uhr schrieb Kevin Johnson <
***@***.***>:

**Comment by twopirllc** [comment]
@bonusguy,

No worries. Thanks for using the library and helping to improve it.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @bonusguy ,

New stable version _v0.3.14b_ should help resolve this Issue. Please let me know otherwise.

```sh
$ pip install pandas_ta
```

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @bonusguy,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
