### ISSUE TITLE
DataFrame KeyError

### ISSUE THREAD

**Issue by rafalsza** [twopirllc/pandas-ta#331]
python 3.8
pandas_ta version=0.3.2b0

problem with lenght attribute for ta.supertrend, can't calculate lenght > 7

```python
    candlesticks = client.get_historical_klines(symbol, Client.KLINE_INTERVAL_15MINUTE, '1 day ago UTC')

    # trim each candle
    for candle in candlesticks:
        del candle[-6:]  # only need the first few columns
    df = pd.DataFrame(candlesticks[:-1], columns=['timestamp', 'open', 'high', 'low', 'close', 'volume']).astype(float)
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    df = df.set_index(pd.DatetimeIndex(df['timestamp'].values))
    df = ta.ha(df['open'], df['high'], df['low'], df['close'])

    df['sup'] = ta.supertrend(high=df['HA_high'], low=df['HA_low'], close=df['HA_close'], lenght=12, multiplier=2.1)['SUPERT_12_2.1']
```

out:

```sh
Traceback (most recent call last):
  File "C:\supertrend-crypto-bot-main\new3.py", line 60, in <module>
    run_bot()
  File "C:\supertrend-crypto-bot-main\new3.py", line 35, in run_bot
    df['sup'] = ta.supertrend(high=df['HA_high'], low=df['HA_low'], close=df['HA_close'], lenght=12, multiplier=2.1)['SUPERT_12_2.1']
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'SUPERT_12_2.1'
```

**Comment by twopirllc** [comment]
Hello @rafalsza,

It appears that ```lenght != length```. Or is there another Issue that I am not seeing?

Kind Regards,
KJ

**Comment by rafalsza** [comment]
in my case lenght=lenght, question is how can I calculate supertrend for lenght e.g.  12 and multiplier 9  ?

**Comment by rafalsza** [comment]
when I'm using lenght>7 and multiplier>3.0 I'm getting an error e.g. File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'SUPERT_12_9.0'

**Comment by twopirllc** [comment]
@rafalsza,

I apologize if my English was **not** clear the first time. You **clearly** misspelled ```length```. This is a _basic_ user error and **not** an error with Pandas TA, Pandas, or even Python. In your code above, change ```lenght``` to ```length``` to resolve **your** problem.

Furthermore, nowhere in the ```supertrend``` signature does it have ```lenght``` as a parameter/argument! So when you pass in the parameter ```lenght=12```, ```lenght=12``` becomes a key/value pair in the dict ```kwargs``` instead and ```length``` defaults to 7 and **does not** get updated to 12 as you hoped. Therefore the output name of the first DataFrame column ```ta.supertrend``` returns begins with "SUPERT_7" **and not** "SUPERT_12" as you expected.

```python
def supertrend(high, low, close, length=None, multiplier=None, offset=None, **kwargs):
    """Indicator: Supertrend"""
    # Validate Arguments
    length = int(length) if length and length > 0 else 7
    ...
```

Kind Regards,
KJ
