### ISSUE TITLE
Are there any indicators for other Binance outputs?

### ISSUE THREAD

**Issue by reza1615** [twopirllc/pandas-ta#333]
Binance API output has more columns than OHLC. Are there any indicators which uses these data?
#https://binance-docs.github.io/apidocs/spot/en/#compressed-aggregate-trades-list
![image](https://user-images.githubusercontent.com/2202483/124937966-ddf85680-dfd5-11eb-9cc6-209a32043d89.png)

**Comment by twopirllc** [comment]
Hello @reza1615,

Currently there are not. However, contributions are encouraged whether for new indicators, features, optimizations or bug fixes. 😎 

Kind Regards,
KJ
