### ISSUE TITLE
MACDAS Indicator Request

### ISSUE THREAD

**Issue by UlasTosun** [twopirllc/pandas-ta#336]
Hi @twopirllc ,
MACDAS, MACD AS, MACD-AS or Thomas Aspray's MACD is a special version of MACD indicator. People believe that, it reacts faster than classical MACD for buy/sell signals. Since it is based on classical MACD, I hope that it will be easy for you to add MACDAS to Pandas-TA. Could you add it to Pandas-TA please.
I couldn't find better sources for it, however I hope that following links will be enough.
[Main Source](https://tr.tradingview.com/script/YFlKXHnP/)
[Alternative Source 1](https://tr.tradingview.com/script/cCjJn2bp-MACDAS-by-KIVANCfr3762-with-Plots-and-Alerts/)
[Alternative Source 2](https://tr.tradingview.com/script/MHHBY0K7-MACD-AS/)

**Comment by twopirllc** [comment]
@UlasTosun,

Sure. Looking at the Pinescript code below, it does not warrant a separate indicator. I can add a switch to **macd** to handle the additional differences.

```
fastMA = ema(close, fastperiod)
slowMA = ema(close, slowperiod)
macd = fastMA - slowMA
signal = ema(macd, signalperiod)

macdAS = macd - signal
signalAS = ema(macdAS, signalperiod)
```

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@UlasTosun,

So I added the _AS_ mode to **macd** if you want to test it out on the _development_ branch. You can test it out like so: ```ta.macd(.., asmode=True)```.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by UlasTosun** [comment]
@twopirllc 
I have tested it out and it works properly, no bugs at first glance.
I am grateful to you, thanks!
Also, when will you release it as a stable version? Do you have any plan for it?
Kind regards.

**Comment by twopirllc** [comment]
@UlasTosun,

> I have tested it out and it works properly, no bugs at first glance.

Great! Thanks for promptly testing it out. 

> Also, when will you release it as a stable version? Do you have any plan for it?

Soon I hope! Maybe in a few days. 🤷🏼‍♂️ I have been busy answering Issues and lacking the time to spend the time fixing and adding new features and indicators ⚖️ ; MACDAS was an exception since it was an addition to an existing indicator. Don't fret, I'll keep you posted.

> I am grateful to you, thanks!

No worries. Thank you!
KJ

**Comment by twopirllc** [comment]
Hello @UlasTosun ,

New stable version _v0.3.14b_ ought to have this feature. Please let me know otherwise.

```sh
$ pip install pandas_ta
```

Thanks,
KJ

**Comment by UlasTosun** [comment]
@twopirllc 
Yes it has and works properly.
Thank you again!
