### ISSUE TITLE
Supertrend is not calculating period >7

### ISSUE THREAD

**Issue by rafalsza** [twopirllc/pandas-ta#337]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
pandas-ta-0.3.5b0

**Describe the bug**
even if I put lenght = e.g. 12 still ta.supertrend is for a 7 period

**To Reproduce**
```python
df = df.ta.supertrend(high=df['HA_high'], low=df['HA_low'], close=df['HA_close'], lenght=12, multiplier=9.0)
```

out:
```sh
                     SUPERT_7_9.0  SUPERTd_7_9.0  SUPERTl_7_9.0  SUPERTs_7_9.0
2021-07-10 00:00:00       16.0789             -1            NaN        16.0789
```

**Comment by twopirllc** [comment]
@rafalsza,

I **already** went over with at the end of your _last_ Issue #311 which you have refused to acknowledge or confirm as well as **deny** your mistake.

For example, please tell me which of these work **and** why:
```python
df = df.ta.supertrend(high=df['HA_high'], low=df['HA_low'], close=df['HA_close'], lenght=12, multiplier=9.0)
```

and 

```python
df = df.ta.supertrend(high=df['HA_high'], low=df['HA_low'], close=df['HA_close'], length=12, multiplier=9.0)
```

KJ

**Comment by rafalsza** [comment]
```
df = df.ta.supertrend(high=df['HA_high'], low=df['HA_low'], close=df['HA_close'], length=7, multiplier=9.0)
```
is working fine
problem is only for calculating lenght >7
even i"m putting lenght=12 i'm getting lenght=7

**Comment by rafalsza** [comment]
i'm sorry. My mistake with "lenght"
