### ISSUE TITLE
How to create many entry/exit signals in vectorbt

### ISSUE THREAD

**Issue by jjruizz** [twopirllc/pandas-ta#338]
Hi!
First of all congratulate you for the work done with pandas-ta.

I would like to know if several entry/exit signals can be indicated beyond the gold crossover example.
For the RSI indicator, I would want as entry RSI_14 > 30 and as exit RSI_14 < 70

How can this be done?

Thanks in advance.
Best Regards

**Comment by twopirllc** [comment]
Hello @jjruizz,

> I would like to know if several entry/exit signals can be indicated beyond the gold crossover example.

Yes. You can use the partially implemented method ```ta.xsignals``` method, see ```help(ta.xsignals)``` for more details. It is **BETA** and subject to change, currently it implements two of four cases for crossings. The other two cases need to be implemented and tested. Luckily your case is one of the two versions fits your case.

Here is the current approach:

```python
import numpy as np
import pandas as pd
import pandas_ta as ta
import vectorbt as vbt


bounds = [30, 70]

df = # ohlcv data
df.ta.constants(True, np.array(bounds))
df.ta.rsi(append=True)
last = 300 # df.shape[0] // 2

# RSI 14 crosses above 30 and then below 70
signals = ta.xsignals(df["RSI_14"].shift(-1), bounds[0], bounds[1], above=True)

# Vector BT 
psettings = {
    "init_cash": 100_000, "fees": 0.01, "size": 100, "slippage": 0.02,
    "freq": "D", "direction": "longonly", "accumulate": False
}

rsi_pf = vbt.Portfolio.from_signals(
    df.Close, # Whatever the open/close values you choose
    entries=signals.TS_Entries,
    exits=signals.TS_Exits,
    **psettings
)

stats = pd.concat([rsi_pf.returns_stats(), rsi_pf.stats()], axis=1)
stats.columns = ["Return Stats", "Stats"]
print(stats)

# Misc Vector BT analysis ...
```

RSI Plot
```python
rsi_entries = df["RSI_14"] * signals["TS_Entries"].replace({0: np.nan})
rsi_exits = df["RSI_14"] * signals["TS_Exits"].replace({0: np.nan})
df[["RSI_14", f"{bounds[0]}", f"{bounds[1]}"]].tail(last).plot(figsize=(16, 3), color=["silver", "green", "red"], grid=True)
rsi_entries.tail(last).plot(figsize=(16, 3), color=["blue"], marker="^", grid=True)
rsi_exits.tail(last).plot(figsize=(16, 3), color=["purple"], marker="v", grid=True)
```

Trend-Trade Plot
```python
signals["TS_Trends"].tail(last).plot(figsize=(16, 1.25), kind="area", stacked=False, color=["green"], alpha=0.3, grid=True)
signals["TS_Entries"].tail(last).plot(figsize=(16, 1.25), color=["black"], grid=True)
```

Let me know if this helps.

Kind Regards,
KJ

**Comment by jjruizz** [comment]
Thank you so much for the example! I didn't know it was in beta, I just read the README.md and it helped me a lot up to this point.

I guess the example will help me with what I was looking for. I'll test it and keep an eye out for future releases :-)
