### ISSUE TITLE
Use TP for BB

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [twopirllc/pandas-ta#339]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
NA

**Upgrade.**
NA

**Is your feature request related to a problem? Please describe.**

BB uses TP instead of close. But the current implementation uses close. Should a BB with TP be added?

https://www.investopedia.com/trading/using-bollinger-bands-to-gauge-trends/

**Describe the solution you'd like**

NA

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by twopirllc** [comment]
Hello @prRZ5F4LXZ,

The implemented version of **bbands** is tightly correlated to the _de facto_ TA Lib and by default it uses a single source, typically _close_. There are two solutions if you want to incorporate _Typical Price_ to **bbands**.

1. Replace ```close``` with ```hlc3```.

```python
tp = ta.hlc3(high, low, close)
bbands = ta.bbands(tp, ...)
```

2. Modify your local copy of ```ta.bbands``` to include ```high``` and ```low``` series, then import ```ta.hlc3``` to calculate _Typical Price_.
    * Make sure to replace ```close``` with ```tp``` before calculating standard deviation and it's moving average.

```python
from pandas_ta.overlap import hlc3

def bbands(high, low, close, ...):
    # ...
    else:
        tp = hlc3(high, low, close)
        standard_deviation = stdev(close=tp length=length, ddof=ddof)
        deviations = std * standard_deviation
        mid = ma(mamode, tp, length=length, **kwargs)
        # ...

```

Hope this helps!

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @prRZ5F4LXZ,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
