### ISSUE TITLE
Probably a bug. No consistency with talib

### ISSUE THREAD

**Issue by bonusguy** [twopirllc/pandas-ta#343]
Version: 0.3.02b

![image](https://user-images.githubusercontent.com/22365509/126035566-e8e5be77-0de6-469e-9d59-74922d4837f0.png)

**Comment by twopirllc** [comment]
Hello @bonusguy,

This has been addressed in your Issue #330 and fixed in PR #334 and is available on the _development_ branch as I previously told you.

Thanks,
KJ
