### ISSUE TITLE
1) Values different to talib 2) pandas_ta not reacting on 'length' parameter

### ISSUE THREAD

**Issue by bonusguy** [twopirllc/pandas-ta#344]
Version: 0.3.02b

![image](https://user-images.githubusercontent.com/22365509/126035640-c4be6d47-14c6-4cef-a1dc-614c03110336.png)

**Comment by twopirllc** [comment]
Hello @bonusguy,

It is spelled ```length``` and not ```lenght```.

Kind Regards,
KJ
