### ISSUE TITLE
IBM Watson juypter notebook import

### ISSUE THREAD

**Issue by atefar2** [twopirllc/pandas-ta#35]
The pip install works perfectly fine but the import pandas_ta as ta on the jupyter notebook version of  ibm watson studio has this error below

AttributeError                            Traceback (most recent call last)
<ipython-input-3-7e9e877eb48f> in <module>
      5 import numpy as np
      6 import pandas as pd
----> 7 import pandas_ta as ta
      8 import pandas_datareader.data as web
      9 import datetime

C:\ProgramData\WatsonStudioDesktop\miniconda3\envs\desktop\lib\site-packages\pandas_ta\__init__.py in <module>
    122 
    123 # DataFrame Extension
--> 124 from .core import *
    125 

C:\ProgramData\WatsonStudioDesktop\miniconda3\envs\desktop\lib\site-packages\pandas_ta\core.py in <module>
     25 
     26 
---> 27 @pd.api.extensions.register_dataframe_accessor('ta')
     28 class AnalysisIndicators(BasePandasObject):
     29     """AnalysisIndicators is class that extends the Pandas DataFrame via

AttributeError: module 'pandas.api' has no attribute 'extensions'

**Comment by twopirllc** [comment]
Hello @atefar2,

Thanks for making this a separate issue.  The ```AttributeError: module 'pandas.api' has no attribute 'extensions'``` is a Pandas issue.
- What version of Pandas are you running?
- Have you tried upgrading Pandas or can you?
- Have you tried other solutions presented [here](https://www.google.com/search?client=firefox-b-1-d&q=AttributeError%3A+module+%27pandas.api%27+has+no+attribute+%27extensions%27)?
- Also what version of Python are you running?

Thanks

**Comment by twopirllc** [comment]
Hello @atefar2,

Any progress?
