### ISSUE TITLE
Signal line implemented for TRIX instead of TSI

### ISSUE THREAD

**Issue by danlim-wz** [twopirllc/pandas-ta#351]
**Which version are you running?**
0.3.2b0

**Describe the bug**
The signal line seems to have been implemented for TRIX instead of TSI.

**Expected behavior**
According to the definitions on investopedia for:
TRIX: https://www.investopedia.com/terms/t/trix.asp
TSI: https://www.investopedia.com/terms/t/tsi.asp,
there should be a signal line for TSI and no signal line for TRIX. 

The in-built indicators on TradingView also displays the expected behavior:
![Screenshot from 2021-07-24 14-34-01](https://user-images.githubusercontent.com/52344837/126859886-1b8049bb-4a5c-4f2f-95e4-ba8420d43940.png)

**Screenshots**
![Screenshot from 2021-07-24 14-19-42](https://user-images.githubusercontent.com/52344837/126859523-fcc8a703-7b11-4298-8f9c-236287dabb59.png)

**Comment by twopirllc** [comment]
Hello @danlim-wz,

Doh! Nice catch with the missing feature/signal line for **tsi**. I am surprised no one else caught it sooner! But it does **not** classify as a bug. Anyhow, it is easy enough to incorporate with a Pull Request if you feel like contributing 😎. If not, I will include it when I get a chance.

Also [**trix**](https://www.tradingview.com/scripts/trix/?solution=43000502331) typically has a signal line according to TradingView and was incorporated as requested in Issue #57.
<img width="480" alt="Screen Shot 2021-07-24 at 10 38 59 AM" src="https://user-images.githubusercontent.com/18198392/126876794-b55dfc4e-9acd-4231-b6a3-0d1bb7a6fd30.png">

Kind Regards,
KJ
