### ISSUE TITLE
BBands not using the entered std parameter

### ISSUE THREAD

**Issue by nraposo1** [twopirllc/pandas-ta#356]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.3.2b0

I tried using a std of 1.5 and the same numbers are returned as the default std of 2.

```python
bbands = pandas_ta.bbands(bars['Close'], length=20, std=2)
print(f"BB_Bands Upper:::\n{round(bbands['BBU_20_2.0'].iloc[-1], 2)}")
print(f"BB_Bands Upper:::\n{bbands.iloc[-1]}")

bbands_15 = pandas_ta.bbands(bars['Close'], length=20, std=1.5)
print(f"BB_Bands:::\n{bbands_15}")
print(f"BB_Bands Upper 1.5:::\n{round(bbands_15['BBU_20_1.5'].iloc[-1], 2)}")
```

**Comment by twopirllc** [comment]
@nraposo1,

Using your code above:
<img width="572" alt="Screen Shot 2021-07-27 at 7 52 14 AM" src="https://user-images.githubusercontent.com/18198392/127176421-2a575e97-1bf6-4d99-a906-d55ee9c9e3f5.png">

Where are your results?

Kind Regards,
KJ

**Comment by nraposo1** [comment]
BB_Bands:::
     BBL_20_2.0  BBM_20_2.0  BBU_20_2.0  BBB_20_2.0  BBP_20_2.0
0           NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN
2           NaN         NaN         NaN         NaN         NaN
3           NaN         NaN         NaN         NaN         NaN
4           NaN         NaN         NaN         NaN         NaN
..          ...         ...         ...         ...         ...
329    2.838857    2.869500    2.900143    2.135780    0.181821
330    2.845374    2.872995    2.900616    1.922805    0.987038
331    2.845374    2.872995    2.900616    1.922805    0.264763
332    2.845374    2.872995    2.900616    1.922805    0.264763
333    2.832781    2.870245    2.907709    2.610519   -0.237305

[334 rows x 5 columns]
BB_Bands Upper:::2.9077091415214817
BB_Bands:::
     BBL_20_1.5  BBM_20_1.5  BBU_20_1.5  BBB_20_1.5  BBP_20_1.5
0           NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN
2           NaN         NaN         NaN         NaN         NaN
3           NaN         NaN         NaN         NaN         NaN
4           NaN         NaN         NaN         NaN         NaN
..          ...         ...         ...         ...         ...
329    2.838857    2.869500    2.900143    2.135780    0.181821
330    2.845374    2.872995    2.900616    1.922805    0.987038
331    2.845374    2.872995    2.900616    1.922805    0.264763
332    2.845374    2.872995    2.900616    1.922805    0.264763
333    2.832781    2.870245    2.907709    2.610519   -0.237305

[334 rows x 5 columns]
BB_Bands Upper 1.5:::2.9077091415214817

Am I missing something?
Code: Using symbol 'XELA' this morning:
bbands = pandas_ta.bbands(bars['Close'], length=20, std=2)
print(f"BB_Bands:::\n{bbands}")
print(f"BB_Bands Upper:::{bbands['BBU_20_2.0'].iloc[-1]}")

bbands_15 = pandas_ta.bbands(bars['Close'], length=20, std=1.5)
print(f"BB_Bands:::\n{bbands_15}")
print(f"BB_Bands Upper 1.5:::{bbands_15['BBU_20_1.5'].iloc[-1]}")

**Comment by twopirllc** [comment]
@nraposo1,

Ok. It looks like you have TA Lib installed in your environment as well as Pandas TA checks here on [line 22](https://github.com/twopirllc/pandas-ta/blob/e44ff1b30eb877ad3c6121d7c74fd29440afda54/pandas_ta/volatility/bbands.py#L22).

I have fixed this Issue and related TA Lib indicators in version _0.3.4b0_.

There are two solutions: Install the _development_ branch (version _0.3.13b0_) or patch your local **bands** copy.

### Development Branch
Please let me know if this resolves your Issue before I update the _main_ branch. 😎 

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

### Local Patch
Modify your local copy of **bbands** and shortcut the if statement until I update the _main_ branch.

```python
def bbands(...):
    # ...

    if False: # Shortcut to the condition
        # ...
    else:
        # ...
```

Please let me know which worked for you.

Hope this helps!

Thanks
KJ

**Comment by nraposo1** [comment]
I used the local patch method and it fixed the issue. Thanks for your help and time...

**Comment by twopirllc** [comment]
@nraposo1,

No problem. Thanks for informing me. Funny enough, today is a new stable release _v0.3.14b_ and should correct the other TA Lib indicator attribute issues. Standard install:

```sh
$ pip install pandas_ta
```

Thanks,
KJ
