### ISSUE TITLE
Live Trading and incremental indicator calculation

### ISSUE THREAD

**Issue by malakeel** [twopirllc/pandas-ta#360]
During live trading, a new data row is received and appended to the existing one. Indicators needs to be evaluated again. For example, ta.sma with 200 periods has to be evaluated for all previous periods when only new candlestick data is added. 

Is there a way to apply the indicator and evaluate only the new row ?

**Comment by twopirllc** [comment]
Hello @malakeel,

Please see Issues#87 and #288 where this is discussed.

Kind Regards,
KJ
