### ISSUE TITLE
Memory leak when download data using yfinance.

### ISSUE THREAD

**Issue by yeus** [twopirllc/pandas-ta#361]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**

0.3.14b0

**Describe the bug**
I think I found a potential memory leak (I am trying to run pandas-ta on a server on a regular basis). Whenever I download financial data memory consumption kept increasing quiet a bit.

I ran a test using "pympler" to research where in my code objects got created without getting deleted by the python GC
(https://pympler.readthedocs.io/en/latest/muppy.html#the-tracker-module).

**To Reproduce**

```python
# -*- coding: utf-8 -*-
import time

import pandas as pd
import pandas_ta as ta
from pympler import tracker

print(ta.__version__)

df = pd.DataFrame()

tracker = tracker.SummaryTracker()
for i in range(10):
    df = df.ta.ticker("BTC-USD", period="20", inteval="1d")

    time.sleep(2)
    print(f"\nadditional objects, iteration # {i}:\n")
    tracker.print_diff()
```

When running this program I get this output:

```
0.3.14b0

additional objects, iteration # 0:

                       types |   # objects |   total size
============================ | =========== | ============
                         str |       12190 |      2.61 MB
                        list |        8539 |    733.34 KB
                        dict |        1272 |    624.53 KB
                       tuple |        1146 |    485.44 KB
                        type |         417 |    332.03 KB
                        code |        1534 |    269.62 KB
                         int |        3319 |     91.48 KB
                         set |          82 |     59.80 KB
   cython_function_or_method |         290 |     56.64 KB
                  re.Pattern |          81 |     45.93 KB
                     weakref |         587 |     41.27 KB
                   frozenset |          39 |     32.23 KB
  builtin_function_or_method |         340 |     23.91 KB
           getset_descriptor |         311 |     19.44 KB
         function (__init__) |         114 |     15.14 KB

additional objects, iteration # 1:

                     types |   # objects |   total size
========================== | =========== | ============
                       str |         764 |      1.60 MB
                      list |         762 |     68.44 KB
      lxml.etree._LogEntry |          59 |      5.07 KB
                       int |         147 |      4.02 KB
                      code |           0 |    112     B
                     tuple |           1 |     80     B
  urllib.parse.SplitResult |           1 |     80     B

additional objects, iteration # 2:

                     types |   # objects |   total size
========================== | =========== | ============
                       str |           2 |      1.54 MB
                      code |           0 |      1.25 KB
                      list |           0 |    176     B
                     tuple |           1 |     80     B
  urllib.parse.SplitResult |           1 |     80     B
      lxml.etree._LogEntry |          -8 |   -704     B

additional objects, iteration # 3:

                     types |   # objects |   total size
========================== | =========== | ============
                       str |           2 |      1.55 MB
                      code |           0 |    681     B
                      dict |           0 |    280     B
                     tuple |           1 |     80     B
  urllib.parse.SplitResult |           1 |     80     B
      lxml.etree._LogEntry |          -9 |   -792     B

additional objects, iteration # 4:

(MORE ITERATIONS GIVE SAME RESULT....)

```

**Expected behavior**

The tables for iteration 3 and 4 and following should be empty if everything was cleaned up correctly. But in each iteration there are new objects that get created and not cleaned up. If I run my program over the course of a day it will significantly increase memory consumption (in the order of 1-2GB) even though I am only downloading yfinance data every 30mins. or  so.

**Additional context**
The table above show that there are strings that don't get cleaned up. I suspect it might hacve something to do with lxml. SO I am not suere where exactly the memory leak can be found. Might be in lxml or in pandas-ta or somewhere else...

Thanks for developing pandas TA!

**Comment by twopirllc** [comment]
Hello @yeus,

Interesting! We all hope our code doesn't have memory leaks. I hope it's not Pandas TA! 😎

Have you compared _yfinance_ yet vs _pandas-ta_? Pandas TA wraps _yfinance_ and returns the ```df``` and applies the ticker name ```df.name = ticker``` based on your arguments and no additional printing or verbosity. Not sure if applying the ticker name could be the extra strings not being cleaned up. 🤷🏼‍♂️ How is the _lxml_ testing coming?

Thanks for using Pandas TA!

Kind Regards,
KJ

**Comment by yeus** [comment]
Hi @twopirllc 

no I haven't done any comparisons yet. For now I am downloading the data in my project in a separate process in order to mitigate the memory leak and then send it back to the main process. From the tables in pympler I suspect, that yfinance is the problem. I am not sure though ...  maybe it stores some lxml node (from the pympler table it might be an error log?) and then doesn't release it afterwards... From the size of the memory leak (2-3 MB / iteration I don't think its just the ticker name... it has to be something "bigger" maybe the complete textfile with historic data? I dont know ...)

wlll investigate further at some point if I have the time

**Comment by twopirllc** [comment]
Hello @yeus,

Thanks for the update. Keep me posted when you get a chance.

Thanks,
KJ
