### ISSUE TITLE
Does ddof of stdev work?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [twopirllc/pandas-ta#362]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**

```sh
>>> pandas_ta.__version__
'0.3.14b0'
```

**Describe the bug**

See below

**To Reproduce**

```python
import pandas
import sys
import pandas_ta as ta
df = pandas.read_csv(sys.stdin)
df['stdev'] = ta.stdev(df['close'], length=3, ddof=int(sys.argv[1]))
df.to_csv(sys.stdout, sep='\t', index=False)
```

Using the above code, I see dof has no effect on the result.

```sh
$ { echo close; seq 3; } | ./main.py 0
close	stdev
1
2
3	0.8164965809277263
$ { echo close; seq 3; } | ./main.py 1
close	stdev
1
2
3	0.8164965809277263
$ { echo close; seq 3; } | ./main.py 2
close	stdev
1
2
3	0.8164965809277263
```

**Expected behavior**

I expect that ddof can affect the result.

**Screenshots**
NA

**Additional context**
NA

**Comment by twopirllc** [comment]
Hello @prRZ5F4LXZ,

Do you have TA Lib installed in your environment? If so, you need to disable TA Lib using the argument ```talib=False```.

```python
import pandas
import sys
import pandas_ta as ta

df = pandas.read_csv(sys.stdin)
df['stdev'] = ta.stdev(df['close'], length=3, ddof=int(sys.argv[1]), talib=False)
df.to_csv(sys.stdout, sep='\t', index=False)
```

Kind Regards,
KJ

**Comment by prRZ5F4LXZ** [comment]
It doesn't matter. Using talib, I still get the same results for different ddofs.

**Comment by twopirllc** [comment]
Hello @prRZ5F4LXZ,

This should be fixed now. If you can test it out on the _development_ branch and let me know, that would be great.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks
KJ

**Comment by prRZ5F4LXZ** [comment]
Looks good. But is it better to use n-1 as the default ddof?

In R, n-1 is used for `sd()`, n is used for `var()`.

https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/sd

**Comment by twopirllc** [comment]
@prRZ5F4LXZ,

Well, I chose to use _Pandas_' [**std**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.std.html) and [**var**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.var.html) _ddof_ defaults of 1. Even _Numpy_ and _Statsmodels_ use a _ddof_ of 0 for **std** and **var** whereas _R_ is using _n_ and _n-1_. Perhaps **std** and **var** should be 0 instead so they are inline with _Numpy_ and _Statsmodels_?

Many users use both TA Lib and Pandas TA and when it comes down to it, they will choose speed every time. Now they get the benefit of both libraries with minimal cointegration friction as possible. That is why ```talib=True``` is the default.

I apologize if these are not the answers you seek. However, it is an Open Source library and you are welcome to _fork_ and make the necessary accommodations to fit your use case.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @prRZ5F4LXZ,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
