### ISSUE TITLE
Output index differs from input index (stoch, td_seq)

### ISSUE THREAD

**Issue by polakowo** [twopirllc/pandas-ta#363]
Hello @twopirllc,

upon releasing vectorbt v0.20 I noticed some pandas-ta tests failing. As you know, I previously created a simple parser to extract the meta of each pandas-ta indicator (it builds a dummy DataFrame with 50 random floating elements and passes it to pandas-ta to see what outputs to expect). The parser started to fail for some of the indicators:

```python
>>> import vectorbt as vbt

>>> vbt.IndicatorFactory.get_pandas_ta_indicators(silence_warnings=False)
Function stoch: Couldn't parse the output: mismatching index
Function td_seq: Couldn't parse the output: mismatching index
Function trix: Couldn't parse the indicator: inputs are all NaN
Function ichimoku: 'NoneType' object has no attribute 'index'
UserWarning: Function kvo: 'NoneType' object has no attribute 'index'
```

I can't remember which ones I wasn't able to parse previously (probably Ichimoku), but the new ones are definitely `stoch` and `td_seq`. Upon looking closer, I noticed that `stoch` removes head entries that are NaN, while `td_seq` returns a simple range index instead of a datetime-like index. 

To address this, I can quickly patch vectorbt to 1) fill the missing index if the output index is of the same type and 2) copy the input index if the output index has another type but the same length. 

Would love to hear your thoughts on this matter.

Edit: I'm running 0.3.14b0

**Comment by twopirllc** [comment]
Hello @polakowo,

> upon releasing vectorbt v0.20 I noticed some pandas-ta tests failing. As you know, I previously created a simple parser to extract the meta of each pandas-ta indicator (it builds a dummy DataFrame with 50 random floating elements and passes it to pandas-ta to see what outputs to expect). The parser started to fail for some of the indicator

Hmmm.... 🤔  Thanks bringing these to my attention! I was not aware that these were causing issues. Good to know.

> I can't remember which ones I wasn't able to parse previously (probably Ichimoku), but the new ones are definitely stoch and td_seq. Upon looking closer, I noticed that stoch removes head entries that are NaN, while td_seq returns a simple range index instead of a datetime-like index.

I will investigate these and let you know what I find out. I now **ichimoku** is different from the rest since it returns two DataFrames. It's first DataFrame's index _should_ be inline with it's input index, but I will double check. I will try and fix the indicators with **stoch** and/or **td_seq** and hope that those resolve the parser warnings.

On another note, it seems you removed **active_returns()** [```Portfolio.active_returns().vbt.plot(*, **)```] in a newer version of _v0.18.1_. Out of curiosity, is there an easy way to replicate it?

Thanks for reaching out and especially the donation! 😎  I really appreciate it! Thank you!
KJ

**Comment by polakowo** [comment]
@twopirllc thank you, I will keep the things untouched for now.

Regarding `active_returns`: it has been renamed to `asset_returns` (but I'm not sure about 0.18.1), so now you have `value` and `returns` that take into account both assets and cash, and `asset_value` and `asset_returns` that take into account assets only. This naming is more intuitive in my opinion. Also, many methods based on returns now have an argument `use_asset_returns` to switch between both types. I recommend pulling the latest version - it's the only one that's reflected on the documentation website.

**Comment by twopirllc** [comment]
@polakowo,

Ahhh.. that's what it got renamed to. Thanks for the clarification.

Thanks again,
KJ

**Comment by twopirllc** [comment]
@polakowo,

So I updated the some of the indicators above. 

```python
# vbt.__version__: 0.20.0
import vectorbt as vbt
vbt.IndicatorFactory.get_pandas_ta_indicators(silence_warnings=False)
```

Running the method above yields:
```sh
<ipython-input-3-1580852f9bc2>:1: UserWarning: Couldn't parse the indicator
  vbt.IndicatorFactory.get_pandas_ta_indicators(silence_warnings=False)
<ipython-input-3-1580852f9bc2>:1: UserWarning: 'NoneType' object has no attribute 'index'
  vbt.IndicatorFactory.get_pandas_ta_indicators(silence_warnings=False)
```

I am unable to ascertain the results of the following _UserWarnings_, but I seemed to have cleared up the indexing issues.

The _development_ branch can be installed with:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by polakowo** [comment]
@twopirllc,

perfect, I'll look into the other two and maybe tweak the parser a bit. Thank you!

**Comment by bennycode** [comment]
Why does it need 9 inputs of high, low, close before the Stochastic Oscillator returns a result?

The [Example Calculation](https://tulipindicators.org/stoch) uses a %k period of 5 and a %k slowing period of 3. Shouldn't this mean that 8 inputs are enough?

**Comment by twopirllc** [comment]
@bennycode,

> Why does it need 9 inputs of high, low, close before the Stochastic Oscillator returns a result?

It has the required inputs to calculate ```ta.stoch``` as described in ```help(ta.stoch)```, which is closer to 7. Some (```offset, fillna, fill_method```) you won't use unless you actually need them.

Is ```ta.stoch``` **not** working as expected?

```python
Stochastic (STOCH)

    Args:
        high (pd.Series): Series of 'high's
        low (pd.Series): Series of 'low's
        close (pd.Series): Series of 'close's
        k (int): The Fast %K period. Default: 14
        d (int): The Slow %K period. Default: 3
        smooth_k (int): The Slow %D period. Default: 3
        mamode (str): See ```help(ta.ma)```. Default: 'sma'
        offset (int): How many periods to offset the result. Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method
```

<br/>

However, I should probably add another ```mamode``` like TA-Lib does:

```c
/*
 * TA_STOCH - Stochastic
 * 
 * Input  = High, Low, Close
 * Output = double, double
 * 
 * Optional Parameters
 * -------------------
 * optInFastK_Period:(From 1 to 100000)
 *    Time period for building the Fast-K line
 * 
 * optInSlowK_Period:(From 1 to 100000)
 *    Smoothing for making the Slow-K line. Usually set to 3
 * 
 * optInSlowK_MAType:
 *    Type of Moving Average for Slow-K
 * 
 * optInSlowD_Period:(From 1 to 100000)
 *    Smoothing for making the Slow-D line
 * 
 * optInSlowD_MAType:
 *    Type of Moving Average for Slow-D
 * 
 */
```

Kind Regards,
KJ
