### ISSUE TITLE
SSF indicator computation

### ISSUE THREAD

**Issue by DrPaprikaa** [twopirllc/pandas-ta#365]
Hi @twopirllc,

I'm reviewing the computation of the [SSF](https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/overlap/ssf.py) indicator, and it behaves strangely at the begining of the input data.

Let's compute and plot the SSF with a length of 10, using :

```python
df.ta.ssf(length=10, poles=2, append=True, col_names=('SSF',))
```
       
![image](https://user-images.githubusercontent.com/64958936/128628052-1b9d9177-d97d-4db8-91cc-783508367ffa.png)
That's strange !

Skipping the first 10 points when plotting gives :
![image](https://user-images.githubusercontent.com/64958936/128628056-05f9702d-763c-4214-9a37-91e0a5382daa.png)
which is (almost) what we want.

I beleive this behavior comes from this part in the computation :

```python
    for i in range(0, m):
        ssf.iloc[i] = c1 * close.iloc[i] + b1 * ssf.iloc[i - 1] + a1 * ssf.iloc[i - 2]
```

Aren't `ssf.iloc[i - 1]` and `ssf.iloc[i - 2]` undefined when `i<2` ? No error is raised, so I'm confused.
More generaly, I think that the SSF series should countain `NaN`s for `i<length`.

Could you please take a look ?

Thanks!

**Comment by twopirllc** [comment]
Hey @DrPaprikaa,

I see what you mean. 

> Aren't ```ssf.iloc[i - 1]``` and ```ssf.iloc[i - 2]``` undefined when ```i<2```? No error is raised, so I'm confused.

It doesn't error since it ```ssf``` is initialized earlier with ```ssf = close.copy()```.

> More generaly, I think that the SSF series should countain ```NaN```s for ```i<length```.

Correct! Thanks for catching that mistake.

Until I update _main_, update your local copy of ```ssf```. 😅 

```python
from numpy import nan as npNaN
# ...

def ssf(...):
    # ...

    if poles == 3:
        # ...

        ssf.iloc[:3] = npNaN   # After the for loop
    else: # poles == 2
        # ...

        ssf.iloc[:2] = npNaN   # After the for loop
```

Please let me know if this fix resolves your Issue in the interim.

Thanks,
KJ

**Comment by DrPaprikaa** [comment]
Hey @twopirllc,

Yes `ssf` is initialized earlier with `ssf = close.copy()`, but aren't we iterating over negative indexes when `i<2` ? Meaning that, for example, `ssf.iloc[i-2]` is equivalent to `ssf.iloc[-2]` for `i=0` ?

Also I think that the fix is incorrect, let me explain.
Current behavior :
![image](https://user-images.githubusercontent.com/64958936/128689783-49ced733-8030-4235-829b-a8919865513d.png)

With your fix `ssf.iloc[:2] = npNaN` :
![image](https://user-images.githubusercontent.com/64958936/128689836-6a02bc8e-1765-4a9f-8213-7a3a78ca2b10.png)

Replacing `for i in range(0, m)` by `for i in range(poles, m)`:
![image](https://user-images.githubusercontent.com/64958936/128690340-549e24ac-e475-4285-b5b8-5356f421a75f.png)

Therefore I think that the fix is to simply start the loop at the number of poles instead of at 0.

Let me know what you think!

**Comment by twopirllc** [comment]
@DrPaprikaa,

> Therefore I think that the fix is to simply start the loop at the number of poles instead of at 0, with the constraint that ```length > poles```.

Yes, I noticed it also. Simple fix.

I also think ```ssf.iloc[:poles] = npNaN``` should be included, some sources are using ```0``` but that makes the plot odd if the chart starts at say 100 for example. What do you think?

KJ

**Comment by DrPaprikaa** [comment]
Good point, but I think that we should include `ssf.iloc[:length] = npNaN` instead of `ssf.iloc[:poles] = npNaN` .

This is because the indicator cannot be defined for the indexes smaller than `length` : it has not enough data for `i < length`. But it should never be `ssf.iloc[:length] = 0`, which makes no sense imo.

So to sum up, the fix is made of 3 changes :

- `length > poles`
- `for i in range(poles, m)`
- `ssf.iloc[:length] = npNaN`

With `df.ta.ssf(length=10, poles=2, append=True, col_names=('SSF',))` :

![image](https://user-images.githubusercontent.com/64958936/129019597-fa07894f-dcdb-44fd-b0c2-08ea66d3fd47.png)

It now works as intended !

**Comment by twopirllc** [comment]
@DrPaprikaa,

Sounds good! No worries.
- ```length > poles``` 
- ```for i in range(poles, m)```
- ```ssf.iloc[:length] = npNaN```

KJ

**Comment by twopirllc** [comment]
Hey @DrPaprikaa,

Thanks for you patience. I have a working version, I think, on the _development_ branch if you want to test it out first.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by twopirllc** [comment]
Hey @DrPaprikaa,

Please update to the latest _development_ version when you get a chance. I split **ssf** into **ssf** and **ssf3**. Plus some other speed enhancements, better documentation and typing.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ
