### ISSUE TITLE
Smoothed Moving Average not available

### ISSUE THREAD

**Issue by Harold-coder** [twopirllc/pandas-ta#368]
It would be great if we could have the Smoothed Moving Average because the 200 SMMA is the same as the 400 EMA so it takes less candles to analyze correctly.

**Comment by twopirllc** [comment]
Hello @Harold-coder,

You are correct that it is currently not available via ```pip``` nor on the latest (_main_) branch. However it is on the _development_ branch if you want to check it out before I update the _main_ branch. The **smma** was a requirement for **alligator** indicator as requested in Issue #194.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ

**Comment by Harold-coder** [comment]
Hey @twopirllc, 

Thank you very much for the quick answer. 
I will try it out. 

Thanks for the great work, I really enjoy using pandas-ta.

**Comment by g-stick** [comment]
Sorry to dig this up again, but I felt it was better to necro this than open a new issue. Up until last week the Smoothed Moving Average smma was available from the dev branch, But it is no longer available this morning.

Thanks

**Comment by twopirllc** [comment]
@Harold-coder

Which _development_ version are you on? I updated the _development_ branch yesterday to _0.4.4b_ and **smma** also cleared its _tests_. Do you have TA-Lib installed and some code to replicate it?

Kind Regards,
KJ
