### ISSUE TITLE
ALMA output is vastly different from other charting software

### ISSUE THREAD

**Issue by UncleVasya** [twopirllc/pandas-ta#373]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
`0.3.14b0`

**Describe the bug**
Current implementation of ALMA produces vastly different results than built-in alma indicator on TradingView.

**To Reproduce**
```
# 1. read price data into df
...

# 2. add alma
    df['alma'] = ta.alma(df['close'], 50)

#3. plot result
...

#4. Visually inspect the chart and compare with few other implementations of alma 
(TradingView, SierraCharts, Ninjatrader, etc)
```
**Expected behavior**
I expect for plotted output of alma indicator to match alma plots of other charting software.

**Screenshots**

![](https://i.imgur.com/5qWDdYn.png)
- black line is the current implementation of ALMA (50);
- red line is what I believe to be the correct ALMA (50);

Same chart on TradingView platform:
![](https://www.tradingview.com/x/507GbBwH/)

**Additional context**
The reason why I believe other implementations to be correct is because I found the difference between current implementation and the original one provided by authors. After fixing it alma works as expected.

**Comment by twopirllc** [comment]
Hello @UncleVasya,

Yeah. Not only is it a correlation issue with other libraries and platforms, it also has a performance issue that I am trying to fix. Thanks for the PR #374 and contribution. 😎 

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hey @UncleVasya,

I have an update **alma** on the _development_ branch if you want to test it out first. It should be quicker also.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by UncleVasya** [comment]
I tested your version. It is both correct and amazingly fast. Nice one!

Compared it with another version on 50k candles:
```
def a():
    df['talma'] = alma(df['close'], 150)

def a1():
    df['a1'] = ta.alma(df['close'], 150)

import timeit

ic(timeit.timeit(stmt=a, number=5))
ic(timeit.timeit(stmt=a1, number=5))
```

```
timeit.timeit(stmt=a, number=5): 143.09172812399993
timeit.timeit(stmt=a1, number=5): 0.29279039500011095
```

This now must be the best open source implementation of alma out there.

**Comment by twopirllc** [comment]
@UncleVasya,

> I tested your version. It is both correct and amazingly fast. Nice one!
> This now must be the best open source implementation of alma out there.

Thanks! It is definitely faster. It is only slightly off from TradingView's but still greater than 99% correlated with it.

KJ

**Comment by pssolanki111** [comment]
@twopirllc this sounds like a to-be-closed issue?

**Comment by twopirllc** [comment]
@pssolanki111,

I'll close it when I update the _main_ branch as well as other Issues in the similar state.

KJ
