### ISSUE TITLE
Stochastic indicator is shifted

### ISSUE THREAD

**Issue by GhostusSK** [twopirllc/pandas-ta#376]
pandas version: 0.3.14b0

When I compared the output of the stoch indicator with TradingView the output(k and d line) of the stoch indicator is shifted to the left.

I think that the problem is caused with those two lines:
```python
stoch_k = ma(mamode, stoch.loc[stoch.first_valid_index():,], length=smooth_k)
stoch_d = ma(mamode, stoch_k.loc[stoch_k.first_valid_index():,], length=d)
```

When I changed those lines like this(I removed the loc), the output of the stochastic indicator was correct:
```python
stoch_k = ma(mamode, stoch, length=smooth_k)
stoch_d = ma(mamode, stoch_k, length=d)
```

I attached 3 images: 
- one from tradingView
<img width="2330" alt="tradingView-stoch" src="https://user-images.githubusercontent.com/4710231/130081092-abf19ef9-31de-4d2f-b6d0-9e33259b4888.png">

- one with shifted output of the stoch indicator
<img width="1528" alt="pandas-ta_stoch_shifted" src="https://user-images.githubusercontent.com/4710231/130081157-8a80f899-5a7a-427c-a89c-8462ec05a497.png">

- one with correct output of the stoch indicator after I removed the loc[stoch.first_valid_index():,]
<img width="1527" alt="pandas-ta_stoch-fixed" src="https://user-images.githubusercontent.com/4710231/130081203-1afa0c36-f2ce-4ce6-9b8c-833100a9caa8.png">

My guess is, that in the stoch indicator the  'loc[stoch.first_valid_index():,]' code skips some invalid values. But this shifts output of the indicator which is not good.  I compared the stoch indicator with stochrsi and the stochrsi doesn't use the loc at all. 

I'm calling the stoch indicator like this:
```python
stoch(high= highSeries, low= lowSeries, close= closeSeries, k= 14, d= 3, smooth_k= 1)
```

I also attached JSON with the high, low and  close values, that I used as input for the stoch indicator.
[input.txt](https://github.com/twopirllc/pandas-ta/files/7014850/input.txt)

**Comment by twopirllc** [comment]
Hello @GhostusSK,

Thanks for looking into this. While visual analysis is a good smell test, numerical results are much easier to verify and check for correlation.

Also the minimum bar of Pandas TA testing is _TA Lib_, which **stoch** and **stochrsi** have 99.99% and 100% correlation respectively. And in the unittests for **stoch** and **stochrsi**, I have a comment reminding me that they are TV correlated as well; but they could be wrong 🤷🏼‍♂️ .

https://github.com/twopirllc/pandas-ta/blob/bc3b292bf1cc1d5f2aba50bb750a75209d655b37/tests/test_indicator_momentum.py#L447-L485

<br/>

### Testing Trading View Indicators vs Pandas TA

This is a generic guide to verify and correlate with TV, one needs to **Export Chart Data** from TradingView for comparison by using the _hamburger menu_ in the upper left corner; I use the ISO format.

<img width="342" alt="Screen Shot 2020-09-02 at 7 54 25 AM" src="https://user-images.githubusercontent.com/18198392/91999924-ca170080-ecf1-11ea-911f-c73dabe9ed13.png">

Once you have exported your chart data from TradingView, try the following:
```python
import pandas as pd
import pandas_ta as ta

# Load the TV export data or whatever you saved it as
data = pd.read_csv("path/to/tradingview_data.csv") 
chande = ta.cmo(data['close'], length=9, talib=False)
print(chande.iloc[-1])

# Alternatively
data.ta.cmo(length=9, talib=False, append=True)
print(data.corr()) # Check their correlation
```

Also please reply to this issue with your results so I can see your correlations. You may need to drop some columns before running ```data.corr()``` so it's not filled with extraneous columns.

For example, here my results when exporting from TradingView and turning off TA Lib in **cmo**:

<img width="687" alt="Screen Shot 2020-09-02 at 8 27 18 AM" src="https://user-images.githubusercontent.com/18198392/92005251-1d8c4d00-ecf8-11ea-9411-f4f0a1b60834.png">

<br/>

If you are not able to export and do a correlation test with TV, I will do it again as soon as I can.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @GhostusSK,

Ok, found some time to do a correlation test and some equivalent row prints.

Here is the raw data I exported from TV prior to running Pandas TA **stoch** and **stochrsi** indicators that I have include below: [SPY_D_STOCH_STOCHRSI.csv](https://github.com/twopirllc/pandas-ta/files/7024450/SPY_D_STOCH_STOCHRSI.csv)


### Imports and Settings
```python
import pandas as pd
import pandas_ta as ta

pd.set_option("min_rows", 50)
pd.set_option("max_rows", 80)

def highlight_top(s, v=0.98):
    return ["background-color: lightgreen" if cell else "" for cell in s > v]
```

### Pandas TA and TV: STOCH(14,3,3)
```python
df = pd.read_csv("SPY_D_STOCH_STOCHRSI.csv")
df.set_index(pd.DatetimeIndex(df["time"]), inplace=True, drop=True)
df.ta.stoch(append=True)
df.drop(["time", "TV_STOCHRSIk_14_3_3", "TV_STOCHRSId_14_3_3"], axis=1, errors="ignore", inplace=True)
df = df[df.columns[4:]]

print(f"Total bars: {df.shape[0]}")
stcorr = df.corr()
stcorr.style.apply(highlight_top)
```

<img width="590" alt="Screen Shot 2021-08-20 at 4 20 00 PM" src="https://user-images.githubusercontent.com/18198392/130302051-4d94e27f-872a-4242-a52b-dcbb1ed830b7.png">


```python
df[10:30].style.background_gradient(cmap="bwr")
```
<img width="634" alt="Screen Shot 2021-08-20 at 4 20 10 PM" src="https://user-images.githubusercontent.com/18198392/130302102-edd87ed2-6ee0-4d5e-a86b-4a505e27ee12.png">

<br/><br/>

### Pandas TA and TV: STOCHRSI(14,14,3,3)


```python
df = pd.read_csv("SPY_D_STOCH_STOCHRSI.csv")
df.set_index(pd.DatetimeIndex(df["time"]), inplace=True, drop=True)
df.ta.stochrsi(append=True)
df.drop(["time", "TV_STOCHk_14_3_3", "TV_STOCHd_14_3_3"], axis=1, errors="ignore", inplace=True)
df = df[df.columns[4:]]

print(f"Total bars: {df.shape[0]}")
stcorr = df.corr()
stcorr.style.apply(highlight_top)
```

<img width="716" alt="Screen Shot 2021-08-20 at 4 22 28 PM" src="https://user-images.githubusercontent.com/18198392/130302180-91bf89a5-ae30-4792-b11b-ee68687dbe4b.png">

```python
df[-20:].style.background_gradient(cmap="bwr")
```

<img width="752" alt="Screen Shot 2021-08-20 at 4 22 46 PM" src="https://user-images.githubusercontent.com/18198392/130302175-ad34b20b-370a-4eea-a0aa-99f214a02178.png">

<br/>

Hope this helps clarify the correlations that exist between TV and Pandas TA's **stoch** and **stochrsi** not to mention their correlation with TA Lib that I have excluded.

If you want to verify their correlations with TA Lib **and** you have TA Lib installed, you will need to modify [test_indicator_momentum.py](https://github.com/twopirllc/pandas-ta/blob/main/tests/test_indicator_momentum.py#L447-L485) before you run:

```sh
$ make test_ta
```

```python
    def test_stoch(self):
        # TV Correlation
        result = pandas_ta.stoch(self.high, self.low, self.close)
        self.assertIsInstance(result, DataFrame)
        self.assertEqual(result.name, "STOCH_14_3_3")

        print() # Add this... makes it easier to find
        try:
            expected = tal.STOCH(self.high, self.low, self.close, 14, 3, 0, 3, 0)
            expecteddf = DataFrame({"STOCHk_14_3_0_3_0": expected[0], "STOCHd_14_3_0_3": expected[1]})

            # Add the next line
            print(pandas_ta.utils.df_error_analysis(result.iloc[:, 0], expecteddf.iloc[:, 0], col=CORRELATION))

            pdt.assert_frame_equal(result, expecteddf)
        except AssertionError:
            try:
                stochk_corr = pandas_ta.utils.df_error_analysis(result.iloc[:, 0], expecteddf.iloc[:, 0], col=CORRELATION)
                self.assertGreater(stochk_corr, CORRELATION_THRESHOLD)
            except Exception as ex:
                error_analysis(result.iloc[:, 0], CORRELATION, ex)

            try:
                stochd_corr = pandas_ta.utils.df_error_analysis(result.iloc[:, 1], expecteddf.iloc[:, 1], col=CORRELATION)
                self.assertGreater(stochd_corr, CORRELATION_THRESHOLD)
            except Exception as ex:
                error_analysis(result.iloc[:, 1], CORRELATION, ex, newline=False)


    def test_stochrsi(self):
        # TV Correlation
        result = pandas_ta.stochrsi(self.close)
        self.assertIsInstance(result, DataFrame)
        self.assertEqual(result.name, "STOCHRSI_14_14_3_3")

        print() # Add this... makes it easier to find
        try:
            expected = tal.STOCHRSI(self.close, 14, 14, 3, 0)
            expecteddf = DataFrame({"STOCHRSIk_14_14_0_3": expected[0], "STOCHRSId_14_14_3_0": expected[1]})

            # Add the next line
            print(pandas_ta.utils.df_error_analysis(result.iloc[:, 0], expecteddf.iloc[:, 1], col=CORRELATION))

            pdt.assert_frame_equal(result, expecteddf)
        except AssertionError:
            try:
                stochrsid_corr = pandas_ta.utils.df_error_analysis(result.iloc[:, 0], expecteddf.iloc[:, 1], col=CORRELATION)
                self.assertGreater(stochrsid_corr, CORRELATION_THRESHOLD)
            except Exception as ex:
                error_analysis(result.iloc[:, 0], CORRELATION, ex, newline=False)
```

<br/>

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @GhostusSK,

I assume by no response that the provided details were sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by GhostusSK** [comment]
Hi @twopirllc,

sorry for late response, but I was busy last week. I believe you, that your implementation of TA passes the test, but those two lines doesn't give me a sense:

stoch_k = ma(mamode, stoch.loc[stoch.first_valid_index():,], length=smooth_k)
stoch_d = ma(mamode, stoch_k.loc[stoch_k.first_valid_index():,], length=d)

Imagine that you have 1000 candles and imagine that the first_valid_index() returns an index. That means, that the stoch series contains invalid values(probably NaN values).  This will cause that the stoch_k and stoch_d values will be shifted and they won't fit the input candles. If the calculated stoch_k and stoch_d don't fit the input candles, the indicator is not very usable. What purpose has the output that doesn't fit the input data?

Wouldn't it be better to not skipping the invalid values by using the code below?
stoch_k = ma(mamode, stoch, length=smooth_k)
stoch_d = ma(mamode, stoch_k, length=d)

In this case the output wouldn't be shifted because we are not skipping invalid values. Maybe for NaN values the output will contain also Nan values, but that is ok. At least the output will fit the input candles.

**Comment by twopirllc** [comment]
@GhostusSK,

>  sorry for late response, but I was busy last week.

No worries. It happens to us all.

> Imagine that you have 1000 candles and imagine that the first_valid_index() returns an index. That means, that the stoch series contains invalid values(probably NaN values).

Yes, **stoch**'s first ``` k - 1``` values will be ```Nan``` and the remaining are not ```NaN```.

> This will cause that the stoch_k and stoch_d values will be shifted and they won't fit the input candle.

No. It doesn't cause a shift in ```stoch```, _first_valid_index()_ is a fancy selector that returns a subset of the data. It's quicker to perform calculations on a smaller set than a larger set. ```stoch_k``` and ```stoch_d``` are shifted because they are moving averages of ```stoch``` of lengths ```smooth_k``` and ```d``` respectively; they don't start where ```stoch``` left off.

<br/>

In fact, whether 
```python
stoch_k = ma(mamode, stoch.loc[stoch.first_valid_index():,], length=smooth_k)
stoch_d = ma(mamode, stoch_k.loc[stoch_k.first_valid_index():,], length=d)
```

<img width="636" alt="Screen Shot 2021-08-23 at 1 57 07 PM" src="https://user-images.githubusercontent.com/18198392/130518827-a17c73ed-86c9-4ac6-a5ec-e88f8d291593.png">

<br/>

_OR_

```python
stoch_k = ma(mamode, stoch, length=smooth_k)
stoch_d = ma(mamode, stoch_k, length=d)
```

<img width="651" alt="Screen Shot 2021-08-23 at 1 55 11 PM" src="https://user-images.githubusercontent.com/18198392/130518854-61948a0c-714f-402c-b7ee-6a29bd95bdc7.png">

<br/>

is used, yields no significant difference in output and the same correlations posted previously. So at this point I don't see why it needs to be changed if they are both the same? 🤷🏼‍♂️ 

<br/><br/>

If this still concerns you or think that what is implemented is incorrect, you are in luck! It is an Open Source package and you are welcome to fork, edit/experiment, and submit Pull Requests. Contributions are welcome. 😎 

Hope this helps!?

Thanks,
KJ
