### ISSUE TITLE
How to calculate indicator

### ISSUE THREAD

**Issue by Ylelmon** [twopirllc/pandas-ta#378]
If I wrote help(ta.inductor)

It will print calculations of the indicator but how do I apply the calculations  in the dataframe ?

**Comment by twopirllc** [comment]
@Ylelmon?

**Comment by twopirllc** [comment]
@Ylelmon,

> so can I merge tow indicators to become one indictor ?

Yes, you can merge two indicators or chain or compose them. You can even [create your own indicator](https://github.com/twopirllc/pandas-ta/issues/355) which does that and add it to the library or your forked copy of the library.

What indicators were you attempting to merge? Please be detailed.

Thanks,
KJ

**Comment by Ylelmon** [comment]
Zscore and Vwap

**Comment by twopirllc** [comment]
@Ylelmon,

To clarify, you want the **zscore** of **vwap**?

If so, here is a basic outline.

```python
import pandas as pd
import pandas_ta as ta

df = # your ohlcv data

# VWAP requires the DataFrame index to be a DatetimeIndex.
# Replace "datetime" with the appropriate column from your DataFrame
df.set_index(pd.DatetimeIndex(df["datetime"]), inplace=True)

# Get vwap and add it to the df 
vwap = df.ta.vwap(append=True)

# Input vwap into zscore and add result to the df
zs = df.ta.zscore(close=vwap, append=True)

print(df.columns) # Verify they are there

# Quick plot of zscore(vwap)
zs.plot(figsize=(16,3), color=["blue"], grid=True).axhline(0, color="black")
```

Hope this helps!

Kind Regards,
KJ

**Comment by Ylelmon** [comment]
Yoooh thx

**Comment by SUVIANY** [comment]
hey KJ 
thx for all support u are offering 

I try it but i want to use my on period how can i do this ?

@twopirllc
