### ISSUE TITLE
VWAP indicator is calculating wrong vwap values for past days in dataframe

### ISSUE THREAD

**Issue by codesutras** [twopirllc/pandas-ta#38]
@twopirllc  Thanks for creating this wonderful python module. I'm extensively using this module for my algos. 

I found an issue with VWAP indicator when I ran it with my backtesting data. As per definition, VWAP should be calculated on daily data(Intraday).

Since, we pass series data, which contains past dates data as well. It calculates the cumulative sum incorrectly in that case.  Each day's opening volume and hlc price will be different for sure. 

Thus, the calculation for vwap should start with fresh data of each day. eg cumsum()

Note: Calculation is absolutely correct in a case of series data contains only 1-day data. 

Maybe we could give a  try to group a series data according to date and performing a calculation. It's just my thought. But, I would be happy to hear from you. As it's important for cross-checking strategies with backtesting data.

**Comment by twopirllc** [comment]
Hello @codesutras,

Glad that you find the module useful.

I have known about this issue for some time but unfortunately I do not have a time frame when I will have a fix.  I will keep you posted via this thread.

Thanks
KJ

**Comment by twopirllc** [comment]
Sounds good.  Two heads are better than one.  Let me know what you come up with so we can help all.

Thanks

**Comment by twopirllc** [comment]
Hello @codesutras,

Any progress so far?

Regards,
KJ

**Comment by twopirllc** [comment]
Hi @codesutras 👋

**Comment by codesutras** [comment]
@twopirllc Sorry mate. I'm occupied with some other work at this moment and will not be able to focus on this defect at this moment.

**Comment by twopirllc** [comment]
@codesutras All good. 🍀  Stay safe.

**Comment by codesutras** [comment]
@twopirllc and @YuvalWein for fixing that issue. Just got a chance to look into that. 

Kudos to you both !!

**Comment by twopirllc** [comment]
Hello @codesutras,

Kudos to @YuvalWein! Thanks for your patience.

See [Timeseries Offset Aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases) for additional options. Requires the DataFrame index to be a DatetimeIndex.

Kind Regards,
KJ

**Comment by codesutras** [comment]
Yup,

Tested already, it's working as expected !!

**Comment by YuvalWein** [comment]
Glad to hear :)
