### ISSUE TITLE
How can we use this from real time ?

### ISSUE THREAD

**Issue by bibinvargheset** [twopirllc/pandas-ta#380]
Can we generate only the last value and generate a scanner from this ?, as historic values and indicator values will be already available.

if possible how can do that?
Is there an example for checking for new signal changes for a wide range of symbols periodically with minimal delay for calculation?

**Comment by bibinvargheset** [comment]
May be I did not explain properly, 

I checked the the example strategy , its on the back testing side, my question was how can we  calculate only the  new elements.


The simplest way to help is an option to calculate only missing  values of the result Or for the added information.

Since different strategies'\indicator will have different lookback truncating and applying again wont we so efficient.


for instance 

MyStrategy = ta.Strategy(
    name="DCSMA10",
    ta=[
        {"kind": "ohlc4"},
        {"kind": "sma", "length": 10},
        {"kind": "donchian", "lower_length": 10, "upper_length": 15},
        {"kind": "ema", "close": "OHLC4", "length": 10, "suffix": "OHLC4"},
    ]
)

# (2) Run the Strategy
df.ta.strategy(MyStrategy, append=True)


df.append(new_data_df)

df.ta.strategy(MyStrategy, append=True, calculate_new_only=True)  ## since most of the elements are already calculated, only new rows without indicator values should be calculated
.

Hopefully i have made it clear now

**Comment by twopirllc** [comment]
@bibinvargheset,

Again, there are no incremental computations in the library yet. However contributions to add that functionality are accepted. 😎 For more information, please see Issues #87 and #288 where this has been previously discussed.

Kind Regards,
KJ
