### ISSUE TITLE
vwap

### ISSUE THREAD

**Issue by Ylelmon** [twopirllc/pandas-ta#384]
How to have different vwap with different inputs ?

**Comment by twopirllc** [comment]
Hello @Ylelmon,

There are four required inputs as described in ```help(ta.vwap)```. What do you want to input or replace? The more specific you are, the better I can help you.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@Ylelmon,

> cumulativePeriod1 = input(210, "Period")

What is input?

I think I understand that:
> Tpv1 = sum(typicalPriceVolume, cumulativePeriod1)
cumulativeVolume1 = sum(volume, cumulativePeriod1)
vwapValue1 = tpv/ cumulativeVolume1

depends on _cumulativePeriod1_ above. But I still do not understand what you are trying to achieve.

<br/><br/>

Since **vwap** has four different inputs: ```high, low, close, volume```, you can replace one of them or any combination of them but you have to do it explicitly.

For instance, if you wanted the **vwap** of strictly ```close``` (or ```high``` or ```low``` for that matter) and ```volume```, you could do:

```python
df = # your ohlcv data

# Default anchor is D for Daily
vwapc = ta.vwap(df.close, df.close, df.close, df.volume, anchor="D") # Default
```

Here are the other [Timeseries Offset Aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases) you can use for an ```anchor```.

Kind Regards,
KJ

**Comment by Ylelmon** [comment]
Okay now I got thx

**Comment by Ylelmon** [comment]
df = # your ohlcv data

# Default anchor is D for Daily
vwapc = ta.vwap(df.close, df.close, df.close, df.volume, anchor="D") # Default



That one veal I'm trying to put multiple vwap in the chart and every vwap had different periods like this  ![image](https://user-images.githubusercontent.com/42420576/131909628-0c7f00c9-7403-4a63-b54d-213b21fd57b7.jpeg)

**Comment by twopirllc** [comment]
@Ylelmon,

Are you sure that is **vwap**? If so, what is the source (where the image is from)? Are you sure you do not mean **vwma**, which uses defined periods?

**Note:** **vwma** is not **vwap**. For more info:

```python
import pandas_ta as ta
help(ta.vwma)
```

KJ

**Comment by Ylelmon** [comment]
I'm sure it is vwap and the picture from TradingView 


That the code 


typicalPrice = (high + low + close) / 3
typicalPriceVolume = typicalPrice * volume

cumulativePeriod1 = input(210, "Period")
cumulativeTypicalPriceVolume1 = sum(typicalPriceVolume, cumulativePeriod1)
cumulativeVolume1 = sum(volume, cumulativePeriod1)
vwapValue1 = cumulativeTypicalPriceVolume1 / cumulativeVolume1
plot(vwapValue1,title='210',color=#35e8ff,style=circles)


cumulativePeriod2 = input(400,"Period2")
cumulativeTypicalPriceVolume2 = sum(typicalPriceVolume, cumulativePeriod2)
cumulativeVolume2 = sum(volume, cumulativePeriod2)
vwapValue2 = cumulativeTypicalPriceVolume2 / cumulativeVolume2
plot(vwapValue2,title='400',color=#f995ff,style=circles,transp=1,linewidth=1)


cumulativePeriod3 = input(1700,"Period3")
cumulativeTypicalPriceVolume3 = sum(typicalPriceVolume, cumulativePeriod3)
cumulativeVolume3 = sum(volume, cumulativePeriod3)
vwapValue3 = cumulativeTypicalPriceVolume3 / cumulativeVolume3
plot(vwapValue3,title='1700',color=#acff35,style=circles,transp=1,linewidth=1)


cumulativePeriod4 = input(3100,"Period4")
cumulativeTypicalPriceVolume4 = sum(typicalPriceVolume, cumulativePeriod4)
cumulativeVolume4 = sum(volume, cumulativePeriod4)
vwapValue4 = cumulativeTypicalPriceVolume4 / cumulativeVolume4
plot(vwapValue4,title='3100',color=#f3ff00,style=circles,transp=1)

**Comment by Ylelmon** [comment]
![image](https://user-images.githubusercontent.com/42420576/131919776-74f6e4b2-c408-46ab-aa25-8884577da9cf.png)

That what it look like in the chart

**Comment by Ylelmon** [comment]
![image](https://user-images.githubusercontent.com/42420576/131919905-b4256650-fa56-4cc0-999f-6b6760109724.jpeg)
That what look like in chart

**Comment by Ylelmon** [comment]
![image](https://user-images.githubusercontent.com/42420576/131920105-c1088c68-7e8f-4ab0-9e10-411e692ea3df.jpeg)that what look like in chart

**Comment by twopirllc** [comment]
@Ylelmon,

Ahhhh... so https://github.com/twopirllc/pandas-ta/issues/384#issuecomment-912066556 is a TV Pinescript indicator. Please provide an html link to the source.

Thanks,
KJ

**Comment by Ylelmon** [comment]
HTML u mean the web ? If that it tradingview

**Comment by twopirllc** [comment]
@Ylelmon,

Whose code is it?

<img width="537" alt="Screen Shot 2021-09-02 at 3 08 50 PM" src="https://user-images.githubusercontent.com/18198392/131922887-7da06c3e-b66a-44ef-a469-9945084608a0.png">
<img width="538" alt="Screen Shot 2021-09-02 at 3 10 16 PM" src="https://user-images.githubusercontent.com/18198392/131922888-692ec7a0-a884-450f-a594-eddb2f2fe4e0.png">
<img width="531" alt="Screen Shot 2021-09-02 at 3 10 25 PM" src="https://user-images.githubusercontent.com/18198392/131922889-9f5ef0e8-9c52-48b1-98c3-eb865d283a2e.png">
<img width="532" alt="Screen Shot 2021-09-02 at 3 10 34 PM" src="https://user-images.githubusercontent.com/18198392/131922891-f34ff1aa-bdd2-418c-9c47-bd6221ebeaae.png">

**Comment by Ylelmon** [comment]
You can't find it if u search it in tradingview it files someone code it and u just copy and pasted in the pin scrip

**Comment by Ylelmon** [comment]
I already sent to u

**Comment by twopirllc** [comment]
@Ylelmon,

Those are all the public TV **vwap**s. You **must** have used one of them. If you are unable to identify which one you used, then I can not help you until you figure it out.

**Comment by Ylelmon** [comment]
It in my script and u can't search it in tradingview but thx for try to help

**Comment by twopirllc** [comment]
@Ylelmon,

Ok. To be clear, it's **not** the same as TV's builtin _nor_ Pandas TA's **vwap**.
