### ISSUE TITLE
Stochastic Rsi is very different from trading view values (again without proof)

### ISSUE THREAD

**Issue by hosseinghafarian** [twopirllc/pandas-ta#385]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
I ran a simple call to stochastic rsi with the same parameters 14,14,3,3. The result are much different from Tradingview values. 

**To Reproduce**
      dt = ta.stochrsi(df['Close'], length=14, rsi_length=14, k=3, d=3)

        df['momentum_stoch_rsi_d'] = dt['STOCHRSId_14_14_3_3']
        df['momentum_stoch_rsi_k'] = dt['STOCHRSIk_14_14_3_3']

It is much different even though parameters are the same. 

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @hosseinghafarian,

> Which version are you running?

There are three versions of the package listed on the README. Which are you using (that was originally requested)? Furthermore how do I know if you could have an older version or not? 🤷🏼‍♂️ 

If you are running an earlier version, then upgrade.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

<br/>

In the future, as mentioned in the [README](https://github.com/twopirllc/pandas-ta#issues-and-contributions), please "First, search the Closed Issues before you Open a new Issue; it may have already been solved."

There is **already** correlation with TV's **stochrsi** as addressed in Issue https://github.com/twopirllc/pandas-ta/issues/376#issuecomment-903008444 13 days ago. If you have _proof_ to the contrary, please provide _detailed_ **and** _convincing_ analysis to back up your unsubstantiated claim of "I ran a simple call to stochastic rsi with the same parameters 14,14,3,3. The result are much different from Tradingview values."

Kind Regards,
KJ
