### ISSUE TITLE
UnboundLocalError: local variable 'df' referenced before assignment

### ISSUE THREAD

**Issue by enoch-prince** [twopirllc/pandas-ta#386]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
    I'm running version 0.3.14b0

**Description of the bug**
I keep getting an UnboundedLocalError saying  local variable 'df' referenced before assignment. The piece of code is below:

**To Reproduce**
```python
import pandas as pd
import pandas_ta as ta

df = pd.DataFrame()

tesla = df.ta.ticker('tsla', period='3mo')
```

**Expected behavior**
I expected to get a dataframe object with a 3 month historical data for the Tesla stock

**Full Traceback**

     Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "C:\Users\MKEDONKOR\.virtualenvs\Stock-Patterns-tBWpuVT_\lib\site-packages\pandas_ta\core.py", line 
     851, in ticker
            df = yf(ticker, **kwargs)
     File "C:\Users\MKEDONKOR\.virtualenvs\Stock-Patterns-tBWpuVT_\lib\site-packages\pandas_ta\utils\data\yahoofinance.py", line 99, in yf
          if df.empty: return
     UnboundLocalError: local variable 'df' referenced before assignment

**Comment by twopirllc** [comment]
Hello @enoch-prince,

Weird! I am running running ```yfinance==0.1.63```, what about you? 

Thanks,
KJ

**Comment by enoch-prince** [comment]
Hi @twopirllc ,

I'm running the same version of yfinance.

Many thanks for your consideration.
Enoch Prince

**Comment by twopirllc** [comment]
@enoch-prince,

Could you add an empty DataFrame on line https://github.com/twopirllc/pandas-ta/blob/bc3b292bf1cc1d5f2aba50bb750a75209d655b37/pandas_ta/utils/data/yahoofinance.py#L90 in your local copy of Pandas TA?

<br/>

Please edit ```/pandas_ta/utils/data/yahoofinance.py``` :
```python
def yf(ticker: str, **kwargs):
    # ...
    if Imports["yfinance"] and ticker is not None:
    # ...
        df = DataFrame() # Add this
        try:
            df = yfd.history(period=period, interval=interval, proxy=proxy, **kwargs)
        except:
            # ...
```

Does that take care of the ```UnboundLocalError```? If it is still not loading data, it may be a ```yfinance``` issue. Do other tickers work?

Thanks,
KJ

**Comment by enoch-prince** [comment]
@twopirllc 

I restarted VS Code and tried to reproduce the bug with adding the line as you suggested and it worked. I tried it again and it still worked. It's kind of strange. 

I have added the line of code as well and it still works.

Cheers!

**Comment by twopirllc** [comment]
@enoch-prince,

Awesome! I appreciate you responding promptly and your the temporary fix solves the ```UnboundLocalError``` issue. I will add the fix for the next version so it does not occur again.

Thank you,
KJ
