### ISSUE TITLE
TA Values not Applied When Using Multiprocessing Library Explicitly

### ISSUE THREAD

**Issue by alphazwest** [twopirllc/pandas-ta#390]
**Which version are you running? The latest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.3.14b0

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```
Done. Same issue present.

**Describe the bug**
When applying ta indicators using the Multiprocessing.Pool() function, values are not being appended as expected.

**To Reproduce**

"""
Reference: 

The DataFrame object I am using:

```sh
           Date        Open        High         Low       Close     Volume
0    2020-09-10  119.590816  119.729920  111.781046  112.764717  182274400
1    2020-09-11  113.837816  114.493602  109.297022  111.284241  180860300
2    2020-09-14  113.986855  115.189122  112.079127  114.622765  140150100
3    2020-09-15  117.573791  118.070596  112.883954  114.801620  184642000
4    2020-09-16  114.493601  115.258677  111.323985  111.413406  154679000
..          ...         ...         ...         ...         ...        ...
247  2021-09-02  153.869995  154.720001  152.399994  153.649994   71115500
248  2021-09-03  153.759995  154.630005  153.089996  154.300003   57808700
249  2021-09-07  154.970001  157.259995  154.389999  156.690002   82278300
250  2021-09-08  156.979996  157.039993  153.979996  155.110001   74420200
251  2021-09-09  155.490005  156.110001  153.949997  154.070007   54962409
```
"""

```python
import pandas as pd
import pandas_ta as ta
from multiprocessing import Pool as processPool
```

# The Function
```python
def add_ta(frame: pd.DataFrame) -> None:
    """Adds the TA to a dataframe"""
    frame.ta.sma(length=50, append=True)
```

# This works, when not using multiprocessing
`add_ta(df)`

# This doesn't
# Note: Edited (was mistakenly written as threadPool)
```python
def mp_add_ta_to_data(datas: [pd.DataFrame]):
    with processPool() as pp:
        pp.map(add_ta, df)

# Running the MP approach in main
if __name__ == '__main__':
    mp_add_ta_to_data(df)
```

**Expected behavior**
I have a collection of pandas.DataFrame objects I am using the multiprocessing Pool function to map to a function that will apply one or more pandas_ta indicators to. When adding the indicators to a single frame, using the function to which the multiprocessing library maps to, indicators are added as expected. However, when mapping the DataFrame objects to that function via Pool they are not being applied (though from some initial errors in column names it would seem they *are* being calculated).

**Screenshots**

**Additional context**
Happy to elaborate if needed. I'm not intimately familiar with the multiprocessing library and am aware the pandas_ta library envelopes it to some degree. I hope I'm just doing something silly.

Best,

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @alphazwest,

So to clarify, you have a collection of DataFrames and you want to create a _Threadpool_ to process them with TA?

If this is correct, then this is a Python Multithreading problem, since your using a _threadPool_, and **not** a bug with Pandas TA's Multiprocessing (though that could be an issue if eventually implement ```frame.ta.strategy()``` within ```def add_ta()```.

While this is beyond the scope of support of Pandas TA, I will try and help. **Note:** Pandas TA is using Multiprocessing and not Multithreading, so I am not too familiar with it's implementation.

When running your ```__main__```, do you get any errors or warnings? Do you have any additional boilerplate code that you can share so I can be of more assistance?

Additionally, here are some resources I have used to help me:
* [Python Multithreading](https://docs.python.org/3/library/threading.html#module-threading)
* [Multiprocessing vs Multithreading](https://timber.io/blog/multiprocessing-vs-multithreading-in-python-what-you-need-to-know/)
* [Tutorials Point Multithreading](https://www.tutorialspoint.com/python/python_multithreading.htm)
* [Threads, Processses, & Concurrency](https://people.duke.edu/~ccc14/cspy/19B_Threads_Processses_Concurrency.html)
    * [Duke's Computational Stats in Python](https://people.duke.edu/~ccc14/cspy/#indices-and-tables)

Kind Regards,
KJ

**Comment by alphazwest** [comment]
@twopirllc Sorry, I had been working on a network solution using multi-threading earlier and had mistakenly used the incorrect syntax. I am, in fact, using _multprocessing_ with a _process_pool (i.e. multiprocessing.Pool()) rather than multithreading. Sorry for the confusion there—I've updated my initial comment to reflect a less erratic syntax.

After some further messing around, I have a big more insight. It seems that with using the Pool.map() function there is a copy of the dataframes being created. See the following:

`def add_ta(frame: pd.DataFrame) -> None:
    """Adds the TA to a dataframe"""
    print("add_ta initial:", id(frame))
    frame.ta.cores = 0  # no multiprocessing here b/ daemonic processes can't bear children
    # frame.ta.sma(length=50, append=True)

    frame['SMA_50'] = ta.sma(length=50, close='Close')
    print("add_ta after SMA:", id(frame))
    return frame


def mp_add_ta_to_data(datas: [pd.DataFrame]):
    """Adds TA indicators to a collection of historical data"""
    logging.info(f'Preparing to TA {len(datas)} datum.')
    with processPool() as pp:
        pp.map(add_ta, data)


df = pd.read_csv('tmp/AAPL.csv')[["Date", "Open", "High", "Low", "Close", "Volume"]]
    print("initial frame:", id(df))


    mp_add_ta_to_data([df])

    print(df.head(3))
    print("resulting frame:", id(df))`

The output of this code is as follows:

`
initial frame: 1659839723648    <--------The ID of the initial DataFrame, before being mapped to the add_ta function

add_ta initial: 2070170516208   <--------The ID of the DataFrame after being passed. Presumably a shallow copy.

add_ta after SMA: 2070170516208 <--------The ID of the DataFrame after being having a pandas_ta (or other function) applied.

         Date        Open        High         Low       Close     Volume
0  2020-09-10  119.590816  119.729920  111.781046  112.764717  182274400
1  2020-09-11  113.837816  114.493602  109.297022  111.284241  180860300
2  2020-09-14  113.986855  115.189122  112.079127  114.622765  140150100

resulting frame: 1659839723648   <--------The ID of the initial DataFrame, clearly not having been affected by the multiprocessing process.` 

I agree this is not an issue with pandas_ta and, rather, a Multiprocessing issue. 

I apologize for the clutter. If you have any ideas I'd love to hear them otherwise feel free to close this thread as being irrelevant.

Best,
AZ

**Comment by pssolanki111** [comment]
@alphazwest it might be very late to answer, but you shouldn't be using `.map` for one df object. instead `.submit` is what you need.

```py
with mp.Pool(blah-blah) as pool:
    future = pool.submit(function_name, arg1, arg2, arg3)
```

also remember to keep it inside the `if __name__ == '__main__':` guard (the ifmain guard)

**Comment by pssolanki111** [comment]
also @twopirllc i feel this issue needs to be closed. They can re-open if they feel the need to any time they want.

**Comment by alphazwest** [comment]
> @alphazwest it might be very late to answer, but you shouldn't be using `.map` for one df object. instead `.submit` is what you need.
> 
> ```python
> with mp.Pool(blah-blah) as pool:
>     future = pool.submit(function_name, arg1, arg2, arg3)
> ```
> 
> also remember to keep it inside the `if __name__ == '__main__':` guard (the ifmain guard)

Thanks, it was actually a collection of `DataFrame` objects and wrapped in `if __name__ == "__main__"` per my initial comment. The last few comments were just casual discussions.

This issue can 100% be closed. I should have already indicated such.
