### ISSUE TITLE
Do we have AWS ARN for lambda function layer for pandas_ta?

### ISSUE THREAD

**Issue by gjhansaliya13** [twopirllc/pandas-ta#393]
Do we have AWS ARN for lambda function layer for pandas_ta?

I am looking for Asia Pacific (Mumbai)ap-south-1 python version 3.7.

can you please create?

**Comment by twopirllc** [comment]
Hello @gjhansaliya13,

Do we have AWS ARN for lambda function layer for pandas_ta?

Not that I know of. I would have to look into it.

Kind Regards,
KJ

**Comment by gjhansaliya13** [comment]
Appreciate your reply and help

**Comment by twopirllc** [comment]
@gjhansaliya13,

I'm sorry but this will not be implemented. We are not using Pandas TA on AWS nor do I see how it will benefit the library. If this is some internal thing related to you or some business you work for then I would ask them.

Kind Regards,
KJ

**Comment by ddabongcoin** [comment]
OMG,,, that's why pandas_ta does not work on AWS....
