### ISSUE TITLE
ta.zlma indicator Error

### ISSUE THREAD

**Issue by AureliusMarcusHu** [twopirllc/pandas-ta#394]
Running Python 3.9 32 bits on OS Windows 10 64 bit
Pandas Version: 1.3.1
pandas-ta:  Version: 0.3.14b0     successfully installed with pip.

In the beginning of my script I import as follows:
```python
import pandas as pd
import pandas_ta as ta
import numpy as np
```

I run the following script in python debugger:
```python
df['zmla'] = ta.zlma(df['close'], length=5, mamode="t3", offset=1)
```

I get the following error:
```sh
File "C:\Program Files (x86)\Python39-32\lib\site-packages\pandas_ta\overlap\zlma.py", line 27, in zlma
   elif mamode == "t3":     zlma = t3(close_, length=length, **kwargs)
TypeError: 'module' object is not callable
```

It works only for me with mamode=  'dema'  or 'ema'.
All the other mamode indicators give the same error as I explained above.

By the way, if I run the script below with the same data any problems at all, it work like a charm.
```python
df['t3ma'] = ta.t3(df['close'], length=5, offset=1)
```

Is there a problem with reimporting the ma's in the zlma module ?
Or what am I doing wrong ?

**Comment by twopirllc** [comment]
Hello @AureliusMarcusHu,

> Or what am I doing wrong ?

I don't think you have done anything wrong.  I also noticed there was something weird with ```zlma```.

> Is there a problem with reimporting the ma's in the zlma module ?

That's what I think. Unfortunately, I haven't had the time to look into it. If you have ideas on how to fix it, that would be great. Contributions are welcome. 😎 

Kind Regards,
KJ

**Comment by AureliusMarcusHu** [comment]
Thanks for the response. For me python is new, I'm still struggling with the syntax. But in the meantime I have found a working solution. I copied the zlma module into my project as below. The first line of importing the ma's is a bit different. On this way all mamode= ma's work as a charm. Maybe it give you an idea what is wrong with the import in your module.

```python
def zlma(close, length=None, mamode=None, offset=None, **kwargs):
    from pandas_ta import dema, ema, fwma, hma, linreg, pwma, rma, sma, swma, sinwma, t3, tema, trima, vidya, wma
    from pandas_ta.utils import get_offset, verify_series
    """Indicator: Zero Lag Moving Average (ZLMA)"""
    # Validate Arguments
    length = int(length) if length and length > 0 else 10
    mamode = mamode.lower() if isinstance(mamode, str) else "ema"
    close = verify_series(close, length)
    offset = get_offset(offset)

    if close is None: return
    # Calculate Result
    lag = int(0.5 * length - 1)
    close_ = 2 * close  - close.shift(lag)
    if   mamode == "dema":   zlma = dema(close_, length=length, **kwargs)
    elif mamode == "fwma":   zlma = fwma(close_, length=length, **kwargs)
    elif mamode == "hma":    zlma = hma(close_, length=length, **kwargs)
    elif mamode == "linreg": zlma = linreg(close_, length=length, **kwargs)
    elif mamode == "pwma":   zlma = pwma(close_, length=length, **kwargs)
    elif mamode == "rma":    zlma = rma(close_, length=length, **kwargs)
    elif mamode == "sma":    zlma = sma(close_, length=length, **kwargs)
    elif mamode == "swma":   zlma = swma(close_, length=length, **kwargs)
    elif mamode == "sinwma": zlma = sinwma(close_, length=length, **kwargs)
    elif mamode == "t3":     zlma = t3(close_, length=length, **kwargs)
    elif mamode == "tema":   zlma = tema(close_, length=length, **kwargs)
    elif mamode == "trima":  zlma = trima(close_, length=length, **kwargs)
    elif mamode == "vidya":  zlma = vidya(close_, length=length, **kwargs)
    elif mamode == "wma":    zlma = wma(close_, length=length, **kwargs)
    else:                    zlma = ema(close_, length=length, **kwargs) # "ema"
`
    # Offset
    if offset != 0:
        zlma = zlma.shift(offset)

    # Handle fills
    if "fillna" in kwargs:
        zlma.fillna(kwargs["fillna"], inplace=True)
    if "fill_method" in kwargs:
        zlma.fillna(method=kwargs["fill_method"], inplace=True)

    # Name & Category
    zlma.name = f"ZL_{zlma.name}"
    zlma.category = "overlap"

    return zlma, zlma.name
``

**Comment by twopirllc** [comment]
@AureliusMarcusHu,

Glad you found a work around!

Thanks for sharing.
KJ

**Comment by twopirllc** [comment]
@AureliusMarcusHu,

Unfortunately, even I couldn't come up with a better alternative. 🤷🏼‍♂️
However, please try out the _ branch. It has speed improvements, better documentation, and typing.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ
