### ISSUE TITLE
TypeError: ma() got multiple values for argument 'name'

### ISSUE THREAD

**Issue by windowshopr** [twopirllc/pandas-ta#395]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
Python 3.7.9, 
pandas-ta @ git+https://github.com/twopirllc/pandas-ta@bc3b292bf1cc1d5f2aba50bb750a75209d655b37
Windows 10

**Upgrade.**
Done

**Describe the bug**
TypeError: ma() got multiple values for argument 'name'

**To Reproduce**
```python
def main_start():
    df = pd.DataFrame()
    df = df.ta.ticker("aapl")
    print(df)
    
    # Add the tecnical indicators
    df.ta.strategy(name='all', verbose=True)
    print(df)

if __name__ == '__main__':
    main_start()
```

**Expected behavior**
Would like to add all technical indicators to the dataset in one function call.

**Screenshots**
![image](https://user-images.githubusercontent.com/40477419/134078863-d03aad60-2888-4181-8f08-c8b192a4f637.png)

**Additional context**
None

**Comment by twopirllc** [comment]
Hello @windowshopr,

This is not a bug. I would remove ```name=``` when calling ```df.ta.strategy()``` as described on the README [Builtin Strategies](https://github.com/twopirllc/pandas-ta#types-of-strategies) and it should work as intended.

```python
def main_start():
    df = pd.DataFrame()
    df = df.ta.ticker("aapl")
    print(df)
    
    # Add the tecnical indicators
    df.ta.strategy('all', verbose=True)
    print(df)

if __name__ == '__main__':
    main_start()
```

Result:
<img width="597" alt="Screen Shot 2021-09-20 at 3 05 09 PM" src="https://user-images.githubusercontent.com/18198392/134082149-a3cfc4e8-762e-4862-9b8a-eaa836ef1cc6.png">

Kind Regards,
KJ
