### ISSUE TITLE
pandas_ta is designed in ascending dates

### ISSUE THREAD

**Issue by Silverback-Ren** [twopirllc/pandas-ta#396]
Hi @twopirllc,

First of all, I am very thankful for this initiative, this is really helpful to us. Please continue developing it as it helps many people just like me. 

Just noticed that indicators (e.g. sma) are designed for OHLC with ascending dates (1st row is oldest and succeeding rows' dates are newer), is there a simple trick to make it descending (1st row is newest and succeeding rows' dates are older)? I am not sure if df.ta.reverse will solve the problem, I tried to play around with this command but was not able to accomplish what I am intending to do (or I was not able to use it right). Please do advise. 

Thanks and warm regards.

**Comment by twopirllc** [comment]
Hello @Silverback-Ren,

> First of all, I am very thankful for this initiative, this is really helpful to us. Please continue developing it as it helps many people just like me.

You're welcome. Thanks for using it!

> Just noticed that indicators (e.g. sma) are designed for OHLC with ascending dates (1st row is oldest and succeeding rows' dates are newer), is there a simple trick to make it descending (1st row is newest and succeeding rows' dates are older)?

It is not true that the indicators are designed for ascending dates for _ohlcv_ data. The only one that matter is **vwap**, but it will still run and give you a warning of ```[!] VWAP volume series is not datetime ordered. Results may not be as expected.```.

> I am not sure if df.ta.reverse will solve the problem, I tried to play around with this command but was not able to accomplish what I am intending to do (or I was not able to use it right). Please do advise.

Yes _df.ta.reverse_ is a convience property that will reverse the order of the DataFrame. You just need to overwrite the original DataFrame or make a new DataFrame.

```python
import pandas_ta as ta

df = ta.df.ta.ticker("aapl", period="3mo")
print(df)

# Make a copy of the reversed DataFrame
dfr = df.ta.reverse.copy()

# Apply TA
dfr.ta.sma(append=True)
dfr.ta.vwap(append=True)  # Will give warning.
print(dfr)
```

<br/>

**Results:**
<img width="677" alt="Screen Shot 2021-09-22 at 2 49 59 PM" src="https://user-images.githubusercontent.com/18198392/134426820-be144a29-b363-4893-9df7-cb526391a65a.png">



Hope this helps! Let me know otherwise.

Kind Regards,
KJ

**Comment by Silverback-Ren** [comment]
Thanks for your quick reply KJ. 

I had the same result as yours. Correct me if I'm wrong, the first few rows of the SMA_10 are NaN and the last rows have values, should it be the other way around? If I will do it manually, the first 9 rows should have values and the last 9 rows are blanks since you don't have the right amount of N.

**Comment by twopirllc** [comment]
@Silverback-Ren,

Ok. I guess I did not understand what you originally wanted. **(A)** Did you want to reverse the DataFrame and then apply indicators? (That's the result of my previous comment). **(B)** Or did you want to apply indicators in ascending order and then reverse the DataFrame? (code below)

```python
import pandas_ta as ta

df = ta.df.ta.ticker("aapl", period="3mo")
# Apply TA
df.ta.sma(append=True)
df.ta.vwap(append=True)  # Will give warning.
print(df)

# Make a copy of the reversed DataFrame
dfr = df.ta.reverse.copy()
print(dfr)
```

<br/>

Regarding *SMA_10*, it requires 10 values before it can calculate it's first value on the 10th row. That is just how some indicators work. Hence the first 9 values are ```NaN```.

Kind Regards,
KJ

**Comment by Silverback-Ren** [comment]
Hi KJ, sorry for late reply. I guess its A. But nonetheless,  I got your guidelines. Thanks.
