### ISSUE TITLE
Docstrings not showing correctly

### ISSUE THREAD

**Issue by xmatthias** [twopirllc/pandas-ta#399]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**

0.3.14b0

**Describe the bug**
Running `help(pta.adx)` will correctly show the `__doc__`.

However, the way docstrings are assigned (manually assigning to `__doc__` of the function) causes IDE completion to not show the docstring correctly.

![2021-09-28-200456_559x216_scrot](https://user-images.githubusercontent.com/5024695/135141561-d0718b3d-7110-4a97-a476-01f52c580d29.png)

**To Reproduce**
Use VSCode with python extension, use virtualenv with pandas_ta installed and use a very simple sample-snippet like  the below.

``` python
import pandas_ta as pta

pta.adx
```
Uppon opening the parenteses after ADX, the docstring should show.
Also on hover on the method, the docstring should show (but only the "one line" after the function header is showing).

**Expected behavior**
Docstring will also show up as part of the autocompletion.

**Screenshots**
![2021-09-28-200456_559x216_scrot](https://user-images.githubusercontent.com/5024695/135141561-d0718b3d-7110-4a97-a476-01f52c580d29.png)

Same behaviour also shows on pycharm - so it's apparently not an editor issue.
![2021-09-28-201617_419x304_scrot](https://user-images.githubusercontent.com/5024695/135143104-7f71272b-36b5-45d3-86bd-7799030c4518.png)

**Additional context**
One can argue that it's a problem of the the IDE - but it works fine for other packages ... 

On top of this, IDE completion for "Dataframe extension mode" does not work at all ... but i suspect that's an issue with pandas more than with pandas_ta).

Also - i think it would be nice to have a "full" documentation build based on the available docstrings that's available as website (like readthedocs.io or github pages...).
While it'll seem sufficient to point users to "run `help(pta.adx)`" - having a webpage that allows to search for things in a "decently rendered" way would improve usability.

**Comment by twopirllc** [comment]
Hello @xmatthias,

Thank you for the inclusion of Pandas TA in **freqtrade**. 😎 

> However, the way docstrings are assigned (manually assigning to __doc__ of the function) causes IDE completion to not show the docstring correctly.

That is true. I noticed it as well with VS Code. It's unfortunate the IDE can not resolve ```__doc__``` but whatever... luckily that's an easy fix and I (or hopefully someone else) can make these edits relatively soon.

> On top of this, IDE completion for "Dataframe extension mode" does not work at all ... but i suspect that's an issue with pandas more than with pandas_ta).

I think so as well.

>  Also - i think it would be nice to have a "full" documentation build based on the available docstrings that's available as website (like readthedocs.io or github pages...).
While it'll seem sufficient to point users to "run help(pta.adx)" - having a webpage that allows to search for things in a "decently rendered" way would improve usability.

I agree. It's something I have been thinking about as well. Based on your experience developing **freqtrade**, what would you recommend?

Thank you,
KJ

**Comment by xmatthias** [comment]
I feel our case might be slightly different - as we have a ton of "standalone" documentation (explicitly written in .md files) - which is pretty easy to serve / deploy with readthedocs.

for pandas-ta, i see most of the indicator-specific documentation in doc-strings (which is also perfectly fine) - but from a usability perspective, a standalone version where you can maybe also compare two indicstors calculations without running help multiple times would definitely help.

You might wanna look into sphinx or mkdocs with [plugins](https://github.com/mkdocstrings/mkdocstrings) to automatically generate pages out of the available docstrings.
Both ways will need some configuration to make it find all docstrings, and to move them all in the desired way ... but it can be a simple/easy way to auto-generate documentation.

Obviously additional documentation can still be added (like the readme.md page) - but i'd see that almost as a second step.

**Comment by twopirllc** [comment]
@xmatthias,

> You might wanna look into sphinx or mkdocs with plugins to automatically generate pages out of the available docstrings.

I've used sphinx once but will definitely need to play around with it a bit more.

Thanks for the suggestions and sharing your experience. I appreciate it.

KJ

**Comment by twopirllc** [comment]
Hey @xmatthias,

I have updated the doc strings so that they _should_ work as expected. Please test them out on the _development_ branch before I update the _main_ branch.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

If I missed something, please let me know.

Thanks,
KJ

**Comment by pssolanki111** [comment]
@twopirllc i used shpinx to build the docs for my library (for polygon.io financial data APIs) and it works so well. 

https://polygon.readthedocs.io/en/latest/index.html

It has this section which basically describes the entire library API in readable form at https://polygon.readthedocs.io/en/latest/Library-Interface-Documentation.html

**Comment by twopirllc** [comment]
@pssolanki111,

> i used shpinx to build the docs for my library (for polygon.io financial data APIs) and it works so well.

I am aware of Sphinx, just little xp with it. Thanks for providing reference links. 😎 

Thanks,
KJ
