### ISSUE TITLE
Stochastic Fast indicator

### ISSUE THREAD

**Issue by razamit** [twopirllc/pandas-ta#401]
Hi

I am using the latest version of Pandas Ta as a replacement for TA-Lib

I was using STOCHF - Stochastic Fast from TA-Lib (http://www.tadoc.org/indicator/STOCHF.htm)
I did not see it in Pandas-ta.
I it possible to "create" it using the parameters passed to the pandas-ta.stoch function?

Thanks

Amit

**Comment by twopirllc** [comment]
Hello @razamit,

Early in Pandas TA's development, **stoch** used to return both **stoch** and **stochf** values. Also **stoch** is one of several Pandas TA indicators that is not wrapping TA Lib's _STOCH_ and _STOCHF_. A Python only **stochf** like **stoch** can be easily added to the library (as most of the code between the two is similar), but I can not give an expected completion time given my current list of unresolved and backlogged Issues.

If you need it soon, perhaps you (or someone else) can help contribute by following Issue #355 **Creating a Custom Indicator: The Big 4** and then making a Pull Request. 😎 If stuck at any point, I can help guide as needed.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@razamit,

It's on the _development_ branch now if you want to double check that it's working as intended.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @razamit,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
