### ISSUE TITLE
Type stubs

### ISSUE THREAD

**Issue by jeremyfx** [twopirllc/pandas-ta#404]
**Which version are you running? The lastest version is Github. Pip is for major releases.**
0.3.14b

**Is your feature request related to a problem? Please describe.**
Python is ever more growing towards typing. Even major projects like Pandas, Numpy, Matplotlib have added typing hinting to the projects and made type stubs available to developers. For my job, or when I create a serious project, I ensure my code is type safe. While my type checker can infer some return types from the library, the input types are always unknown.

**Describe the solution you'd like**
Progressively add type hints to the code base and generate type stubs to be made available to developers using pandas_ta.

**Comment by twopirllc** [comment]
Hello @jeremyfx,

I agree. There are a lot of lingering issues and new features yet to be implemented in Pandas TA, typing included. This package is beyond the maintainability to do both for one person. If you are willing to contribute, I would appreciate help progressively typing Pandas TA. 😎 

Kind Regards,
KJ

**Comment by pssolanki111** [comment]
@twopirllc to confirm, this is about adding type hinting to all the classes, methods, and functions for their arguments and return types, right? 

(and I'm assuming docstrings included, lemme know if otherwise).

**Comment by twopirllc** [comment]
@pssolanki111,

That is correct. More so for the individual indicators in their respective sub-directories than all the DataFrame Extension Indicator Methods (sma, ema, et al) in _core.py_ for now.

Thanks,
KJ

**Comment by pssolanki111** [comment]
@twopirllc That makes sense. two questions here

1. I'm assuming we're NOT supposed to only use `|` for compound type indication and that it is okay to use `Union` from typing?
2. it is okay to raise PRs for component files in groups, as opposed to raising one BIG PR with all the type hints done and dusted?

I'm almost entirely certain about both being True but wanted to confirm.

Regards
P S

**Comment by twopirllc** [comment]
@pssolanki111,

1. Whatever is flexible and creates minimal future technical debt.
1. Yes, groups would be manageable. 

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @jeremyfx,

Typing has been included thanks to @pssolanki111. 😎  If you want to test it out, check out the _development_ branch.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Kind Regards,
KJ

**Comment by pavittarx** [comment]
For some reason, I am still getting missing stubs issue.

![image](https://github.com/user-attachments/assets/695504a4-41c6-4b07-b5e2-66c2613cf4d5)
