### ISSUE TITLE
Kaufman's Adaptive Moving Average (KAMA) - calculation issue

### ISSUE THREAD

**Issue by onachassi** [twopirllc/pandas-ta#405]
```python
import yfinance as yf
from pandas_ta.overlap import kama
import mplfinance as mpf

ticker = yf.Ticker("SPY")
minute_data = ticker.history(period="7d", interval="1m")

kama_results = kama(minute_data["Close"])
addplot = [
    mpf.make_addplot(kama_results, color='blue')
]
mpf.plot(minute_data, volume=True, type='candle', addplot=addplot)
```

![Figure_1](https://user-images.githubusercontent.com/21048244/136270412-3e96de80-6de0-4a36-9d02-8f691ae40a72.png)

I tried using the Kama indicator (snippet and picture above), seems like there's a bug with the calculate the Kama. The initial Kama value relies on the previous value which I believe from the snippet below returns zero for the first value.

https://github.com/twopirllc/pandas-ta/blob/bc3b292bf1cc1d5f2aba50bb750a75209d655b37/pandas_ta/overlap/kama.py#L34

[This doc](https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:kaufman_s_adaptive_moving_average) was referenced on a comment in the kama.py file and suggests that "the first KAMA is just a simple moving average".

Is there anyway we can add another arg for starting_kama or generate some sma based on the "slow" length?

**Comment by twopirllc** [comment]
Hello @onachassi,

I added **sma** as the default MA mode for **kama** on the _development_ branch if you want to test it out before I update the _main_ branch. Note: Not all mamodes are applicable due to their individual bootstrap lengths, but the majority are. See ```help(ta.kama)``` after installing the _development_ branch.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Please let me know if it works as intended now. Thanks for noticing the Issue. 😎 

Kind Regards,
KJ

**Comment by onachassi** [comment]
@twopirllc I'm getting the same thing as before. Taking a look at the development branch I don't think anything has changed: https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/overlap/kama.py

Am i missing something?

**Comment by bazoka12** [comment]
https://stackoverflow.com/a/73619226/1233573
