### ISSUE TITLE
Squeeze parameters values so that the result be identical to the "Squeeze Momentum Indicator [LazyBear]" in TradingView

### ISSUE THREAD

**Issue by Nerque** [twopirllc/pandas-ta#408]
I have tried with :
a) ta.squeeze(df['High'], df['Low'], df['Close'], use_tr=True, lazybear=True)
b) ta.squeeze(df['High'], df['Low'], df['Close'], bb_length=20, bb_std=2, kc_length=20, kc_scalar=1.5, mom_length=12, mom_smooth=6, use_tr=True, mamode='sma', lazybear=True)

None give me the same result.

Example:
* BTCUSDT (Binance) 15 minutes: 10 Oct'21 20:15 (UTC+2) ==> SQZMOM_LB Value = 48.71; ta.squeeze = 59.60;

It's probably because of the values I pass to the method, but it's not clear to me. I may even be missing some of them.

Any idea what could be the problem?

**Comment by twopirllc** [comment]
Hello @Nerque,

I will be closing this Issue until you have time to test the data and code I provided above in https://github.com/twopirllc/pandas-ta/issues/408#issuecomment-940169486.

Thanks,
KJ
