### ISSUE TITLE
Add MAMA and FAMA indicators

### ISSUE THREAD

**Issue by arshpreetsingh** [twopirllc/pandas-ta#413]
**Which version are you running? The lastest version is Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
0.3.14b0

```

**Describe the solution you'd like**
Mesa Adaptive moving average indicator is not available. 
mama, fama = ta.mama(df['Close'], fastLimit=0.5,slowLimit=0.05)

**Additional context**
Available in TA-Lib

import talib
mama,fama=talib.mama(nd array, fastLimit,slowLimit)

**Comment by twopirllc** [comment]
Hello @arshpreetsingh,

Noted. It will sometime before it will be implemented. If you would like it available sooner, please fork, edit and make a PR. Contributions are appreciated. 😎 Instructions on how to add an indicator to Pandas TA can be found in Issue #355 _Creating a Custom Indicator: The Big 4_.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @arshpreetsingh,

Alas **mama** (& **fama**) are complete; combined into **mama**. They are available on the _development_ branch.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Please test it out when you get a chance.

Kind Regards,
KJ

**Comment by abhisheksoni27** [comment]
how can I use this?

**Comment by abhisheksoni27** [comment]
@twopirllc was the code ever merged?

**Comment by twopirllc** [comment]
@arshpreetsingh 

Literally my last comment.
