### ISSUE TITLE
Clarifying Question about the implemented TD Sequential Indicator

### ISSUE THREAD

**Issue by drixie** [twopirllc/pandas-ta#421]
Thank you for the great work on this!

I was going through the  code for the TD Sequential indicator and noticed it was configured to work from 1 to 13. What parameters do I need to pass if I need to only count from 1 to 9. 

I feel like the relevant argument here is "offset", I just don't know what to pass into it. Perhaps an example in the documentation will be helpful

TIA

**Comment by drixie** [comment]
Also, is it possible for the generated TD Sequential dataframe to have a key that will make it easier to merge back to the OHLCV data?

**Comment by drixie** [comment]
When using td_seq as a TA extension, I kept receiving this error: TypeError: td_seq() got multiple values for argument 'asint'

Works fine when used with standard format. 

Using version 0.3.14b on Google Colab
Sample code: td_df = df.ta.td_seq(df["close"], asint=True)

**Comment by twopirllc** [comment]
@drixie,

> I was going through the code for the TD Sequential indicator and noticed it was configured to work from 1 to 13. What parameters do I need to pass if I need to only count from 1 to 9.

At this time, no. However, if you want values 6-9, then set keyword argument ```show_all=False``` as described in ```help(ta.td_seq)```.

> I feel like the relevant argument here is "offset", I just don't know what to pass into it. Perhaps an example in the documentation will be helpful

```offset``` does not have anything to do with the count sequence. It's a general keyword argument used by all the indicators to ```shift()``` the results forward or backwards as needed before returning the result(s).

> Also, is it possible for the generated TD Sequential dataframe to have a key that will make it easier to merge back to the OHLCV data?

I'm sorry, I do not understand what you mean by "have a key". Is ```df.ta.td_seq(append=True)``` not appending it to the OHLCV DataFrame?

> When using td_seq as a TA extension, I kept receiving this error: TypeError: td_seq() got multiple values for argument 'asint'

You can either do ```td_df = df.ta.td_seq(close=df["Close"], asint=True)``` or  ```td_df = df.ta.td_seq(asint=True)```. The latter assumes you are using "Close" from the ```df``` and thus does not need to be explicitly told.

Hope this helps.

Kind Regards,
KJ

**Comment by drixie** [comment]
KJ, 

Thanks for your responses, they are very helpful. 

For the third point, passing an argument of append=True **does not** append the generate td_seq columns to the OHLCV DataFrame

I could not recreate the issue in the fourth point, so maybe it was caused by something on my end

**Comment by twopirllc** [comment]
@drixie

> Thanks for your responses, they are very helpful.

No worries.

> For the third point, passing an argument of append=True does not append the generate td_seq columns to the OHLCV DataFrame

Interesting. However I see no issue appending it to the OHLCV DataFrame, thus working as intended.

<img width="460" alt="Screen Shot 2021-11-02 at 8 23 07 AM" src="https://user-images.githubusercontent.com/18198392/139877198-4accc959-81d9-4f85-b106-18120cadfc56.png">

> I could not recreate the issue in the fourth point, so maybe it was caused by something on my end

I'll take your word for it.

KJ

**Comment by drixie** [comment]
Weird behavior when using it as an extension. Screenshot below. Here is the link to the colab if you want check it out: https://colab.research.google.com/drive/1ieHkSsieEMzKs_gI4xnx25QdtNZOu2f1?usp=sharing


<img width="1195" alt="Screen Shot 2021-11-02 at 11 05 42 AM" src="https://user-images.githubusercontent.com/1880792/139921814-68a6785f-a44a-47d4-9297-b6957a720b42.png">

**Comment by twopirllc** [comment]
@drixie,

Ahhh Google Colab.... unfortunately not easy to test against. 😞 

Anyhow regarding ```td_seq```, after Pandas TA v 0.3.14b, ```td_seq``` had an unusual bug with a Pandas DataFrame index initialization. However that patch is on the _development_ branch and addresses the ```append=True``` problem.

Changes I made:

### Cell 1
```python
!pip install numpy
!pip install pandas
!pip install yfinance
!pip install ccxt
!pip install -U git+https://github.com/twopirllc/pandas-ta.git@development

import pandas
import pandas_ta as ta
import ccxt
```

### Cell 2
```python
ddog = ta.df.ta.ticker("ddog")
ddog.ta.td_seq(asint=True, show_all=True, append=True)
ddog
```

### Cell 3
```python
# Check
ddog_td = ta.td_seq(close=ddog["Close"], asint=True)
ddog_td
```

### Cell 4
```python
binance = ccxt.binance()
ohlcv = binance.fetch_ohlcv("BTC/USDT", "8h")

df = pandas.DataFrame(ohlcv)
df.columns = ["t", "o", "h", "l", "c", "v"]
df["t"] = df["t"]/1000
df["t"] = pandas.to_datetime(df["t"], unit="s")
df.set_index("t", inplace=True)
df.index = df.index.tz_localize("UTC").tz_convert("America/New_York")

df
```

### Cell 5
```python
df.ta.td_seq(close=df["c"], asint=False, show_all=True, append=True)
df
```

### Cell 6
```python
df.iloc[:,-2:].plot(
    figsize=(16, 3), kind="line", color=["green", "red"],
    linewidth=1, title="TD_SEQ", alpha=0.95, grid=True
  ).axhline(y=0, color="black")
```

Should plot something similar:
<img width="947" alt="Screen Shot 2021-11-02 at 1 17 55 PM" src="https://user-images.githubusercontent.com/18198392/139945872-a7d7a95c-e232-4ddb-87a2-ec9ce4c2cbf0.png">

Hopefully the changes I included work for you as well.

KJ

**Comment by drixie** [comment]
Works perfect! As you suggested, some of the issues came from Colab

Thanks a lot for your effort and time!!

**Comment by twopirllc** [comment]
@drixie,

You're welcome. Thanks for your patience.

KJ

**Comment by JIMBOB32** [comment]
thank you so much for that explination :)
