### ISSUE TITLE
STC not working

### ISSUE THREAD

**Issue by rajeshdhar** [twopirllc/pandas-ta#425]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python

0.3.14b0
```

**Describe the bug**
KeyError: 1

**To Reproduce**
Provide sample code.
df.ta.stc(append=True)

**Expected behavior**
Should work without crashing

**Screenshots**

**Additional context**
You are not converting pd.series to list. Converting series to list will fix the problem

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @rajeshdhar,

Based on the code you provided, I disagree with your assessment.

<img width="546" alt="Screen Shot 2021-11-13 at 10 52 01 AM" src="https://user-images.githubusercontent.com/18198392/141655807-74e44672-6666-4521-a95b-ed580a005b12.png">

<br/>

Perhaps you could please provide reproducible code and screenshots (as requested) to help me verify and address the Issue you describe.

Kind Regards,
KJ

**Comment by rajeshdhar** [comment]
Here you go, CSV file and code screen shots


[OHLC_File.csv](https://github.com/twopirllc/pandas-ta/files/7540247/OHLC_File.csv)
![Screenshot 2021-11-15 222321](https://user-images.githubusercontent.com/47864683/141821961-10b499f8-7c4b-4568-9df5-75a9f155bedf.jpg)
![Screenshot 2021-11-15 222444](https://user-images.githubusercontent.com/47864683/141822112-38869ec5-51c5-4c4e-8639-546b178501b3.jpg)
![Screenshot 2021-11-15 222600](https://user-images.githubusercontent.com/47864683/141822279-73ab5fdf-a468-4086-b12f-e4fa3f24c4c5.jpg)
![Screenshot 2021-11-15 222701](https://user-images.githubusercontent.com/47864683/141822448-30badfab-eba2-411f-b718-4ca1e365242f.jpg)

**Comment by twopirllc** [comment]
@rajeshdhar,

Could you please truncate and share 2 or 3 tickers worth of the CSV?

Thanks,
KJ

**Comment by rajeshdhar** [comment]
I am not sure I understand your new question "Could you please truncate and share 2 or 3 tickers worth of the CSV?"

CSV file has only 3 tickers 20MICRONS, ABB and ADANIENT. CSV has data for each ticker for date range of 01-Jan-2016 to 15-Nov-2021.

**Comment by twopirllc** [comment]
@rajeshdhar,

I accidentally submitted the "Comment" before I noticed that you shared a copy of your _csv_. Hence I deleted that comment. Apologies for the confusion. 🤦🏼‍♂️ 

Thank you for sharing the _csv_, it really helps. 😎 
KJ

**Comment by twopirllc** [comment]
Hey @rajeshdhar,

This is what I was able to accomplish.

In Jupyter:

```python
d = pd.read_csv(f"OHLCV_File.csv", parse_dates=["Date"], infer_datetime_format=True, dayfirst=True)
d.sort_values(["Stock", "Date"], ascending=[True, True], inplace=True)

_data = d.copy()
_data
```
<img width="460" alt="Screen Shot 2021-11-19 at 8 34 17 AM" src="https://user-images.githubusercontent.com/18198392/142658324-f781842b-a220-4441-b9b1-05e4a2ba15bf.png">

```python
data = []
for ticker in _data["Stock"].unique():
    df = _data[(_data["Stock"] == ticker)].copy()
    if not df.ta.datetime_ordered:
        df.set_index(pd.DatetimeIndex(df["Date"]), inplace=True, drop=True)
    df.drop(columns=["Date"], errors="ignore", inplace=True)

    df.ta.bbands(length=20, std=2, mamode="sma", append=True)
    df.ta.stc(append=True)
    data.append(df)

data
```
<img width="483" alt="Screen Shot 2021-11-19 at 8 36 22 AM" src="https://user-images.githubusercontent.com/18198392/142658856-2393f32e-2f10-4dd9-9389-58de7bba0f2a.png">

Hope this helps! Please let me know if you obtain similar results.

Thanks,
KJ
