### ISSUE TITLE
False initial signal from cross utility

### ISSUE THREAD

**Issue by lucasmlofaro** [twopirllc/pandas-ta#426]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
Version: `0.3.14b0`

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Upgraded: ✓

**Describe the bug**
Using `ta.cross()` might give a false positive on the first period in the series. The problematic line can be found [here](https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/utils/_signals.py#L79).

Using `shift(1)` to check the relative position of the two series for the previous period can cause a false positive in the first entry of final series under certain circumstances. Since the first entry of both `series_a.shift(1)` and `series_b.shift(1)` is `Nan`, the computation of `previous` will always yield `False` in the first entry (because `NaN < NaN == False`) and, when `above == False`, then `~previous` will necessarily start with `True`. This means that `~current & ~previous` can evaluate to `True` in certain circumstances (namely when `series_a <= series_b`).

**To Reproduce**
```python
import pandas
import pandas_ta as ta

series_a = pandas.Series([1, 2, 3])
series_b = pandas.Series([4, 5, 6])
cross = ta.cross(series_a, series_b, above=False)

assert cross[0]  # this should fail but doesn't
```

**Expected behavior**
The first entry in the series should always be `False`.

**Additional context**
The rationale is that, given that there is no data for previous to first entry, there should be no way to get a proper signal for the first period.

The easiest thing to do is probably just force the first entry to always be `False` explicitly.

**Comment by twopirllc** [comment]
Hello @lucasmlofaro,

Should be taken care of on the _development_ branch if you want to double check that it's working as intended.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

KJ
