### ISSUE TITLE
HWMA not included in overlap strategies

### ISSUE THREAD

**Issue by CMobley7** [twopirllc/pandas-ta#428]
It appears that the `hwma` indicator is missing from the `overlap` strategies on both main and development, https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/__init__.py#L57 and https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/__init__.py#L58 respectively. So,  it's not included when one runs `df.ta.strategy("overlap")`. Was this done on purpose?

**Comment by twopirllc** [comment]
Hello @CMobley7,

Nice catch! And it was not intentional. It was accidentally forgotten to be added. Feel free to make PR when you can! 😎 

Kind Regards,
KJ

**Comment by CMobley7** [comment]
Awesome, I'll submit one later today. Main or develop?

**Comment by twopirllc** [comment]
@CMobley7,

Either is fine.

Thanks,
KJ

**Comment by CMobley7** [comment]
Awesome, I added a PR to the development branch. I'll close this when it's merged in. Thanks for such a great library @twopirllc !
