### ISSUE TITLE
Cannot run example - Error with file looping

### ISSUE THREAD

**Issue by hhashim1** [twopirllc/pandas-ta#430]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
0.3.14b0
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
I have copied the code from example.ipynb to a local file however I am getting an error and the file keeps looping. I cant figure out the problem. This happens with the Chart Class code. Here are the screenshots of the errors.

From what I can tell, I think its the strategy part in the below line that is causing an error. I had the same problem with the All Examples file. I turned analyze=False in that file. In the PandasTA_Strategy_Examples.ipynb file, I get this error on `watch.load(verbose=True)`
`
        self.df.ta.strategy(self.strategy, verbose=self.verbose)`

**Screenshots**
![image](https://user-images.githubusercontent.com/62855649/141849112-b90ff32b-4e24-419e-9eb2-36d05178e02b.png)
![image](https://user-images.githubusercontent.com/62855649/141849140-d46188a4-abd5-421b-863a-64250c3e4acd.png)

**Comment by twopirllc** [comment]
Hello @hhashim1,

I recommend looking at the pinned Issue #181, Freeze Support Error, for the solution to your problem as indicated by the last block of lines in your last screenshot. It is a simple fix to get around this Issue.

Hope this solves your Issue. Let me know otherwise.

Kind Regards,
KJ

**Comment by pssolanki111** [comment]
multiprocessing code must always have the `ifmain` guard to avoid spawning redundant processes. 

```py
if __name__ == '__main__':
    # do multiprocessing stuff here. 
```
if you don't directly use multiprocessing, but a lib you use does (like this lib), keep that lib code within ifmain guard
@hhashim1

**Comment by hhashim1** [comment]
Thank you.
