### ISSUE TITLE
MACD is not working

### ISSUE THREAD

**Issue by graphicgeared** [twopirllc/pandas-ta#432]
macd = ta.macd(data['close'], fast=12, slow=26, signal=9, talib=True, offset=None)

Output is missing

**Comment by pssolanki111** [comment]
@twopirllc can be closed for lack of activity. They can always reopen. No one can do absolutely anything about it unless there is some solid info on what's wrong :D

**Comment by twopirllc** [comment]
@pssolanki111,

Seems @graphicgeared  figured it out and forgot to close the Issue. Reopen this Issue @graphicgeared, when you address my prior comment. 

Thanks,
KJ
