### ISSUE TITLE
How to use ADX function?

### ISSUE THREAD

**Issue by Ylelmon** [twopirllc/pandas-ta#433]
I tried so many time but it won't work

**Comment by pssolanki111** [comment]
hey @Ylelmon we'd need more information about the issue. Please try and follow the issue template if you can or at least provide reproducible code, the issue you have and any relevant environment information you might have.

Regards
P S

**Comment by Ylelmon** [comment]
this is the code im using

from get_data import get_klines
import numpy
import pandas_ta as ta
ticker ='BTCUSDT'
interval = '15m'
depth = "20 hours ago UTC+3"

df =get_klines (ticker ,interval,depth)
print(df)


data = df.ta.adx(high=df['High'], low=df['Low'], close=df['Close'], length=10, lensig=10, scalar=100, mamode=rma, drift=1, offset=0)


the error



Traceback (most recent call last):
  File "c:/Users/DELL/Desktop/begging/test.py", line 15, in <module>
    data = df.ta.adx(high=df['High'], low=df['Low'], close=df['Close'], length=10, lensig=10, scalar=100, mamode=rma, drift=1, offset=0)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas_ta\core.py", line 1406, in adx
    result = adx(high=high, low=low, close=close, length=length, lensig=lensig, mamode=mamode, scalar=scalar, drift=drift, offset=offset, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas_ta\trend\adx.py", line 24, in adx
    atr_ = atr(high=high, low=low, close=close, length=length)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas_ta\volatility\atr.py", line 24, in atr
    from talib import ATR
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\talib\__init__.py", line 52, in <module>
    from ._ta_lib import (
  File "talib\_ta_lib.pyx", line 1, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by Ylelmon** [comment]
And the same error with MACD

**Comment by twopirllc** [comment]
@Ylelmon ,

What does your:

```python
# ...

df =get_klines (ticker ,interval,depth)
print(df)
```

Print out?

**Comment by Ylelmon** [comment]
Data from binance

**Comment by twopirllc** [comment]
@Ylelmon,

Ok! Real data would be nice. I want to see the columns... Mixed cases?

The error:
```sh
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

is a Numpy Error. Not a Pandas TA Error. You should probably upgrade your numpy version. Then post some data.

Thanks,
KJ

**Comment by Ylelmon** [comment]
But I used vp =volume profile and work even without upgrade numpy

**Comment by Ylelmon** [comment]
I upgraded numpy now it work thx

**Comment by Ylelmon** [comment]
![بدون عنوان](https://user-images.githubusercontent.com/42420576/142464896-f7a0a52f-0a67-4d37-90b7-ebfa8c5e43db.png)

**Comment by twopirllc** [comment]
@Ylelmon,

Excellent! 😎 

Always check the Error for the correct package.

KJ

**Comment by Ylelmon** [comment]
![بدون عنوان](https://user-images.githubusercontent.com/42420576/142481845-b08a3834-3e8a-478c-a5b8-5402b43d320b.png)
![بدون عنوان](https://user-images.githubusercontent.com/42420576/142482010-2fa3f044-2ea0-4a72-9bb1-a5453972299e.png)
 why the output different ?

**Comment by twopirllc** [comment]
Compared to what?

**Comment by Ylelmon** [comment]
Ok thanks.

**Comment by pssolanki111** [comment]
@twopirllc sounds like to be closed.
