### ISSUE TITLE
Reflex and Trendflex Question

### ISSUE THREAD

**Issue by CMobley7** [twopirllc/pandas-ta#436]
I was comparing the implementations of `Reflex` and `Trendflex` in pandas-ta to their implementations on https://www.prorealcode.com/prorealtime-indicators/reflex-and-trendflex-indicators-john-f-ehlers/. There appears to have been an extra `0.5 *` added in front of `close[i - 1]` here, https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/trend/trendflex.py#L67. Also, the original implementation of both `Reflex` and `Trendflex` used 10 for smooth, instead of 20. Did you find 20 to provide better results?

**Comment by rengel8** [comment]
I would have to check on that again. On the first look it is simply a multiplication instead of a division by 2, but there are other deviations in the super smoother part. I will have a look at that, hopefully some time soon.

**Comment by CMobley7** [comment]
Sorry for the delayed reply, I thought that at first as well. However, line 17 here, https://www.prorealcode.com/prorealtime-indicators/reflex-and-trendflex-indicators-john-f-ehlers/, is the same for `Reflex` and `Trendflex`. However, https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/cycles/reflex.py#L66 and https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/trend/trendflex.py#L67 are different, with the latter, https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/trend/trendflex.py#L67, adding an extra `0.5` in front of `close[i - 1]`. Also, the smooth parameter, https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/cycles/reflex.py#L47 and https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/trend/trendflex.py#L47, default to 20 instead of the standard 10. Did you find 20 to provide better results?

**Comment by twopirllc** [comment]
Hello @CMobley7,

I likely screwed up something. I'll take a look as soon as I can. Apologies in advance.

KJ

**Comment by CMobley7** [comment]
@twopirllc, if I'm wrong let me know. If not, let me know if you want me to put in a pull request or if @rengel8 should do it. Also, no need to apologize. Your library is amazing. Thanks for all the time you've put into making it what it is!

**Comment by rengel8** [comment]
I once made a comparison based on output data coming from Trading View I think (SPY_D_REFLEX_TRENDFLEX.csv). Maybe we should do that again or with output from prorealcode (default parameters) to check where we are?

@CMobley7 Better results is very dependend on the situation (market etc). I would prefer to have a state that is close to the originating code and which is working like expected.

**Comment by CMobley7** [comment]
@rengel8 , it appears that the extra `0.5` in front of `close[i - 1]` was adding in the following commit, https://github.com/twopirllc/pandas-ta/commit/36ab37a1eca449478a45f67a191499cca494484a#diff-0c0c06628224d80ef2e133c513e0d14c7aa0b3d63797e3509cdf11b3022a8a92. If you want to keep `Trendflex` as close to the original code as possible, I also suggest that we remove the extra `0.5` and change the smooth parameter to 10 instead of 20. In regard to trading view, I've never used it. Is it free? If you give me a date range and a security name, I can upload the `Trendflex` numbers for both the current implementation and what I'm suggesting for you to review.

**Comment by twopirllc** [comment]
@CMobley7,

Sorry, needed to finish up the lingering PRs. I will look into these now.

KJ

**Comment by twopirllc** [comment]
Hello @CMobley7,

This should be fixed if you want to test it out. Let me know otherwise.

$ pip install -U git+https://github.com/twopirllc/pandas-ta

Thanks for the catch!
KJ

**Comment by twopirllc** [comment]
Hi @CMobley7,

Oops! Please try the _development_ branch instead. Speed improvements, docs, typing, et al.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ
