### ISSUE TITLE
Request to add random walk index indicator

### ISSUE THREAD

**Issue by bharathraja** [twopirllc/pandas-ta#439]
Can random walk index indicator be added to the panda-ta library ? thanks

References:
[Technical Indicators](https://www.technicalindicators.net/indicators-technical-analysis/168-rwi-random-walk-index)
[trading sim](https://tradingsim.com/blog/random-walk-index/)
[linnsoft](https://www.linnsoft.com/techind/random-walk-index)
[fmlabs](https://www.fmlabs.com/reference/default.htm?url=rwi.htm)

**Comment by twopirllc** [comment]
Hello @bharathraja,

Eventually. Though it looks fairly trivial for someone to implement and make a contribution instead of waiting for me to get around to it. If you are willing and want contribution credit, that would be awesome. 😎 If so, check out Issue #355 [Creating a Custom Indicator](https://github.com/twopirllc/pandas-ta/issues/355).

Kid Regards,
KJ

**Comment by bharathraja** [comment]
Thanks for sharing respective resources, @twopirllc . I am first trying to recreate it on excel to match with the chart displayed by a broker software. If it works, i will try to add it as a feature.

**Comment by rengel8** [comment]
Hello there..
I had a look at that, but did only do a quick python implementation. Below is a SpreadSheet with data and results. I think that it wouldn't be that trivial to recreate it inside of excel or thelike.
[rwi-data-plot.ods](https://github.com/twopirllc/pandas-ta/files/7677154/rwi-data-plot.ods)

![grafik](https://user-images.githubusercontent.com/34138513/145239148-7eb27f69-c224-4f11-b095-519e69724825.png)

It would be great to have some example data from other implementations as SpreadSheet or CSV.

Regards,
rengel

**Comment by twopirllc** [comment]
@bharathraja,

Random Walk has now been added to the _development_ branch.

Thanks for your patience!
KJ
