### ISSUE TITLE
THIS PACKAGE IS TOO AWESOME

### ISSUE THREAD

**Issue by Distortedlogic** [twopirllc/pandas-ta#44]
BUG: NOT ENOUGH WATER TO PUT OUT THE FIRE HERE

**Comment by twopirllc** [comment]
Thank you!

I appreciate the feedback.

KJ

**Comment by cujo0072** [comment]
I agree!! :)

**Comment by mtvu** [comment]
Completely agreed! @twopirllc. Just wondering if you have thought of the roadmap for this package. I'm happy to contribute.
