### ISSUE TITLE
Utility

### ISSUE THREAD

**Issue by Ylelmon** [twopirllc/pandas-ta#440]
Sorry but it might be weird question but how to use Utility ? Is like 

If EMA 50 cross ema100 buy or something different?

**Comment by twopirllc** [comment]
Hello @Ylelmon,

In short yes. They are basic methods to determine how two series interact. This Issue [#406 ](https://github.com/twopirllc/pandas-ta/issues/406) shows an example as well as an example using ```ta.xsignals``` instead.

Hope this helps!
KJ

**Comment by Ylelmon** [comment]
Oh thinks
