### ISSUE TITLE
Zig Zag Indicator

### ISSUE THREAD

**Issue by AureliusMarcusHu** [twopirllc/pandas-ta#443]
Hi, 
pandas_ta is a fantastic project, thanks for sharing it.

Maybe it si a good idea to implement the Zig-Zag indicator.
It is a indicator that is nog based on periods but on % of change.
On this way will be easy to find the higest and lowest pivot points in the past.
It is also great to see the trend is up or down.
In the link below the indicator is explained:
[https://www.investopedia.com/terms/z/zig_zag_indicator.asp](url)

**Comment by twopirllc** [comment]
Hello @AureliusMarcusHu,

It's on the list. Hopefully someone can help contribute so it can be added quicker. 😎 

Kind Regards,
KJ

**Comment by puneeth714** [comment]
Did anyone working on Zig Zag indicator ?

**Comment by twopirllc** [comment]
Hello @puneeth714,

No one has submitted a working PR with it implemented yet. If you are feeling up to it, see #355 Creating a Custom Indicator on how to integrate it. Your contribution would be greatly appreciated. 😎 

Thanks,
KJ

**Comment by jonathandumaresq** [comment]
Not a direct code, but I use this once for a project and look to be working great. Maybe a start ?

https://github.com/djoffrey/HarmonicPatterns

**Comment by aligheshlaghi97** [comment]
Hi there!
That's an honor for me using pandas-ta library regularly and this motivated me to participate in its development. I developed zigzag indicator to resolve #443 
If there was any problems or feedback about it, please do not hesitate to get in touch as I am always love to learn more.
