### ISSUE TITLE
get_all_indicators

### ISSUE THREAD

**Issue by ajit1310** [twopirllc/pandas-ta#444]
Hi ,  can you add a function to get all the available indicator .
Thanks
Ajit

**Comment by twopirllc** [comment]
Hello @ajit1310,

It's covered under [Pandas TA Strategies](https://github.com/twopirllc/pandas-ta#pandas-ta-strategies) on the README. Also see [Pandas TA Strategy Examples](https://github.com/twopirllc/pandas-ta/blob/main/examples/PandasTA_Strategy_Examples.ipynb) on ways to further customize Pandas TA Strategies.


Kind Regards,
KJ
