### ISSUE TITLE
Specifying or detecting the order of data?

### ISSUE THREAD

**Issue by akovachev** [twopirllc/pandas-ta#45]
Hello,

First, thank you for this awesome package! It's nicely done!

I have the following issue - The data is in reverse order on my end, i.e. most recent candle is index 0.

For example:
```
>>> data.SPY
           date    open    high     low   close       volume
0    2020-05-06  288.04  288.45  283.87  284.34   67758728.0
1    2020-05-05  286.64  289.25  283.71  286.19   79330400.0
2    2020-05-04  280.74  283.90  279.13  283.57   80873200.0
3    2020-05-01  285.31  290.66  281.52  282.79  125063900.0
4    2020-04-30  291.71  293.32  288.59  290.48  122901700.0
...         ...     ...     ...     ...     ...          ...
6862 1993-02-04   44.97   45.09   44.47   45.00     531500.0
6863 1993-02-03   44.41   44.84   44.38   44.81     529400.0
6864 1993-02-02   44.22   44.38   44.13   44.34     201300.0
6865 1993-02-01   43.97   44.25   43.97   44.25     480500.0
6866 1993-01-29   43.97   43.97   43.75   43.94    1003200.0

[6867 rows x 6 columns]
```

And e.g. when I do atr, it seems that it goes in reverse order, filling most recent with NaN:

```
>>> data.SPY.ta.atr()
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...   
6862    0.556601
6863    0.565054
6864    0.580380
6865    0.552330
6866    0.545352
Name: ATR_14, Length: 6867, dtype: float64
```

Now I know that the easiest thing in the world is to reverse the data with [::-1], but still... would be great if we could specify the order somehow, or even better - detect it form the date field.

**Comment by twopirllc** [comment]
Hello @akovachev,

Thank you!  Glad it is working out for you!

Index order agnostic was by design originally.  I figured one would source and clean their data before applying these indicators (features).  It seems like a good idea.  But I wonder how many would find this useful?  After all, it is simple to reverse.

Thanks,
KJ

**Comment by akovachev** [comment]
Thank you for the update @twopirllc,

It's simply prone to error, and financial data is often in reverse index order.

Could it be done similar to "adjusted" property? i.e. how hard is it to have ta.reversed property?
I could spend a few cycles to implement that if you approve of the idea (we'll need to agree on approach).

If not... brainstorming here... Perhaps as a sanity check it could at least alert if time/date fields are going the wrong way?

Regards,
AK

**Comment by twopirllc** [comment]
@akovachev,

I like that idea of a ```reverse``` property to just reverse it.  Plus it should be simple implementation.  Also one of the reasons I made it order agnostic is because the indicators can run on series and time-series alike.

Also a sanity check might be good as well if it is not annoying.

Thanks,
KJ

**Comment by robertddewey** [comment]
I just noticed this as well. I am very thankful for this package though, and the documentation is quite well done. But it wasn't clear that a reverse order was used. I just reversed my data frame to fix

**Comment by twopirllc** [comment]
Thanks!

Order is not imposed and has been the responsibility of the user.

KJ

**Comment by twopirllc** [comment]
@akovachev  and @robertddewey,

So I have created two new ```ta``` properties:
* A ```reverse``` property which returns as new DataFrame that is reversed using df.iloc[::-1] irregardless of the type of index.
* A ```datetime_ordered``` property which returns _True_ or _False_ if the index is of type datetime64 and that it is ordered.

Just putting some finishing touches and adding testing before updating the Github repository.  I think this is a balanced approach, what do you think?

Thanks,
KJ

**Comment by akovachev** [comment]
> @akovachev and @robertddewey,
> 
> So I have created two new `ta` properties:
> 
> * A `reverse` property which returns as new DataFrame that is reversed using df.iloc[::-1] irregardless of the type of index.
> * A `datetime_ordered` property which returns _True_ or _False_ if the index is of type datetime64 and that it is ordered.
> 
> Just putting some finishing touches and adding testing before updating the Github repository. I think this is a balanced approach, what do you think?
> 
> Thanks,
> KJ

That sounds great! Thank you KJ!

I would definitely use the ``reverse`` property.

Not so sure about the ``datetime_ordered`` - Since I'm not using the date as index, I would prefer to be able to set which column holds the actual date.

**Comment by twopirllc** [comment]
@akovachev,

Cool.  Hope it helps.  The ```datetime_ordered``` property is just a helper method, it's not required.  You can use it to check if your index is ```datetime64``` and ordered normally.  If it's not, then you can reverse and set your index however you like.

Something to the effect of:
```python
if not data.ta.datetime_ordered:
    data = data.ta.reverse
    data.set_index('date', inplace=True)
```

Thanks,
KJ
