### ISSUE TITLE
td_seq indicator datetime index and append

### ISSUE THREAD

**Issue by yhmickey** [twopirllc/pandas-ta#450]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
pandas-ta 0.3.14b0
pandas 1.0.3
numpy 1.18.2
python 3.7

**Do you have _TA Lib_ also installed in your environment?**
yes

**Describe the bug**

td_seq returns lost the datetime index. Thus the ta.td_seq(append=True) can not work correctly.

**Solution** 
[td_seq.py  line 30] 
td_num = Series(td_num) 

change to:
td_num = Series(td_num,index=series.index)

**Comment by twopirllc** [comment]
Hello @yhmickey,

When using the Standard Convention call (like TA Lib), ```ta.td_seq()```, ```append``` is not an argument and doesn't know how to append it to the current DataFrame. However when you call **td_seq** using the DataFrame Extension Convention, ```df.ta.td_seq(append=True)```, it will append it to the current DataFrame. See Issue with a working example #421.

Make a PR for the datetime index fix if it is working for you or at least fix your local copy in the mean time.

Also, **td_seq** has a known speed issue #367 and needs to be reworked. 

Kind Regards,
KJ

**Comment by yhmickey** [comment]
Thank you @twopirllc ,

When I use the original code and try the example #421 , the td_seq can not append.  Thus ， I check the code and fix my local copy and it works for me.
Maybe the version of pandas make this problem, I guess.
 
Original:

![test](https://user-images.githubusercontent.com/34559558/145489734-9f639246-3dea-48d5-a0df-3f69830ad811.PNG)

Fixed:
Change:  td_num = Series(td_num,index=series.index)

![test2](https://user-images.githubusercontent.com/34559558/145490506-fc0fb7ff-a9f0-4242-83b6-a80cb0b87de2.PNG)

Regards,
yhmickey

**Comment by twopirllc** [comment]
Hi @yhmickey,

> Maybe the version of pandas make this problem, I guess.

Yeah, that might be possible. I recommend trying to the _development_ branch then. Off the top of my head, I do not recall if it fixes the Issue. But if you install it and test it and let me know, I would appreciate it.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by yhmickey** [comment]
Hi @twopirllc ,

The issue is solved in the development branch. 

Thank you!
yhmickey

**Comment by joseamador0898** [comment]
Hi, same issue, I see:

![Index issue](https://github.com/user-attachments/assets/5a25c04f-bba5-446b-a8a3-9d4fc6cf75bb)

Which is funny as it would be impossible to append if the index is dropped
