### ISSUE TITLE
ADD KDJ ，BRAR，Keltner Channel     func

### ISSUE THREAD

**Issue by homily** [twopirllc/pandas-ta#46]
Hello my friend

Thank you very much for creating such a very convenient library.

I often use some indicators
KDJ, Brar and Aberration(Keltner channel) related libraries.

I implemented its algorithm using pandas.

so, I hope  can be add  to Panda-TA, 
can you help me? thank you!

### BRAR
```
    #BRAR

    df.columns = ['time','open','high','low','close','volume']
    df['HO']=df['high']-df['open']
    df['OL']=df['open']-df['low']
    df['HCY']=df['high']-df['close'].shift(1)
    df['CYL']=df['close'].shift(1)-df['low']
    df.loc[df['HCY']<0,'HCY']=0
    df.loc[df['CYL']<0,'CYL']=0
    df['ar']=df['HO'].rolling(26).sum()/df['OL'].rolling(26).sum()*100
    df['br']=df['HCY'].rolling(26).sum()/df['CYL'].rolling(26).sum()*100
```
### BIAS
```
    df.columns = ['time','open','high','low','close','volume']
    result_MA=df.ta(kind='sma',length=MA_lengh)
    C=df['close']
    BIAS=(C-result_MA)/result_MA
```
### KDJ
```
    #KDJ
    N=44
    M1=9
    H6['llv_low']=H6['low'].rolling(N).min()
    H6['hhv_high']=H6['high'].rolling(N).max()
    H6['rsv']=(H6['close']-H6['llv_low'])/(H6['hhv_high']-H6['llv_low'])
    H6['k']=H6['rsv'].ewm(adjust=False,alpha=1/M1).mean()
    H6['d']=H6['k'].ewm(adjust=False,alpha=1/M1).mean()
    H6['j']=3*H6['k']-2*H6['d']
```

### Aberration
```
def Aberration(RAW,MA_lengh,ATR_lengh):
    df = pd.DataFrame(RAW)
    df.columns = ['time','open','high','low','close','volume']
    JG=(df['high']+df['low']+df['close'])/3
    ZG=df.ta(kind='sma',close=JG,length=MA_lengh)
    ATR=df.ta(kind='ATR',length=ATR_lengh)
    SG=ZG+ATR
    XG=ZG-ATR
   
    result = pd.concat([ZG,SG,XG,ATR], axis=1)

```

**Comment by twopirllc** [comment]
Hello @homily,

Thanks for trying the library and that you find it useful.  Sure.  We can add those to the library.  Could you please tell me what each category they fall under: ```momentum, overlap, performance, statistics, trend, volatility, or volume```?

Thanks,
KJ

**Comment by homily** [comment]
BIAS-momentum
KDJ-momentum
Aberration-trend (other)
BRAR- (other)
Or create a new folder name 'other' 

For Aberration just return(SG,ZG,XG)
It is an improved version based on 'Keltner channels'

[https://www.tradingview.com/ideas/keltnerchannels/?solution=43000502266](https://www.tradingview.com/ideas/keltnerchannels/?solution=43000502266)

Keltner Channels are volatility-based envelopes set above and below an exponential moving average. This indicator is similar to Bollinger Bands, which use the standard deviation to set the bands. Instead of using the standard deviation, Keltner Channels use the Average True Range (ATR) to set channel distance. The channels are typically set two Average True Range values above and below the 20-day EMA. The exponential moving average dictates direction and the Average True Range sets channel width. Keltner Channels are a trend following indicator used to identify reversals with channel breakouts and channel direction. Channels can also be used to identify overbought and oversold levels when the trend is flat.

In his 1960 book, How to Make Money in Commodities, Chester Keltner introduced the “Ten-Day Moving Average Trading Rule,” which is credited as the original version of Keltner Channels. This original version started with a 10-day SMA of the typical price {(H+L+C)/3)} as the centerline. The 10-day SMA of the High-Low range was added and subtracted to set the upper and lower channel lines. Linda Bradford Raschke introduced the newer version of Keltner Channels in the 1980s. Like Bollinger Bands, this new version used a volatility based indicator, Average True Range (ATR), to set channel width. StockCharts.com uses this newer version of Keltner Channels.

[https://stockcharts.com/acp/?s=%24BTCUSD](https://stockcharts.com/acp/?s=%24BTCUSD)

Keltner channels= MA(EMA)+-ATR
Aberration  = MA(EMA)+- Std

**Comment by twopirllc** [comment]
@homily,

I'll see what I can get done.

Thanks,
KJ

**Comment by twopirllc** [comment]
@homily,

So I made a rough draft of them in TradingView to get an idea of what they looked liked before I put them into ```pandas_ta```.  The default values are in _()_ next to the indicator name.  Do these look like accurate representations visually?

![homily indicators](https://user-images.githubusercontent.com/18198392/81747836-a3407000-945d-11ea-9de9-c5402e341ed8.png)

Thanks,
KJ

**Comment by twopirllc** [comment]
@homily,

All indicators added to ```pandas_ta```.

Thanks,
KJ

**Comment by mwpwalshe** [comment]
How can I generate signal or trade BRAR?
