### ISSUE TITLE
tvmode value to be declared first so that default tvmode is always true

### ISSUE THREAD

**Issue by khannavivek** [twopirllc/pandas-ta#463]
https://github.com/twopirllc/pandas-ta/blob/bc3b292bf1cc1d5f2aba50bb750a75209d655b37/pandas_ta/trend/cksp.py#L22

Hi,

As per the function docstring default value of tvmode is true, but the default value passed as a function param is None and after the declaration of dependent variables then tvmode value is assumed to default in case of none,

![image](https://user-images.githubusercontent.com/62461665/148568556-43090293-1dfb-461d-9cf4-6296550cdbc9.png)

can we move line 22 to line 10 as per the attached screenshot?

**Comment by twopirllc** [comment]
Hello @khannavivek,

Doh! Good catch. If you haven't already, update your local copy in the mean time.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @khannavivek,

This should be fixed if you want to test it out. Let me know otherwise. 

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Thanks for the catch!
KJ
