### ISSUE TITLE
Pandas_TA and Pandas performance with Intel Modin

### ISSUE THREAD

**Issue by krazykoder** [twopirllc/pandas-ta#464]
**Pandas_TA and Pandas performance with Intel Modin.**
I consider myself a newbie in python. I have been using pandas_ta and pandas in general for a while now. 

I saw on Intel's website that `modin` library with Intel's optimization can speed up performance of pandas significantly. And all of it can be achieved by using modin.pandas instead of pandas as below. 

```python
# import pandas as pd
import modin.pandas as pd
```

I am wondering if this improvement of pandas base library will have any improvement on pandas_ta package as well. Is there a way to test it and anyone can guide us how to do it. 

Thanks for the support. 
towshif

**Comment by twopirllc** [comment]
Hello @krazykoder,

> I consider myself a newbie in python. I have been using pandas_ta and pandas in general for a while now.

Nice! 😎 

I've heard of ```modin``` but have not had time to play with it.

> I am wondering if this improvement of pandas base library will have any improvement on pandas_ta package as well. Is there a way to test it and anyone can guide us how to do it.

Honestly, I don't know. 🤷🏼‍♂️ I am curious as well. Perhaps someone else has done so and they could share what they have done.

Kind Regards,
KJ

**Comment by pssolanki111** [comment]
the short answer is, It can.

I've tried modin, and for small datasets, the performance gain was minimal and not very significant.

but as i kept increasing the dataset sizes during the benchmarks, the performance gain kept getting better. In my (limited) testing of modin, it appeared to make things a bit faster.

Beware that modin needs either a ray or dask backend to work and sometimes they both can be a pain to setup. (for me, it was an easy process fortunately but I've come across people failing to make modin even run)

@twopirllc @krazykoder consider closing this issue too.

**Comment by twopirllc** [comment]
Heya @krazykoder,

I took a look at some of the **modin** documentation last night. It looks promising.

While they do not currently support Pandas' [register_dataframe_accessor ](https://github.com/modin-project/modin/issues/3044) which is the core of Pandas TA. I think you can apply **modin** on individual indicators. 🤔  But I haven't tested that. 🤷🏼‍♂️ In terms of supporting it, it's not something I am looking to take on without another developer wanting to help.

KJ

**Comment by krazykoder** [comment]
Hi @twopirllc and @pssolanki111 
Thanks for the response and closing this issue. I really value the inputs of the supporters of this project. 👍 

thanks
KK
