### ISSUE TITLE
Problem with strategy (all)

### ISSUE THREAD

**Issue by hn2** [twopirllc/pandas-ta#466]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
Yes
TA-Lib                             0.4.17

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
When trying to add all indicators (ta.AllStrategy) to my dataframe I get:

```sh
Traceback (most recent call last):
  File "C:\Users\hanna\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\hanna\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\hanna\Anaconda3\lib\site-packages\pandas_ta\core.py", line 467, in _mp_worker
    return getattr(self, method)(*args, **kwargs)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\pandas_ta\core.py", line 874, in cdl_pattern
    result = cdl_pattern(open_=open_, high=high, low=low, close=close, name=name, offset=offset, **kwargs)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\pandas_ta\candles\cdl_pattern.py", line 64, in cdl_pattern
    pattern_result = Series(pattern_func(open_, high, low, close, **kwargs) / 100 * scalar)
  File "_abstract.pxi", line 352, in talib._ta_lib.Function.__call__
  File "_abstract.pxi", line 383, in talib._ta_lib.Function.__call_function
  File "C:\Users\hanna\Anaconda3\lib\site-packages\talib\__init__.py", line 24, in wrapper
    return func(*args, **kwargs)

TypeError: Argument 'open' has incorrect type (expected numpy.ndarray, got NoneType)
```

As you can see it is probably due to cdl_pattern error.

When I switch to ta.CommonStrategy I get:

Index(['open', 'high', 'low', 'close', 'volume', 'SMA_10', 'SMA_20', 'SMA_50',
       'SMA_200', 'VOL_SMA_20'],

I get 6 indicators(sma) added to my dataframe.
Is this the expected behavior? Only 6  common indicators?

**Comment by twopirllc** [comment]
Hello @hn2,

> When I switch to ta.CommonStrategy I get:

```sh
Index(['open', 'high', 'low', 'close', 'volume', 'SMA_10', 'SMA_20', 'SMA_50',
'SMA_200', 'VOL_SMA_20'],
```

> I get 6 indicators(sma) added to my dataframe.
> Is this the expected behavior? Only 6 common indicators?

Yes. This is the correct behavior for the _Common Strategy_ (as defined below). These are the indicators used the be financial news media (CNBC, Bloomberg, et al...) You are welcome to submit more Builtin Strategies if you want to share with the community.

https://github.com/twopirllc/pandas-ta/blob/b92e45c0b8f035ac76292f8f130be32ec49b2ef4/pandas_ta/core.py#L92-L110

<br/>

Could you please share reproducible code that _was_ requested in the bug report?

According to the Stack Trace, it is **not** a Pandas TA problem. The problem has to do with your "open" data type: ```TypeError: Argument 'open' has incorrect type (expected numpy.ndarray, got NoneType)```. For some reason, your "open" data type is not like your "close" and "volume" data types (since those worked fine with the _Common Strategy_).

Kind Regards,
KJ

**Comment by hn2** [comment]
I believe that it has to do with the fact the pandas-ta candlestick patterns are build on top of ta-lib, and ta-lib is probably expecting a different data type. Could that be the reason for the error?

**Comment by hn2** [comment]
I am still not sure how to resolve it though. I tried converting to nparray but it didn't work.

**Comment by hn2** [comment]
`class technical_features:

    def __init__(self,
                 security,
                 open_name,
                 high_name,
                 low_name,
                 close_name,
                 volume_name):

        open_price = security[open_name].values
        high_price = security[high_name].values
        low_price = security[low_name].values
        close_price = security[close_name].values

        security['open'] = np.array(open_price)
        security['high'] = np.array(high_price)
        security['low'] = np.array(low_price)
        security['close'] = np.array(close_price)

        print('Type')
        print(type(security['open']))

        
    def get_indicators_all(self):
       
        security.ta.strategy('all')

        
        print(security.columns)
        print(security.ta.categories)
        print(security)

        return security`

**Comment by hn2** [comment]
The type is this:
Type
<class 'pandas.core.series.Series'>
for open and for close.

**Comment by twopirllc** [comment]
> I believe that it has to do with the fact the pandas-ta candlestick patterns are build on top of ta-lib, and ta-lib is probably expecting a different data type. Could that be the reason for the error?

No. It's a Type Error as the stack trace says. Again, it is **not** a Pandas TA error.

Thanks for sharing "some" code this time. Please share your input data or how you read your data in? Also please provide a small csv sample (around 300 rows should do).

What type is ```security```? A Pandas DataFrame or a dict? You are not clear on that in your code since there are no type hints.  When  calling: ```security.ta.strategy('all')```, ```security``` needs to be a DataFrame.

Also, you shouldn't have to use either of these:
```python
        open_price = security[open_name].values  # This converts to numpy values
        security['open'] = np.array(open_price) # This line is redundant
```

<br/>

Do you have ```yfinance``` installed?  (```pip install yfinance```) If so, you should be able to do the following:

```python
import pandas as pd
import pandas_ta as ta

security = pd.DataFrame()
security = security.ta.ticker("aapl", period="1y")
security.ta.strategy(timed=True)

print(security)
print(security.columns)
```
<img width="982" alt="Screen Shot 2022-01-20 at 8 36 43 AM" src="https://user-images.githubusercontent.com/18198392/150381945-8c7c47ba-33d6-4da5-add4-833c8f412e76.png">

<br/>

Would be interested in your output with the code I provided.

Kind Regards,
KJ

**Comment by hn2** [comment]
You code did not run for me. Same error:
TypeError: Argument 'open' has incorrect type (expected numpy.ndarray, got NoneType)
I have an older pandas version (I need it to work with quantconnect).
pandas  0.25.3
numpy   1.19.5
TA-Lib    0.4.17

**Comment by twopirllc** [comment]
Screenshot?

**Comment by hn2** [comment]
![image](https://user-images.githubusercontent.com/7550282/150389123-a2e44997-4fa3-4b49-911c-d5c09db8e525.png)

**Comment by twopirllc** [comment]
Not just the error... the code a well.

**Comment by hn2** [comment]
![image](https://user-images.githubusercontent.com/7550282/150389790-dbfaa761-b2b8-4f44-a91f-4b4ddd12be34.png)

**Comment by twopirllc** [comment]
Is there anything in ```security```?

```python
import pandas as pd
import pandas_ta as ta

security = pd.DataFrame()
security = security.ta.ticker("aapl", period="1y")
print(security)
print(security.dtypes)
```

**Comment by twopirllc** [comment]
```pip install yfiance```

**Comment by twopirllc** [comment]
Also upgrade Pandas TA. 

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Has other bug fixes and new features. I am changing ```strategy()``` to ```study()``` but both will work.

**Comment by twopirllc** [comment]
Your local environment could be corrupted... it happens sometimes.

**Comment by hn2** [comment]
That wouldn't help.
I believe that the problem has to do with TA-Lib.
Are you sure that you are getting all 61 TA-Lib candlestick patterns?
My guess is that you are not.

**Comment by twopirllc** [comment]
I am sorry solutions I have presented have not solved your issue.

> I believe that the problem has to do with TA-Lib.
I agree. I would recreate the local environment, usually solves most of my problems. Also time permitting, I am trying to implement numpy versions of TA Lib and hopefully the candles so TA Lib is optional.

> Are you sure that you are getting all 61 TA-Lib candlestick patterns?

Yes, I am sure. In fact, 62.

<img width="525" alt="Screen Shot 2022-01-20 at 10 21 38 AM" src="https://user-images.githubusercontent.com/18198392/150398459-9e298d56-2abc-4454-8dde-e85720998491.png">

<img width="526" alt="Screen Shot 2022-01-20 at 10 20 05 AM" src="https://user-images.githubusercontent.com/18198392/150398498-2d6d179f-0fce-43f4-b5a8-622ab3854743.png">

<br/>

KJ

**Comment by hn2** [comment]
What version of TA-Lib are you using?

**Comment by twopirllc** [comment]
<img width="208" alt="Screen Shot 2022-01-20 at 10 32 31 AM" src="https://user-images.githubusercontent.com/18198392/150400446-04f199ca-5c24-4cff-acf7-0006a5f0147b.png">

**Comment by twopirllc** [comment]
> I wish that you could implement everything including candle patterns in pure python without TA-Lib which is a pain to install.

I know. That's partly the reason this package exists.

**Comment by hn2** [comment]
I upgraded my ta-lib. I now get this error:

<ipython-input-15-6eaa48f7e17b> in get_indicators_all(self)
     81         # self.security.ta.strategy(ta.CommonStrategy)
     82 
---> 83         security.ta.strategy('all')
     84 
     85         # # Use verbose if you want to make sure it is running.

~\Anaconda3\lib\site-packages\pandas_ta\core.py in strategy(self, *args, **kwargs)
    790 
    791         # Apply prefixes/suffixes and appends indicator results to the  DataFrame
--> 792         [self._post_process(r, **kwargs) for r in results]
    793 
    794         if verbose:

~\Anaconda3\lib\site-packages\pandas_ta\core.py in <listcomp>(.0)
    790 
    791         # Apply prefixes/suffixes and appends indicator results to the  DataFrame
--> 792         [self._post_process(r, **kwargs) for r in results]
    793 
    794         if verbose:

~\Anaconda3\lib\site-packages\tqdm\std.py in __iter__(self)
   1178 
   1179         try:
-> 1180             for obj in iterable:
   1181                 yield obj
   1182                 # Update and possibly print the progressbar.

~\Anaconda3\lib\multiprocessing\pool.py in <genexpr>(.0)
    318                     result._set_length
    319                 ))
--> 320             return (item for chunk in result for item in chunk)
    321 
    322     def imap_unordered(self, func, iterable, chunksize=1):

~\Anaconda3\lib\multiprocessing\pool.py in next(self, timeout)
    733         if success:
    734             return value
--> 735         raise value
    736 
    737     __next__ = next                    # XXX

Exception: inputs are all NaN

This is my data:

   open      high       low     close  volume
0    1.151420  1.151915  1.150835  1.151040     0.0
1    1.151040  1.155060  1.145575  1.146480     0.0
2    1.146480  1.149190  1.143950  1.147080     0.0
3    1.147080  1.147700  1.137870  1.139860     0.0
4    1.139860  1.143285  1.135630  1.137515     0.0
..        ...       ...       ...       ...     ...
995  1.131090  1.133190  1.128465  1.129500     0.0
996  1.129515  1.136490  1.129005  1.136155     0.0
997  1.135980  1.136255  1.134955  1.135365     0.0
998  1.135385  1.135825  1.128505  1.133005     0.0
999  1.132985  1.137550  1.131305  1.136600     0.0

**Comment by hn2** [comment]
I guess that the dataframe needs datetimeindex?
Is there a workaround?

**Comment by twopirllc** [comment]
@hn2,

> I guess that the dataframe needs datetimeindex?

No. The only indicator that requires it is: **vwap**.

How come you use time invariant data?

> Is there a workaround?
Yes. You can _exclude_ a list of indicators you don't want from strategy. 

```python
import pandas as pd
import pandas_ta as ta

security = pd.DataFrame()
security = security.ta.ticker("aapl", period="1y")

vwap_ = ["vwap"]  # 
security.ta.strategy(exclude=vwap_, timed=True)

print(security)
print(security.columns)

# help(security.ta.strategy)  # Documentation on the strategy method
```

<hr/>

Also, since you are using Windows and _strategy_ (which uses multiprocessing), you might get a ```freeze_support error when creating a strategy``` Pinned Issue https://github.com/twopirllc/pandas-ta/issues/181

<hr/>

Here are others ways to get [help](https://github.com/twopirllc/pandas-ta#quick-start). I recommend reading _Quick Start_, _Help_ **and** _Issues_.

![Screen Shot 2022-01-21 at 9 43 06 AM](https://user-images.githubusercontent.com/18198392/150575058-d7ddcd43-9622-4d5d-932d-20da34531d1a.png)

KJ

**Comment by hn2** [comment]
Thank you

**Comment by hn2** [comment]
Is there a way to easily exclude the entire volume group of indicators?
