### ISSUE TITLE
td sequence indicator not working

### ISSUE THREAD

**Issue by ismail-invict** [twopirllc/pandas-ta#477]
df.ta.td_seq() does not generate valid result, resulting columns are all null?

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
version: 0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
yes

**Comment by twopirllc** [comment]
Hello @ismail-invict,

This was a known bug and resolved in the _Latest Version_. Please upgrade as mentioned in the Bug Report you filled out.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Let me know if this doesn't resolve the Issue.

Kind Regards,
KJ

**Comment by ismail-invict** [comment]
I uninstalled manually package and run below command
$ pip install -U git+https://github.com/twopirllc/pandas-ta

when i use related function as below, generated 2 colums are fully null **(td_seq_up, td_seq_dn)**, so still no working

df.ta.td_seq()

**Comment by ismail-invict** [comment]
with dev branch, it is working thnks

**Comment by twopirllc** [comment]
@ismail-invict,

Great!

> But I am curious as to why you are getting all NaNs? Is your DataFrame empty to begin with? You provided no reproducible code nor screenshots as requested in the Bug form, so I have no way to tell what you are doing incorrectly.

Thanks,
KJ
