### ISSUE TITLE
How to compute the band of VWAP?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [twopirllc/pandas-ta#479]
**Which version are you running? The latest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
0.3.14b0
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
...
TA-Lib                  0.4.21
...
```

**Did you upgrade? Did the upgrade resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**

The help only shows VWAP. But there is no mentioning the bands. On the 2nd link, it mentions `sigma = sqrt(sum_{i=1}^N(x_i-x_bar)^2/N)`. But this is not weighted by the volume. Since the x_bar is averaged using volume, should the computation of sigma also weighted?

```python
vwap(high, low, close, volume, anchor=None, offset=None, **kwargs)
    Volume Weighted Average Price (VWAP)

    The Volume Weighted Average Price that measures the average typical price
    by volume.  It is typically used with intraday charts to identify general
    direction.

    Sources:
        https://www.tradingview.com/wiki/Volume_Weighted_Average_Price_(VWAP)
        https://www.tradingtechnologies.com/help/x-study/technical-indicator-definitions/volume-weighted-average-price-vwap/
        https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:vwap_intraday

    Calculation:
        tp = typical_price = hlc3(high, low, close)
        tpv = tp * volume
        VWAP = tpv.cumsum() / volume.cumsum()

    Args:
        high (pd.Series): Series of 'high's
        low (pd.Series): Series of 'low's
        close (pd.Series): Series of 'close's
        volume (pd.Series): Series of 'volume's
        anchor (str): How to anchor VWAP. Depending on the index values, it will
            implement various Timeseries Offset Aliases as listed here:
            https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases
            Default: "D".
        offset (int): How many periods to offset the result. Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.Series: New feature generated.
```

**To Reproduce**
NA

**Expected behavior**
See above.

**Screenshots**
NA

**Additional context**
NA

**Comment by twopirllc** [comment]
Hello @prRZ5F4LXZ,

This sounds like a good enhancement to add. I do not know the answer at this time. But hopefully someone can contribute in the mean time.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @prRZ5F4LXZ,

Have you had an opportunity to test it the **vwap** bands graciously provided by @austinvdubs that's on the _development_ branch? If not, please give it a go so I can close the request.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards
KJ

**Comment by Karlheinzniebuhr** [comment]
> Hello @prRZ5F4LXZ,
> 
> Have you had an opportunity to test it the **vwap** bands graciously provided by @austinvdubs that's on the _development_ branch? If not, please give it a go so I can close the request.
> 
> ```shell
> $ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
> ```
> 
> Kind Regards KJ

is there documentation on how to enable the bands?
