### ISSUE TITLE
Schaff Trend Cycle: stc - Cannot Adjust tclen=stc_tclen

### ISSUE THREAD

**Issue by CoinHood** [twopirllc/pandas-ta#480]
**Which version are you running? = 0.3.14b0

The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version) 
```

**Do you have _TA Lib_ also installed in your environment?** 
YES = TA-Lib                 0.4.21
```sh
$ pip list
```

**Did you upgrade? Did the upgrade resolve the issue?** NOP
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
The indicator (stc) appears to be hard codes for tclen=10 which is he default.
No matter what value I enter the results are the same. Even when I place quotes around the number no error is produces. Seems like this parameter is being ignored. 

**To Reproduce**
```python
stcy = df.ta.stc(tclen=10, fast=26, slow=12,append=True)
stcy = df.ta.stc(tclen=26, fast=26, slow=12,append=True)

stcy = df.ta.stc(tclen='10', fast=26, slow=12,append=True)
```

**Expected behavior**
STC_10_12_26_0.5 
and
STC_26_12_26_0.5 with different values.

**Screenshots**
See attached screenshot
![pandas_ta(stc)](https://user-images.githubusercontent.com/93855887/152451648-38425141-343a-4ffb-8ac0-4e589066e88c.png)

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hey @CoinHood 

Doh! That is undesirable, isn't it? Thanks for bringing it to my attention. Hopefully someone can patch it soon. Otherwise I will let you know when it's testable on the _development_ branch.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @CoinHood,

So, if you could check out **stc** on _development_ branch and confirm that it's working, that would be great. There are also many other bug fixes, speed improvements, documentation and typing.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ
