### ISSUE TITLE
watchlist import

### ISSUE THREAD

**Issue by BenjaminVermeulen** [twopirllc/pandas-ta#483]
Hello,
First of, pandas-ta is a great package and it helped me tremendously with my first projects. 
As described as a possiblity in the doc watchlist.py, I was not able to import the watchlist library. Hence, I copied the watchlist.py file in my project directory. 

I followed the initial structure of [watchlist.py](https://github.com/twopirllc/pandas-ta/blob/main/examples/PandasTA_Strategy_Examples.ipynb): starting at AV, data_source to creating the watchlist. however, when running watch.load(), the code does not terminate and runs forever showing the error message of freeze_support().... . I would appreciate any help in the interpretation of this particular issue. Thank you!
Best,
Ben

**Comment by twopirllc** [comment]
Hello @BenjaminVermeulen,

Thanks!

Did you solve your own Issue?

The [Freeze Support](https://github.com/twopirllc/pandas-ta/issues/181) Issue is not a Pandas TA bug.

Kind Regards,
KJ
