### ISSUE TITLE
Please install TA-Lib to use 2crows. (pip install TA-Lib) message ...

### ISSUE THREAD

**Issue by tbeesofar** [twopirllc/pandas-ta#484]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
yes
![image](https://user-images.githubusercontent.com/63505156/152672264-f1c475fd-8b8f-4005-bf26-21c236425e35.png)

**Did you upgrade? Did the upgrade resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```
Yes.. i have installed talib using the updated version only as mentioned in the readme...

**Describe the bug**
[A clear and concise description of what the bug is.] 

i am simply trying to import ticker data from yfinance and using df.ta.strategy(ta.AllStrategy) to build all the indicators. However, i am getting messages saying: **Please install TA-Lib to use 2crows. (pip install TA-Lib)** 

first 7 lines of the output of df.ta.strategy(ta.AllStrategy)

**0it [00:00, ?it/s][X] Please install TA-Lib to use 2crows. (pip install TA-Lib)
[X] Please install TA-Lib to use 3blackcrows. (pip install TA-Lib)
[X] Please install TA-Lib to use 3inside. (pip install TA-Lib)
[X] Please install TA-Lib to use 3linestrike. (pip install TA-Lib)
[X] Please install TA-Lib to use 3outside. (pip install TA-Lib)
[X] Please install TA-Lib to use 3starsinsouth. (pip install TA-Lib)
[X] Please install TA-Lib to use 3whitesoldiers. (pip install TA-Lib)**

**To Reproduce**
Provide sample code.
Code:
(https://colab.research.google.com/drive/1eGviU_45HrZLDj_hSHLvXkTvw2gln-vd?usp=sharing)

**Expected behavior**
My expectation is what is written in the readme that "Runs and appends all indicators to the current DataFrame by default"

**Screenshots**
![image](https://user-images.githubusercontent.com/63505156/152672066-087b1fc5-a040-4fe3-88e7-ed4d1f9c9c68.png)
![image](https://user-images.githubusercontent.com/63505156/152672086-63279f2d-a2d5-404a-be2a-33600d5eb62c.png)

**Additional context**

I want to generate all the indicators at one go.. Also, I am seeing many indicators are having Null. Not sure whether it is because of the installation issue itself mentioned previously.. 

![image](https://user-images.githubusercontent.com/63505156/152672178-90ef5b8e-f3d7-4c55-a473-e2346bce2a3e.png)

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @tbeesofar,

Actually, you have ```tblib``` installed... not ```talib```. In fact, I don't even know what ```tblib``` is? Pandas TA was correct in identifying that you do not have ```talib``` installed. Please follow in the instructions at [TA Lib](https://github.com/mrjbq7/ta-lib) to properly install it.

If you installed it correctly, you should see it in the ```pip list``` like so:
<img width="212" alt="Screen Shot 2022-02-06 at 9 51 38 AM" src="https://user-images.githubusercontent.com/18198392/152694234-f4693a04-eae1-4029-855b-6cbc3f95fb5e.png">

Furthermore you said you upgraded Pandas TA, but you listed version _v0.3.14_, which is the _last_ ```pip``` version. I **recommend** that you upgrade to the _development_ version instead since many bugs and features in the Current Issues list have been fixed.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Let me know on your progress!

Kind Regards,
KJ

**Comment by baotang2118** [comment]
Moreover, You also need to install the TAlib from source (the real one build from source), the python TAlib is just a wrap of real TAlib.

**Comment by tbeesofar** [comment]
Hi @baotang2118 @twopirllc for pointing out the error and taking time out to respond.. I gave it another try.. 

I was able to install it successfully in jupyter-notebook in my local system.. However, when i am trying to install the talib in google colab, it is giving me below error.. Is there anything else i have to keep in mind while installing talib in google collab?

Collecting TA-Lib
  Downloading TA-Lib-0.4.24.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 19.3 MB/s 
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from TA-Lib) (1.19.5)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (setup.py) ... error
  ERROR: Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
Failed to build TA-Lib
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s8i90642/ta-lib_c8e50c5fd0b74dc881799251aaec7be1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s8i90642/ta-lib_c8e50c5fd0b74dc881799251aaec7be1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lrsymhg8/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/TA-Lib Check the logs for full command output

Jupyter
![image](https://user-images.githubusercontent.com/63505156/152852939-42b530bc-fa8a-4d6c-8654-adec97f024fa.png)

Google collab:
![image](https://user-images.githubusercontent.com/63505156/152853006-26cb5bb3-01ab-4546-b813-1ff0aa758a04.png)

**Comment by tbeesofar** [comment]
Sorry if it is a lame question and i am missing out on something very trivial

**Comment by twopirllc** [comment]
@tbeesofar,

Sorry, been very busy. I know there is an Issue where someone got it working with Collab. Not exactly sure which it was, but I will update the Issue when I find it.

KJ

**Comment by twopirllc** [comment]
Hi @tbeesofar,

Were you able to figure it out? If so, your solution would help us all.

If you are still working on it, I wonder if Issue https://github.com/twopirllc/pandas-ta/issues/329 may help? I recently read that TA Lib requires/prefers that ```numpy``` is installed before TA Lib. 🤷🏼‍♂️  But I would check on [TA Lib Issues](https://github.com/mrjbq7/ta-lib/issues) also if you haven't already.



KJ

**Comment by tbeesofar** [comment]
Sorry @twopirllc , i didn't try my hands on using talib in google collab lately. Have been using talib in jupyter notebook and exporting the calculated data and importing it in google collab for the time being as a workaround. 

Today, i tried the resolution given in issue #329, i was able to install it successfully in google colab. 

You may choose to close this ticket if you want and let me know if you get to know anything else in the future.

keep the good work up,
Thanks
Tuhin

**Comment by twopirllc** [comment]
@tbeesofar,

Thanks!

Thanks for replying and letting me know what's happening.

KJ
