### ISSUE TITLE
Custom Strategy not applying some/all strategies

### ISSUE THREAD

**Issue by hozRifai** [twopirllc/pandas-ta#486]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
Yes, and I just upgraded it to confirm that the bug is still here. 

**Did you upgrade? Did the upgrade resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Yes

**Describe the bug**

I am calling a function where I am looping over some tickers dataframes.  The dataframes I am reading have only these columns in order: `Date, Open, Close, high, Low, Volume`. I am then reading these CSV files and apply my custom strategy. 

The current behavior I am facing is that my Custom Strategy is being only applied to first 22 dataframes while having 9192 CSV files. The other files are being saved without applying my custom strategy, the columns are still 6 columns. 

**To Reproduce**

A very straight forward way of applying TA to a dataframe.

```python
CustomStrategy = ta.Strategy(
    name="My Strategy",
    description="Testing",
    ta = [
        {"kind": "ema", "length": 3},
        {"kind": "ema", "length": 5},
        {"kind": "ema", "length": 9},
        {"kind": "ema", "length": 20},
        {"kind": "fisher", "length": 10},
    ]
)

def apply_technical_analysis():
    stocks = os.listdir(main_path)

    for stock in tqdm(stocks):
        full_link = main_path + f'/{stock}'
        try:
            df = pd.read_csv(full_link)
            df.ta.strategy(CustomStrategy)
            if df.shape[0] > 0:
                df.to_csv(f'5mins_ta/{stock}', index=False)
        except:
            print(f"Something wrong happened with {stock}")

apply_technical_analysis()
```

**Expected behavior**
Based on my custom strategy above, I am expecting to have ALL the saved dataframes to have 12 columns ( 6 input ) and another 6 columns: 4 for the EMAs ( 4 columns ) 2 for fisher.

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @hozRifai,

First I would upgrade to the _development_ branch as v_0.3.14b0_ is no longer supported. There are many bug fixes, speed improvements, documentation and typing.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Multiprocessing is the default mode when using _study_ / _strategy_. Multiprocessing is not always quicker. Setting up and Multiprocessing Pool takes time and resources to initialize, run and tear down for each strategy... in your case, you are doing this 9192 times per file and equivalently 9192 MP pools.

Since you are using a small set of indicators, I recommend starting with _zero_ cores and increasing as needed. I assume this is your test set of indicator, by it's description, but out of curiosity how many indicators do you plan to use?

```python
CustomStudy = ta.Study(
    name="My Strategy",
    description="Testing",
    ta = [
        {"kind": "ema", "length": 3},
        {"kind": "ema", "length": 5},
        {"kind": "ema", "length": 9},
        {"kind": "ema", "length": 20},
        {"kind": "fisher", "length": 10},
    ]
)

def apply_technical_analysis():
    stocks = os.listdir(main_path)

    for stock in tqdm(stocks):
        df = pd.read_csv(f"{main_path}/{stock}")
        try:
            df.ta.study(CustomStudy, cores=0)
            if not df.empty:
                df.to_csv(f'5mins_ta/{stock}', index=False)
        except:
            print(f"Something wrong happened with {stock}")

apply_technical_analysis()
```

Here is the corresponding [readme](https://github.com/twopirllc/pandas-ta/tree/development).

Kind Regards,
KJ

**Comment by hozRifai** [comment]
@twopirllc

> Hello @hozRifai,
> 
> First I would upgrade to the _development_ branch as v_0.3.14b0_ is no longer supported. There are many bug fixes, speed improvements, documentation and typing.
> 
> ```shell
> $ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
> ```
> 
> Multiprocessing is the default mode when using _study_ / _strategy_. Multiprocessing is not always quicker. Setting up and Multiprocessing Pool takes time and resources to initialize, run and tear down for each strategy... in your case, you are doing this 9192 times per file and equivalently 9192 MP pools.
> 
> Since you are using a small set of indicators, I recommend starting with _zero_ cores and increasing as needed. I assume this is your test set of indicator, by it's description, but out of curiosity how many indicators do you plan to use?
> 
> ```python
> CustomStudy = ta.Study(
>     name="My Strategy",
>     description="Testing",
>     ta = [
>         {"kind": "ema", "length": 3},
>         {"kind": "ema", "length": 5},
>         {"kind": "ema", "length": 9},
>         {"kind": "ema", "length": 20},
>         {"kind": "fisher", "length": 10},
>     ]
> )
> 
> def apply_technical_analysis():
>     stocks = os.listdir(main_path)
> 
>     for stock in tqdm(stocks):
>         df = pd.read_csv(f"{main_path}/{stock}")
>         try:
>             df.ta.study(CustomStudy, cores=0)
>             if not df.empty:
>                 df.to_csv(f'5mins_ta/{stock}', index=False)
>         except:
>             print(f"Something wrong happened with {stock}")
> 
> apply_technical_analysis()
> ```
> 
> Here is the corresponding [readme](https://github.com/twopirllc/pandas-ta/tree/development).
> 
> Kind Regards, KJ

Indeed, I am still not able to see all the indicators being saved within the CSV files. when I was using CustomStrategy, it was only saving around 16 stocks, the script used to continue without saving any CSV files. However using Study, the script is saving all the CSV files but only few files have the indicators saved with them ( around the same number 16). 

Also, for the time being, I am not planning to increase the number of indicators.

**Comment by twopirllc** [comment]
@hozRifai,

Do they get applied when you don't send ```to_csv()```?
