### ISSUE TITLE
Ways to speed up ta.strategy

### ISSUE THREAD

**Issue by bizso09** [twopirllc/pandas-ta#489]
I've read https://github.com/twopirllc/pandas-ta/issues/466#issuecomment-1017714455 
and see that ta.strategy runs in 1s on your machine. I'm getting on the other hand 2s. 

Do you have recommendations for speeding up performance?

I installed Python 3.10 and VS Build Tools 2019 for linking Ta-Lib. Then installed packages with pip.

CPU specs
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 1690 Mhz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	32.0 GB

```
[i] Runtime: 2127.5418 ms (2.1275 s)
                  Open        High  ...   ZL_EMA_10     ZS_30
Date                                ...                      
2021-02-16  134.689475  135.206391  ...         NaN       NaN
2021-02-17  130.474522  131.438792  ...         NaN       NaN
2021-02-18  128.436638  129.231914  ...         NaN       NaN
2021-02-19  129.470485  129.937710  ...         NaN       NaN
2021-02-22  127.253658  128.953561  ...         NaN       NaN
...                ...         ...  ...         ...       ...
2022-02-08  171.729996  175.350006  ...  173.417466  0.518299
2022-02-09  176.050003  176.649994  ...  174.592473  0.777294
2022-02-10  174.139999  175.479996  ...  174.093840  0.141745
2022-02-11  172.330002  173.080002  ...  172.553141 -0.396170
2022-02-14  167.369995  169.571396  ...  170.803480 -0.313026

[253 rows x 285 columns]
Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'ABER_ZG_5_15', 'ABER_SG_5_15', 'ABER_XG_5_15',
       ...
       'VIDYA_14', 'VTXP_14', 'VTXM_14', 'VWAP_D', 'VWMA_10', 'WCP',
       'WILLR_14', 'WMA_10', 'ZL_EMA_10', 'ZS_30'],
      dtype='object', length=285)
```

**Comment by twopirllc** [comment]
Hello @bizso09,


First I would upgrade to the _development_ branch. There are many bug fixes, speed improvements, documentation and typing.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Second, you might you can adjust your cores. I recommend starting with zero cores and increasing it if it improves the performance.

```python
import pandas as pd
import pandas_ta as ta

df = pd.DataFrame()
df = df.ta.ticker("aapl", period="1y")
df.ta.study(cores=0, timed=True)

print(df)
print(df.columns)
```

Here is the corresponding [readme](https://github.com/twopirllc/pandas-ta/tree/development).

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @bizso09,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
