### ISSUE TITLE
Ichimoku with pandas-ta

### ISSUE THREAD

**Issue by tebrich** [twopirllc/pandas-ta#495]
Hi,

Who can help me? The Ichimoku indicator is one of my favorites for market analysis. I found excellent Pandas TA - A Technical Analysis Library in Python 3, but there is a problem with the Ichimoku indicator , in the formula. For Tenkan Sen and Kijun Sen the values used are "High", "Low", but in this Library the formula includes the "Close" (which is used only in Chikou Span, one of the technical lines of the Ichimoku), therefore the values do not match with the values of the graphics. Who knows how to modify this indicator inside the library? or any suggestions... Thanks

ichimoku = ta.ichimoku(df['high'], df['low'], df['close'])
df1 = pd.concat([df, ichimoku[0],ichimoku[1]], axis=1)

**Comment by twopirllc** [comment]
Hello @tebrich,

Unfortunately, saying it is incorrect without justification is insufficient to look into the issue. You have provided no numerical data (preferably as a _csv_), your ohlcv data **with** ichimoku applied on that data, so there is no way to confirm that your claim is correct. Please provide said _csv_ so it can be test against Pandas TA.

Kind Regards,
KJ
