### ISSUE TITLE
df.ta.to_utc unexpected behavior caused by JupyterLab

### ISSUE THREAD

**Issue by GF-Huang** [twopirllc/pandas-ta#496]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**

0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**

yes

**Did you upgrade? Did the upgrade resolve the issue?**

I try upgrade, not solve.

**Describe the bug**
The `df.ta.to_utc` is a property, but it is not idempotent. When you type `df.ta.` then press `tab` for auto completion, it will cause the `df.ta.to_utc` be called. I don't know why this design as a property rather a method.

**To Reproduce**
1. `df = ...` # In JupyterLab, create a dataframe with non-UTC datetime index.

![image](https://user-images.githubusercontent.com/4510984/155868582-d4106033-d887-486d-bc4c-768d00cef3e5.png)

2. Type `df.ta.`, then press `tab`.

3. Show the `df` again. If you can't see the index time zone changed, try step 2 multi-times then try step 3 again, you will see it.

![image](https://user-images.githubusercontent.com/4510984/155868640-34758fec-ce89-44e8-b3ef-fb15cffb6156.png)
 

**Expected behavior**
The `df.ta.to_utc` property should design as a method.

**Screenshots**

https://user-images.githubusercontent.com/4510984/155868723-36fe4bb3-31b2-4221-a3f9-6e392e78b42d.mp4

**Comment by twopirllc** [comment]
Hello @GF-Huang,

> The df.ta.to_utc is a property, but it is not idempotent.  I don't know why this design as a property rather a method.

Yeah. Good point.

Contributions are welcome to improve the library. 😎 

Kind Regards,
KJ
