### ISSUE TITLE
Indicator Zigzag

### ISSUE THREAD

**Issue by Khanhlinhdang** [twopirllc/pandas-ta#498]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, web links, or screenshots about the feature request here.

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Duplicate request
