### ISSUE TITLE
The stochastic indicator doesn't work for smooth_k = 1

### ISSUE THREAD

**Issue by KimWuWei** [twopirllc/pandas-ta#501]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.3.2b0

**Do you have _TA Lib_ also installed in your environment?**
Yes

**Did you upgrade? Did the upgrade resolve the issue?**
I upgraded but it didn't help.

**Describe the bug**
If you try to get the unsmoothed stochastic indicator it throws and exception because the SMA function on _TA Lib_ doesn't accept the value "1" as the length parameter.

**To Reproduce**
```
ta.stoch(df.High, df.Low, df.Close, k=14, smooth_k=1)
```

**Expected behavior**
The calculation of a Stochastic series getting the same result as TradingView

**Screenshots**
![screenshot](https://i.imgur.com/ii2oreP.png)

**Additional context**
In my installation I changed the line 29 (stoch.py file) from
`
    stoch_k = ma(mamode, stoch.loc[stoch.first_valid_index():,], length=smooth_k)
`
to
`
    stoch_k = stoch if smooth_k==1 else ma(mamode, stoch.loc[stoch.first_valid_index():,], length=smooth_k)
`
And apparently it worked:
![solved?](https://i.imgur.com/lFfrxg4.png)

I also suggested this change but it seems it has been discarded.

**Comment by twopirllc** [comment]
Hello @KimWuWei,

> If you try to get the unsmoothed stochastic indicator it throws and exception because the SMA function on TA Lib doesn't accept the value "1" as the length parameter.

That is true. Unfortunately TA Lib is no longer maintained for some time now.

> ```stoch_k = stoch if smooth_k==1 else ma(mamode, stoch.loc[stoch.first_valid_index():,], length=smooth_k)```

Great! You found a fix that works. I'll add it to the _development_ branch unless you want to make a PR and get contribution credit. 😎 

Additionally, I recommend updating to the _development_ branch after the fix.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

> I also suggested this change but it seems it has been discarded.

I must have missed it... But according to Github, this is your first Issue and I don't see any comments in the Issues either with your username. I **only** deal with Pandas TA Issues on Github, not email, reddit, stack*, et al.

<img width="668" alt="Screen Shot 2022-03-10 at 8 03 25 AM" src="https://user-images.githubusercontent.com/18198392/157708020-3e2a6645-a55d-41dd-959a-d5673b4cb237.png">

<br/>

<img width="968" alt="Screen Shot 2022-03-10 at 8 01 07 AM" src="https://user-images.githubusercontent.com/18198392/157708085-74108d3f-1f97-4a6e-ac83-539ad439a7e5.png">

<br/>

Kind Regards,
KJ

**Comment by KimWuWei** [comment]
Hello @twopirllc,
> I'll add it to the development branch unless you want to make a PR and get contribution credit.

No need for credit, I'm glad if you accept it :smiley:

> I must have missed it... But according to Github, this is your first Issue and I don't see any comments in the Issues either with your username. I only deal with Pandas TA Issues on Github, not email, reddit, stack*, et al.

Sorry, it was my fault. I don't know much about this Github thing...I tried to edit the code directly and created a fork instead :sweat_smile::sweat_smile:

**Comment by twopirllc** [comment]
@KimWuWei,

No worries. I'm no Github master either... still learning new things.

Thanks for the quick fix you provided! 😎  Will let you know when it's available.

KJ

**Comment by KimWuWei** [comment]
Hi @twopirllc, I updated to the development branch but I'm afraid the fix is not working by default here. If you want to get this indicator with smooth_k=1 (which is, by the way, the default value on TradingView), you have to pass the argument talib=False (otherwise TA_lib overrides the parameter by 3 without warning).

To work around this I changed line 68 from
`    if Imports["talib"] and mode_tal:`
to
`    if Imports["talib"] and mode_tal and smooth_k > 3:`

**Comment by twopirllc** [comment]
Hi @KimWuWei,

Thanks for checking out the _development_ branch before I pushed it! I'll update it.

KJ

**Comment by twopirllc** [comment]
Hi @KimWuWei,

I updated the _development_ branch with your suggested change. Let me know if it suits you.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @KimWuWei,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by KimWuWei** [comment]
> Hello @KimWuWei,
> 
> I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.
> 
> Kind Regards,
> KJ

Sorry, I didn't see it. Yes, it was sufficient. Thanks!
