### ISSUE TITLE
Issue running vwap with dataframe index from yFinance data

### ISSUE THREAD

**Issue by Gillani0** [twopirllc/pandas-ta#504]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
no

**Did you upgrade? Did the upgrade resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```
yes but didn't resolve the issue
**Describe the bug**
I'm trying to run the simple example to calculate the vwap. Since it's provided, the vwap requires the datetime indexing.
However, the data coming via yFinance doesn't have this column and we get the key error for the dataframe

**To Reproduce**
```python
import pandas as pd
import pandas_ta as ta

df = pd.DataFrame()
df = df.ta.ticker("aapl", period="9d", interval="5m")

df.set_index(pd.DatetimeIndex(df["datetime"]), inplace=True)
print(df.columns)
df.ta.vwap(append=True)
```
**Screenshots**
![image](https://user-images.githubusercontent.com/4449380/159678191-7a639b18-34b1-40fd-95e0-56e146be433d.png)

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @Gillani0,

Did you upgrade? Did the upgrade resolve the issue?
> yes but didn't resolve the issue

```python
import pandas as pd
import pandas_ta as ta

df = pd.DataFrame()
df = df.ta.ticker("aapl", period="9d", interval="5m")

# Not needed. ticker(**kwargs) returns a df with a DatetimeIndex
# df.set_index(pd.DatetimeIndex(df["datetime"]), inplace=True)
print(df.index[:1])

df.ta.vwap(append=True)
print(df.columns)
```

<br/>

<img width="648" alt="Screen Shot 2022-03-23 at 11 52 53 AM" src="https://user-images.githubusercontent.com/18198392/159775389-c4bb802e-cb2c-437d-8226-103449a961ae.png">

<br/>

Hope that helps.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @Gillani0,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by Gillani0** [comment]
Hi,
Thanks for the clarification. Yeah, I found out later that it was already indexed. I think the doc can be updated for it.

**Comment by twopirllc** [comment]
@Gillani0,

> Thanks for the clarification. Yeah, I found out later that it was already indexed. 

Glad you got it resolved.

> I think the doc can be updated for it.

I came to the same conclusion. 🤣 Thanks for the reminder!

Kind Regards,
KJ
