### ISSUE TITLE
Possible Bug in the Center of Gravity Indicator

### ISSUE THREAD

**Issue by CMobley7** [twopirllc/pandas-ta#507]
When I ran `Center of Gravity: cg` over 3 months of Bitcoin prices ("20200801" to "20201101"), I got

| | Close | cg | 
| -- | -- | -- |
| count | 132481.000000 | 132472.000000 |
| mean | 11378.306788 | -5.499988 |
| std | 844.355621 | 0.001991 |
| min | 9881.820000 | -5.616297 |
| 25% | 10710.500000 | -5.500833 |
| 50% | 11368.680000 | -5.499987 |
| 75% | 11742.540000 | -5.499146 |
| 100% | 14068.490000 | -5.458667 |

After reading http://www.mesasoftware.com/papers/TheCGOscillator.pdf, I believe there should be both positive and negative values, as well as a fair bit of variance. Based on the equations and pseudo code given in the pdf, I think a `.sum()` at the end of the following line, https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/momentum/cg.py#L42, is needed.

Thanks again for the amazing library!

**Comment by twopirllc** [comment]
@CMobley7,

Thanks!

Yeah it's possible. I thought I made a TV comparison in an Issue awhile back... but can not find it. 🤷🏼‍♂️ It's a weird one cause it lingers around -5.5 with some variance.

> Based on the equations and pseudo code given in the pdf, I think a .sum() at the end of the following line, https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/momentum/cg.py#L42, is needed.

Thanks, I will look into it as soon as I can.

KJ

**Comment by CMobley7** [comment]
Upon further examination, your code was correct. However, I did notice a slight bug in the calculation of the coefficients variable here, https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/momentum/cg.py#L41. Based on http://www.mesasoftware.com/papers/TheCGOscillator.pdf, I believe it should be 1 to length, instead of length to 1.

```
Python 3.8.13 (default, Mar 18 2022, 02:13:38) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> length = 10
>>> coefficients = [length - i for i in range(0, length)]
>>> print(coefficients)
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
>>> coefficients = list(range(1, length+1))
>>> print(coefficients)
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```
