### ISSUE TITLE
PPO returns same values as MACD not percentages

### ISSUE THREAD

**Issue by CitizenBruceLee** [twopirllc/pandas-ta#508]
Percentage Price Oscillator: ppo indicator should generate % (or range between -1 to +1) values. Now it generates the same values as MACD
<img width="1462" alt="Screenshot 2022-03-29 at 13 29 11" src="https://user-images.githubusercontent.com/83833076/160601627-52757838-01c0-42c1-b59b-e02b6ecc15c1.png">

**Comment by twopirllc** [comment]
@CitizenBruceLee,

Thanks. Well **ppo** is not the same as **macd** except their first operation: ```ema(fast) - ema(slow)```. The code is similar but **not** the same either after the first operation. The only thing that was incorrect was the Source: in the documentation 🤦🏼‍♂️ .

### MACD
<img width="634" alt="Screen Shot 2022-03-29 at 8 35 44 AM" src="https://user-images.githubusercontent.com/18198392/160649910-11cc8684-b412-4200-9a69-1d127ea3867e.png">

### PPO
<img width="421" alt="Screen Shot 2022-03-29 at 8 35 57 AM" src="https://user-images.githubusercontent.com/18198392/160649955-32565c43-97cb-4858-8882-731e66119070.png">

<br/>

### Value Comparisons
<img width="652" alt="Screen Shot 2022-03-29 at 8 29 17 AM" src="https://user-images.githubusercontent.com/18198392/160650089-3bd10fa2-4ec7-44a9-be13-2931e3d6b57d.png">


In any case, please update to the _development_ version.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

<br/>

KJ

**Comment by CitizenBruceLee** [comment]
Thank you KJ! The code is correct as it indeed devides the ppo by the slowma for the final relative results. You have been great help!

Cheers!

**Comment by twopirllc** [comment]
@CitizenBruceLee,

Sure. 🍀 

KJ
