### ISSUE TITLE
momentum/stoch.py : column loss when slow_d = slow _k

### ISSUE THREAD

**Issue by FGU1** [twopirllc/pandas-ta#51]
In stoch.py lines 47 -> 50
`    fastk.name = f"STOCHF_{fast_k}"
    fastd.name = f"STOCHF_{slow_d}"
    slowk.name = f"STOCH_{slow_k}"
    slowd.name = f"STOCH_{slow_d}"`
If slow_d = slow_k (or fast_k=slow_d) slow (or fast) stochastic names become identical. in this case the returned dataframe lose a column. 
Thanks a lot for your work on this project ;)

**Comment by twopirllc** [comment]
Hello @FGU1,

Thanks! Excellent catch! Yeah, that would do it.

Thanks for using it.
KJ
