### ISSUE TITLE
Possible Bug in Correlation Trend Indicator

### ISSUE THREAD

**Issue by CMobley7** [twopirllc/pandas-ta#510]
When I ran `Correlation Trend Indicator: cti` over 3 months of Bitcoin prices ("20200801" to "20201101"), I got

| | Close | CTI_12
| -- | -- | -- |
| count | 132481.000000 | 132470.000000
| mean | 11378.306788 | 11378.307752
| std | 844.355621 | 844.427776
| min | 9881.820000 | 9891.418974
| 25% | 10710.500000 | 10710.538205
| 50% | 11368.680000 | 11368.933526
| 75% | 11742.540000 | 11742.752564
| 100% |14068.490000 | 14026.834744

According to https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/momentum/cti.py#L17, the `cci` should range between -1 and 1. It looks like `cci` calls https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/momentum/cti.py#L42, but `r=True` isn't taken into account if you have TA-Lib installed; so, https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/overlap/linreg.py#L79 is run instead of https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/overlap/linreg.py#L106-L110. Probably the easiest fix would be to change https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/overlap/linreg.py#L68 to only execute if `r != True` as well.

**Comment by twopirllc** [comment]
Hi @CMobley7,

Nice catch! I appreciate it.

Want to PR after testing your hypothesis out?

Thanks,
KJ

**Comment by CMobley7** [comment]
@twopirllc ,

My apologies for the delay; however, I tested my hypothesis out and got the results below. This appears to fix the bug in `cti`. So, I submitted a PR with these changes, as well as changes to fix what I believe to be a minor bug in `cg`.

| | Close | CTI_12
| -- | -- | -- |
| count | 132481.000000 | 132470.000000
| mean | 11378.306788 | 0.009241
| std | 844.355621 | 0.651962
| min | 9881.820000 | -0.995214
| 25% | 10710.500000 | -0.642996
| 50% | 11368.680000 | 0.019920
| 75% | 11742.540000 | 0.661844
| 100% | 14068.490000 | 0.995496

Thanks for the great library and your responsiveness. God bless.
