### ISSUE TITLE
Fisher Transform produces incorrect results

### ISSUE THREAD

**Issue by balioglum** [twopirllc/pandas-ta#517]
Hi,

Fisher Transform produces incorrect results, particularly for securities with lots of zeros after decimal point, such as SHIBA coin, or HOLO coin.

```
import pandas as pd
import pandas_ta as ta
import yfinance as yf
data = yf.download(tickers='SHIB-USD', start="2022-01-01", end="2022-03-30")
data.ta.fisher(append=True)
data.tail(5)
```

<img width="879" alt="Screenshot 2022-04-16 at 16 20 37" src="https://user-images.githubusercontent.com/66515087/163676517-8c69d630-9be0-4f19-8e38-9a43659c71bf.png">

The Fisher Transform value does not even change over time.

**Comment by twopirllc** [comment]
Hello @balioglum,

Please fill in the unanswered questions from the [bug report form](https://github.com/twopirllc/pandas-ta/issues/new/choose) please.

Thanks,
KJ
