### ISSUE TITLE
Difference in EMA values between pandas-ta and tradingview

### ISSUE THREAD

**Issue by Yukemaster** [twopirllc/pandas-ta#519]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
0.3.14b0
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
Yes, 0.4.24
```

**Did you upgrade? Did the upgrade resolve the issue?**
```sh
Requirement already satisfied
```

**Describe the bug**
There seem to be discrepancies between EMA values when comparing pandas-ta output with tradingview.

**To Reproduce**
![grafik](https://user-images.githubusercontent.com/103902096/163768218-5faa4127-ffe3-4b65-a92d-08a2774f31f5.png)

**Expected behavior**
I would expect the values to match up, meaning the output for 17th of april would be approximately 44419.5 instead of 48125. Since I am using CCXT to fetch the data from bybit I am not sure if this is the right place to ask but I still hope that you can help me. The close data from the dataframe matches up with the values on bybit so I assume the EMAs are calculated a little differently?

**Screenshots**
![grafik](https://user-images.githubusercontent.com/103902096/163768302-144fc763-0dc6-4f86-b361-f9d93fce8b21.png)

Thanks

**Comment by twopirllc** [comment]
Hello @Yukemaster,

Since you have TA Lib in your environment, that is the default that is used. Based on the code you shared, it does not appear that you tried any other **ema** arguments for comparison. You can disable TA Lib if you do not want it's calculations as well as try other options as described in ```help(ta.ema)```. 

For the purpose of Pandas TA, I am only concerned about at least matching what TA Lib returns since it remains the _de facto_ TA library in the industry. If there is no TA Lib version, then I try TradingView since it is the next most popular and likely used platform with many public indicators. Sadly though, there are **no** standards regarding TA indicators since different platforms use different variations likely due to language of choice 🤷🏼‍♂️ . For instance see the TA Lib source of ```ta_EMA.c``` with the following comment regarding it's calculation:

```c
/* The first EMA is calculated differently. It
* then become the seed for subsequent EMA.
*
* The algorithm for this seed vary widely.
* Only 3 are implemented here:
*
* TA_MA_CLASSIC:
*    Use a simple MA of the first 'period'.
*    This is the approach most widely documented.
*
* TA_MA_METASTOCK:
*    Use first price bar value as a seed
*    from the begining of all the available
*    data.
*
* TA_MA_TRADESTATION:
*    Use 4th price bar as a seed, except when
*    period is 1 who use 2th price bar or something
*    like that... (not an obvious one...).
*/
```

<br/>

If you are still convinced that **ema** is incorrect, feel free to contribute a PR. 😎 

Kind Regards,
KJ

**Comment by mihakralj** [comment]
seems like you don't understand how EMA works and how it is implemented in Tradingview. The settings in the screenshot above are using `ema k= 2/(198+1)` but for the first 198 days you are using SMA with smoothing of 5 days only.

To generate data identical to Pandas-TA EMA, you need to use the same period value for both EMA Length and Smoothing Length in Tradingview.

EMA(n) = SMA(period) when n<period and EMA(period) when n>= period. Both periods should match.

**Comment by twopirllc** [comment]
@mihakralj,

Whom are you addressing?

**Comment by mihakralj** [comment]
Yukemaster who opened the issue.

**Comment by twopirllc** [comment]
@mihakralj, @Yukemaster 

Gotcha. Was a bit confused at first.

Ignore the SMA5 smoothing signal he posted... TV added that to version 5 of their EMA. But I do _hope_ he is **not** comparing the Smoothed (SMA5) of EMA198, or SMA(EMA198, 5), to Pandas TA's EMA198 and claiming Pandas TA is incorrect.

```
//@version=5
indicator(title="Moving Average Exponential", shorttitle="EMA", overlay=true, timeframe="", timeframe_gaps=true)
len = input.int(9, minval=1, title="Length")
src = input(close, title="Source")
offset = input.int(title="Offset", defval=0, minval=-500, maxval=500)
out = ta.ema(src, len)
plot(out, title="EMA", color=color.blue, offset=offset)

ma(source, length, type) =>
    switch type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

typeMA = input.string(title = "Method", defval = "SMA", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="Smoothing")
smoothingLength = input.int(title = "Length", defval = 5, minval = 1, maxval = 100, group="Smoothing")

smoothingLine = ma(out, smoothingLength, typeMA)
plot(smoothingLine, title="Smoothing Line", color=#f37f20, offset=offset, display=display.none)
```
<br/>

My concern is that s/he didn't read the indicator help, ```help(ta.ema)``` _nor_ try any other **ema** arguments before making the claim that Pandas TA does not match TradingView's **ema**. 🤷🏼‍♂️

**Comment by twopirllc** [comment]
@Yukemaster,

Did you test out the other **ema** parameters as suggested? If so, did it in/validate your conclusion? I want to make sure that your issue was resolved since many Moving Averages are the core of indicators and strategies that people use.

Thanks,
KJ

**Comment by Yukemaster** [comment]
Sorry for the late response, I was walking my dog. But the issue was that I was only feeding it 200 bars of data for an almost equally long EMA (198 in this case). This has nothing to do with pandas-ta but moreso with my understanding of how exponential functions work. 

Having 1000 bars of data for a 198 EMA gives a much more accurate result than only using 200. The label is 'bug' - much more fitting would be 'user error'.

Merry Christmas

**Comment by Conceptron** [comment]
> seems like you don't understand how EMA works and how it is implemented in Tradingview. The settings in the screenshot above are using `ema k= 2/(198+1)` but for the first 198 days you are using SMA(5). Seeding for the first value of EMA on the day 197 is SMA of the previous FIVE numbers, not SMA(198) - as it should be.
> 
> To generate data identical to Pandas-TA EMA, you need to use the same period value for both EMA Length and Smoothing Length in Tradingview. To be honest, there is no value to use different periods to calculate the seed and to calculate the EMAs. If you would roll the data 100+ bars forward, EMA converges regardless what seeding you use - zero, infinity, close, SMA or NaN.
> 
> By definition, EMA(n) = SMA(period) when n<period and EMA(period) when n>= period. Both periods **should** match.

if by "the screenshot" you are referring to the tradingview screenshot. i think you are misunderstanding what the "smoothing section" in it means: it doesn't control the EMA calculation at all but is instead an additional smoothed line whose visibility can be controlled in the "Visibility" section
