### ISSUE TITLE
MACD unsupported operand type(s) for -: 'float' and 'NoneType' line 34

### ISSUE THREAD

**Issue by imomin** [twopirllc/pandas-ta#523]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```
Lib 0.3.14b0
```

**Do you have _TA Lib_ also installed in your environment?**
```
No
```

**Did you upgrade? Did the upgrade resolve the issue?**
```
Yes
```

**Describe the bug**
I am using _ta.Strategy_ to calculate MCAD. When I run it against a ticket $CSLM. I get following error. **Looks like the issue happens if the record set is > 25 rows.**
```python
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```
The error is happens on line  [34](https://github.com/twopirllc/pandas-ta/blob/720bbcf0196d363d621beeced8fba711990d075d/pandas_ta/momentum/macd.py#L34) in macd.py. 

```
File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas_ta/momentum/macd.py", line 34, in macd
    histogram = macd - signalma
```

**To Reproduce**
```python
MyStrategy = ta.Strategy(
        name="MACD",
        description="Non Multiprocessing Strategy by rename Columns",
        ta=[
            {"kind": "macd", "fast": 12, "slow": 26, "signal":9, "col_names": ("MACD_fast", "MACD_slow", "MACD_signal")}
        ]
    )
    df.ta.strategy(MyStrategy)
```

**Comment by twopirllc** [comment]
Hello @imomin,

Welp! I can not currently replicate it, so if you could provide a sample _csv_ of the offending data that would help.

Also I recommend upgrading to the _development_ branch instead for several reasons... If it's a problem on _0.3.14b_, I want to iron it out on the _development_ branch.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ

**Comment by imomin** [comment]
@twopirllc 
I update the lib to development and now I am getting following error. Below is the CSV

```
[!] DEPRECIATION WARNING:
    Use study() instead of strategy().

Traceback (most recent call last):
  File "main.py", line 267, in <module>
    calculateTI()
  File "main.py", line 142, in getCalculateTIData
    df.ta.strategy(MyStrategy)
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas_ta/core.py", line 564, in strategy
    return self.study(*args, **kwargs)
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas_ta/core.py", line 731, in study
    getattr(self, ind["kind"])(*params, **{**ind, **kwargs})
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas_ta/core.py", line 1003, in macd
    result = macd(close=close, fast=fast, slow=slow, signal=signal, offset=offset, **kwargs)
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas_ta/momentum/macd.py", line 69, in macd
    signalma = ema(close=macd_fvi, length=signal, talib=mode_tal)
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas_ta/overlap/ema.py", line 82, in ema
    close.iloc[length - 1] = sma_nth
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 670, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 657, in _get_setitem_indexer
    return self._convert_to_indexer(key, axis=axis)
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 2155, in _convert_to_indexer
    self._validate_key(obj, axis)
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1994, in _validate_key
    self._validate_integer(key, axis)
  File "/Users/mac/opt/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 2063, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

Sample Code:
```python
    df.sort_index(inplace=True)
    MyStrategy = ta.Strategy(
        name="EMAs, and MACD",
        description="Non Multiprocessing Strategy by rename Columns",
        ta=[
            {"kind": "ema", "length": 9, "col_names":"EMA_9"},
            {"kind": "ema", "length": 26, "col_names":"EMA_26"},
            {"kind": "macd", "fast": 12, "slow": 26, "signal":9, "col_names": ("MACD_fast", "MACD_slow", "MACD_signal")}
        ]
    )
    df.ta.strategy(MyStrategy)
```
[Query Results.csv](https://github.com/twopirllc/pandas-ta/files/8557600/Query.Results.csv)

**Comment by twopirllc** [comment]
@imomin,

Thanks. I will take a look as soon as I can.

Kind Regards,
KJ

**Comment by giusepic** [comment]
same here - issue happens if csv has too few rows - any updates?

**Comment by twopirllc** [comment]
@imomin & @giusepic,

Nearly all indicators in commit: https://github.com/twopirllc/pandas-ta/commit/bfb96547382d3e495965b2cdbca91d873111f9fe on May 2nd have been updated to not compute the indicator nor append to the DataFrame when using ```df.ta.study()``` if it doesn't meet a minimum length (**macd** included). This is related to Issue #520 where there are not enough rows/observations/bars/candles.

Given @imomin ```results.csv``` (with 32 rows) and the current _development_ verison _0.3.65b_, I receive the following results:

<img width="810" alt="Screen Shot 2022-05-22 at 3 06 48 PM" src="https://user-images.githubusercontent.com/18198392/169718378-19306a65-815f-44b8-8cfc-3d38dc53d9e8.png">

In this case, **macd** aborts further calculation since ```close.size < slow + signal - 1``` (32 < 26 + 9 - 1 = 34) whereas in the following case, it does not:

<img width="805" alt="Screen Shot 2022-05-22 at 3 28 19 PM" src="https://user-images.githubusercontent.com/18198392/169718676-326ed0e8-a83e-49ec-858d-3b0b23afba03.png">

<br>

Please update to the _development_ branch.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Hope this helps!
KJ

**Comment by imomin** [comment]
@twopirllc 
I am using latest dev build and it working fine.

**Comment by twopirllc** [comment]
@imomin,

Thanks

**Comment by imomin** [comment]
No, thank you!

**Comment by alighten-dev** [comment]
It's 12/9/2022, and I just installed the latest production version, and I am having this issue. I just wanted to make everyone aware of the issue. Installing the latest dev branch causes an issue with custom indicators "verify_sereies is not in utils."

**Comment by kotyara85** [comment]
I'm having the same issue on `pandas-ta           0.3.14b0`

**Comment by ViniciusRaphael** [comment]
At first I was using `pandas-ta==0.3.14b0` to apply RSI and MACD to a dataframe. RSI is working perfectly, MACD is returning 
`TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'`.

After that I've updated to the develop branch as instructed
`$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development`

Now it's returning a new error
`TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`
