### ISSUE TITLE
How to specify length for volume indicators?

### ISSUE THREAD

**Issue by spiritix** [twopirllc/pandas-ta#525]
When using volume indicators like 'ad', 'obv', 'pvi', etc. there is no parameter to specify the length. This results in diverging results, depending on how large the dataset is (the series passed to the indicator). Like this, I can't use multiprocessing to calculate indicators on a large dataset, instead I have to calculate row by row to create predictable outputs. 

Is there a reason for this and a possible workaround?

**Comment by twopirllc** [comment]
Hello @spiritix,

It would be great if you could fill this out:

**Upgrade** to _development_ branch.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Verify your version**
```python
import pandas_ta as ta
print(ta.version)
```

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@spiritix,

Also, do you have TA Lib installed? If so, what version?

> The only workaround for now is to run the calculation for the affected indicators individually for each row, which takes significantly more time than using multiprocessing and is cannot be done in production environments.

Please provide reproducible code so I can replicate your issue. Including the code you use to circumvent the problem. Please provide less abstraction and more concrete examples. 😎

If you need Incremental Calculations, check out: https://github.com/nardew/talipp

> A length parameter should be added to all indicators.

All indicators accept ```**kwargs```. So ```kwargs["length"]``` is captured even if ```length``` is **not** a named argument (like: open_, high, low, close, volume, fast, slow, ... sans length), however **not** all indicators will act on ```kwargs["length"]```.

> Like this, I can't use multiprocessing to calculate indicators on a large dataset, instead I have to calculate row by row to create predictable outputs.

So you are unable to use ```df.ta.study()``` for multiprocessing?

> It's hard to believe that nobody else got stuck with this issue before, is there maybe another workaround I didn't figure out?

Perhaps. 🤷🏼‍♂️ Is there another library or platform that currently does this, hopefully Open Source, so I do not have to reinvent the wheel?

Kind Regards,
KJ

**Comment by spiritix** [comment]
Something like this would probably solve the issue (untested): https://github.com/aureatauri/pandas-ta/commit/fd2fa8d8369caf468ec4c0f5f273e42484e6a2ee

**Comment by twopirllc** [comment]
@spiritix,

Awesome! Thanks for sharing this. I will take a look as soon as I can.

KJ

**Comment by twopirllc** [comment]
@spiritix,

> When using volume indicators like 'ad', 'obv', 'pvi', etc ...

Those named indicators as well as 'adosc', 'aobv', 'cmf', 'nvi', and 'pvt' utilize ```cumsum()```. So I am not sure if that is creating this indifference. 🤷🏼‍♂️ If that fix works and applies to the other indicators I listed, let me know or make a PR. 😎 

Additionally, I recommend forking or updating your branch to the _development_ branch before making a lot of changes. There are many bug fixes, new validation methods, better documentation and numpy/numba support.

KJ

**Comment by twopirllc** [comment]
@spiritix

Just pushed a new _development_ v0.3.64b update. Much better than previous. 🤞🏼 

KJ

**Comment by spiritix** [comment]
Thanks @twopirllc, I'll check it out soon.
