### ISSUE TITLE
ta.psar TypeError for *

### ISSUE THREAD

**Issue by AJCWhite** [twopirllc/pandas-ta#527]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
0.3.14b0
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
no
```

**Did you upgrade? Did the upgrade resolve the issue?**
```sh
Using latest already
```

**Describe the bug**
When using other indicators I get the expect df data back (rsi, macd, ema, sma) but with PSAR I get a type error

**To Reproduce**
sar = ta.psar(df['high'], df['low'], df['close'])

**Expected behavior**
As per other indicators, showing result of technical indicator

**Screenshots**
![image](https://user-images.githubusercontent.com/23178407/165980190-d53129a0-ad71-4ca0-a4dd-ab2812571ac0.png)

![image](https://user-images.githubusercontent.com/23178407/165979932-557e781e-eaff-414b-915b-e3ecdaa690d4.png)

**Additional context**
original data from SQL database and I'm using latest pycharm

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hi @AJCWhite,

Please update to the _development_ branch and test again please.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

There are more bug fixes on the branch, documentation, speed et al.

Kind Regards,
KJ

**Comment by AJCWhite** [comment]
Hi KJ,

Thank you so much for the quick response. That did the trick alongside forcing the float data type from the MySQL data source.

Thanks, Alex

**Comment by twopirllc** [comment]
@AJCWhite,

Excellent! 😎 

No worries,
KJ
