### ISSUE TITLE
Some Indicators using future data?

### ISSUE THREAD

**Issue by ruifeng96150** [twopirllc/pandas-ta#530]
I do a test as following,and possible found more some functions may use future data. pls help to check. 

```python
def f1(d1):
    df = d1.sort_values(by=["time"], ascending=True)
    df["datetime"] = df.fdate + " " + df.time
    df.set_index(pd.DatetimeIndex(df["datetime"]), inplace=True)
    df.ta.strategy("All")
    return df

d1= pd.read_csv("d0.csv")
d1=d1.drop(columns=['Unnamed: 0'])

d2= f1(d1)
ti='10:38:00'
d3=d2[d2.time==ti].to_dict('records')[0]
d4= f1(d1[d1.time<=ti])
d5= d4[d4.time==ti].to_dict('records')[0]

def f2(a):
    if isnan(a):
        return 0
    return a

columns=[]
for key,value in d3.items():
    value2= d5[key]
    if f2(value)!= f2(value2):
        print(key,value,d5[key])
        columns.append(key)
columns
```

As we known ,there should be no output, but we got as following. And if we change other time to compare, may got a little different output:

```sh
CMF_20 -0.004939720791613105 -0.00493972079161308
DPO_20 0.026749999999879037 nan
ICS_26 249.899 nan
KAMA_10_2_30 237.83228903629384 237.83228903629387
PDIST 0.3290000000000366 0.3290000000000364
PSARs_0.02_0.2 250.94690886735899 250.06393713383017
PSARaf_0.02_0.2 0.02 0.04
QS_10 -0.047300000000003985 -0.04730000000000416
RVGI_14_4 -0.08171189979124054 -0.0817118997912414
RVGIs_14_4 -0.07689200433736693 -0.07689200433736772
SSF_10_2 249.3078711628632 249.30787116286317
TOS_STDEVALL_LR 250.20212995457177 249.332361892583
TOS_STDEVALL_L_1 249.10576720854496 248.5124019077995
TOS_STDEVALL_U_1 251.2984927005986 250.15232187736652
TOS_STDEVALL_L_2 248.00940446251818 247.692441923016
TOS_STDEVALL_U_2 252.39485544662537 250.97228186215003
TOS_STDEVALL_L_3 246.91304171649136 246.87248193823245
TOS_STDEVALL_U_3 253.49121819265218 251.79224184693356

['CMF_20',
 'DPO_20',
 'ICS_26',
 'KAMA_10_2_30',
 'PDIST',
 'PSARs_0.02_0.2',
 'PSARaf_0.02_0.2',
 'QS_10',
 'RVGI_14_4',
 'RVGIs_14_4',
 'SSF_10_2',
 'TOS_STDEVALL_LR',
 'TOS_STDEVALL_L_1',
 'TOS_STDEVALL_U_1',
 'TOS_STDEVALL_L_2',
 'TOS_STDEVALL_U_2',
 'TOS_STDEVALL_L_3',
 'TOS_STDEVALL_U_3']
```

-----------------------------------------------------------------------
my env:

Python 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] on linux

```sh
$ pip list|grep pandas-ta
pandas-ta                     0.3.14b0

d0 d0.head() as following:
       open	       high	       low	       close	        volume	fdate	time
0	249.500	255.000	249.500	253.662	70360.0	2022-05-06	09:31:00
1	253.734	254.600	250.560	251.000	56630.0	2022-05-06	09:32:00
2	250.842	252.225	250.842	252.039	31920.0	2022-05-06	09:33:00
3	252.016	252.016	250.221	251.000	21650.0	2022-05-06	09:34:00
4	251.060	252.922	251.060	252.757	15260.0	2022-05-06	09:35:00
```

and I upload the d0 data:
[d0.csv](https://github.com/twopirllc/pandas-ta/files/8646107/d0.csv)

**Comment by twopirllc** [comment]
Hello @ruifeng96150,

There is nothing to fix. TA came long before AI/ML and cheap computing were abundant. There will likely be
indicators that break AI/ML conventions and it is up to the AI/ML developer to decide whether to adjust or
remove/ignore said indicators before building and fitting their models. For more info regarding data leaks,
like **dpo**, please see Issue #60.

Hope this helps!

Kind Regards,
KJ

**Comment by ruifeng96150** [comment]
Ok, I see. I think it's good to have a parameter to disable indicators that have data leakage when using all.
But thank you all the same.

**Comment by twopirllc** [comment]
@ruifeng96150,

First, I recommend upgrading to the _development_ [branch](https://github.com/twopirllc/pandas-ta/tree/development).

```python
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

>  I think it's good to have a parameter to disable indicators that have data leakage when using all.

As mentioned on the [README](https://github.com/twopirllc/pandas-ta/tree/development), there is a parameter called ```lookahead``` for both [**dpo**](https://github.com/twopirllc/pandas-ta/blob/f0eed3c24020aefdf9a05a1da8d8f11bc026932c/pandas_ta/trend/dpo.py#L45) and [**ichimoku**](https://github.com/twopirllc/pandas-ta/blob/f0eed3c24020aefdf9a05a1da8d8f11bc026932c/pandas_ta/trend/dpo.py#L45). 

```python
df = # ohlcv
df.ta.study(lookahead=False, verbose=True)  # development branch
```

> I think it's good to have a parameter to disable indicators that have data leakage when using all.

Contributions are welcome. They are the fastest way to get bugs and features incorporated sooner especially if someone else can concur your findings. 😎

KJ

**Comment by twopirllc** [comment]
Hello @ruifeng96150,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
