### ISSUE TITLE
custom columns for functions

### ISSUE THREAD

**Issue by AndreyStille** [twopirllc/pandas-ta#534]
Would you mind adding custom columns for functions? Like SMA for volume, not only for close 
Can't understand such humans who do huge work but are still completely useless, nevertheless people appreciate those(2500 stars)
Dear God help me!!!

**Comment by twopirllc** [comment]
@AndreyStille,

> Would you mind adding custom columns for functions?

You can do it through the use of a custom study().

```python
# Set EMA's and SMA's 'close' to 'volume' to create Volume MAs, prefix 'volume' MAs with 'VOLUME' so easy to identify the column
# Take a price EMA and apply LINREG from EMA's output
volmas_price_ma_chain = [
    {"kind":"ema", "close": "volume", "length": 10, "prefix": "VOLUME"},
    {"kind":"sma", "close": "volume", "length": 20, "prefix": "VOLUME"},
    {"kind":"ema", "length": 5},
    {"kind":"linreg", "close": "EMA_5", "length": 8, "prefix": "EMA_5"},
]
vp_ma_chain_ta = ta.Study("Volume MAs and Price MA chain", cores=0, ta=volmas_price_ma_chain)

df = # ohlcv
df.ta.study(volmas_price_ma_chain)
print(df.columns)
```

But I assume that is not enough? As the most active maintainer of this package, I always appreciate others that chip in when they can to support the package for _all_ users whether they incorporate additional features, fix bugs, improve documentation, et al. This is beyond a free solo project. 😎

You are more than welcome to fork, edit and make a PR to 

> Can't understand such humans who do huge work but are still completely useless

Thanks for the backhanded compliment!

Kind Regards,
KJ
