### ISSUE TITLE
More Notebooks and Examples

### ISSUE THREAD

**Issue by twopirllc** [twopirllc/pandas-ta#54]
More Notebooks with different strategies and visualizations (matplotlib, bokeh, mplfinance)

**Comment by scorpio155** [comment]
Thanks a lot for creating this framework. Would it be possible to use pandas-ta over DataFrameGroupBy?

ggetDataFrame = getDataFrame.groupby('multiple_tickers')
ggetDataFrame['rsi'] = ggetDataFrame.ta.rsi(length=14)

**Comment by twopirllc** [comment]
Thanks! Glad you like it.

I have not tried DataFrame.groupby. If you have something setup already, give it a go and let me know. Just keep in mind that, ggetDataFrame has to be a DataFrame to work.

Regards,
KJ

**Comment by twopirllc** [comment]
Hello All,

Recently added the **new** [Pandas TA Strategy Class](https://github.com/twopirllc/pandas-ta/blob/master/examples/PandasTA_Strategy_Examples.ipynb) Examples Notebook. Let me know if it is helpful or missing anything.

What other notebook topics would be helpful to add to the library to help users of all levels?

Have an Notebook you would like to share, put in a pull request.

Thanks for using the library!
KJ

**Comment by apavlo89** [comment]
Hello everyone,

It would be awesome if someone made a notebook where all available technical analysis techniques are implemented to a csv database of historical stock data. Is there such a thing?

**Comment by apavlo89** [comment]
Nevermind, I found it!

df.ta.strategy("all")
df_list = list(df.columns)

This script is the absolute bomb. Thank you for your efforts!
