### ISSUE TITLE
Vidya calculation result is wrong number

### ISSUE THREAD

**Issue by A-Salimi-A** [twopirllc/pandas-ta#541]
Dear friends

Vidya calculation result is different number from original source: https://www.tradingview.com/script/hdrf0fXV-Variable-Index-Dynamic-Average-VIDYA/
For example in the NEARUSDT chart at 1h timeframe with vidya(close , 9), tradingview result was 5.355 but python ta.vidya result was 4.178

Fix it Please

Thanks

**Comment by twopirllc** [comment]
Hello @A-Salimi-A,

Please fill out a proper bug report!

Kind Regards
KJ
