### ISSUE TITLE
Indicator for moving average of volume

### ISSUE THREAD

**Issue by vivekruhela** [twopirllc/pandas-ta#547]
Hi,

I am looking for the moving average indicator for the volume so that I can track volume also. Is there any indicator in pandas-ta for the same purpose? If yes, please let me know.

**Comment by twopirllc** [comment]
Hello @vivekruhela,

There is no moving average whose default source is ```volume```. So you have to override the default source ```close``` with ```volume```. Additional examples are under the **Programming Conventions** section of the [README](https://github.com/twopirllc/pandas-ta#programming-conventions) including overriding the default sources like ```volume```.

In short, for you use case...

### Standard
```python
df = # ohlcv
volma = ta.sma(df["volume"], length=10)
```

### Pandas DataFrame Extension
```python
df = # ohlcv
volma = df.ta.sma(close=df["volume"], length=10)
```

### Strategy (or Study)
```python
df = # ohlcv
VolMA = ta.Strategy(
    name="Vol SMA",
    description="Volume SMA 10",
    ta=[{"kind": "sma", "close": "volume", "length": 10, "prefix": "VOLUME"}]
)
# To run your "Custom Strategy"
df.ta.strategy(VolMA)
```

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @vivekruhela,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by vivekruhela** [comment]
Issue solved. Thanks
