### ISSUE TITLE
Supertrend Indicator

### ISSUE THREAD

**Issue by alexonab** [twopirllc/pandas-ta#55]
Would it be possible to add the ST indicator?  Definition and sample implementation is bellow.

https://www.tradingfuel.com/supertrend-indicator-formula-and-calculation/

https://www.quantopian.com/posts/error-computing-super-trend-indicator#5a204aeb9160496397ed534c

**Comment by twopirllc** [comment]
Hello @alexonab,

Sure. It was on my radar also.

KJ

**Comment by FGU1** [comment]
Ok, I push it tomorrow.

**Comment by twopirllc** [comment]
Thanks @FGU1,

I have some additional updates that I am working on as well on the development branch that I am hoping to push within a day.

Thanks,
KJ

**Comment by FGU1** [comment]
PR #56 sent. Please review the code carefully : I do not have a lot of xp in python (+quite new to github) so there is a non negligible probability that errors can be found. Apologies in advance !

**Comment by twopirllc** [comment]
Hey @FGU1,

No worries. Thanks for the contribution. I'll fold it into development and adjust as needed.

Thanks,
KJ
