### ISSUE TITLE
ichimoku cloud is a delayed 1 day

### ISSUE THREAD

**Issue by ismail-invict** [twopirllc/pandas-ta#556]
when I use ichimoku indicator and check with the tradingview default ichimoku cloud, values calculated with this package seems 1 day delayed.
In other words, as an example values seen on 28th June on tradingview are written to Dataframe to date 29th June. So it creates 1 day mismatch

**Comment by twopirllc** [comment]
Hello @ismail-invict,

Thanks for letting me know. When I get a moment to verify the claim or someone else can verify it, then it will be fixed. In the mean time, I recommend modifying your local copy to address the issue for your case. Of course you are also welcome to submit a Pull Request (PR) with the adjustment. 😎

Lastly, I recommend using the _development_ version if you are not already.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ

**Comment by pandodaniel** [comment]
There seems to be an issue with the shifting of the span to the second (future) DataFrame. As a work around while this is not solved, you can use the first Span A and Span B values of the second (future) DataFrame, as those are the correct ones for the latest closed candle. Hope I've helped

**Comment by ISMAILHKYILDIZ** [comment]
I have same issue when I tried to use ichimoku indicator.
T-1 values are written to T day in the dataframe, so when I try to use ichimoku cloud its one day delayed so today's values will be calculated tomorrow. I am not python expert that lagged data makes this indicator useless, maybe it is a very easy to fix issue.
Thanks

**Comment by ISMAILHKYILDIZ** [comment]
I have just checked results of dev branch, problem still exists. Also I just found its9 feature's value is incorrect.
I think this must be fixed ASAP as ichimoku is one of popular indicators.
If I can help, I would like to but I am not a pyhton dev, I can just evaluate outputs with tradingview :(

**Comment by kliden1** [comment]
@ISMAILHKYILDIZ @ismail-invict 

I solved this problem by taking the series of data (the column) and applying .shift(-1).

Here is one of my leadlines, for example. (NOTE: I am also concatenating the two series together (current and future calcs), feel free to ignore this if not needed)

imc_leadline1_1min = pd.concat([imc_1min[0]["ISA_9"], imc_1min[1]["ISA_9"]], axis=0).shift(-1)

Simply put, it's [SERIES].shift(-1) to pull it back one.

@twopirllc I'm sure there is a better permanent fix, but this is a quick fix yall may want to reference until the actual issue is addressed. Hope this helps!

**Comment by twopirllc** [comment]
Hello @ismail-invict, @pandodaniel, @ISMAILHKYILDIZ, and @kliden1,

The _development_ branch has been updated with the required _shifts_ thanks to the code shared by @kliden1.
Will assume it is working as expected and will close the issue in a few days if no replies.

Kind Regards,
KJ

**Comment by someoneelse131** [comment]
Hello everyone, seems like it is not quite fixed yet. 
(On Default Values) i got the ISA_9 shifted one day (timeframe) behind. 
All other Values are correct even the forecast.

I'll try to find a fix and post it here if i'm successful
