### ISSUE TITLE
Dev branch: TypeError: bind() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by souresia** [twopirllc/pandas-ta#565]
I've upgraded to the development branch and while trying some custom indicator I get:

```
    import_dir(ta_dir)
  File "/opt/homebrew/lib/python3.9/site-packages/pandas_ta/custom.py", line 198, in import_dir
    bind(module_name, _callable, _method_callable)
TypeError: bind() takes 2 positional arguments but 3 were given
```

In custom.py something doesn't look right as here we call bind with 3 arguments:

https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/custom.py#L198

whereas bind() only has 2:

https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/custom.py#L14

Perhaps it's an ongoing work but just to let you know! Thanks!

PS: I'm trying to use (and debug) the new vwap indicator. On my side all bands have the same values, but not sure if something is wrong on my side yet. I'm a bit stuck because trying the new vwap on the main branch is missing some methods like `[X] An error occurred when attempting to load module vwapro: No module named 'pandas_ta._typing'`

**Comment by twopirllc** [comment]
Hello @souresia,

>  PS: I'm trying to use (and debug) the new vwap indicator. ...

Gotcha! 

> I've upgraded to the development branch and while trying some custom indicator...

So you are trying to create a custom indicator in a custom directory? Also which version of the _development_ branch are you on? I assume ```vwapro``` is your custom indicator?

> Perhaps it's an ongoing work but just to let you know! Thanks!

I appreciate it.

Looks like the 3rd argument on Line 14 in custom.py is never used, hence I commented it out and didn't finish refactoring it. Can you locally try removing the 3rd argument on Line 198 like so: ```bind(module_name, _callable)``` and seeing if it works as expected?

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @souresia,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by CMobley7** [comment]
@twopirllc ,

The solution you provided above works. Is there any way we can have that merged into development? I could submit a PR, but it's a one-line change. Let me know what you'd like me to do.

**Comment by CMobley7** [comment]
@twopirllc, there are a few other minor things, I'd like to add to custom.py. I'll submit a PR tomorrow.
