### ISSUE TITLE
'DataFrame' object has no attribute 'ta'

### ISSUE THREAD

**Issue by dkaralis** [twopirllc/pandas-ta#567]
Hello, trying to start using pandas_ta and I get this error.  
I found a similar issue but the solution didn't worked for me.

Thank you

![Screenshot 2022-07-25 at 06 43 11](https://user-images.githubusercontent.com/1788507/180695114-72193c15-3e60-4b87-989b-7f17e724f1a6.png)

**Comment by twopirllc** [comment]
Hello @dkaralis,

If you figured this out, please close the issue. If not, please provide more details. Also do not create a module named ```pandas_ta``` as it might get confused between it and this package.

Kind Regards,
KJ

**Comment by dkaralis** [comment]
Hello Kevin.  After your last comment I renamed my file from pandas_ta.py to pand_t.py and now it is working.  
Thank you!

**Comment by twopirllc** [comment]
@dkaralis,

Excellent! Glad it's working now for you. 😎 

KJ
