### ISSUE TITLE
SuperTrend always returns period=7

### ISSUE THREAD

**Issue by Walduss** [twopirllc/pandas-ta#575]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)

0.3.14b0
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list

Not sure: i dont see ta-lib, only ta version 0.10.1
Let me know if something is needed
```

**Did you upgrade? Did the upgrade resolve the issue?**
```sh
$ pip install -U 
git+https://github.com/twopirllc/pandas-ta

Not Upgraded: I get this error:
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

**Describe the bug**
I am running Supertrend with different Periods values, but always I get the same values no matter what  period has been choosen

for isntance:
import pandas_ta as ta
data1 = df
data2 = df
data3 = df

data1.ta.supertrend(period=7, multiplier=1.7, append=True)
data2.ta.supertrend(period=10, multiplier=1.7, append=True)
data3.ta.supertrend(period=20, multiplier=1.7, append=True)

I get the same exact result in the three datasets. Even thought, the column names for all of them are the same no mather what vaules are cheosen

Index(['open', 'high', 'low', 'close', 'open_time_bck', 'SUPERT_7_1.7',
       'SUPERTd_7_1.7', 'SUPERTl_7_1.7', 'SUPERTs_7_1.7'],
      dtype='object')

**To Reproduce**
check above

**Expected behavior**
diferent values  should be returned

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

![image](https://user-images.githubusercontent.com/96188772/186008290-e28e841d-d5e6-47bf-9b7a-eedd19cc90f3.png)

**Comment by Walduss** [comment]
Hi,  

I have seem similar issue in    https://github.com/twopirllc/pandas-ta/issues/337

It seems i should use length instead period paramenter name

**Comment by Walduss** [comment]
Sorry, it was my fault using a wrong parameter name.

thanks and regards

**Comment by twopirllc** [comment]
Hello @Walduss,

Glad you were able to resolve your issue similar to #337. 😎 

Note: You can use ```help(ta.indicator_name)``` to get more information about a particular indicator including parameters and keyword arguments.

```sh
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```
This error just means you do not have ```git``` installed. I won't go into details about ```git```, but this YT video by [Fireship](https://www.youtube.com/watch?v=hwP7WQkmECE) is a good introduction. Also there is a GUI application called Github Desktop that may help with working with _git_.

Lastly, I recommend upgrading to the _development_ branch which will require _git_ to be installed.
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ
