### ISSUE TITLE
Wrong calculation for CMO indicator between different versions

### ISSUE THREAD

**Issue by codesutras** [twopirllc/pandas-ta#58]
@twopirllc , I've just updated pandas-ta package to the latest version and it has updated my installed package to pandas_ta-0.1.63b. 

I've run my one of the strategy, where I'm using CMO (Chande Momentum Oscillator) and fond that calculation are different than previous stable version of pandas_ta-0.1.39b0. 

I didn't look into the recent commits, but checked README and observed that you have corrected CMO indicator too. Perhaps, the current change is not producing accurate results. I've validated it through some of the charting software. 

Not sure, what's the correct value the current one (with pandas_ta-0.1.63b) or the previous version(pandas_ta-0.1.39b0)

**Comment by twopirllc** [comment]
@codesutras,

Thanks for the heads up.  I'll take a look into it.

Thanks,
KJ

**Comment by twopirllc** [comment]
@codesutras,

It is not uncommon for an indicator to have more than one implementation and CMO is no exception in this case. Before the current CMO (v63b) it was not more than 99+% correlated with TA Lib so I corrected it. At this point, neither implementation is wrong; just different flavors.

To support both versions, I have included the argument ```talib``` with ```talib=True``` as the default. You will need to pass in ```talib=False``` to use the prior version. This will happen in a future update and I will close this issue when that occurs.

Hope this helps!
KJ

**Comment by codesutras** [comment]
> @codesutras,
> 
> It is not uncommon for an indicator to have more than one implementation and CMO is no exception in this case. Before the current CMO (v63b) it was not more than 99+% correlated with TA Lib so I corrected it. At this point, neither implementation is wrong; just different flavors.
> 
> To support both versions, I have included the argument `talib` with `talib=True` as the default. You will need to pass in `talib=False` to use the prior version. This will happen in a future update and I will close this issue when that occurs.
> 
> Hope this helps!
> KJ

Pretty much mate. Thanks a lot for your quick response.
