### ISSUE TITLE
Ichimoku error when using different parameters - can only concatenate str (not "Timedelta") to str

### ISSUE THREAD

**Issue by mdmoura** [twopirllc/pandas-ta#580]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ branch? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**

**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @mdmoura,

Please fill out the report above. 👍🏼 

Kind Regards,
KJ
