### ISSUE TITLE
Adding automatic tests by Github Actions

### ISSUE THREAD

**Issue by Karsten-Fyhn** [twopirllc/pandas-ta#583]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
Yes

**Is your feature request related to a problem? Please describe.**
It is easier to contribute to a library, if there is a clear and transparent way of running tests and it is traceable when a test started failing.

**Describe the solution you'd like**
I would like the test suite to be run in Github Actions on every PR to main.

**Describe alternatives you've considered**
None

**Additional context**
I have made a PR adding this functionality: https://github.com/twopirllc/pandas-ta/pull/582

Thanks for using Pandas TA!

**Comment by Karsten-Fyhn** [comment]
Merging the above PR might also be a step on the way to addressing https://github.com/twopirllc/pandas-ta/issues/423.

**Comment by twopirllc** [comment]
Hello @Karsten-Fyhn,

Awesome! 😎  Thanks for making a PR #582 to handle these tests with TA Lib with GitHub Actions. I will try it out as soon as I can.

Kind Regards,
KJ
