### ISSUE TITLE
No module named 'pandas_ta.candles'

### ISSUE THREAD

**Issue by alexonab** [twopirllc/pandas-ta#59]
version: pandas-ta-0.1.65b0

$ python3.7
Python 3.7.7 (default, Apr  1 2020, 13:48:52) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import pandas_ta as ta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.7/site-packages/pandas_ta/__init__.py", line 21, in <module>
    from pandas_ta.core import *
  File "/lib/python3.7/site-packages/pandas_ta/core.py", line 8, in <module>
    from pandas_ta.candles import *
ModuleNotFoundError: No module named 'pandas_ta.candles'

**Comment by twopirllc** [comment]
@alexonab,

Doh!  Thanks!
KJ

**Comment by twopirllc** [comment]
@alexonab,

Try again please.

Thanks,
KJ

**Comment by alexonab** [comment]
The update works.  I'm able to import the library again.  Cheers
