### ISSUE TITLE
Locate wrong index.

### ISSUE THREAD

**Issue by graceyangfan** [twopirllc/pandas-ta#596]
https://github.com/twopirllc/pandas-ta/blob/bc3b292bf1cc1d5f2aba50bb750a75209d655b37/pandas_ta/trend/psar.py#L58
The sar compute should started from 2 instead of 1,or the sar will select the last value of pandas DataFrame in the future.

**Comment by twopirllc** [comment]
Hello @graceyangfan,

Excellent eye! However this minor error was also part of a **psar** fix in Pull Request #543 and part of the _development_ branch. Update to _development_ branch when you get a chance.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ
