### ISSUE TITLE
Possible future data leak on CUBE and IFISHER

### ISSUE THREAD

**Issue by FanaticPythoner** [twopirllc/pandas-ta#597]
After quick inspection, if I'm not wrong, there seem to be a future data leak with CUBE and IFISHER when using `study.AllStudy`, as they both have an offset set by default to -1. Please update the readme to point this out. AI model time series feature importance impact evaluation: 
![image](https://user-images.githubusercontent.com/45826736/192151599-4ecb54f8-042d-4aea-8c12-c2f1b045df75.png)

**Comment by twopirllc** [comment]
Hello @FanaticPythoner,

Thanks for the heads up! 😎 

They need to be reevaluated anyhow.

Kind Regards,
KJ

**Comment by FanaticPythoner** [comment]
Thanks for your prompt answer @twopirllc . I appreciate your hard work.

If I may, I would say it's pretty urgent / important to update the README so individuals training DNN(s) can know what I found, as not everyone will dig in in the library / do steps to identify anomalies in features, therefore may not spot it and may run under the false assumption that only DPO and ichimoku need to be looked at.
