### ISSUE TITLE
SMMA curve very different than TradingView

### ISSUE THREAD

**Issue by yeraydiazdiaz** [twopirllc/pandas-ta#599]
First thank you very much for your work in pandas-ta 🙏🏻

This is more of a general question rather than a bug report but I thought I'd use this template. I hope it's ok.

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```
0.3.72b0
```

**Do you have _TA Lib_ also installed in your environment?**
No, installing TA Lib causes a NumPy version conflict in my virtual environment and prevented me from running pandas-ta.

**Have you tried the _development_ version? Did it resolve the issue?**
I am working with the development version and it did not resolve the issue.

**Describe the bug**
Again I don't believe it's a bug but it's more of a general question since I'm very likely missing something. I'm trying to recreate TradingView's Smoothed Moving Average using pandas-ta so naturally I tried the development version's `ta.smma`. However, the result is quite different.

**To Reproduce**
Assuming a `close` Series with the data, in this case a 5 minute chart for EURGBP
```
import pandas_ta as ta
sma_21 = ta.smma(close, 21)
d = pendulum.parse('2022-09-26 22:30')
data_for_plot = data.loc[data.index >= d].copy()
plot_df_dict = {
    "sma_21": sma_21[sma_21.index >= d],
}
plot_df = pd.DataFrame(plot_df_dict)
apdict = mpf.make_addplot(plot_df)
mpf.plot(data_for_plot, type="candle", volume=True, addplot=apdict, figscale=2)
```

**Expected behavior**
I expect the curves to match, in the screenshots below you can see how TradingView's SMMA does not hug the prices quite as tightly.

**Screenshots**
<img width="1317" alt="Screenshot 2022-09-27 at 18 54 26" src="https://user-images.githubusercontent.com/6739793/192601025-5e4a1007-cf58-4d39-b2f1-345b11f022d4.png">
<img width="1258" alt="Screenshot 2022-09-27 at 18 55 36" src="https://user-images.githubusercontent.com/6739793/192601267-674c8ef7-8eed-4d28-9a9e-51a337e8da92.png">

**Additional context**
I've tried using different implementations in Python, even wrote a simplified version of pandas-ta's SMMA code, and they all yield the exact same curve. I also noted that the SMMA is also the EMA with (length * 2) - 1, and again the result is the same.

The pine code in TradingView is deceptively simple and has no parameters other than the length, so I'm not really sure what am I missing.

Apologies if it's something really obvious, hopefully someone can point me in the right direction.

Thanks!

**Comment by yeraydiazdiaz** [comment]
Apologies, it seems I've messed something up in my data loading stage. 🙏🏻

**Comment by twopirllc** [comment]
Hello @yeraydiazdiaz,

Glad you were able to solve your Issue. 😎  Data differences are often the first potential culprit. 

Thanks for the detailed answers to the *bug** prompts. I appreciate it.

Kind Regards,
KJ
