### ISSUE TITLE
Future data leak on DPO indicator

### ISSUE THREAD

**Issue by brunofacca** [twopirllc/pandas-ta#60]
Thank you for this great library.

I've used the `strategy` method to add all indicators to a data frame. DPO_1 got a massive feature importance score and any models trained with that indicator had accuracy of 99 to 100% :smile:. 

It seems that when `center=True` (the default), [this line](https://github.com/twopirllc/pandas-ta/blob/279423a50675191729f665a801f7ee18323a4efa/pandas_ta/trend/dpo.py#L16) leaks future data into the past.

**Comment by twopirllc** [comment]
Hello @brunofacca,

Thanks! Glad that you like it.

That is quite a boost! 😄  However upon reviewing the code, it seems the code is not in line with other implementations, so it will be corrected.

Thanks
KJ

**Comment by twopirllc** [comment]
@brunofacca,

Indicator corrected. Let me know of any issues.

Thanks,
KJ

**Comment by brunofacca** [comment]
That was fast! Thank you :slightly_smiling_face:

**Comment by ben-watt-es** [comment]
I'm just chiming in to say that I have the same issue. I am running 0.1.97b0, and either DPO leaks future data, or it is the holy grail of indicators.

**Comment by twopirllc** [comment]
Hello @ben-watt-es,

Crazy! So, I ran a correlation test with TradingView. They are also perfectly correlated, centered or not. I guess it unknowingly is the holy grail. 🤣 

<img width="319" alt="Screen Shot 2020-09-01 at 9 48 17 AM" src="https://user-images.githubusercontent.com/18198392/91883065-bd82a180-ec38-11ea-9a63-52085c03c3f5.png">

Thanks,
KJ

**Comment by brunofacca** [comment]
If it's too good to be true, it's usually not true :sweat_smile:. I guess a simple way to ensure that it is not leaking future data would be to calculate it within a rolling window and compare the results with calculating it in the usual way. Something like:

```
rolling_window_calc = data.expanding(min_periods=1).apply(lambda x: your_dpo_function(x)[-1], raw=True)
full_data_calc = your_dpo_function(x)
if rolling_window_calc != full_data_calc:
  print('There is a leak')
```

**Comment by twopirllc** [comment]
> If it's too good to be true, it's usually not true 😅

I subscribe to that as well.

It's worth checking out.

**Comment by andybrewer** [comment]
I think DPO is still leaking data here: https://github.com/twopirllc/pandas-ta/blob/4804beaa3820c010f7554c3934983c401ed4ddd2/pandas_ta/trend/dpo.py#L18

In my data table, DPO is generating data before the 20 day SMA can be calculated, and prior to the 11 day previous close.

<img width="719" alt="Screen Shot 2020-09-03 at 5 00 45 PM" src="https://user-images.githubusercontent.com/7093/92184832-0a1bd780-ee07-11ea-8b36-2976f6df168c.png">


Removing `.shift(-t)` should fix it.

FYI, with `'centered': False`, DPO_20 doesn't generate any data until the 30th day, so it's shifted too far in the other direction. Although I'm not sure if `centered` is even needed on this indicator.

**Comment by twopirllc** [comment]
@andybrewer 

Thanks for the additional details.

Yeah. I know the line. I included it since it was part of Trading View's builtin **dpo** options and an easy one-liner. I'll look at it again soon after I tie up some other loose ends. 

Thanks,
KJ

**Comment by andybrewer** [comment]
For those coming across this in the future, it appears that the centered DPO indicator is both correct (per: https://school.stockcharts.com/doku.php?id=technical_indicators:detrended_price_osci) and simultaneously leaks future data if used in the wrong context.

When `length=20` (default), the centered version calculation translates to:
"Take the close from 11 days ago and subtract the simple moving average for the last 20 days. Then shift that data into the past 11 days." So, assuming your trading data has information every day of the week, the non-centered DPO value for the 21st of the month would be the close on the 10th minus the SMA from the 1st-21st. For the non-centered version, that's fine and doesn't leak data. With the centered version it then places that value on the 10th of the month. So your centered DPO on the 10th is in part made up of the SMA from the 1st-21st. Without this context it'll appear that your DPO value is somehow amazing at predicting the price for up to 10 days into the future.

https://github.com/twopirllc/pandas-ta/blob/master/pandas_ta/trend/dpo.py#L18

**Comment by myilmazhaubtech** [comment]
Is there a list of indicators on pandas-ta that leak data like this?

**Comment by twopirllc** [comment]
Hello @myilmazhaubtech,

From a Technical Analysis perspective, they are not data leaks; they are by design. However they are data leaks for ML/AI. The only two indicators in Pandas TA that leak data for ML/AI users are: **dpo** and **ichimoku** but that can be remedied.

### Handling data leaks
For **dpo** set centered to ```False```:
```python
df.ta.dpo(centered=False) # default of centered is True
```

For **ichimoku**, remove the last column of the resultant DataFrame, the Chikou Span. The Chikou Span just shifts ```close``` to the left, so for your data set it is not necessary.

Hope this helps!

Regards,
KJ

**Comment by twopirllc** [comment]
Hi @myilmazhaubtech,

It has been updated on the README.

Regards,
KJ

**Comment by aleksthegreat** [comment]
still leaking [data[](url)](url)
![dpo_leak](https://user-images.githubusercontent.com/1139557/110062840-0296a600-7d38-11eb-9c65-2e5ba1eb7bbc.png)

**Comment by twopirllc** [comment]
Hello @aleksthegreat,

How can I help you?

**Comment by masafumimori** [comment]
> Hello @myilmazhaubtech,
> 
> From a Technical Analysis perspective, they are not data leaks; they are by design. However they are data leaks for ML/AI. The only two indicators in Pandas TA that leak data for ML/AI users are: **dpo** and **ichimoku** but that can be remedied.
> 
> ### Handling data leaks
> For **dpo** set centered to `False`:
> 
> ```python
> df.ta.dpo(centered=False) # default of centered is True
> ```
> 
> For **ichimoku**, remove the last column of the resultant DataFrame, the Chikou Span. The Chikou Span just shifts `close` to the left, so for your data set it is not necessary.
> 
> Hope this helps!
> 
> Regards, KJ

Thank you!
This is very helpful (Although it took ages to figure out why my machine learning is performing too good on backtesting and not working on the realtime data).

It would be great if this info is written in when doing `help(ta.dpo)` or something so people can find easily.
If needed, i can add docstring to `dap` function and make PR :)

**Comment by twopirllc** [comment]
Hello @masafumimori,

> This is very helpful (Although it took ages to figure out why my machine learning is performing too good on backtesting and not working on the realtime data).

I can see how that can be confusing or frustrating. However it is up to the user to manage their own _pre_ and _post_ processing.

> It would be great if this info is written in when doing help(ta.dpo) or something so people can find easily.
If needed, i can add docstring to dap function and make PR :)

Sure! Please checkout out the _development_ branch and update the relevant indicators docstring if you have some time. 😎 

Kind Regards,
KJ
