### ISSUE TITLE
AttributeError: module 'pandas_ta.momentum' has no attribute 'WilliamsRIndicator'

### ISSUE THREAD

**Issue by Nav-deep123** [twopirllc/pandas-ta#600]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
I am using 0.3.14b0 version of pandas_ta

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Is your feature request related to a problem? Please describe.**
I am trying to calculate William R indicator using pandas_ta library but ended up getting attribute error. I am unable to understand why?
![Capture 1](https://user-images.githubusercontent.com/114574931/192750534-567c9b3e-412e-4652-8e18-7af5d2dc2b43.PNG)

**Describe the solution you'd like**

**Describe alternatives yo
u've considered**

**Additional context**
Add any other context, web links, or screenshots about the feature request here.

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @Nav-deep123,

The ```ta.momentum.WilliamsRIndicator()``` belongs to the following [TA](https://github.com/bukosabino/ta) library and **not** Pandas TA. If that is the exact indicator you are intending to use, then make an Issue with that library.

Kind Regards
KJ
