### ISSUE TITLE
BBands.py percent offset using wrong variable

### ISSUE THREAD

**Issue by nexlcap** [twopirllc/pandas-ta#606]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
'0.3.14b0'
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
percent offset calculation is now like **bandwidth**.shift(offset), should be **percent**.shift(offset) instead

**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/67345521/194134791-7843cccf-65af-40a8-b6fb-b247be483f43.png)

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @nexlcap,

Thanks for looking out! However, please search older Issues prior to making a new one. For instance, see #409.

You made this post and never tried the following as requested on the Bug Report
**Have you tried the development version? Did it resolve the issue?**

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards
KJ

**Comment by twopirllc** [comment]
Hello @nexlcap,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
