### ISSUE TITLE
Can not import talib

### ISSUE THREAD

**Issue by mostafanu** [twopirllc/pandas-ta#61]
I am trying to test project files under tests directory
it shows the following error:

 Collecting talib
  Using cached talib-0.1.1.tar.gz (1.3 kB)
Using legacy setup.py install for talib, since package 'wheel' is not installed.
Installing collected packages: talib
    Running setup.py install for talib: started
    Running setup.py install for talib: finished with status 'error'

    ERROR: Command errored out with exit status 1:
     command: 'D:\dev\projects\pandas-ta\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TAS01\\AppData\\Local\\Temp\\pycharm-packaging\\talib\\setup.py'"'"'; __file__='"'"'C:\\Users\\TAS01\\AppData\\Local\\Temp\\pycharm-packaging\\talib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TAS01\AppData\Local\Temp\pip-record-4jfhoad9\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\dev\projects\pandas-ta\venv\include\site\python3.8\talib'
         cwd: C:\Users\TAS01\AppData\Local\Temp\pycharm-packaging\talib\
    Complete output (14 lines):
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\TAS01\AppData\Local\Temp\pycharm-packaging\talib\setup.py", line 32, in <module>
        setup(
      File "C:\Users\TAS01\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\TAS01\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\TAS01\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\TAS01\AppData\Local\Temp\pycharm-packaging\talib\setup.py", line 20, in run
        raise Exception("You probably meant to install and run ta-lib")
    Exception: You probably meant to install and run ta-lib
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\dev\projects\pandas-ta\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TAS01\\AppData\\Local\\Temp\\pycharm-packaging\\talib\\setup.py'"'"'; __file__='"'"'C:\\Users\\TAS01\\AppData\\Local\\Temp\\pycharm-packaging\\talib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TAS01\AppData\Local\Temp\pip-record-4jfhoad9\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\dev\projects\pandas-ta\venv\include\site\python3.8\talib' Check the logs for full command output.

**Comment by twopirllc** [comment]
Hello @mostafanu,

I am sorry but I do not troubleshoot TA Lib installations. One of the reasons I wrote pandas_ta was because of this issue with TA Lib and Windows installation. I develop on a Mac which thankfully did not have such TA Lib installation issues.  I test against TA Lib so that users get TA Lib quality indicators across platforms with the benefit Python and Pandas.

Here are some links which may lead you in the right direction in getting TA Lib successfully installed on Windows.
- [Google Search: cannot install talib on windows](https://www.google.com/search?source=hp&ei=2sTbXqOAJMXB7gKP0IfoCg&q=cannot+install+talib+on+windows&oq=cannot+install+talib+on+windows&gs_lcp=CgZwc3ktYWIQAzIICCEQFhAdEB46BQgAELEDOgUIABCDAToCCAA6BwgAEEYQ_wE6BAgAEAo6CAgAEBYQChAeOgQIABANOgYIABANEB46CAgAEA0QBRAeOgYIABAWEB5Q1whYwVhgv1xoAHAAeACAAaUEiAHRG5IBCjIwLjkuMS41LTGYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwij1YHEzu3pAhXFoFsKHQ_oAa0Q4dUDCAg&uact=5)
- [ta-lib issue #301](https://github.com/mrjbq7/ta-lib/issues/301)
- [Stackoverflow](https://stackoverflow.com/questions/41155985/python-ta-lib-install-problems)

Hope this helps.
KJ

**Comment by HosseinKurd** [comment]
@twopirllc I have some problems in fedora-32 too

```
pip3 install ta-lib
Collecting ta-lib
  Using cached https://files.pythonhosted.org/packages/d7/15/ebf1a6ebcf7580dc53e342979c7425affc38ef272bc10a7f4565ee87b394/TA-Lib-0.4.18.tar.gz
Requirement already satisfied: numpy in /usr/local/lib64/python3.8/site-packages (from ta-lib) (1.18.5)
Installing collected packages: ta-lib
    Running setup.py install for ta-lib ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9rvicb_5/ta-lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9rvicb_5/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2s6qjor3/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-9rvicb_5/ta-lib/
    Complete output (25 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/talib
    copying talib/test_stream.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_func.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_data.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_pandas.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/stream.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/__init__.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/deprecated.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_abstract.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/abstract.py -> build/lib.linux-x86_64-3.8/talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/talib
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/lib64/python3.8/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/usr/include/python3.8 -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.8/talib/_ta_lib.o
    talib/_ta_lib.c:4:10: fatal error: Python.h: No such file or directory
        4 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9rvicb_5/ta-lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9rvicb_5/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2s6qjor3/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by twopirllc** [comment]
Hello @HosseinKurd,

I am sorry but I do not troubleshoot TA Lib installations. You do not need TA-Lib to use ```Pandas TA```, only if you want to test the library.  If you want to add code to ```Pandas TA```, you do not need TA-Lib.

Regards,
KJ

**Comment by khazaddim** [comment]
@HosseinKurd 

I had to deal with the Python.h error:

https://gist.github.com/brunocapelao/ed1b4f566fccf630e1fb749e5992e964#gistcomment-3715406

I think it was **_sudo apt install libpython3.7-dev_** that fixed it.  I also did some other stuff in the comment link above.
