### ISSUE TITLE
FutreWarning during execution of macd function

### ISSUE THREAD

**Issue by mpele** [twopirllc/pandas-ta#610]
Hi,
I have noticed new FutreWarning during execution of macd function:
`FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.`
Is there a plan for fixing this soon because this message overwhelms the output?

ps. I am using version 0.3.14b0

**Comment by twopirllc** [comment]
Hello @mpele 

> Is there a plan for fixing this soon because this message overwhelms the output?

Did you look up past [_FutureWarning_ Issues](https://github.com/twopirllc/pandas-ta/search?q=FutureWarning&type=issues) prior to this post? Did you try the _development_ version to see if that solved the Issue as asked on the Bug Report?

Kind Regards
KJ

**Comment by mpele** [comment]
I was doing a search, but to be honest I wasn't on that keyword. I was not persistent in my search because I saw that the code had not been changed in the last 15 months. I understand that this is not critical, but I did not expect it to be hidden in the development code for so long.

Is it recommended that the development code be used for everyday use?

**Comment by twopirllc** [comment]
@mpele

In short, yes. Eventually the _development_ branch, with over 200+ commits ahead of _main_, will replace the _main_ branch. For more info, see the _development_ branch [README](https://github.com/twopirllc/pandas-ta/tree/development). 

If the _development_ version does not solve your Issue or you feel it is insufficient for daily use, then you are welcome to fork and add [FutureWarning suppression](https://stackoverflow.com/questions/15777951/how-to-suppress-pandas-future-warning) to your local version.

The library is _overwhelmed_ with Issues so contributions of all kinds are welcome to expedite bug fixes, additional indicators, new features, documentation, and coffee. 😎

Kind Regards
KJ

**Comment by mpele** [comment]
Oh, I wasn't aware of this.
Thanks for the clarification.
