### ISSUE TITLE
installing pandas-ta on venv (WLS Ubuntu)

### ISSUE THREAD

**Issue by abstractumx** [twopirllc/pandas-ta#611]
**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
yes I am trying to install it on a new venv

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
No, I prefer to use the stable version

**Describe the bug**
Cant install pandas-ta lib using WLS Ubuntu

**Expected behavior**
Look screenshot msg error, seems using Ubuntu WLS you cannot install the pkg

**Screenshots**
![image](https://user-images.githubusercontent.com/98787313/196543544-32813327-17d5-460f-b472-9394a78d5fb3.png)

**Additional context**
NA

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @abstractumx,

> No, I prefer to use the stable version

I recommend the _development_ version. Many more improvements, bug fixes, documentation et al.

Anyhow I received no error when installing *pandas_ta* with WSL and virtualenv on my system. In any event, have you tried searching for [error: invalid command 'bdist_wheel'](https://www.google.com/search?q=error+invalid+command+%27bdist_wheel%27) and trying the recommended solutions? This is more of a *pip* or *pip3* issue and not a Pandas TA issue.

Kind Regards
KJ

**Comment by mohdhasnain902** [comment]
try installing these side packges. for me it worked
pip install --upgrade pandas_ta numpy
