### ISSUE TITLE
Indicator Request: Williams Fractal Indicator

### ISSUE THREAD

**Issue by ISMAILHKYILDIZ** [twopirllc/pandas-ta#613]
simple view as follows that is one the standard indicators in tradingview
it may be implemented as 1 0 -1 like signals similar to candle indicators
![image](https://user-images.githubusercontent.com/20664520/197650689-5407cc02-dae6-4402-8ef8-00cd7195a0e8.png)

**Comment by twopirllc** [comment]
Hello @ISMAILHKYILDIZ 

It among **many** other indicator requests are in limbo _until_ current outstanding bugs and PRs are resolved as well as the remaining non-candlestick indicators from TA Lib are completed. Hopefully someone whom is also interested in the indicator being included soon will make a PR to bump it up in priority.

Kind Regards
KJ
