### ISSUE TITLE
Understanding ta.vp indicator (Volume Profile). bug?

### ISSUE THREAD

**Issue by argcast** [twopirllc/pandas-ta#615]
For testing & understanding purposes I've created a `DataFrame` and run `vp` on the first 10 rows which is the minimum width required by the indicator.

I understand as on [vp.py](https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/volume/vp.py) close series is evaluated and through the `series.diff(1)` in the `signed_series` function current close is compared to the next close and then assigned a positive or negative value, which then results in either `pos_volume` or `neg_volume `for the `vp` itself.

As I understand, the total volume in a given price range, should be the same as the total `vp` volume should return. Is this correct?
I have checked Issues #74 and #185 looking for an already answered similar question.

Here is the `df.head(10)` :

![image](https://user-images.githubusercontent.com/103273391/200646909-1f15176c-38c9-4126-a45e-51b9bcc9cd57.png)

And here is `df.ta.vp()` where you can see Volume data loss on 2nd and 3rd rows:

![image](https://user-images.githubusercontent.com/103273391/200647169-70fbc4f8-60b1-4e7c-a413-ec8d4e26cf83.png)

As you can see, when close prices are equal on consecutive rows, issues arise as 
`df.ta.vp()['total_Volume'].sum() == df.Volume.sum()` evaluates to `False`

What am I missing or maybe not understangid about vp?

**Comment by twopirllc** [comment]
Hello @argcast,

Yeah that does look like an issue. Something I would have to find some time to dig into more when I get a chance.

I found these links for VP which may help as its actual source is hard to find.
* [akhilman - vol-poorofile](https://github.com/akhilman/vol-poorofile)
* [Fr3d0's Volume Profile Visible Range - TV version 4](https://gist.github.com/4skinSkywalker/d5e42f46851decf69054e0d0287ab6f5)
* [reddit algotrading](https://www.reddit.com/r/algotrading/comments/ccomnl/volume_profile_python_code/)

If you have any ideas on how to fix it, that would be helpful. 😎 

Apologies for the late reply.

Kind Regards
KJ

**Comment by argcast** [comment]
Hey @twopirllc ,

sorry for the late reply. I have been working on it with a simple fix. Here is my approach:

Since the issue happens only when open and closing prices are equal, current `vp.py` does not know wether if it is pos_Volume or neg_Volume happening. Neither do we and that means we cannot directly sum it to either of them.
That's why I modified the code a little bit adding a new `neut_volume` (neutral volume) that computes those cases.

Let me explain better:

```
import pandas as pd
import pandas_ta as ta
import yfinance as yf

df = yf.download('RVP', start="2023-03-01")
```

<img width="398" alt="Screenshot 2023-03-24 at 11 13 23" src="https://user-images.githubusercontent.com/103273391/227497113-fb248186-871c-4d40-a8e0-3630e13135aa.png">

As we can see, we have found one case where `open == close` and upon calling `df.ta.vp()`we can see we have data loss:

<img width="528" alt="Screenshot 2023-03-24 at 11 13 30" src="https://user-images.githubusercontent.com/103273391/227497710-6f24043e-3c8a-4fe1-992b-66809f14ca45.png">

While if we consider `neut_vol` (neutral volume) as what is happening in those cases we can avoid data loss:

<img width="621" alt="Screenshot 2023-03-24 at 11 13 55" src="https://user-images.githubusercontent.com/103273391/227498101-5e763052-fce6-414b-85b9-9bdb273fa82b.png">

and VP charting should consider that "neutral" volume too

<img width="335" alt="Screenshot 2023-03-24 at 11 14 31" src="https://user-images.githubusercontent.com/103273391/227498107-3d7218d6-7c39-44bc-8204-c42eeb0f1fd2.png">

PS: I'm not sure wether if "neutral" should be the correct naming for this volume
I've created a PR #670  with modified `vp.py` so you can take a look at it and make any necessary adjustments.

I hope this helps 🙂
Albert.
