### ISSUE TITLE
[Question] Indicators lookback candle period

### ISSUE THREAD

**Issue by arjunChouksey** [twopirllc/pandas-ta#616]
Recently, i was using rsi indicator and found out result difference from tradingview calculations, Further i found out that for precise rsi calculation 290 previous candles are required. So is there any document that has more information regarding each indicator and it's lookback candles ?

**Comment by twopirllc** [comment]
Hello @arjunChouksey,

If I understand you correctly, it seems you are describing what is known as _Unstable Period_ as noted in TA Lib and described [here](https://ta-lib.org/d_api/ta_setunstableperiod.html). Basically, depending on your set of indicators you will need to determine what is the minimum bars needed. It's situational but the rough rule, again _depending_ on your set, is at least 200 bars or so.

Hope it helps!

Kind Regards
KJ

**Comment by twopirllc** [comment]
Hello @arjunChouksey,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
