### ISSUE TITLE
CMO (Chande Momentum Oscillator) calculation

### ISSUE THREAD

**Issue by mihakralj** [twopirllc/pandas-ta#628]
Original CMO explanation from Chande's book:
![206595953-ab02f2ce-514e-4941-a711-76298c174bf4](https://user-images.githubusercontent.com/31756078/206600175-0b3bf9e7-d48d-42d2-a40e-472b5a27666d.png)
![206595986-af72ad1e-f8a1-4786-bf6c-b17d3f82aa73](https://user-images.githubusercontent.com/31756078/206600204-aa245a98-9af9-4e63-87c0-0cfc295df9eb.png)

**To Reproduce**
```python
df = ta.DataFrame({'close': [101.0313, 101.125, 101.9687, 102.7813, 103, 102.9687, 103.0625, 102.9375, 102.7188, 102.75, 102.9063, 102.9687 ]})
df['cmo'] = ta.cmo(close = ff['close'], length=10)
df
```

**Expected behavior**
This should generate THREE cmo values - for the last three rows of data, equivalent to what is in the book.
Instead, we get:
```sh
close   | cmo
101.031 | NaN
101.125 | NaN
101.969 | NaN
102.781 | NaN
103.000 | NaN
102.969 | NaN
103.062 | NaN
102.938 | NaN
102.719 | NaN
102.750 | NaN
102.906 | 60.091
102.969 | 61.928
```
Remark: TA-LIB also mis-calculates CMO and returns different results from the book (and different results from Pandas-TA)...

**Comment by twopirllc** [comment]
Hello @mihakralj,

Thanks for sharing the relevant pages of CMO! 😎  This is really helpful. I do want a pure implementation of CMO but the default will always be TA Lib. Hopefully someone can help and submit a PR as a conditional option.

KJ

**Comment by mihakralj** [comment]
According to my reproduction, your CMO implementation returns different data than TA-LIB's CMO... And neither of them matches what Chanda wrote in his book...

**Comment by mihakralj** [comment]
According to my reproduction, your CMO implementation returns different data than TA-LIB's CMO... And neither of them matches what Chanda wrote in his book...

**Comment by OskarBienko** [comment]
@twopirllc @mihakralj You're right that ta.cmo returns wrong values, even though that you have made mistake by trying to reproduce the results from the book. You didn't include the first input "101.031" at time 0. That's why you have got 2 results instead of 3. I'll try to make push request regarding ta.cmo() function this week.

**Comment by twopirllc** [comment]
@OskarBienko,

Cool!  Looking forward to it. 😎

Thanks,
KJ

**Comment by twopirllc** [comment]
@mihakralj, @OskarBienko 

Ok. Finally had a bit of time research this.

Pandas TA is also correct when:
1. When ```talib=False```
2. The close values in the table in the book begins with two 101.0313's, not one.

### Example
```python
import pandas as pd
import pandas_ta as ta

df = pd.DataFrame({"close": [101.0313, 101.0313, 101.125, 101.9687, 102.7813, 103, 102.9687, 103.0625, 102.9375, 102.7188, 102.75, 102.9063, 102.9687 ]})
df.ta.cmo(length=10, talib=False, append=True)
df
```

### Output
<img width="561" alt="Screenshot 2023-05-13 at 12 28 52 PM" src="https://github.com/twopirllc/pandas-ta/assets/18198392/b05064b4-2414-4b73-9577-37dd0ea3408e">

* This is true for both the _main_ and _development_ branches.

Unless I am mistaken, there is no difference between book CMO and Pandas TA (talib=False) CMO?

KJ

**Comment by twopirllc** [comment]
@mihakralj, @OskarBienko

Since there has been no response to confirm or deny the results of my prior results and comment, I'll be closing this issue. Reopen if you have evidence to the contrary.

Kind Regards

**Comment by OskarBienko** [comment]
@twopirllc @mihakralj 

Hello there, sorry for delay. I confirm that with the `talib=False` argument you obtain the right results. However, by default this argument is set to True, so you obtain wrong results by default. Thus, I recommend changing the default argument `talib=True` into `talib=False`. How does that sound?

![image](https://github.com/twopirllc/pandas-ta/assets/56788563/b95356a8-c367-4fed-aa6e-6ac00ad837df)
