### ISSUE TITLE
ta.above append question

### ISSUE THREAD

**Issue by fypdoctave** [twopirllc/pandas-ta#63]
Hi Kevin,

Apologies in advance for a very stupid question. I updated the code base today. But I'm not sure what happened since then as using the 'above' function is not appending anymore. 

*Below line is not appending now but was working in a previous version*
df.ta.above(df['MACD_12_26_9'], df['MACDs_12_26_9'], append=True) 

*This is appending just fine*
df.ta.macd(fast=12, slow=26, signal=9, min_periods=None, append=True)

Can you take a look and tell me what I am doing wrong. Thanks in advance.

**Comment by twopirllc** [comment]
Hello @fypdoctave,

Doh! Thanks for finding the bug. Easy fix. I will try to update it over the weekend if that's not too long.
Until I push a fix, you can do this:
```python
macddf = df.ta.macd(append=True)
df['MACD_>_MACDs'] = ta.above(macddf.iloc[:,0], macddf.iloc[:,1])
```

Thanks,
KJ
