### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by michaelto20** [twopirllc/pandas-ta#632]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.4.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
yes 

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Is your feature request related to a problem? Please describe.**
I find it frustrating to recalculate a techincal indicator for the entire data set for every new data point when operating in a real-time setting.

**Describe the solution you'd like**
Currently if you are using this library for streaming data, real time updates require you to append the data to your dataframe and calculate the technical indicator for the entire history. It would be nice to have a streaming API that allows you to give just the latest piece of data and get the updated value for the technical indicator. 

For example, let's say you have 100,000 rows of data and you are calculating the 200 EMA. For backtesting, you can just calculate the 200 EMA for every row and move forward with your back test. With the streaming API feature, if you had the 100,001st data point, you would need to append it to your historical data and then calculate the 200 EMA for every data point, which is slow and redundant.

Similar to this: https://github.com/mrjbq7/ta-lib#streaming-api

**Describe alternatives you've considered**
I've considered only keeping X number of historic data points so recalculating the newest technical indicator value is fast but this is a pain to implement.

**Additional context**
I'm a software engineer and would be happy to help build this with others. I'm curious if there is much interest out there for this feature though before putting in a bunch of work to pull it off.

Thanks for using Pandas TA!

**Comment by michaelto20** [comment]
Thanks for the reply @twopirllc, I had missed that discussion in #87 thanks for pointing that out. Additionally I'd never heard of talipp, which sounds like an excellent solutions. Thanks for the information!

**Comment by twopirllc** [comment]
@michaelto20

No worries! Hope it helps! 🍀 

KJ
