### ISSUE TITLE
does pandas-ta look at the future?

### ISSUE THREAD

**Issue by makovez** [twopirllc/pandas-ta#639]
Hi, I really appreciate your work.

We are using your project for a machine learning project. I would like to know if it possible that talib, for some technical indicators uses futures points to assign its values or only past points?

So for example, let's say we calculate all the technical indicators in all the dataset.

If we look at the technical indicators in candle x, is it possible that some of those technical indicators have used candles after x (x +1, x+2, ...) to calculate them?

I encoutered a problem with these indicators in particular:
'sti_TOS_STDEVALL_LR',
'sti_TOS_STDEVALL_L_1',
'sti_TOS_STDEVALL_U_1',
'sti_TOS_STDEVALL_L_2',
'sti_TOS_STDEVALL_U_2',
'sti_TOS_STDEVALL_L_3',
'sti_TOS_STDEVALL_U_3',

I use same dataset to generate these technical indicators, but different in length. 

So firstly i create these technical indicators using whole dataset, and then only using same dataset but from 0 to 1000 row

After, comparing the two dataset i get all technical indicators same except the ones cited above. Might this be because pandas-ta uses future data to calc them?

**Comment by makovez** [comment]
Ok sti seems to use the future by default.

But what about these ones: `sti_KURT_30 `and `ichi_chikou_span`

Are they intended to use future as well?

**Comment by twopirllc** [comment]
Hello @makovez,

> We are using your project for a machine learning project. I would like to know if it possible that talib, for some technical indicators uses futures points to assign its values or only past points?

Awesome! talib as in [TA Lib](https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/)? It's hard to keep track of it all, luckily the source is available.

By _future_, do you mean indicators that leak data? If so, there are currently 4 listed on the _development_ version [readme](https://github.com/twopirllc/pandas-ta/tree/development#overlap-35) like **ichimoku**:

<img width="668" alt="Screenshot 2023-02-08 at 11 07 56 AM" src="https://user-images.githubusercontent.com/18198392/217628500-4e78d7f0-d50d-4eb2-8f67-8060972010c5.png">

I do not recall _kurtosis_ being mentioned in prior [data leak](https://github.com/twopirllc/pandas-ta/issues?q=is%3Aissue+leak) issues. 🤔  But Pandas TA is wrapping [Pandas calculation](https://github.com/pandas-dev/pandas/search?q=kurt) of kurtosis.

https://github.com/twopirllc/pandas-ta/blob/4814dabf32b0b7d132518cb09c594a3529413bdf/pandas_ta/statistics/kurtosis.py#L41

Apologies for the delayed response.

Kind Regards,
KJ

**Comment by makovez** [comment]
Yeah the one mentioned in the previous comment seems all to leak future
data.

Il mer 8 feb 2023, 20:33 Kevin Johnson ***@***.***> ha
scritto:
