### ISSUE TITLE
Publishing to Azure Serverless function: ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by fbeenaerts** [twopirllc/pandas-ta#64]
When running locally, this runs perfect. But when publishing to Azure Serverless (App function), I always get "ModuleNotFoundError: No module named 'pandas'". However the pandas is installed before.

**Comment by twopirllc** [comment]
Hello @fbeenaerts 

Thanks for using Pandas TA. I have no experience running it on Azure Serverless, so I am unable to help. All I can recommend at this time is double checking your settings/configurations. I put a "Help Wanted" label up so someone with Azure Serverless experience may chime in and help.

Regards,
KJ
