### ISSUE TITLE
How to add cdl_pattern to Custom Strategy?

### ISSUE THREAD

**Issue by ma7555** [twopirllc/pandas-ta#640]
I am trying to add a cdl_pattern to custom strategy by setting for example:

```python
{"kind": "closingmarubozu"}, 
```
In the ta list inside the strategy by I receive the following error:
```sh
AttributeError: 'AnalysisIndicators' object has no attribute 'closingmarubozu'
```

**Comment by twopirllc** [comment]
@ma7555,

The ```"kind"``` should be ```"cdl_pattern"``` and the ```"name"``` is the actual candle indicator.

See if this works? FYI: This is with the _development_ branch.
```python
import pandas as pd
import pandas_ta as ta

cdls = [
    {"kind": "cdl_pattern", "name":"closingmarubozu"},
]

custom = ta.Study(
    name="Custom Candles",  # name
    ta=cdls,  # ta
    description="Custom Candles ...",  # description
    cores=0
)
df.ta.study(custom)
```

KJ

**Comment by ma7555** [comment]
Works, thanks for clarification.
