### ISSUE TITLE
stoch - fastk - fastd values

### ISSUE THREAD

**Issue by STOCKZE** [twopirllc/pandas-ta#641]
trying to get fastk and fastd values from stoch indicator - the talib code is below, how can I get them in pandas-ta

```python
self.stoch=bt.talib.STOCHF(self.data.high, self.data.low, self.data.close, fastk_period=10, slowk_period=4, slowd_period=4)
self.fastk=self.stoch.fastk
self.fastd=self.stoch.fastd
```

**Comment by twopirllc** [comment]
Hello @STOCKZE,

Have you read the README section: [Standard Programming Convention](https://github.com/twopirllc/pandas-ta#standard)? This section details how to run indicators like TA Lib. Also, do you have TA Lib installed? What version of Pandas TA are you running?

Kind regards,
KJ
