### ISSUE TITLE
SMMA having error. It didn't happen before 

### ISSUE THREAD

**Issue by VietnameseRick** [twopirllc/pandas-ta#645]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
pandas-ta-0.3.79b0
**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
yes
**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
I am using the development version
**Describe the bug**
3-4 weeks ago I installed the development version and then use it to calculate the SMMA in my Linux WSL and it ran perfectly. And then I installed it with Windows 10 and then both Linux WSL and Windows 10 facing error with 
```numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('float64'), dtype('<U14')) -> None```
**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/95068784/215385258-d05352cc-30ba-4536-aac4-c80da42caa15.png)

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @VietnameseRick,

That is odd. Are your dependency packages different since installing on Windows 10 with WSL?

Kind Regards
KJ

**Comment by VietnameseRick** [comment]
> Hello @VietnameseRick,
> 
> That is odd. Are your dependency packages different since installing on Windows 10 with WSL?
> 
> Kind Regards KJ

Yes it is, before that my Windows 10 got version 0.3.14b and my WSL (which is Ubuntu 20.04) got version 0.3.79b0. Both were working fine until I install version 0.3.79b0 in my Windows 10

**Comment by twopirllc** [comment]
@VietnameseRick,

It's a _numpy_ exception. Are there differences with _numpy_?

**Comment by VietnameseRick** [comment]
> @VietnameseRick,
> 
> It's a _numpy_ exception. Are there differences with _numpy_?

Sorry for late response, I didn't do any thing with numpy. I tried to write my own code to calculate SMMA (kinda similar to the way pandas_ta calculate SMMA ) and it worked fine. That's why I think there is something wrong with pandas_ta

**Comment by twopirllc** [comment]
@VietnameseRick

No worries. Busy myself. 😑 

If you feel like submitting a PR, that would be great! 😎 

KJ

**Comment by VietnameseRick** [comment]
> @VietnameseRick
> 
> No worries. Busy myself. 😑
> 
> If you feel like submitting a PR, that would be great! 😎
> 
> KJ

Sure, I will submit a PR when I can 👍
