### ISSUE TITLE
Using Polars instead of Pandas

### ISSUE THREAD

**Issue by mihakralj** [twopirllc/pandas-ta#646]
There are so many performance comparison between [Pandas](https://pandas.pydata.org/) and [Polars](https://www.pola.rs/), I asked myself two questions:

1. Would Pandas-TA library perform better if it used Polars?
2. Would the code be tighter if it followed Polars approach?

I rewrote four indicators into Polars expressions and compared the results and execution time between Pandas-TA and Polars-TA. I thought you'd be curious to see side-by-side comparison.

```Python
import polars as pl
import pandas_ta as ta
from numpy import nan as NaN

def sma(source:pl.Series, length:int) -> pl.Series:
    return source.rolling_mean(length, min_periods=length).fill_null(NaN)

def ema(source:pl.Series, length:int) -> pl.Series:
    return pl.concat([source.rolling_mean(length)[:length],source[length:]]).ewm_mean(span=length,adjust=False).fill_null(NaN)

def dema(source:pl.Series, length:int):
    ema1 = pl.concat([source.rolling_mean(length)[:length],source[length:]]).ewm_mean(span=length,adjust=False)
    ema2 = ema1.ewm_mean(span=length,adjust=False)
    return (2*ema1-ema2).fill_null(NaN)

def tema(source:pl.Series, length:int):
    ema1 = pl.concat([source.rolling_mean(length)[:length],source[length:]]).ewm_mean(span=length,adjust=False)
    ema2 = ema1.ewm_mean(span=length,adjust=False)
    ema3 = ema2.ewm_mean(span=length,adjust=False)
    return (3*(ema1-ema2)+ema3).fill_null(NaN)
```

And here is the super-simple test on data Series:

```Python
data_ta :ta.Series = ta.Series([data array])
data_pl :pl.Series = pl.Series([data array])

# Polars
sma_pl  = sma(data_pl, length=5)
ema_pl  = ema(data_pl, length=5)
dema_pl = dema(data_pl, length=5)
tema_pl = tema(data_pl, length=5)

# Pandas-TA
sma_ta  = ta.sma(data_ta, length=5)
ema_ta  = ta.ema(data_ta, length=5)
dema_ta = ta.dema(data_ta, length=5)
tema_ta = ta.tema(data_ta, length=5)
```

No matter how I weave the tests, Polars execution is consistently at least twice as fast as Pandas executiion. And I like the tightness of the Polars indicator code too...#645 

Suggestion: should we consider some conditional clauses - just like for TA-LIB - and if Polars is installed, convert the dataframe from Pandas to Polars and execute?

**Comment by twopirllc** [comment]
Hi @mihakralj,

> * Would Pandas-TA library perform better if it used Polars?

Last Spring, I looked at Polars (and Vaex) and **absolutely** agree that they are better DataFrame implementations than Pandas. Wish I had know about them prior committing to Pandas as well as adding partial _numpy/numba_ support.

> * Would the code be tighter if it followed Polars approach?

Unfortunately I have not had the time to research and build a few indicators to be certain. Though from my basic understanding, implementing them in Polars with lazy evaluation support would be tighter and faster.

> Suggestion: should we consider some conditional clauses - just like for TA-LIB - and if Polars is installed, convert the dataframe from Pandas to Polars and execute?

That is one possibility, like TA Lib and numpy/numba on the _development_ branch. Or the other alternative I was kicking around was to just implement some TA in Polars Rust. 🤷🏼‍♂️  However there is already some existing Rust TA crates out there... but I have no seen one utilizing Polars.

KJ

**Comment by mihakralj** [comment]
should we try this:
if the input frame/series is Polars-derived type, do Polars execution. Else, if the input frame/series is Pandas/Numpy type, do business-as-usual?

**Comment by twopirllc** [comment]
That's one way to do it.

Out of curiosity, do you know the performance difference between _numba_ and _polars_?

**Comment by twopirllc** [comment]
@mihakralj 

Looks promising: [Pandas - PyArrow and Polars](https://pandas.pydata.org/docs/dev/user_guide/pyarrow.html?highlight=polars) on their the Pandas _dev_ branch. 😎

**Comment by mihakralj** [comment]
No worries, nobody ever even thought about SWITCHING. Initial idea was to experiment on a DEV branch to ADD Polars as an alternative to Pandas - for users that have their frames in Polars format and don't want to convert them to Pandas in order to use Pandas-TA. Pandas users that use Pandas-TA with Pandas frames would never notice any difference.

But now that Pandas actually plans to switch/add Polars internally, we'll just wait.

**Comment by mihakralj** [comment]
Here is one indicator of pandas working on Apache Arrow integration: https://pandas.pydata.org/docs/dev/user_guide/pyarrow.html

**Comment by Chuck321123** [comment]
@twopirllc Any update on polars implementation? If not, could you at least add numpy support?

**Comment by twopirllc** [comment]
Hello @Chuck321123 @impredicative 

> Any update on polars implementation?

Luckily for me, there is no need. However [some](https://github.com/search?q=polars-ta&type=repositories) have already begun this journey on GitHub.

> If not, could you at least add numpy support?

In fact I have already started to include _numpy_/_numba_ support on the _development_ branch. Indicators _for_ loops will be converted first and the rest as needed.

Unfortunately this will take some time since few contribute, donate or sponsor this library. Even my yearly _development_ costs are not covered. 🤷🏼‍♂️ ☹️ 

Kind Regards
KJ
