### ISSUE TITLE
Using numpy.int64 as `offset` argument for `ema()` causes it to be treated as a zero

### ISSUE THREAD

**Issue by bigtonylewis** [twopirllc/pandas-ta#652]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
Yes, tried both with and without TA-Lib installed

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
Yes, 0.3.79b0.  The error still occurs

**Describe the bug**
When using an numpy int64 instead of an int for at least the offset value in `df.ta.ema()`, it gets treated as a zero and gives the wrong result.

**To Reproduce**
Provide sample code.
```python
import pandas as pd
import numpy as np

import pandas_ta as ta
print(ta.version)

s = pd.DataFrame(range(1,20), columns=['close'])

five = 5
five_int64 = np.int64(five)

assert(s.ta.ema(3, five).equals(s.ta.ema(3, int(five_int64))))   # works
assert(s.ta.ema(3, five).equals(s.ta.ema(3, five_int64)))        # does not work, but should
```

**Expected behavior**
When an int-like is passed in, it is successfully treated like an int

**Additional context**
This might apply to other indicators also, I didn't test

**Comment by twopirllc** [comment]
Hello @bigtonylewis,

> When using an numpy int64 instead of an int for at least the offset value in df.ta.ema(), it gets treated as a zero and gives the wrong result.

I feel I am missing some context here. 😕  I am stuck on why not just use ```int``` which clearly works?

If you to tinker an immediate fix for your local installation, I would start here on the _development_ branch. That way you can target any ```int``` indicator parameter types being checked.

https://github.com/twopirllc/pandas-ta/blob/4814dabf32b0b7d132518cb09c594a3529413bdf/pandas_ta/utils/_validate.py#L62-L67

If your changes pass your scrutiny, feel free to make a PR. Contributions are welcome! 😎 

Kind Regards
KJ

**Comment by bigtonylewis** [comment]
Hi, the context was that I wanted to generate a list of EMAs, of different length and offset, and test their predictive power.  So my code is like this:

```python
for length in [1, 2, 3, 5, 9, 12, 18, 24, 36, 48, 72]:
    for offset in np.geomspace(ema * 0.2, ema * 5, 12).astype(int):
        thisema = df.ta.ema(length, offset)
...
```

There was no error, but each `thisema` for a given length turned out the same, regardless of `offset`, and it looks like it was because `offset` is being defaulted to 0, because even with `.astype(int)`, they were `np.int64` not `int`.  Pandas kinda spoils me in that things like this don't happen, or they raise exceptions.  I consider it a bug because it silently fails with the wrong value.

My workaround is easy, I can just use `int(offset)` in the call to `ema()` (which I'm doing), but it seemed like this could be fixed.  But I also have done a couple of pull requests, one for main (if you're interested) and one for the development branch.  Both these seem to fix my issue.

**Comment by bigtonylewis** [comment]
> But I also have done a couple of pull requests

I am very green at github and almost as green at git.  Feedback welcome on these PRs if they are not done right.  I am unsure if the PRs can or should be linked here, but they are visible in the PR tab for the project, so :man_shrugging:

**Comment by twopirllc** [comment]
@bigtonylewis

Should be better now. Please try out the _development_ branch and let me know when you get a chance.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ
