### ISSUE TITLE
AlphaTrend Indicator Request

### ISSUE THREAD

**Issue by arifkenan** [twopirllc/pandas-ta#658]
Hi, thank you for all your work. You people are amazing. I was wondering if you can add AlphaTrend Indicator by Kıvanç Özbilgiç?
Because we all getting amazing reviews on this new indicator and maybe you can help us. Thank you!

Here is the python code: https://github.com/OnlyFibonacci/AlgoSeyri/blob/main/alphaTrendIndicator.py
Tradingview: https://tr.tradingview.com/script/o50NYLAZ-AlphaTrend/

**Comment by twopirllc** [comment]
Hello @arifkenan,

Sure it can be added. For quickest inclusion into the library hopefully you or someone else can checkout the _development_ branch and make PR with the indicator. Should be pretty easy considering existing Python code from the link you provided. 😎 

Thanks
KJ

**Comment by ekremus** [comment]
I'm waiting for you to add it. It's better than SuperTrend. 

Besides, I think so too, you guys are great ❤️

**Comment by twopirllc** [comment]
@arifkenan @ekremus 

_Alpha Trend_ has been out on the _development_ branch for about a month now. Check it out and reopen this issue if there is an issue.

Kind regards,
KJ
