### ISSUE TITLE
Calculating DEMA indicator never ends

### ISSUE THREAD

**Issue by MislavSag** [twopirllc/pandas-ta#66]
Hi,

I have just download the package. I tried to create several indicators and had problem with EMA indicator.

When I execute `data.ta.sma()` it works as expected, but when I execute `data.ta.ema()` the code hangs, it didn't end even after 10 minutes.

I have 3 mil of observations. If I use talib `EMA()` function, it works instantly.

**Comment by MislavSag** [comment]
Hm, it seems it is just very slow. But than, why it is so much slower than talib package?

**Comment by twopirllc** [comment]
Hello @MislavSag,

TA Lib was written in C so it will inherently be faster.  So if that is your only bottleneck, then use TA Lib's EMA as needed.

However there is another option you can use that may speed up ```pandas-ta```'s EMA. You can use Panda's builtin Mathematical implementation of EMA aka EWM by setting the parameter ```ewm=True``` like so: ```data.ta.ema(ewm=True)``` to speed it up, however there is likely to be differences in correlation. Yet, many online tutorials use EWM as calculation for EMA but that is not technically correct in comparison to Technical Analysis literature and TA Lib's implementation.

Regards,
KJ

**Comment by MislavSag** [comment]
Thanks for feedback, I will use talib than, sinceis more accurate.
