### ISSUE TITLE
how to combine more than condition to be entry point

### ISSUE THREAD

**Issue by ahmed159159** [twopirllc/pandas-ta#668]
how to combine more than condition to be entry point for example 

```python
df['RSI'] = ta.rsi(df['close'], length=14)
df['sma']= ta.sma(df['close'], length=14)

df['sma1']= ta.sma(df['close'], length=50)

entry = (df['sma']>df['sma1'] )& (df['RSI']  >20) 
```

is this correct way

**Comment by twopirllc** [comment]
Hello @ahmed159159,

Upgrade to the _development_ version if not already:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

- I recommend reading Issue #406.
    - It covers how to use ```ta.xsignals()``` which is useful for indicators like **rsi** which are event based. For more info, see ```help(ta.xsignals)```.
    - There is also ```ta.tsignals()``` which are useful indicators like moving averages which can be trend based. For more info, see ```help(ta.tsignals)```.
    - A more complicated example, see #587.

For you particular case: ```entry = (df['sma']>df['sma1'] )& (df['RSI']  >20) ```

What do you mean by: ```df['RSI']  >20```? Whenever RSI is above 20? Or when RSI crosses above 20 and then below 20? Do you not have an upper bound? 

Kind Regards,
KJ

**Comment by ahmed159159** [comment]
> Hello @ahmed159159,
> 
> Upgrade to the _development_ version if not already:
> 
> ```shell
> $ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
> ```
> 
> * I recommend reading Issue [How to use cross? #406](https://github.com/twopirllc/pandas-ta/issues/406).
>   
>   * It covers how to use `ta.xsignals()` which is useful for indicators like **rsi** which are event based. For more info, see `help(ta.xsignals)`.
>   * There is also `ta.tsignals()` which are useful indicators like moving averages which can be trend based. For more info, see `help(ta.tsignals)`.
>   * A more complicated example, see [Boolean Operations on Multiple (X)Signals #587](https://github.com/twopirllc/pandas-ta/issues/587).
> 
> For you particular case: `entry = (df['sma']>df['sma1'] )& (df['RSI'] >20) `
> 
> What do you mean by: `df['RSI'] >20`? Whenever RSI is above 20? Or when RSI crosses above 20 and then below 20? Do you not have an upper bound?
> 
> Kind Regards, KJ

RSi >20  the value of rsi be over 20

**Comment by ahmed159159** [comment]
so if the valuo of rsi over 20 and sma 20 cross over sma 50  ths be buy signal

**Comment by twopirllc** [comment]
@ahmed159159

#### You
> how to combine more than condition to be entry point for example
```python
df['RSI'] = ta.rsi(df['close'], length=14)
df['sma']= ta.sma(df['close'], length=14)

df['sma1']= ta.sma(df['close'], length=50)

entry = (df['sma']>df['sma1'] )& (df['RSI']  >20) 
```

> is this correct way?
so if the value of rsi over 20 and in the same time sma crose over sma1  this will be a buy signal how to do this 
or ```entry = (ta.cross(ema, ema1)) & (rsi > 20)```

**Comment by twopirllc** [comment]
@ahmed159159,

Did you _read_ and _try_ anything suggested from my March 29th comment above?

> ```entry = (ta.cross(ema, ema1)) & (rsi > 20)```

Will **not** work as anticipated.
