### ISSUE TITLE
no module named pandas-ta and no module named pandas_ta when installing using conda install -c conda-forge pandas-ta

### ISSUE THREAD

**Issue by jan1379** [twopirllc/pandas-ta#677]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**

**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @jan1379,

The Python package is called: ```pandas_ta```. Not to be confused with the Github URL name: ```pandas-ta```.

For more help, please see Anaconda's [Help](https://docs.anaconda.com/anaconda/user-guide/tasks/install-packages/) on installing Python packages.

Kind Regards,
KJ
