### ISSUE TITLE
strategy error

### ISSUE THREAD

**Issue by saetthakij** [twopirllc/pandas-ta#680]
pip show pandas_ta
Version: 0.3.14b0
Python 3.9.16
TA-Lib 0.4.24

df2.ta.strategy('candles')
df.ta.strategy('momentum')
does not work as it use to be

it should give me columns of feature related to a specific strategy

data example 
<class pandas.core.frame.DataFram'>
DatetimeIndex: 331 entries, 2021-12-09 to 2023-04-21
Data columns (total 5 columns):
Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   open    331 non-null    float64
 1   high    331 non-null    float64
 2   low     331 non-null    float64
 3   close   331 non-null    float64
 4   Volume  331 non-null    int64  
dtypes: float64(4), int64(1)

error code
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[30], line 11
      6 df.set_index("time", inplace = True)
      7     #pdta_extract_df2 = pdta_extract_df.copy()
      8     
      9     #create and clean cdl
     10 #df.ta.strategy('candles')
---> 11 df.ta.strategy('momentum')

File ~\anaconda3\envs\py39\lib\site-packages\pandas_ta\core.py:725, in AnalysisIndicators.strategy(self, *args, **kwargs)
    723 if use_multiprocessing:
    724     _total_ta = len(ta)
--> 725     with Pool(self.cores) as pool:
    726         # Some magic to optimize chunksize for speed based on total ta indicators
    727         _chunksize = mp_chunksize - 1 if mp_chunksize > _total_ta else int(npLog10(_total_ta)) + 1
    728         if verbose:

File ~\anaconda3\envs\py39\lib\multiprocessing\context.py:119, in BaseContext.Pool(self, processes, initializer, initargs, maxtasksperchild)
    117 '''Returns a process pool object'''
    118 from .pool import Pool
--> 119 return Pool(processes, initializer, initargs, maxtasksperchild,
    120             context=self.get_context())

File ~\anaconda3\envs\py39\lib\multiprocessing\pool.py:212, in Pool.__init__(self, processes, initializer, initargs, maxtasksperchild, context)
    210 self._processes = processes
    211 try:
--> 212     self._repopulate_pool()
    213 except Exception:
    214     for p in self._pool:

File ~\anaconda3\envs\py39\lib\multiprocessing\pool.py:303, in Pool._repopulate_pool(self)
    302 def _repopulate_pool(self):
--> 303     return self._repopulate_pool_static(self._ctx, self.Process,
    304                                         self._processes,
    305                                         self._pool, self._inqueue,
    306                                         self._outqueue, self._initializer,
    307                                         self._initargs,
    308                                         self._maxtasksperchild,
    309                                         self._wrap_exception)

File ~\anaconda3\envs\py39\lib\multiprocessing\pool.py:326, in Pool._repopulate_pool_static(ctx, Process, processes, pool, inqueue, outqueue, initializer, initargs, maxtasksperchild, wrap_exception)
    324 w.name = w.name.replace('Process', 'PoolWorker')
    325 w.daemon = True
--> 326 w.start()
    327 pool.append(w)
    328 util.debug('added worker')

File ~\anaconda3\envs\py39\lib\multiprocessing\process.py:121, in BaseProcess.start(self)
    118 assert not _current_process._config.get('daemon'), \
    119        'daemonic processes are not allowed to have children'
    120 _cleanup()
--> 121 self._popen = self._Popen(self)
    122 self._sentinel = self._popen.sentinel
    123 # Avoid a refcycle if the target function holds an indirect
    124 # reference to the process object (see bpo-30775)

File ~\anaconda3\envs\py39\lib\multiprocessing\context.py:327, in SpawnProcess._Popen(process_obj)
    324 @staticmethod
    325 def _Popen(process_obj):
    326     from .popen_spawn_win32 import Popen
--> 327     return Popen(process_obj)

File ~\anaconda3\envs\py39\lib\multiprocessing\popen_spawn_win32.py:45, in Popen.__init__(self, process_obj)
     44 def __init__(self, process_obj):
---> 45     prep_data = spawn.get_preparation_data(process_obj._name)
     47     # read end of pipe will be duplicated by the child process
     48     # -- see spawn_main() in spawn.py.
     49     #
     50     # bpo-33929: Previously, the read end of pipe was "stolen" by the child
     51     # process, but it leaked a handle if the child process had been
     52     # terminated before it could steal the handle from the parent process.
     53     rhandle, whandle = _winapi.CreatePipe(None, 0)

File ~\anaconda3\envs\py39\lib\multiprocessing\spawn.py:183, in get_preparation_data(name)
    180 # Figure out whether to initialise main in the subprocess as a module
    181 # or through direct execution (or to leave it alone entirely)
    182 main_module = sys.modules['__main__']
--> 183 main_mod_name = getattr(main_module.__spec__, "name", None)
    184 if main_mod_name is not None:
    185     d['init_main_from_name'] = main_mod_name

AttributeError: module '__main__' has no attribute '__spec__'`

**Comment by twopirllc** [comment]
Hello @saetthakij,

> does not work as it use to be

What do you mean?

I assume you changed some code it is returning: [
AttributeError: module '__main__' has no attribute '__spec__'`](https://www.google.com/search?client=firefox-b-1-d&q=+AttributeError%3A+module+%27__main__%27+has+no+attribute+%27__spec__%27%60) which is a Python Error and **not** a Pandas TA Error. The links should provide some guidance on how to resolve it.

Kind Regards,
KJ

**Comment by saetthakij** [comment]
sorry for not state the problem clearly. the word "it use to be" meaning that normally when i use .ta.strategy() i would get new columns base on strategy i chose. however, after i run the code recently. i find that the same set of code does not work and give me the error. i also trying to copy code from https://github.com/twopirllc/pandas-ta#types-of-strategies in Categorical section and run with my code. unfortunately, it still error and i have no idea what is going on and what to look for. 

```
<class pandas.core.frame.DataFrame>
RangeIndex: 331 entries, 0 to 330
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   time    331 non-null    datetime64[ns]
 1   open    331 non-null    float64       
 2   high    331 non-null    float64       
 3   low     331 non-null    float64       
 4   close   331 non-null    float64       
 5   Volume  331 non-null    int64         
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 15.6 KB
```


> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[28], line 6
>       4 df = cleansing(df)
>       5 df = df.rename(columns={"volume": "Volume"})
> ----> 6 df.ta.strategy("Momentum")
> 
> File ~\anaconda3\envs\py39\lib\site-packages\pandas_ta\core.py:725, in AnalysisIndicators.strategy(self, *args, **kwargs)
>     723 if use_multiprocessing:
>     724     _total_ta = len(ta)
> --> 725     with Pool(self.cores) as pool:
>     726         # Some magic to optimize chunksize for speed based on total ta indicators
>     727         _chunksize = mp_chunksize - 1 if mp_chunksize > _total_ta else int(npLog10(_total_ta)) + 1
>     728         if verbose:
> 
> File ~\anaconda3\envs\py39\lib\multiprocessing\context.py:119, in BaseContext.Pool(self, processes, initializer, initargs, maxtasksperchild)
>     117 '''Returns a process pool object'''
>     118 from .pool import Pool
> --> 119 return Pool(processes, initializer, initargs, maxtasksperchild,
>     120             context=self.get_context())
> 
> File ~\anaconda3\envs\py39\lib\multiprocessing\pool.py:212, in Pool.__init__(self, processes, initializer, initargs, maxtasksperchild, context)
>     210 self._processes = processes
>     211 try:
> --> 212     self._repopulate_pool()
>     213 except Exception:
>     214     for p in self._pool:
> 
> File ~\anaconda3\envs\py39\lib\multiprocessing\pool.py:303, in Pool._repopulate_pool(self)
>     302 def _repopulate_pool(self):
> --> 303     return self._repopulate_pool_static(self._ctx, self.Process,
>     304                                         self._processes,
>     305                                         self._pool, self._inqueue,
>     306                                         self._outqueue, self._initializer,
>     307                                         self._initargs,
>     308                                         self._maxtasksperchild,
>     309                                         self._wrap_exception)
> 
> File ~\anaconda3\envs\py39\lib\multiprocessing\pool.py:326, in Pool._repopulate_pool_static(ctx, Process, processes, pool, inqueue, outqueue, initializer, initargs, maxtasksperchild, wrap_exception)
>     324 w.name = w.name.replace('Process', 'PoolWorker')
>     325 w.daemon = True
> --> 326 w.start()
>     327 pool.append(w)
>     328 util.debug('added worker')
> 
> File ~\anaconda3\envs\py39\lib\multiprocessing\process.py:121, in BaseProcess.start(self)
>     118 assert not _current_process._config.get('daemon'), \
>     119        'daemonic processes are not allowed to have children'
>     120 _cleanup()
> --> 121 self._popen = self._Popen(self)
>     122 self._sentinel = self._popen.sentinel
>     123 # Avoid a refcycle if the target function holds an indirect
>     124 # reference to the process object (see bpo-30775)
> 
> File ~\anaconda3\envs\py39\lib\multiprocessing\context.py:327, in SpawnProcess._Popen(process_obj)
>     324 @staticmethod
>     325 def _Popen(process_obj):
>     326     from .popen_spawn_win32 import Popen
> --> 327     return Popen(process_obj)
> 
> File ~\anaconda3\envs\py39\lib\multiprocessing\popen_spawn_win32.py:45, in Popen.__init__(self, process_obj)
>      44 def __init__(self, process_obj):
> ---> 45     prep_data = spawn.get_preparation_data(process_obj._name)
>      47     # read end of pipe will be duplicated by the child process
>      48     # -- see spawn_main() in spawn.py.
>      49     #
>      50     # bpo-33929: Previously, the read end of pipe was "stolen" by the child
>      51     # process, but it leaked a handle if the child process had been
>      52     # terminated before it could steal the handle from the parent process.
>      53     rhandle, whandle = _winapi.CreatePipe(None, 0)
> 
> File ~\anaconda3\envs\py39\lib\multiprocessing\spawn.py:183, in get_preparation_data(name)
>     180 # Figure out whether to initialise main in the subprocess as a module
>     181 # or through direct execution (or to leave it alone entirely)
>     182 main_module = sys.modules['__main__']
> --> 183 main_mod_name = getattr(main_module.__spec__, "name", None)
>     184 if main_mod_name is not None:
>     185     d['init_main_from_name'] = main_mod_name
> 
> AttributeError: module '__main__' has no attribute '__spec__'

**Comment by twopirllc** [comment]
@saetthakij,

> unfortunately, it still error and i have no idea what is going on and what to look for.

I recommend _trying_ the suggestions from the link I provided. I do not understand what you are doing differently in your code that requires one to include the 'spec' attribute in **main**. Unfortunately the code you provided is insufficient to help triage why you need the 'spec' attribute for your case. 

KJ
