### ISSUE TITLE
CAGRs are off due to 'years' calculation

### ISSUE THREAD

**Issue by hmTodd** [twopirllc/pandas-ta#684]
I noticed a diff in CAGR results and traced back to total_time() function in utils/_time. 
This line:  "years": time_diff.days / RATE["TRADING_DAYS_PER_YEAR"], 
will return 1.448 years when one year of data is passed in the df.
Need to divide by 365.2425 or whatever you use for one year.

As an example, if you load a year's duration of SPY stock data, say 2022-01-01 through 2023-01-01, you will have 252 days of data but the time_diff.days will be 365 and the number of years should be very near 1.0.

Thanks, and an otherwise nice project.

**Comment by twopirllc** [comment]
Hello @hmTodd,

Thanks!

Yes this is true with _v0.3.14b_. However, it has been resolved via a [PR](https://github.com/twopirllc/pandas-ta/pull/602/files) and available on the _development_ branch.

Per the Bug Form:
> **Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

If you can not install it that way, you can download a zip of the [code](https://github.com/twopirllc/pandas-ta/tree/development) and do a [local pip install](https://www.google.com/search?client=firefox-b-1-d&q=local+pip+install+package).

Lastly if you have further Issues, it would be **great** if you could fill out as much of the _requested_ information on the Bug Form as possible. It really helps! 😎 

Kind Regards,
KJ
