### ISSUE TITLE
Study fails permanently after using it on a data frame with too few rows

### ISSUE THREAD

**Issue by brianensink** [twopirllc/pandas-ta#686]
A similar issue was previously reported [520](https://github.com/twopirllc/pandas-ta/issues/520) but it was closed. I've attached a complete example with data that will hopefully demonstrate the bug still exists.

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.3.88b0

**Do you have _TA Lib_ also installed in your environment?**
No

**Have you tried the _development_ version? Did it resolve the issue?**
Yes I tried the development version.
No it did not resolve the issue. The issue also occurs in latest main release

**Describe the bug**
A `Study` stops working after using it on a data frame with too few rows needed for some of the indicators in the study. The `Study` will no longer work on subsequent data frames even when the data frame contains enough rows.

**To Reproduce**
The code below has two data sets and attempts to produce a SMA 5 on the data sets. One data set contains too few rows. The study will not produce the SMA 5 on the larger data set after using the study on the smaller dataset.

```python
import pandas as pd
import pandas_ta as ta
import io

EnoughRows = """
  datetime,open,high,low,close,volume
  2022-02-22,164.98000,166.69000,162.14999,164.32001,91163000
  2022-02-23,165.53999,166.14999,159.75000,160.07001,90009000
  2022-02-24,152.58000,162.85001,152.00000,162.74001,141148000
  2022-02-25,163.84000,165.12000,160.87379,164.85001,91974000
  2022-02-28,163.06000,165.42000,162.42999,165.12000,95057000
  2022-03-01,164.69501,166.60001,161.97000,163.20000,83474000
  2022-03-02,164.39000,167.36000,162.95000,166.56000,79725000
  2022-03-03,168.47000,168.91000,165.55000,166.23000,76678000
  2022-03-04,164.49001,165.55000,162.10001,163.17000,83820000
  2022-03-07,163.36000,165.02000,159.03999,159.30000,96419000
  2022-03-08,158.82001,162.88000,155.80000,157.44000,131148000
  """
TooFewRows = """
  datetime,open,high,low,close,volume
  2022-02-22,164.98000,166.69000,162.14999,164.32001,91163000
  2022-02-23,165.53999,166.14999,159.75000,160.07001,90009000
  2022-02-24,152.58000,162.85001,152.00000,162.74001,141148000
  2022-02-25,163.84000,165.12000,160.87379,164.85001,91974000
  """

if __name__ == "__main__":
  SimpleStudy = ta.Study(
      name="MA",
      description="",
      ta=[
        {"kind": "sma", "length": 5 }
      ]
  )

  # The study produces the SMA_5 as expected
  df1 = pd.read_csv(io.StringIO(EnoughRows), sep=",")
  df1.ta.study(SimpleStudy)
  assert "SMA_5" in df1.columns # Column exists as expected

  # The study does not produce the SMA_5 beause there are too few rows
  df2 = pd.read_csv(io.StringIO(TooFewRows), sep=",")
  df2.ta.study(SimpleStudy)
  assert "SMA_5" not in df2.columns # Column does not exist as expected

  # But now the study stops working even when given enough rows to produce the SMA_5
  df3 = pd.read_csv(io.StringIO(EnoughRows), sep=",")
  df3.ta.study(SimpleStudy)
  assert "SMA_5" in df3.columns # FAILS
```

**Expected behavior**
In the above code I expect the study to produce the "SMA_5" series when given a data frame with enough rows, but it does not. In general I expect the `Study` to be reusable.

**Comment by twopirllc** [comment]
Hello @brianensink,

Unfortunately, I never heard back from the original poster in Issue #520. At the time, my interim tests worked as expected.

Nonetheless, I updated the _development_ branch so ```df.ta.study()``` is reusable and ignores the too few rows case as expected. Let me know if it works for you as expected.

### Incremental TA Test
```python
SimpleStudy = ta.Study(name="SMA Test", cores=0, ta=[{"kind": "sma", "length": 5}])

def incremental_ta(**kwargs):
    df, study, = kwargs["df"], kwargs["study"]
    bars, start, stride = int(kwargs["bars"]), int(kwargs["start"]), int(kwargs["stride"])
    if start <= 0: start = 1
    if stride <= 0: stride = 1

    df = df.iloc[:bars]
    m = df.shape[0]

    for i in range(start, m, stride):
        _df = df.iloc[:i]
        _df.ta.study(study, cores=0)
        print(f"{_df}\n{'='*71}\n")

tmpdf = pd.DataFrame().ta.ticker("qqq", period="1y")
tmpdf.drop(columns=["adjClose", "Dividends", "Stock Splits"], errors="ignore", inplace=True)
incremental_ta(df=tmpdf, study=SimpleStudy, bars=7, start=4, stride=1)
```

### Output
![Screenshot 2023-05-09 at 2 31 30 PM](https://github.com/twopirllc/pandas-ta/assets/18198392/47999c45-8889-414d-9e89-0075bb5011b9)

Kind Regards,
KJ

**Comment by brianensink** [comment]
Yes this fix works for me as as well. Thank you for the quick turnaround!

**Comment by twopirllc** [comment]
@brianensink,

Awesome! Thanks for letting me know.

KJ
