### ISSUE TITLE
About RSI question

### ISSUE THREAD

**Issue by homily** [twopirllc/pandas-ta#69]
hi。
when i use the RSI calc，it different with Tradingview。
the tradingview use RMA calc

url：https://www.tradingview.com/support/solutions/43000502338-relative-strength-index-rsi/
```
Calculation
RSI = 100 – 100/ (1 + RS)
RS = Average Gain of n days UP  / Average Loss of n days DOWN
For a practical example, the built-in Pine Script function rsi(), could be replicated in long form as follows.

change = change(close)
gain = change >= 0 ? change : 0.0
loss = change < 0 ? (-1) * change : 0.0
avgGain = rma(gain, 14)
avgLoss = rma(loss, 14)
rs = avgGain / avgLoss
rsi = 100 - (100 / (1 + rs))
"rsi", above, is exactly equal to rsi(close, 14).
```
so, Maybe you can view or update the calc code. ^_^

**Comment by twopirllc** [comment]
Hi @homily,

Currently ```rsi``` has at least 99% correlation with _TA Lib_, so it is not a high priority right now. 

That being said, I do not mind adding a _TradingView_ version, but it is more difficult to test against as they do not have an easily testable library. If you know of a better and quicker way to test and compare vs _TradingView_, let me know what needs to be modified so that it matches _TradingView_.

Differences in languages (Python and Pinescript in this case) and how they handle decimals/floats can easily cause minor differences in calculations. What is the current correlation between ```pandas-ta``` and _TradingView_'s ```rsi```?

Regards,
KJ

**Comment by homily** [comment]
Yes, thank you very much.

I've been using your library and it's very convenient.



I think it is very necessary to add tradingview. After all, there are many open scripts written with pin script. If tradingview can be effectively supported, it will be greatly convenient for all users.

**Comment by twopirllc** [comment]
Heya @homily,

Thank you!

Also, thanks for your patience. Yes, I do like TradingView and some of my own TV indicators are also incorporated in **Pandas TA**. If think the differences you may be seeing are the may be the differences in data sources; TV's data source and your data source may not be the same. Computationally, they are the same.

Thanks,
KJ

**Comment by twopirllc** [comment]
@homily,

Revamped **stoch** added **stochrsi**. Both are inline with TradingView.
Use ```help(ta.stoch)``` and ```help(ta.stochrsi)``` for more info.

Thanks,
KJ

**Comment by Vesnog** [comment]
What are the default parameters to get the same RSI reading in Binance, TradingView and this library? I am pretty confused with various methods for calculation of RSI and some explanatory answer will be appreciate greatly.  I call them in the following manner to compare directly with Binance: 

```
    bars_df['rsi7'] = ta.stochrsi(bars_df.close, length=7, rsi_length=14, k=3, d=3)
    bars_df['rsi14'] = ta.rsi(bars_df.close, length=14, rsi_length=14, k=3, d=3)
    bars_df['rsi24'] = ta.rsi(bars_df.close, length=24, rsi_length=14, k=3, d=3)
```

**Comment by twopirllc** [comment]
Hello @Vesnog,

Standard literature for **RSI** has a default length of **14** including most platforms as well as this library.

**STOCHRSI** is the result of applying **STOCH** to **RSI** or in otherwords **STOCHRSI** = **STOCH(_RSI_)**. If you believe **STOCHRSI** has significance then use it, if not then do not include it. Same with any other indicator. Only you can make that determination.

You shouldn't have to call them that way. You are including _kwargs_ in **RSI** that serve no purpose. Recall that you can use ```help(ta.rsi)``` or ```help(ta.stochrsi)``` to list the available _args_ and _kwargs_.

Here are some ways of calling the indicators you listed above:

## **Standard**

```python
import pandas as pd
import pandas_ta as ta

bars_df = # ohlcv data
bars_df["stochrsi7"] = ta.stochrsi(bars_df.close, length=7)
bars_df["rsi14"] = ta.stochrsi(bars_df.close)
bars_df["rsi24"] = ta.stochrsi(bars_df.close, length=24)
```

## **Pandas TA DataFrame**

```python
import pandas as pd
import pandas_ta as ta

bars_df = # ohlcv data
bars_df.ta.stochrsi(length=7, append=True)
bars_df.ta.stochrsi(append=True)
bars_df.ta.stochrsi(length=24, append=True)
```

## **Pandas TA Strategy**

```python
import pandas as pd
import pandas_ta as ta

bars_df = # ohlcv data

# (1) Create the Strategy
RSIStrategies = ta.Strategy(
    name="RSI and STOCHRSI",
    ta=[
        {"kind": "stochrsi", "length": 7},
        {"kind": "rsi"},
        {"kind": "rsi", "length": 24},
    ]
)

# (2) Run the Strategy
bars_df.ta.strategy(RSIStrategies)
```

<br/>

Hope this helps and makes sense!

Kind Regards,
KJ
