### ISSUE TITLE
Cannot import pandas_ta after update to latest 0.3.94b

### ISSUE THREAD

**Issue by khiemdoan** [twopirllc/pandas-ta#692]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
`Python 3.11` and `pandas_ta 0.3.94b`

**Do you have _TA Lib_ also installed in your environment?**
*No*

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
*Yes*

**Describe the bug**
Can not import pandas_ta.

**To Reproduce**
```sh
Python 3.11.3 (main, May 23 2023, 13:34:03) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas_ta as ta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.11/site-packages/pandas_ta/__init__.py", line 8, in <module>
    from pandas_ta.utils import *
  File "/opt/venv/lib/python3.11/site-packages/pandas_ta/utils/__init__.py", line 6, in <module>
    from ._numba import *
  File "/opt/venv/lib/python3.11/site-packages/pandas_ta/utils/_numba.py", line 19, in <module>
    @njit(cache=True)
     ^^^^^^^^^^^^^^^^
TypeError: njit() got an unexpected keyword argument 'cache'
```

**Comment by twopirllc** [comment]
@khiemdoan 

Try: ```pip install numba```

Status quo wants more performance. So I have been slowly introducing _numpy/numba_ support to the library. I believe ```numba``` is worth adding as a necessary requirement moving forward. What do you think?

Kind Regards,
KJ

**Comment by khiemdoan** [comment]
For people who got the same error as me, just install an older version. Example version 0.3.92b:

```bash
pip install git+https://github.com/twopirllc/pandas-ta.git@89b79a4b18fb746ac199e2ce464546758153e547
```

**Comment by twopirllc** [comment]
@khiemdoan 

>I totally agree we need using `numba` to improve the performance.
> * If `numba` is mandatory, we should include it as a dependency.

👍🏼 I will be making it a requirement.

> I tried to install numba 0.57.0 but I got another error:
```RuntimeError: cannot cache function 'np_prepend': no locator available ...```

I see that you are on Linux. On my M1 MB, I updated my ```numba``` to _0.57.0_ but I do not get a `np_prepend` RuntimeError. 🤔 

KJ

**Comment by twopirllc** [comment]
Hello @devanshu125

I am running numpy version _1.24.3_.

**Comment by khiemdoan** [comment]
I have updated this library to `0.4.2b`. I don't know why but everything is ok. Thanks!
