### ISSUE TITLE
Append Method deprecated

### ISSUE THREAD

**Issue by artarrifa** [twopirllc/pandas-ta#695]
/Users/alexistarrifa/miniconda3/envs/tensorflow/lib/python3.10/multiprocessing/pool.py:48: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead. 

Is there anyone working on this method change from append to concat?

**Comment by twopirllc** [comment]
Hello @artarrifa,

Yes, it was taken care of on the *development* branch:
```$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development```.

It is only a *warning* message and **not** a bug. In most cases, it is faster to **not** use multiprocessing. Multiprocessing can be disabled by setting cores to zero.

Lastly in the future, please fill out the Bug Report form. The more information the better.

Kind Regards,
KJ
