### ISSUE TITLE
dl() function in VectorBT_Backtest_with_Pandas_TA jupyter notebook reports eUnboundLocalError when using "lc_cols=True" argument

### ISSUE THREAD

**Issue by xieliaing** [twopirllc/pandas-ta#696]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
Pandas TA v0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
TA-Lib  0.4.24 installed

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
Tried, not resolving the issue

**Describe the bug**
Try to ran VectorBT_Backtest_with_Pandas_TA jupyter notebook, and got the following error message at *Data Acquisition* section for the cell running 
```python
benchmarks = dl(benchmark_tickers, lc_cols=True)
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[6], line 1
----> 1 benchmarks = dl(benchmark_tickers, lc_cols=True)

Cell In[3], line 46, in dl(tickers, same_start, **kwargs)
     44     _df = pd.DataFrame()
     45     for ticker in tickers:
---> 46         received[ticker] = _df.ta.ticker(ticker, **kwargs)
     47         print(f"[+] {ticker}{received[ticker].shape} {ta.get_time(full=False, to_string=True)}")
     49 if same_start and len(tickers) > 1:

File D:\Anaconda\lib\site-packages\pandas_ta\core.py:851, in AnalysisIndicators.ticker(self, ticker, **kwargs)
    849 ds = ds.lower() is not None and isinstance(ds, str)
    850 # df = av(ticker, **kwargs) if ds and ds == "av" else yf(ticker, **kwargs)
--> 851 df = yf(ticker, **kwargs)
    853 if df is None: return
    854 elif df.empty:

File D:\Anaconda\lib\site-packages\pandas_ta\utils\data\yahoofinance.py:99, in yf(ticker, **kwargs)
     96         print(f"[!] https://github.com/ranaroussi/yfinance/issues/760#issuecomment-877355832")
     97         return
---> 99 if df.empty: return
    100 df.name = ticker
    102 try:

UnboundLocalError: local variable 'df' referenced before assignment

On the other hand, if I remove  *lc_cols=True* from the arguments:
```python
benchmarks = dl(benchmark_tickers)
```
data were successfully downloaded:

[i] Downloading: SPY, QQQ
[+] SPY(7651, 8) Friday June 16, 2023, NYSE: 18:54:49
[+] QQQ(6109, 8) Friday June 16, 2023, NYSE: 18:54:49
[*] Download Complete

**To Reproduce**
Just ran the jupyter notebook

**Expected behavior**
Obtain dataframes for all five assets listed.

**Screenshots**
screenshots of errors.
![image](https://github.com/twopirllc/pandas-ta/assets/9838639/52dd5c6b-9e4c-4655-a043-217bac2bce46)

Below is screenshot of successful run without lc_col argument:
![image](https://github.com/twopirllc/pandas-ta/assets/9838639/c904e4a2-2cb4-4e73-9627-4de70897ce37)

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @xieliaing,

Seems like a legacy artifact., so thanks for letting me know this issue still exists on the old version.

Also the keyword argument ```lc_cols``` has been removed from ```df.ta.ticker(**kwargs)``` on the _development_ version as well as it's _developement_ [notebook example](https://github.com/twopirllc/pandas-ta/blob/development/examples/VectorBT_Backtest_with_Pandas_TA.ipynb); so it does resolve the issue.

In any case, please use the _development_ branch of the library in the mean time.

Kind Regards,
KJ
