### ISSUE TITLE
About add Stochastic RSI (STOCH RSI)

### ISSUE THREAD

**Issue by homily** [twopirllc/pandas-ta#70]
hi. When I studied the technical indicators, I found that Stochastic RSI is useful。
so，I modified the RSI code appropriately，But it's not perfect.
I want to add it to the code with your expertise。
Thanks! 

calc in tradingview URL：
https://www.tradingview.com/support/solutions/43000502333-stochastic-rsi-stoch-rsi/

my code：
```
def stochrsi(close, length=None, scalar=None, drift=None,**kwargs):
    # Validate arguments
    length = int(length) if length and length > 0 else 14
    scalar = 100
    drift = int(drift) if drift and drift != 0 else 1

    # Calculate Result
    negative = close.diff(drift)
    positive = negative.copy()

    positive[positive < 0] = 0  # Make negatives 0 for the postive series
    negative[negative > 0] = 0  # Make postives 0 for the negative series
    
    alpha = (1.0 / length) if length > 0 else 0.5
    positive_avg = positive.ewm(alpha=alpha, adjust=False).mean()
    negative_avg = negative.ewm(alpha=alpha, adjust=False).mean().abs()

    rsi = scalar * positive_avg / (positive_avg + negative_avg)
    rsi_low   =  rsi.rolling(length).min()
    rsi_high =  rsi.rolling(length).max()

    fastk = 100 * (rsi - rsi_low) / (rsi_high-rsi_low)

    slowk = fastk.rolling(3).mean()
    slowd = slowk.rolling(3).mean()

    stochdf = pd.DataFrame(list(zip(rsi, slowk,slowd)))
    stochdf.columns=['rsi', 'stochrsi', 'stochrsi_3']

    return stochdf
```

**Comment by twopirllc** [comment]
Hi @homily,

Sure it can be added. I have some other things to clean up and add first and then I can add it to ```pandas-ta```.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hey @homily,

There is an easier solution. How about either having a flag to turn in on in ```ta.rsi``` like ```ta.rsi(stoch=True)``` with default: ```False```. Or by default ```ta.rsi``` returns ```rsi``` and ```stochrsi``` columns? Two for one?

Thanks,
KJ

**Comment by homily** [comment]
Hello, thank you very much for your busy time to discuss this matter with me. I think stochrsi is a separate indicator, and it's better to list it separately.

**Comment by twopirllc** [comment]
@homily,

Seems a little redundant, but doable. I will work it in after I finish developing and testing the current indicator I am working on porting from TradingView.

Thanks,
KJ

**Comment by twopirllc** [comment]
@homily,

Completed! Use ```help(ta.stochrsi)``` for info.

KJ
