### ISSUE TITLE
`ta.volatility` namespace overwritten by `ta.volatility()`

### ISSUE THREAD

**Issue by JanHomann** [twopirllc/pandas-ta#702]
```
pandas-ta       0.3.14b0
TA-Lib          0.4.27
```

### Problem Description
I assume that `ta.volatility` should give you access to all volatility indicators. Unfortunately it seems to have been overwritten by a function `ta.volatility()`. This is very unfortunately, because access to a list (through tab complete) that separates out all volatility indicators is lost. 

### Example
```
ta.volatility.atr()
>> AttributeError: 'function' object has no attribute 'atr'
```

### Expected Behavior
Should execute the `atr()` function.

### Additional Context
The reason for this bug might be the recent addition of an indicator called `volatility()`.

**Comment by twopirllc** [comment]
Hello @JanHomann,

This has been _resolved_ as can be tested with the _development_ branch (as well as #706)
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ

**Comment by JanHomann** [comment]
Hi @twopirllc. Thanks for pointing me to the development version. I wonder why you don’t merge the development version with the main branch. It seems to have a lot of fixes.

**Comment by twopirllc** [comment]
@JanHomann

> Thanks for pointing me to the development version. 

Sure. However, this question was asked on each of your 4 Bug Report Forms which you chose to omit and not try.

❌ **Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

> It seems to have a lot of fixes.

Yes

> I wonder why you don’t merge the development version with the main branch.I wonder why you don’t merge the development version with the main branch.

In short, it is easier to manage given one consistent developer. With more consistent help, the library can grow faster with frequent and updated versions. 

Help can include (and not limited to) improving documentation, adding/updating examples, handle (research & test) issues, fix bugs, include new indicators and supplemental features or by [sponsoring](https://github.com/twopirllc) or [donating](https://www.buymeacoffee.com/twopirllc).

Until then, the next _main_ merge will occur after the remaining non-candlestick indicators from TA Lib; namely the [```ht_*``` indicators](https://github.com/twopirllc/pandas-ta/tree/development#todo) have be added, some core indicators have been _numba-fied_ to improve overall speed as well as any outstanding Pull Requests.

KJ
