### ISSUE TITLE
Lookahead bias on Ehler's Super Smoother Filter (SSF)

### ISSUE THREAD

**Issue by stash86** [twopirllc/pandas-ta#705]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
Latest on github

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
Yes

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
No

**Describe the bug**
For [this line](https://github.com/twopirllc/pandas-ta/blob/084dbe1c4b76082f383fa3029270ea9ac35e4dc7/pandas_ta/overlap/ssf.py#L35), when i  is less than 3, some or all of the calculations are taking futures data.

For [this line](https://github.com/twopirllc/pandas-ta/blob/084dbe1c4b76082f383fa3029270ea9ac35e4dc7/pandas_ta/overlap/ssf.py#L45), it's i less than 2

Also side note, since this is recursive loop, that means where you start the data would also affect the values at last rows. Not sure if this is avoidable, but at least put some notes to make users aware of this?

**To Reproduce**
Calculate SSF based of series of data. Note the first 3 rows. Then reduce the end data. The first 3 rows' value would be different.

**Expected behavior**
The first 3 rows' value should stay the same, no matter where you end the data

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @stash86,

I totally reworked __ssf__ to fix those indexing issues (<=2 and <=3) awhile ago including making it _numba-fied_ to improve its performance. But to verify if it is better, you will need to install the _development_ branch to do so (directions above on _dev_ installation).

Let me know if it works better and if there are additional issues related to __ssf__.

Kind Regards,
KJ
