### ISSUE TITLE
I try to convert Predictive Ranges [LuxAlgo] to the py, whats the problem?

### ISSUE THREAD

**Issue by kaanguven** [twopirllc/pandas-ta#712]
closed

**Comment by twopirllc** [comment]
Hi @kaanguven,

Sorry I have not been able to review this. Been swamped. 😑  Hopefully someone else can help or give some insight on how to fix it before I can get to it!

KJ

**Comment by peachonpizza** [comment]
What do you mean _"According to pinescript, the output in my python code is wrong"_ ?

**Comment by kaanguven** [comment]
> What do you mean _"According to pinescript, the output in my python code is wrong"_ ?

When i check it on tradingview line values are different from my python output
