### ISSUE TITLE
Aroon doc string

### ISSUE THREAD

**Issue by Heraklaitos** [twopirllc/pandas-ta#714]
Hi,

First of all thanks for the great lib. 
I just saw some inconsistency in the doc string of Aroon indicator which can be acessed from link below:
https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/trend/aroon.py

The arguments are high, low, length=None etc... But in the help output Args are listed as:
'
Args:
    close (pd.Series): Series of 'close's
    length (int): It's period. Default: 14
'

Maybe I'm missing something but shouldn't the args in the docstring high and low instead of close? 

Best wishes,

**Comment by sampanacharya** [comment]
HI @Heraklaitos 
I have resolved this issue in my pull request do please review it.
Thanks

**Comment by twopirllc** [comment]
Hello @Heraklaitos @sampanacharya,

Thanks for the update! 😎 Available on the _development_ branch.

KJ
