### ISSUE TITLE
Decay Function Showing Incorrect Results Where Length Greater Than 1

### ISSUE THREAD

**Issue by PVGibson** [twopirllc/pandas-ta#715]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
3.99b0

**Do you have _TA Lib_ also installed in your environment?**
Yes

**Have you tried the _development_ version? Did it resolve the issue?**
Tested in development version.  

**Describe the bug**
According to the documentation provided at https://tulipindicators.org/decay if length is 4 and signals are:

[0, 0, 0, 1, 0, 0, 0, 1]

the output of the decay indicator should be:

[0, 0, 0, 1, .75, 0.5, 0.25, 1]

instead the output is:

[0, 0, 0, 1, .75, 0, 0, 1]

**Expected behavior**
Decay should work for lengths greater than 1 as described in documentation.

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @PVGibson,

Thanks for finding this and letting me know. 😎 

Kind Regards,
KJ

**Comment by sampanacharya** [comment]
HI @twopirllc @PVGibson 
I have fixed the issue and tried to optimise it too.

Data Used for benchmark: [81.59, 81.06, 82.87, 83.00, 83.61, 83.15, 82.84, 83.99, 84.55, 84.36, 85.53, 86.54, 86.89, 87.77, 87.29]
Perf Counter (Original Implementation): 0.003188986040186137
Perf Counter (Optimised Implementation: 0.0003332220367155969 

Hope you find this helpful
Thanks

**Comment by twopirllc** [comment]
Hi @PVGibson & @sampanacharya,

I also converted them to numpy/numba to help with speed. It is available on the _development_ branch.

Thanks for helping! 
KJ
