### ISSUE TITLE
Filter indicators by category in strategy()

### ISSUE THREAD

**Issue by DrPaprikaa** [twopirllc/pandas-ta#72]
Hi,

I came across your library, it's awesome ! Especially the `strategy()` method, which allows to add all the indicators to a dataframe. Is there a way to add all the indicators for a specific category (momentum, statistics, trend...) only ? If not it would make a great feature !

**Comment by twopirllc** [comment]
Hello @DrPaprikaa,

Thanks! Glad you like the library.

Good idea. I'll add it to my list.

Don't forget to :star: if you find the library useful.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @DrPaprikaa,

Almost done with this enhancement.

KJ

**Comment by DrPaprikaa** [comment]
Thanks a lot !
