### ISSUE TITLE
 How to limit the number of candlesticks in calculations?

### ISSUE THREAD

**Issue by peipeilalala** [twopirllc/pandas-ta#720]
Is there a way to limit the number of candlesticks when calculating indicators?

For example, if I load a dataset of 10,000 candlesticks and calculate an indicator for the last candlestick, such as:

```python
sma10 = df.ta.sma(length=10)
```

If I only load the last 50 candlesticks of that 10,000 candlestick dataset and input it into pandas_ta, the results obtained will be inconsistent (referring to the result of the last candlestick).

Is it possible to calculate each candlestick's indicator by considering it and the previous 50 candlesticks when loading the CSV file containing the 10,000 candlesticks?

**Comment by twopirllc** [comment]
Hello @peipeilalala,

If you could provide more information and more example code of what you are doing now that would be helpful.

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ
