### ISSUE TITLE
supertrend.py

### ISSUE THREAD

**Issue by msacs09** [twopirllc/pandas-ta#722]
can we have supertrend use Hull Moving Average?

**Comment by twopirllc** [comment]
Hello @msacs09,

Do you mean ```hma``` instead of ```atr``` for ```supertrend```'s calculation? Or take the ```hma``` of ```supertrend``` like: ```hma(supertrend(high, low, close))```? Or ...

Depending on what you are attempting to achieve and some xp coding, you can alter your fork or local Pandas TA ```supertrend``` to do what you need.

Kind Regards,
KJ
