### ISSUE TITLE
Donchian Indicator - Miscalculation

### ISSUE THREAD

**Issue by DrPaprikaa** [twopirllc/pandas-ta#73]
Hi, I think the Donchian Channels indicator (DC, a volatility indicator) isn't computing the right thing : the computation should be on the highest highs and the lowest lows, instead of on the closes. So the code therefore becomes : 

Definition : 

    def donchian(high, low, lower_length=None, upper_length=None, offset=None, **kwargs):

line 15 : 

    # Calculate Result
    lower = low.rolling(lower_length, min_periods=lower_min_periods).min()
    upper = high.rolling(upper_length, min_periods=upper_min_periods).max()
    mid = 0.5 * (lower + upper)

**Comment by twopirllc** [comment]
Hello @DrPaprikaa,

Nice catch! Thanks for finding it! I can't believe I forgot to replace the _close_ with _high_ and _low_ before adding it to the library. I will update it as soon as I can.

Thanks!
KJ

**Comment by DrPaprikaa** [comment]
No problem ! How does it work, will the update be available via `pip` ? How do I get notified that you updated the library ?

**Comment by twopirllc** [comment]
If you click "watch" above, then when I update the repository, it should notify you as well. But I will also post here. I do not update ```pip``` frequently.
