### ISSUE TITLE
Issue with RWI (in dev branch)

### ISSUE THREAD

**Issue by yellow1912** [twopirllc/pandas-ta#730]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
I'm using the latest development branch from github

After I upgraded python and corresponding packages, I got the following issue:

`TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
`

This was the result of calling RWI, I ensured my Close, High, Low do not contain any non numbers.

I checked the code and I found that inside RWI you have:

```python
atr_ = atr(
    high=high, low=low, close=close,
    length=length, mamode=mamode, talib=mode_tal
)
denom = atr_ * (length ** 0.5)
```

The issue is that due to the window length the first several values of atr will not be numbers. Perhaps this causes the issue? This could be related to how fillna is deprecated now?

**Comment by yellow1912** [comment]
My mistake, the error comes from this check inside the atr:

if all(isnan(atr)):
        return
        
so atr_ is None and now  denom = atr_ * (length ** 0.5) will not work

**Comment by twopirllc** [comment]
Hello @yellow1912,

Interesting. 🤔  Could you please share a _csv_ of the offending data?

Kind Regards,
KJ
