### ISSUE TITLE
Yearly pivots causes error with pandas 2.x

### ISSUE THREAD

**Issue by derenderen** [twopirllc/pandas-ta#732]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
**_0.4.4b0_**
pandas version: pandas 2.0.3
**Do you have _TA Lib_ also installed in your environment?**
**_NO._**

**Have you tried the _development_ version? Did it resolve the issue?**
**_Using development version._**
**Describe the bug**
Whenever i try to create yearly pivot points i receive error:

> ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.

**500 days of stock data.**

`pivots = ta.pivots(df['Open'],df['High'],df['Low'],df['Close'],anchor='Y',method='fibonacci')`

Setting 'Y' for anchor returns error. It says 'M' is also depreciated. However it works fine if i set 'M' for anchor value.

[](https://github.com/pandas-dev/pandas/pull/23264)

**Comment by twopirllc** [comment]
Hello @derenderen,

Pandas TA is still being developed with Pandas v1.4+ to support many others using older versions of Pandas and Python. Unfortunately this library is not quite up to Pandas v2.x and **needs** much more support to progress and to cover more versions. 😐 

Why Pandas 2.x [offset aliases](https://pandas.pydata.org/pandas-docs/version/2.0/user_guide/timeseries.html#timeseries-offset-aliases) is not working as intended is beyond me as they look similar to Pandas 1.x offset aliases. 🤷🏼‍♂️ 

Perhaps the original _pivots_ author @hamedf62 may have knowledge on how to address this issue.

Kind Regards
KJ

**Comment by Rossco8** [comment]
The issue comes about because both the `resample()` method of a pd.Series and  `df.index = df.index + Timedelta(1, anchor.lower())` could both previously accept Y and M, however only `resample()` accepts Y now

PR Raised

**Comment by Rossco8** [comment]
Hi @twopirllc, I'm just browsing to see if there are any issues i can help with and noticed this is still open. Can it be closed following the merge of the PR?
