### ISSUE TITLE
TA-Lib option isn't working on "VIDYA" Indicator

### ISSUE THREAD

**Issue by Hellooosir** [twopirllc/pandas-ta#738]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
-> python 3.12.0 / pandas_ta 0.3.14b

**Do you have _TA Lib_ also installed in your environment?**
-> No

**Have you tried the _development_ version? Did it resolve the issue?**
-> No

When I use "VIDYA" Indicator, "talib = False" isn't working.
"CMO" Indicator is working well, however it doesn't working on "VIDYA" Indicator.

```python
x = ta.cmo(df['close'], 14, talib = True)
x_2 = ta.cmo(df['close'], 14, talib = False)

y = ta.vidya(df['close'], 14, talib = True)
y_2 = ta.vidya(df['close'], 14, talib = False)
```

```sh
         CMO_14     CMO_14     VIDYA_14     VIDYA_14
1495 -29.713676 -27.812194  2086.131474  2086.131474
1496 -29.664858 -44.916821  2085.508539  2085.508539
1497 -28.004686 -44.489495  2084.947465  2084.947465
1498 -39.347130 -53.856041  2083.996908  2083.996908
1499 -36.518572 -60.833053  2083.043297  2083.043297
```

I don't know the reason.

**Comment by twopirllc** [comment]
Hello @Hellooosir,

There is no _vidya_ in [TA Lib](https://ta-lib.org/functions/). Seems I forgot to remove the ```talib``` option before it's submission to the library. Apologies for the confusion.

Kind Regards,
KJ

**Comment by Hellooosir** [comment]
Hello @twopirllc ,
I always enjoy using this library. Thank  you very much.

There is no "vidya" in TA Lib. However, "vidya" is calculated based on the "cmo" indicator.
I believe there is an option for "cmo" values, as seen on below.

```
help(ta.vidya)
talib (bool): If True, uses TA-Libs implementation for CMO. Otherwise uses EMA version. Default: True
```
It appears that the 'CMO' indicator has different values in the TA-Lib and EMA versions.
Therefore, I think there is no EMA version of 'VIDYA'.
```
x = ta.cmo(df['close'], 14, talib = True)
x_2 = ta.cmo(df['close'], 14, talib = False)

y = ta.vidya(df['close'], 14, talib = True)
y_2 = ta.vidya(df['close'], 14, talib = False)

         CMO_14     CMO_14     VIDYA_14     VIDYA_14
1495 -29.713676 -27.812194  2086.131474  2086.131474
1496 -29.664858 -44.916821  2085.508539  2085.508539
1497 -28.004686 -44.489495  2084.947465  2084.947465
1498 -39.347130 -53.856041  2083.996908  2083.996908
1499 -36.518572 -60.833053  2083.043297  2083.043297
```

Could you please check this?

Best Regards,
SH

**Comment by twopirllc** [comment]
@Hellooosir 

If I understand correctly, you want the option for TA Lib's **cmo** correct? Either way, I can add it.

> I always enjoy using this library. Thank you very much.

Thank you
KJ

**Comment by twopirllc** [comment]
@Hellooosir

There might be difference because you are comparing _apples_ (TV data) and _oranges_ (your data) data which is very common thing to do.

**Comment by Hellooosir** [comment]
@twopirllc 

I understand it. Thank you for helping me :)

Best Regards,
SH
