### ISSUE TITLE
How to plot Volume Profile?

### ISSUE THREAD

**Issue by strikar21** [twopirllc/pandas-ta#74]
apdict = [
        mpf.make_addplot(stck.VP,color='y',type = 'line', panel = 1)
        ]

#columns first uper like('Open,High,Low....')
#df.columns = map(str.title, df.columns)

#mpf.plot
mpf.plot(stck,style='yahoo',volume=False,type='candle',addplot=apdict,figratio=(16,8),title=ticker)

RETURNS:

Traceback (most recent call last):
  File "C:/Users/Srika/PycharmProjects/latest project/s&r.py", line 88, in <module>
    mpf.plot(stck,style='yahoo',volume=False,type='candle',addplot=apdict,figratio=(16,8),title=ticker)
  File "C:\Users\Srika\PycharmProjects\latest project\venv\lib\site-packages\mplfinance\plotting.py", line 501, in plot
    ax = _addplot_columns(panid,panels,ydata,apdict,xdates,config)
  File "C:\Users\Srika\PycharmProjects\latest project\venv\lib\site-packages\mplfinance\plotting.py", line 673, in _addplot_columns
    yd = [y for y in ydata if not math.isnan(y)]
  File "C:\Users\Srika\PycharmProjects\latest project\venv\lib\site-packages\mplfinance\plotting.py", line 673, in <listcomp>
    yd = [y for y in ydata if not math.isnan(y)]
TypeError: must be real number, not method

![image](https://user-images.githubusercontent.com/63551985/87831792-16bd8e00-c8a2-11ea-8286-7fb32a316217.png)

**Comment by twopirllc** [comment]
Hello @strikar21,

**Volume Profile**

_Volume Profile_ is rather tricky, not just for plotting but also where to start the calculation and how many observations aka ```width: int = 10``` (default) to use. So you can not just pass it to ```mpf.make_addplot(stck.VP,color='y',type = 'line', panel = 1)```. There is some post processing required.

**Volume Profile and Matplotlib Finance Charting**

Currently **Matplotlib Finance** does not have _Volume Profile_ Charting, though it is a proposed feature request [mplfinance Issue #162](https://github.com/matplotlib/mplfinance/issues/162). If you want **Matplotlib Finance** to support **Pandas TA** _Volume Profile_, please let them know by adding onto Issue #162.

**Volume Profile, Post Processing and Matplotlib Charting**

Here is the code I use to visually verify _Volume Profile_ with Matplotlib.
```python
vpdf = df.tail(30) # Take the last 30 Daily Bars
vp = vpdf.ta.vp() # Run Volume Profile
print("Returns unsorted close\n", vp, "\n") # Visual Table Check

# Set the index to mean_close and in ascending order
vp['mean_close'] = round(vp['mean_close'], 2)
vp.set_index('mean_close', inplace=True)
vp.sort_index(ascending=True, inplace=True)
print("Sorted by mean_close\n", vp, "\n") # Visual Table Check

# Take the last three columns and plot them with horizontal bars
vp[vp.columns[-3:]].plot(
    kind='barh', 
    figsize=(5, 8),
    title="SPY VP (Recent 30 Days)",
    color=['green', 'red', 'silver'],
    alpha=0.45,
    stacked=True,
)
```
_Visual Table Check_

<img width="497" alt="Screen Shot 2020-07-17 at 3 34 31 PM" src="https://user-images.githubusercontent.com/18198392/87835891-530dd180-c843-11ea-9f2f-ccca2ea85a6e.png">

_Volume Profile Chart_

<img width="395" alt="Screen Shot 2020-07-17 at 3 34 47 PM" src="https://user-images.githubusercontent.com/18198392/87835850-36719980-c843-11ea-95d6-49efd80e1869.png">

Thoughts? Suggestions? Solutions? Anything to make this better?
Don't forget to ⭐ if you find the library useful.

Hope this helps! 
KJ

**Comment by strikar21** [comment]
Thank you for the reply.

works just like you've shown. :)
i will wait until this month end for mplfinance then would raise an issue. if the promised matplotlib method of plotting downst help :)

**Comment by dropdx** [comment]
Is there an easier way to plot this with Matplotlib yet?
