### ISSUE TITLE
Bug in TMO: latest closing compared with preceding opening prices in window of length TMO length

### ISSUE THREAD

**Issue by luisbarrancos** [twopirllc/pandas-ta#742]
The PR i submitted [here](https://github.com/twopirllc/pandas-ta/pull/729) for the *development* branch has a bug, in that i was computing the price delta of closing and opening prices, rather than price delta of latest current price and preceding opening prices. 
I'll submit a new PR soon. Feel free to assign this to me.

**Comment by twopirllc** [comment]
@luisbarrancos 

No worries! Thanks for all the help. 😎

**Comment by luisbarrancos** [comment]
@twopirllc done, the PR is [here](https://github.com/twopirllc/pandas-ta/pull/743) with more details.
