### ISSUE TITLE
DataFrame Accessor Method Not Working

### ISSUE THREAD

**Issue by jimmyD30** [twopirllc/pandas-ta#747]
Hello, having dataframe accessor method issue with pandas-ta (other methods work fine), although it works fine with TALib e.g.: data_df = data_df.ta.cdl_pattern(name="all")

DETAILS:
MacOS 13.3, Python 3.9.6, VS Code, all packages are latest versions.

```python
import pandas_ta as pta # imports package fine - tested.

data_df = pd.read_csv(datafile, sep=',') # reads data fine - tested.

help(data_df.pta) # this and other similar dataframe accessor statements causes error
```

```sh
ERROR:
Traceback (most recent call last):
  File "/Users/admin/Desktop/ML/yfinance-momentum.py", line 57, in <module>
    help(data_df.pta)
  File "/Users/admin/Library/Python/3.9/lib/python/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'pta'
```

Let me know if providing more info would help.

**Comment by twopirllc** [comment]
Hello @jimmyD30,

That's true, there is no [DataFrame accessor](https://pandas.pydata.org/pandas-docs/version/1.4/development/extending.html) named ```pta``` nor does the DataFrame accessor or whatever name you choose to import pandas_ta as. The DataFrame accessor is hard coded to the DataFrame with the name ```ta``` to keep it simple as shown below in the code sample.

https://github.com/twopirllc/pandas-ta/blob/affcac4684a85ecfb86d2e596a45eff8f701d699/pandas_ta/core.py#L22

You didn't mention the Pandas TA version, but you _should_ be using the _development_ version. If you are using version _0.3.14b_, then you may also encounter some already existing [Issues](https://github.com/twopirllc/pandas-ta/issues)

Should work
```python
import pandas_ta as pta # imports package fine - tested.

data_df = pd.read_csv(datafile, sep=',') # reads data fine - tested.

help(data_df.ta) # this will work

# Will most likely work since you probably have `yfinance` installed
data_df.ta.ticker("SPY", period="1y", timed=True)
print(data_df.tail())  # this will work

data_df.ta.ema(20, append=True)  # this will work

data_df.ta.study(cores=0, timed=True)  # works with development version
print(data_df.columns)
print(data_df.tail())
```

Hope this helps.

Kind Regards,
KJ

**Comment by jimmyD30** [comment]
Ah, I see, I'm using the wrong dataframe accessor acronym, I need to use the one already set in pandas-ta package.

Yes, I'm using the latest beta version.

I was actually importing talib as 'ta' in the same file, so to distinguish between that package and yours I imported pandas-ta as 'pta'.

I just tried it the way you suggested and it is working.

Thank you kindly and happy holidays!

**Comment by twopirllc** [comment]
@jimmyD30 

> Ah, I see, I'm using the wrong dataframe accessor acronym, I need to use the one already set for pandas-ta (or rather registered to pandas) package.

Yup

> I was actually importing talib as 'ta' in the same file, so to distinguish between that package and yours I imported pandas-ta as 'pta'.

You can do that. It won't affect either.

> I just tried it the way you suggested and it is working.

✅ 

> Thank you kindly and happy holidays!

You're welcome! Likewise!
