### ISSUE TITLE
Does pandas-ta support pandas 2.0?

### ISSUE THREAD

**Issue by kopes18** [twopirllc/pandas-ta#749]

**Comment by twopirllc** [comment]
Hello @kopes18,

Yes.

When updating the library, [Github Actions](https://github.com/twopirllc/pandas-ta/actions/runs/7311648727/job/19921451563) runs Ubuntu and installs the latest Pandas version (currently _2.1.4_). Of course there are some _FutureWarning_ notices, but they are not breaking any indicator computations.

Kind Regards
KJ
