### ISSUE TITLE
case of multiindex dataset (i.e multi symbol) 

### ISSUE THREAD

**Issue by ashraf-01** [twopirllc/pandas-ta#75]
Would you kindly provide an example of how your library work guys on multindex ( row major )
i.e. 
![image](https://user-images.githubusercontent.com/50061659/87871399-3f33ae00-c9b0-11ea-8c8d-1bfabfd9b142.png)

looking forward to your response 

best regards

**Comment by twopirllc** [comment]
Hello @ashraf-01,

_MultiIndexing_ is not managed by **Pandas TA**, that is left to the user. For more info on using [MultiIndexing](https://pandas.pydata.org/docs/user_guide/advanced.html).

If you want to use **Pandas TA** on MultiIndex, you will need to break ```data_2ticker``` into two DataFrames, one for ```CAT``` and the other for ```MAC```, then you can apply ```Pandas TA```.

Good luck!
KJ
