### ISSUE TITLE
Help, keep looping a future warning when running all strategies on script!

### ISSUE THREAD

**Issue by shingtat2** [twopirllc/pandas-ta#750]
Hi all,

Anyone can help on my issue?

environment
Python 3.10.11
Ta-lib installed

Code:
```python
df.ta.strategy(verbose=False, append=True)
```

Keep looping below message and stuck forever:
```sh
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py:48: FutureWarning: Series.getitem treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use ser.iloc[pos]
return list(map(*args))

C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py:48: FutureWarning: Series.getitem treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use ser.iloc[pos]
return list(map(*args))
```

Have tried all ways to disable warnings eg:
```python
# Save the current warning settings
current_warnings = warnings.filters.copy()
# Suppress all warnings
warnings.filterwarnings('ignore')
# Redirect standard output to null
sys.stdout = open(os.devnull, 'w')
# Suppress logging
logger = logging.getLogger()
original_level = logger.getEffectiveLevel()
logger.setLevel(logging.CRITICAL + 1)
# Suppress only FutureWarnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=all)
```

**Comment by twopirllc** [comment]
Hello @shingtat2,

This is a known Issue and is described in Issue #181 which is a pinned Issue at the TOP of the Issue list.

Kind Regards
KJ

**Comment by shingtat2** [comment]
> Hello @shingtat2,
> 
> This is a known Issue and is described in Issue #181 which is a pinned Issue at the TOP of the Issue list.
> 
> Kind Regards KJ

Yes I have read the post and solution to use main and my codes is already in def main(): but the issue still exist. Any other ways or tips to get it working?

def main():
    freeze_support()
    # Save the current warning settings
    current_warnings = warnings.filters.copy()
    # Suppress all warnings
    warnings.filterwarnings('ignore')
    # Redirect standard output to null
    sys.stdout = open(os.devnull, 'w')
    # Suppress logging
    logger = logging.getLogger()
    original_level = logger.getEffectiveLevel()
    logger.setLevel(logging.CRITICAL + 1)
    # Suppress only FutureWarnings
    warnings.simplefilter(action='ignore', category=FutureWarning)
    warnings.simplefilter(action='ignore', category=all)
    warnings.filterwarnings('ignore')

    try:
        df.ta.strategy(verbose=True, append=True)
    except Exception as e:
        # Handle any exception that might be raised
        print(f"An error occurred: {e}")
        
    # Restore the original warning settings
    warnings.filters = current_warnings
    

    print(df)

if __name__ == '__main__':
    main()

**Comment by twopirllc** [comment]
@shingtat2

For one thing, you should be using the _development_ version for many reasons I will not include here.

Also, ```append=True``` is redundant when using ```df.ta.strategy()``` (or ```df.ta.study()``` in _development_). Either automatically appends to the DataFrame.

So change: ```df.ta.strategy(verbose=True, append=True)``` to ```df.ta.study(cores=0, verbose=True)``` (after installing the _development_ branch.

Lastly, I recommend **not** using _multiprocessing_ because it most cases it is not more performant.

**Comment by twopirllc** [comment]
Hello @shingtat2 

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ
