### ISSUE TITLE
Having trouble attempting to "import pandas_ta as ta"

### ISSUE THREAD

**Issue by DaLincerGuy** [twopirllc/pandas-ta#754]
Python 3.12.1
running using PyCharm as my IDE
Package Manager shows "pandas_ta with version 0.3.14b0

when I run the code:
```python
    import pandas as pd
    import requests
    import pandas_ta as ta
```

```sh
Traceback (most recent call last):
  File "D:\Users\DavidL\Documents\Python\TSNTest\TSNTest\.venv\Scripts\TSNTest.py", line 5, in <module>
    import pandas_ta as ta
  File "C:\Users\RollnWX3\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas_ta\__init__.py", line 7, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

Process finished with exit code 1
```

I do not see the _TA Lib_ listed in my package manager, and pip does not understand a space in the name

I must be doing something obvious and easy to fix, and I do not see it yet.

UPDATE:     
noted that pkg_resources is not in my list of modules, and 
         py -m pip install pkg_resources
ERROR: Could not find a version that satisfies the requirement pkg_resources (from versions: none)
ERROR: No matching distribution found for pkg_resources
fails....

David

Here is the pip list from my python console:

PS D:\Users\DavidL\Documents\Python\TSNTest\TSNTest> py -m pip list
Package            Version
------------------ ------------
certifi            2023.11.17  
charset-normalizer 3.3.2       
contourpy          1.2.0       
cycler             0.12.1      
fonttools          4.47.2      
idna               3.6
kiwisolver         1.4.5
matplotlib         3.8.2
numpy              1.26.3
packaging          23.2
pandas             2.2.0rc0
pandas_ta          0.3.14b0
pillow             10.2.0
pip                23.3.2
pyparsing          3.1.1
python-dateutil    2.8.2
pytz               2023.3.post1
requests           2.31.0
six                1.16.0
termcolor          2.4.0
tinytag            1.10.1
tzdata             2023.4
urllib3            2.1.0

_________________________________________

**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**

**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @DaLincerGuy,

Yes it is not a Pandas TA error but an ModuleError for not having that particular module. Have you tried solutions provide [here](https://www.google.com/search?q=ModuleNotFoundError%3A+No+module+named+%27pkg_resources%27)?

Also, please install the _development_ version of the library as listed above.

Kind Regards,
KJ

**Comment by DaLincerGuy** [comment]
KJ,

Thanks for your note, you pointed me to the right place.   

Off to other issues, and I will load the development version as you recommend.

David

**Comment by ABurlo** [comment]
Dev branch works cheers!  :)

AB
