### ISSUE TITLE
rolling calculations issue 

### ISSUE THREAD

**Issue by ashraf-01** [twopirllc/pandas-ta#76]
Hi all , Hi Kevin 

I have run in to the below error while applying a window calc to one of the features implemented within the lib 

it goes as 
df['roll_entp_10']= df_test.ENTP_10.rolling(10)   which is a series , after explicitly turning in to a series still getting the same error 

![image](https://user-images.githubusercontent.com/50061659/87877277-a9af1300-c9dd-11ea-9dad-526e6acca2ff.png)

just for reference 

pd.__version__  1.0.3

![image](https://user-images.githubusercontent.com/50061659/87877390-55586300-c9de-11ea-8c0e-5e67986a403e.png)

I have looked though in to the following as suggested 
https://github.com/pandas-dev/pandas/issues/11704
is there any additional guidance you can provide on that issue ?
best regards

**Comment by twopirllc** [comment]
Hello @ashraf-01,

### Pandas Version

> I have looked though in to the following as suggested
> pandas-dev/pandas#11704

You are using Pandas version 1.0.3. So, did you upgrade Pandas v 1.1.x per the suggestion?

<img width="763" alt="Screen Shot 2020-07-19 at 10 56 42 AM" src="https://user-images.githubusercontent.com/18198392/87881523-a2bcdc00-c9ae-11ea-868e-e2b38657331a.png">

### Pandas Moving Window

Also usually when you use, ```df.rolling(window)```, one applies a function to the window such as ```sum()```, ```mean()```, et al as described here: [Standard Moving Window Functions](https://pandas.pydata.org/docs/reference/window.html). Also ```type(df.rolling(window)) = pandas.core.window.rolling.Rolling``` and not Series.

### Your Code

> df['roll_entp_10']= df_test.ENTP_10.rolling(10) which is a series , after ...

I am also running Pandas 1.0.3 and I have no issue with using ```rolling(window)```, see the screenshot below. Are you unable to show the code that led up to and including ```df['roll_entp_10']= df_test.ENTP_10.rolling(10)``` to see if you introduced logic that would cause that not to work? 

<img width="525" alt="Screen Shot 2020-07-19 at 11 41 06 AM" src="https://user-images.githubusercontent.com/18198392/87882526-51641b00-c9b5-11ea-9fb2-a819d59caa00.png">

Best Regards,
Kevin

**Comment by twopirllc** [comment]
Hello @ashraf-01,

I will assume the prior response was sufficient and will close this issue in a few days if I do not hear back from you.

Best Regards,
KJ
