### ISSUE TITLE
Attribute error when I remove a specific group from dataframe

### ISSUE THREAD

**Issue by Chuck321123** [twopirllc/pandas-ta#765]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
The latest from pip

**Do you have _TA Lib_ also installed in your environment?**
No

**Have you tried the _development_ version? Did it resolve the issue?**
No

**Describe the bug**
So i have a df with some groups and i want to calculate grouped by moving average like this:
```...
# Add SMA
New_Df["SMA"]  = New_Df.groupby('Group')["Value"].transform(lambda x: (ta.sma(close=x, length=2)).bfill())
```
which works, but if i do this:
```
# Remove specific group
New_Df = pd.DataFrame(New_Df[New_Df["Group"] != "ABC"]).reset_index(drop=True)

# Add SMA
New_Df["SMA"]  = New_Df.groupby('Group')["Value"].transform(lambda x: (ta.sma(close=x, length=2)).bfill())
```
It doesnt work and i get this error: AttributeError: 'NoneType' object has no attribute 'bfill'
Im simply just removing a specific group out of many groups, but still it doesnt work out of a mysterious reason, and the craziest part is that this works:
```
# Remove specific ticker
New_Df = pd.DataFrame(New_Df[New_Df["Group"] != "ABC"]).reset_index(drop=True)

# Add SMA
New_Df["SMA"]  = New_Df.groupby('Group')["Value"].transform(lambda x: pd.Series(ta.sma(close=x, length=2)).bfill())
```
And an even crazier part is that i cant replicate it, and i dont know why. So why do i have to pass pd.Series first? I have also tried converting every column to pd.Series before doing so but with no luck.
Btw: been using pandas-ta for over 1 year without needing to pass pd.Series, but this was a really weird bug.

**To Reproduce**
I cant reproduce the problem and i dont know why

**Expected behavior**
That removing a group doesnt mess up the data structure

**Comment by twopirllc** [comment]
Hello @Chuck321123 

Did you close the issue after you figured it out?

Kind Regards,
KJ

**Comment by Chuck321123** [comment]
@twopirllc Yes, the error was on pandas side. Checking if there was any nan values in the groups, "ABC" showed false, but "ABC" never existed in the group nor the df after i removed it, so it shouldnt have been displayed in the first place. ChatGPT suggested to do uppercase on all "Group" values (even though "ABC" values was in upper cases), but that seemed to fix the bug.

**Comment by Chuck321123** [comment]
@twopirllc Yes, kind of rookie mistake from my side. By a weird reason, pandas might change its behaviour when you remove one of the groups as the reason was one of the other groups (Not "ABC") had a group length less than the window/length of the SMA-operation which led to only nan values in one of the groups, hence the error.
