### ISSUE TITLE
Weird behaviour in RSI moment indicator on development branch

### ISSUE THREAD

**Issue by einarjohnson** [twopirllc/pandas-ta#773]
I have one question about the `development` branch. I am currently plugging it into our project I have noticed that the `rsi` momentum indicator does not seem to behave like the one defined on the `main` branch. to be more specific, it seems to me that it is not returning `nan` values for the first 14 rows of data when we use the default `length=14` parameter. There is only a nan value in the first row.

Screen:
![image](https://github.com/twopirllc/pandas-ta/assets/35610046/7670ca76-9ec5-4c1b-a2a7-3f18c5593179)

When I run the same code using the latest release of 0.3.14b0 the expected nan values are there for the first 14 rows.
Screen:
![image](https://github.com/twopirllc/pandas-ta/assets/35610046/7d509714-4499-447b-ac3f-66636607341c)

Is this a bug on the development branch or is this logic something to be expected in future releases?

**Comment by twopirllc** [comment]
Hello @einarjohnson,

**RSI** works as intended with the _prenans_. There are no plans to alter this behavior.

<img width="724" alt="Screenshot 2024-03-09 at 11 11 46 AM" src="https://github.com/twopirllc/pandas-ta/assets/18198392/e41ee015-4400-4ce7-b032-898293c47dae">

Unfortunately, I am unable to replicate you results with the _development_ branch. What is your code to reproduce the resultant output?

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@einarjohnson 

Oh I see... you are **not** using TA Lib. Looks like you are correct with the lack of _prenans_ for the Pandas TA **RSI** version.

<img width="640" alt="Screenshot 2024-03-09 at 11 25 38 AM" src="https://github.com/twopirllc/pandas-ta/assets/18198392/b45a1b5d-2017-4f1b-adcb-7375e2a37f38">

You are correct that it should have prenans there. I'll add it to the todo list. Thanks for the heads up.

**Comment by einarjohnson** [comment]
hi @twopirllc,
thanks for such a lighting fast response. :)

i think the issue boils down to the fact the development branch is using `rma` as the default ma instead of `sma` which is on the main branch. 

If I set the mamode="sma" parameter like so

```
import pandas_ta as pta
df[DataframeColumns.RSI] = pta.rsi(
    df[DataframeColumns.CLOSE], length=self.settings.rsi_default_length, mamode="sma"
)
```
the prenans are returned as expected.

**Comment by twopirllc** [comment]
@einarjohnson 

Oh yeah! It has been awhile since I touch **rsi**. Seems I chose to default to TradingView's _rma_ calculation if TA Lib is not installed.

**Comment by einarjohnson** [comment]
Interesting. SMA seems to be the default one when I use TW.
<img width="373" alt="image" src="https://github.com/twopirllc/pandas-ta/assets/35610046/2310f921-4921-4587-809f-a000f4fb5cf7">

maybe this is a user setting or something that is bound to my account, could very well be since I use TW so much and I might have changed this at some stage _(i can't remember doing that though_)

Anyways, your help and input is very much appreciated and thanks for this brilliant library, it has proven most useful for our project.

**Comment by twopirllc** [comment]
@einarjohnson 

Yes it is easy to forget changing settings over time.

> Anyways, your help and input is very much appreciated and thanks for this brilliant library, it has proven most useful for our project.

Sponsorship or donations help massively to keep this project alive. 😎 

[Buy me a Coffee](https://www.buymeacoffee.com/twopirllc)

Thanks!

**Comment by twopirllc** [comment]
🤣

**Comment by einarjohnson** [comment]
apologies for lateness here, been up to my eyeballs with life/work/kids/etc. the coffee has been delivered. <3

**Comment by twopirllc** [comment]
I know how it is. Much appreciated. Thank you!
