### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Rossco8** [twopirllc/pandas-ta#775]
I'm having a look at the 3 tests that are failing.
```sh
FAILED tests/test_indicator_momentum.py::test_ppo - AttributeError: 'DataFram...
FAILED tests/test_indicator_overlap.py::test_mama - AttributeError: 'DataFram...
FAILED tests/test_indicator_trend.py::test_adx - AttributeError: 'DataFrame' ...
```

Looks like the pandas-ta version of these indicators return a Dataframe, the ta-lib returns a Series, so the `pdt.assert_series_equal(result, expected, check_names=False)` is throwing an error.

Is it an acceptable fix to these 3 tests to extract the relevant series from the pandas-ta result and pass that to `assert_series_equal`. For example

```python
ta_result = result['PPO_12_26_9']
expected = tal.PPO(df['Close'])
pdt.assert_series_equal(ta_result, expected, check_names=False)
```

If so, I'll submit a PR

**Comment by twopirllc** [comment]
Hi @Rossco8,

First, thanks for all the help and the contributions you have recently made. I will address and get to them shortly. 😎 

Yes, I have come across similar failing tests asserting the incorrect data type, Series or DataFrame. These _should_ be addressed in the upcoming _development_ update including the indicators you have listed.

Before we do any more work, let me get this updated _development_ pushed this week and then we can tackle issues and fixes more in sync. 😎

**Comment by twopirllc** [comment]
Hi @Rossco8 

Just updated the _development_ branch. Let me know if you still get those fails.

KJ

**Comment by Rossco8** [comment]
Hi @twopirllc yes looks like the tests are now fixed on the development branch. Except my PR for the PVI indicator fix is failing. Any suggestions why? I updated the tests in `test_indicator_volume.py`, but they still fail when run in the GH workflow

**Comment by twopirllc** [comment]
@Rossco8 

I think we can close this no? I am not getting test errors on my end nor GA actions on my PRs.

**Comment by Rossco8** [comment]
Yep @twopirllc  happy to clsoe this one
