### ISSUE TITLE
Very nice library. When could be available for python 3.11?👍

### ISSUE THREAD

**Issue by hysech** [twopirllc/pandas-ta#791]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
0.3.14b0
```

**Do you have _TA Lib_ also installed in your environment?**
```sh
yes
```

**Upgrade.**
```sh
done already
```

**Is your feature request related to a problem? Please describe.**
I am on python 3.11 preventing to use your nice library for TSI and other nice indicators

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @hysech,

Try the _development_ version for now. It has many fixes and should already support Python 3.11 and 3.12. Can use help rooting out version issues. 😎 

Kind Regards,
KJ
