### ISSUE TITLE
pandas_ta.ema(df.close) returns different to df.ta.ema() when EMA length is greater than DataFrame length

### ISSUE THREAD

**Issue by bigtonylewis** [twopirllc/pandas-ta#794]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
No.  Also I get no difference in result when calling with `talib=True` or `talib=False`

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
Unsure.  I get install errors when trying to install the dev version.  Last line:
```
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**Describe the bug**
When using the ema() function, you can call it either through:
`ta.ema(df)`
or
`df.ta.ema()`

The bug occurs when the length passed to ema() exceeds the length of the DataFrame.  In the first way of calling, `None` is returned, but in the second way, it returns the original DataFrame, unaltered.

**To Reproduce**
```python
import pandas as pd
import pandas_ta as ta

df = pd.DataFrame(range(100), columns = ['close'])

# correct behaviour
ta.ema(df, 101) # returns None

# incorrect behaviour
df.ta.ema(101) # returns df
```

**Expected behavior**
a `None` is workable.  Arguably it should be a Series() of `NaN`, but `None` works well enough

**Comment by twopirllc** [comment]
Hello @bigtonylewis 

Incremental rows with indicator lengths greater than _ohlcv_ rows has been fixed and available on _development_ version. Here is the relevant [test](https://github.com/twopirllc/pandas-ta/blob/development/tests/test_studies.py):

```python
@pytest.mark.parametrize("talib", [False, True])
def test_study_all_incremental_rows_talib(df, all_study, talib):
    MAX_ROWS = 90
    df = df.iloc[:MAX_ROWS]   # Trim for this test

    for i in range(0, MAX_ROWS):
        _df = df.iloc[:i]
        _df.ta.study(all_study, cores=0, talib=talib)
        # Break when max columns reached
        if _df.shape[1] - df.shape[1] == ALL_COLUMNS:
            assert _df.shape[1] > df.shape[1]
            break
```

>  I get install errors when trying to install the dev version.

The message is **not** an error from this library and a web search revealed a potential [solution](https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port) for:
```sh
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

Kind Regards
KJ

**Comment by twopirllc** [comment]
Hello @bigtonylewis,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by bigtonylewis** [comment]
Hi KJ,

I'm still getting the same issue:
```python
$ ipython
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.24.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pandas as pd
   ...: import pandas_ta as ta
   ...: print(ta.version)
0.4.12b0

In [2]: df = pd.DataFrame(range(100), columns = ['close'])

In [3]: assert ta.ema(df, 101) is None

In [4]: assert df.ta.ema(101).equals(df) == False, ".ta.ema() returned the original dataframe when EMA length is > D
   ...: F length"
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 assert df.ta.ema(101).equals(df) == False, ".ta.ema() returned the original dataframe when EMA length is > DF length"

AssertionError: .ta.ema() returned the original dataframe when EMA length is > DF length
```

**Comment by twopirllc** [comment]
@bigtonylewis 

I do not consider this a **bug**. Actially a _feature_ as you have described in your #795 post. 

> I have this workaround in my code, but think it should be in the library, as I'm sure it would benefit others.

😎

**Comment by bigtonylewis** [comment]
I disagree.

1. Calling the function two different ways on the same data yields two different results: `df.ta.ema(101) != ta.ema(df, 101)`
2. The fact that it returns the original dataframe could never be correct behaviour
3. It runs the risk of passing any sanity checks (e.g. an empty Series) and being considered legitimate / correct.

It seems very obvious to me.  What am I not understanding?

**Comment by bigtonylewis** [comment]
Oh, maybe you're relating this too much with #795.  That one is all about returning a `NaN` vs a `Series` of `NaN`, which is for convenience; both are semantically correct, but one is easier to handle for my use case.

This is about `df.ta.ema(length)` returning a clearly wrong result when `length > len(df)`

**Comment by twopirllc** [comment]
@bigtonylewis 

> Oh, maybe you're relating this too much with https://github.com/twopirllc/pandas-ta/issues/795.

Probably. 😅  To correct my misunderstandings, do you have resources and examples that I can learn from?

Let's fix it! ✅  Fork, checkout the _development_ branch, edit (including tests) and make a PR. 😎
