### ISSUE TITLE
Bollinger Bands (BBANDS) error

### ISSUE THREAD

**Issue by Khanhlinhdang** [twopirllc/pandas-ta#798]
this is my resutl when I test Bollinger Bands (BBANDS), a lot of points have nan value! 
![image](https://github.com/twopirllc/pandas-ta/assets/78089189/43acc39c-0a0a-45ae-a9e2-95de44b57422)

**Comment by Khanhlinhdang** [comment]
Sorry! I found the my misstake. I solved it
![image](https://github.com/twopirllc/pandas-ta/assets/78089189/834d76b0-da2d-44d2-9388-50e850b72598)

**Comment by twopirllc** [comment]
Hello @Khanhlinhdang,

> Sorry! I found the my misstake. I solved it

Awesome! 😎 

Next time please fill out the **Bug Report** as detailed as possible as requested. Otherwise the Issue will closed until it is completed.

Kind Regards,
KJ
