### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\g'   return re_.sub("([a-z])([A-Z])","\g<1> \g<2>", x).title()

### ISSUE THREAD

**Issue by kopes18** [twopirllc/pandas-ta#807]
I got this warning after upgrade python from 3.11 to 3.12:
pandas_ta\utils\_core.py:14: SyntaxWarning: invalid escape sequence '\g'
  return re_.sub("([a-z])([A-Z])","\g<1> \g<2>", x).title()

python 3.12.4
pandas_ta 0.3.14b

Do I need to downgrade to python 3.11 for now?

**Comment by twopirllc** [comment]
Hello @kopes18,

Pandas TA _v0.3.1.4_ will not be supporting Python 3.12. However the _development_ branch will and already has a fix (see #787). Though if you want to use _v0.3.14_, you can edit your local version of ```pandas_ta/utils/_core.py``` with the following: ```return re_.sub("([a-z])([A-Z])",r"\g<1> \g<2>", x).title()```.

Kind Regards,
KJ

**Comment by metin02oktay** [comment]
I got the same error. I am using python 3.12. I think pandas_ta library needs to be updated or an alternative library should be used.
