### ISSUE TITLE
FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas.

### ISSUE THREAD

**Issue by esteban2006** [twopirllc/pandas-ta#808]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
pandas_ta V
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**

YES

**Have you tried the _development_ version? Did it resolve the issue?**

NO

**Describe the bug**

FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas.

pandas is not allowing mix of data, so it is requesting a cast, 

`
Value '891.4783225765763' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df = ta.ma(name, df[applyTo], length=val)

\0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12     891.47832
13    1739.77306
14    2525.27395
15    3261.01269
`

**To Reproduce**
calling the following function will procduce the error above

`def allMaUtils(self, name="ema", df=df, val=7, applyTo='close'):
        df = ta.ma(name, df[applyTo], length=val)
        return df

`

**Expected behavior**
to return what has been reported to solve the problem [pandas](https://github.com/pandas-dev/pandas/issues/55791)

Thanks for using Pandas TA!
Thank you Guys

**Comment by twopirllc** [comment]
Hello @esteban2006 

> Have you tried the development version? Did it resolve the issue?
> 
> NO

Install the _development_ version to resolve this like you were asked to do above.

Kind Regards,
KJ
