### ISSUE TITLE
Parameters in strategy()'s ta

### ISSUE THREAD

**Issue by DrPaprikaa** [twopirllc/pandas-ta#81]
Hi @twopirllc,

I'm playing with the new improved `strategy()` method, it's quite an improvement nice work ! You should push it to `pip` ;)

In my workflow, I'm computing a bunch of data on the indicators and then select the relevant ones. However, I don't know _a priori_ which ones nor their parameters, and they are not always the same.

Since all the indictors don't have the same number of parameters, they would be passed as a list of floats, instead of their explicit names. For example :

	CustomStrategy = ta.Strategy(name="MyStrat",
		                     ta=[{'kind':'sma',    'params':[30]}, 
                                     {'kind':'bbands', 'params':[20,2]}},
                                     {'kind':'macd',   'params':[8,21]}, 
                                    ],
		                     )
This way, the code would be more modular. Is it possible to implement that ?

**Comment by twopirllc** [comment]
Hello @DrPaprikaa,

Thanks! I plan to push to ```pip``` in about a week if no major issue(s) with the improvised ```df.ta.strategy``` method creep up. I try to keep the most recent stable version on ```pip```.

I think your **modular** approach is a good idea and I can understand the compactness it provides, so it is conceptually possible to implement. However, I am uncertain of how _devilish the details_ maybe at this point so I would need some time to fool around with it.

For the most part, the argument positions have rarely changed throughout ```Pandas TA```'s evolution. I try to keep the arguments in order of importance from _high_ to _low_ to reduce argument permutation and thus potential breaking changes for users. I will take in account the your **modular** idea as I continue to _refine_ ```df.ta.strategy```.

Also I am considering saving prebuilt **User Strategies** (including some of my own) to ```Pandas TA``` so others can potentially benefit from them. If you would like me to add any of yours, just let me know.

Thanks,
KJ

**Comment by DrPaprikaa** [comment]
Thanks for the reply, I understand that it might be tricky to implement ;) I don't know if I can be of any help, this would be a great feature !

Regarding the User Strategies, my humble opinion is that it would be far from the purpose of this library. It would be better suited to a blog post demonstarting the power of `pandas-ta` through some examples of strategies implementations. The blog post would be, in a way, a frontpage for newcommers. Your attention should be directed towards developping the core of the lib.

**Comment by twopirllc** [comment]
> Thanks for the reply, I understand that it might be tricky to implement ;) I don't know if I can be of any help, this would be a great feature!

No worries.

As far as Strategies, there are not many common or default Strategies that the media pushes out... for instance, a Moving Average Crossover Strategy, et al. Eventually I should make some blog posts demonstrating the potential power of ```pandas-ta```, but a few more well known examples I think would be great to add to showcase the library without diminishing the purpose of the library. Adding known and unknown ```ta.Strategy()```'s are fairly lightweight overall because one can build upon the existing ```pandas-ta``` library without developing new atomic indicators.

**Comment by DrPaprikaa** [comment]
You're right, the hardest part might be to find people willing to share their strategies (and if they do, they might be outdated) ! But they would provide good use-cases anyway.

**Comment by DrPaprikaa** [comment]
I'd be happy to help build this feature if you point me in the right direction !

**Comment by twopirllc** [comment]
Hello @DrPaprikaa,

Hope all is well.

That would be great! Even something partially working would help.

I suppose the best place to start in the _strategy_ method would be here: [_mode["custom"]_](https://github.com/twopirllc/pandas-ta/blob/ab0862cbde0597a118a472a03abe5c47218efb66/pandas_ta[/core.py#L568). You will need to change your Strategy to use a tuple for the params instead of a list since a function, ```f```, takes _named args_, then a tuple of _args_, and finally _kwargs_; basically: ```f(named, *args, **kwargs)```

```python
CustomStrategy = ta.Strategy(
    name="MyStrat",
    ta=[
        {'kind':'sma', 'params':(30)}, 
        {'kind':'bbands', 'params':(20,2)}},
        {'kind':'macd', 'params':(8,21)}
    ]
)
```

In ```mode["custom"]```, make an ```if else``` block if there are ```params``` in ```ta``` and ```isinstance(params, tuple)```, then make another list comprehension similar to [Line 570](https://github.com/twopirllc/pandas-ta/blob/ab0862cbde0597a118a472a03abe5c47218efb66/pandas_ta/core.py#L570) where it stuffs the ```*args``` in the correct position. Then hopefully, the list comprehension is as simple as:

```python
[getattr(self, kwds["kind"])(*kwds["params"], **kwds) for kwds in ta]
```

If you are also interested in figuring out how to get **multiprocessing** working for a Custom Strategy, check out [Process Pools](https://docs.python.org/3.8/library/multiprocessing.html). The Process Pool type should be an _ordered_ variety since Custom Strategies support indicator chaining. You might also need to make a seperate [```mp_worker```](https://github.com/twopirllc/pandas-ta/blob/ab0862cbde0597a118a472a03abe5c47218efb66/pandas_ta/core.py#L29) to support this feature. 

Hope this helps!

Thanks again,
KJ

**Comment by twopirllc** [comment]
@DrPaprikaa,

To be clear I am not asking you to code the **multiprocessing** component, just if you are willing to take a stab at it or you have some familiarity with **multiprocessing**.

Thanks,
KJ

**Comment by DrPaprikaa** [comment]
Hi @twopirllc,

You basically did all the work ! I created a pull request (I hope I did it the right way, it's a first time !). I tested it with some custom strategies and various indicators : for example kurtosis (1-element tuple) and/or macd (3-elements tuple).

Note that the original code already works without this `if/else` statement, would you know why ? 

Unfortunately I'm not very familiar with multiprocessing !

**Comment by DrPaprikaa** [comment]
Hi @twopirllc,

You basically did all the work ! I created a pull request (I hope I did it the right way, it's a first time !). I tested it with some custom strategies and various indicators : for example kurtosis (1-element tuple) and/or macd (3-elements tuple) and it works fine.

Note that the original code already works without this `if/else` statement, would you know why ?

I'm not very familiar with multiprocessing, but I guess that with `mode["custom"]` the code should be identical to the next `else:`  statement of line 571, except for the line 581 that would become `mp_worker, ((self._df, getattr(self, kwds["kind"])(**kwds), kwargs) for kwds in ta), self.cores`. A quick test ran seamlessly on my machine.

I looked for other ways of parralelizing list comprehensions (https://stackoverflow.com/questions/5236364/how-to-parallelize-list-comprehension-calculations-in-python) but I wasn't able to get my head around them for this use-case.

**Comment by twopirllc** [comment]
Hello @DrPaprikaa,

Looks good! Nice job! Will it run the same if ```kwds["params"]``` were removed from the **if** statement? I'll throw in the test case when I merge it with development.

> Note that the original code already works without this if/else statement, would you know why ?

I do not know. 🤷‍♂️  I would rather have something working first before needing to make adjustments.

> I'm not very familiar with multiprocessing, but I guess that with mode["custom"] the code should be identical to the next else: statement of line 571, except for the line 581 that would become mp_worker, ((self._df, getattr(self, kwds["kind"])(**kwds), kwargs) for kwds in ta), self.cores. A quick test ran seamlessly on my machine.

That's essentially my though as well. Have you tried all the Custom Strategies in the Strategy Notebook Example? If the [Chained Custom Strategies](https://github.com/twopirllc/pandas-ta/blob/master/examples/PandasTA_Strategy_Examples.ipynb) break, then it would need an _ordered_ process pool type.

> I looked for other ways of parralelizing list comprehensions (https://stackoverflow.com/questions/5236364/how-to-parallelize-list-comprehension-calculations-in-python) but I wasn't able to get my head around them for this use-case.

Yeah. This implementation is not like **multiprocessing** tutorials and most guides or questions. That's what make it tricky. Or at least to me. 🤷‍♂️ 

Thanks again,
KJ

**Comment by DrPaprikaa** [comment]
Hi @twopirllc,

Yes it works even without the `if kwds["params"]`, since `isinstance(kwds["params"], tuple)` checks the value associated with the `'params'` key. I check with various tuple sizes, ints, floats, np.nan, they all work on my end so I guess we can delete this part of the if statement (didn't test with the example notebook tho).

However when running multiprocessing with a custom strategy, I've got two issues (on my end, at least) :

1. it is slower than without multiprocessing (~4 times with 6 indicators, i have 8 cores)
2. Applying prefixes/suffixes results in an error : `The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

**Comment by twopirllc** [comment]
Heya @DrPaprikaa,

> Yes it works even without the if kwds["params"], since isinstance(kwds["params"], tuple) checks the value associated with the 'params' key. I check with various tuple sizes, ints, floats, np.nan, they all work on my end so I guess we can delete this part of the if statement (didn't test with the example notebook tho).

Excellent!

> However when running multiprocessing with a custom strategy, I've got two issues (on my end, at least):

So you implemented *mp* with a Custom Strategy?

> 1. It is slower than without multiprocessing (~4 times with 6 indicators, i have 8 cores)

Can you please clarify this? It is slower with *mp* when running Custom Strategy? This is anecdotal but when you have few cores, it runs better when not utilizing all the cores. So if you have 8, try setting the cores to 6 or whichever number is consistently quicker.

> 2. Applying prefixes/suffixes results in an error : The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

I guess I would have to see it if you have *mp* implemented for the Custom Strategy. Does the following *not* work in that case?

```python
    for r in result:
        self._add_prefix_suffix(r, **kwargs)
        self._append(r, **kwargs)
```

Thanks again for contributing! I appreciate it.
KJ

**Comment by DrPaprikaa** [comment]
Hey,

Running with less cores is faster than with all cores, but still slower than without mp. I've updated the pull request with the full code (`'params'` and mp) so you can try on your end.



> Does the following _not_ work in that case?
> 
> ```python
>     for r in result:
>         self._add_prefix_suffix(r, **kwargs)
>         self._append(r, **kwargs)
> ```

That's exactly what's not working. I commented it out in the pull request. I guess we can continue this discusson there ?

**Comment by twopirllc** [comment]
Awesome, I'll take a look later.

**Comment by twopirllc** [comment]
@DrPaprikaa,

Thanks so much for your contributions to **Pandas TA**! Excellent work!

I think we can close this one for now.

Thanks,
KJ

**Comment by DrPaprikaa** [comment]
@twopirllc,

It was a pleasure, I'll continue to follow your awesome work.

DrPaprikaa

**Comment by twopirllc** [comment]
@DrPaprikaa,

Awesome! Thank you! I appreciate it.

With your recent experience in the belly of the ```core```, perhaps you may have some insight or ideas on how to improve ```_get_column()``` regarding Issue #137 when you have a moment.

Thanks,
KJ
