### ISSUE TITLE
problem in squeeze_pro.py

### ISSUE THREAD

**Issue by partyhead** [twopirllc/pandas-ta#817]
version pandas_ta-0.3.14b0
import pandas_ta as ta show error for the first line
from numpy import NaN as npNaN
change it to  
from numpy import nan as npNaN  
and all working
numpy try 1.26 and 2

**Comment by DOABrownie** [comment]
i had the same issue and this fix works. cheers

**Comment by bibsn** [comment]
one NaN remain in squeeze_pro.py
