### ISSUE TITLE
Add function update for the new data for live trading

### ISSUE THREAD

**Issue by Khanhlinhdang** [twopirllc/pandas-ta#825]
I am developing a trading platform using python, pyside6 with pandas-ta.
I am using current development version of pandas-ta, it still work well for me and i am not using ta-lib. 
But when I run multiple indicators simultaneously, it is seem all function's indicator have to re-caculate every time update new data.
It make the code slowly.
So, can you add new function. which can caculate only the new update data and add to result.
Thank you much!
This is my project, I am happy to show and share when it is done
https://www.facebook.com/groups/748831980507126
![image](https://github.com/user-attachments/assets/7be3ca26-26f6-4688-843d-7da11474198d)

**Comment by twopirllc** [comment]
Hello @Khanhlinhdang 

What you are looking for is Incremental Calculations. For more information see #632 or more generally, more previous common [issues/requests](https://github.com/twopirllc/pandas-ta/issues?q=is%3Aissue+incremental).

Good luck with your trading platform!

Kind Regards,
KJ
