### ISSUE TITLE
about cdl_doji and strategy()

### ISSUE THREAD

**Issue by wenny0501** [twopirllc/pandas-ta#83]
Hi, 
thanks a lot for your very useful library TA.
today I pip install it,and test it.
I found 2 problems.
1, in jupyter notebook and pycharm, I can import ha, but can not import cdl_doji.
2, df.ta.strategy() does not work.I tried df.ta.strategy(high), error exist yet. 
just look at the photos.
![ta](https://user-images.githubusercontent.com/68882045/88616253-acef7200-d061-11ea-8f77-228089b395a9.JPG)
![ta1](https://user-images.githubusercontent.com/68882045/88616258-af51cc00-d061-11ea-86d7-490b6a93256a.JPG)
![ta2](https://user-images.githubusercontent.com/68882045/88616260-b11b8f80-d061-11ea-8cc6-080a99e8bf8c.JPG)
![ta3](https://user-images.githubusercontent.com/68882045/88616265-b2e55300-d061-11ea-8908-11906053109d.JPG)

**Comment by twopirllc** [comment]
Hello @wenny0501,

Thanks for trying ```Pandas TA```!

If you are running the latest _pip_ version, I recommend upgrading to the latest repository version (per README):

### Latest Version

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

I highly recommend **reading** the [README](https://github.com/twopirllc/pandas-ta) and following along with some of the [Example Notebooks](https://github.com/twopirllc/pandas-ta/tree/master/examples).

For example, per the README, you need to properly import ```pandas-ta``` if you want to use the ```strategy``` method. On top of that, also import ```pandas```.

```python
import pandas as pd
import pandas_ta as ta

data = pd.read_csv("path/your.csv") # Or however your get your data

# In order to use pandas-ta methods, the primary columns: open, high, low, close, and volume
# need to be lower case
data.columns = data.columns.str.lower()

# To run all the indicators, all you need to do is:
data.ta.strategy() # See the README for more options

# Verify the new columns exist
list(data.columns)
```

Show me that the above is working for you before doing specific imports for individual indicators.

Hope this helps!
KJ

**Comment by wenny0501** [comment]
Thanks a  lot for your quick response.
After overcome many difficulties, delete, uninstall and install, now df.ta.strategy() works!!!
I also notice that there is a worning.
And all the name of indicators are capital. we need again to excute "df.columns = df.columns.str.lower()"
![ta](https://user-images.githubusercontent.com/68882045/88723414-d0b0c780-d0f6-11ea-9558-ac48fdda93a7.JPG)

**Comment by twopirllc** [comment]
Hello @wenny0501,

Glad you were able to get it working!

Yes. The primary columns, _open_, _high_, _low_, _close_, _volume_ **must** be _lower case_ so as to distinguish from the _upper case_ indicators.

I am unable to replicate the error you have posted. Can you share more of your prior code so that I can isolate the problem?

Thanks,
KJ

**Comment by wenny0501** [comment]
I find it, whether I run data.ta.strategy() on jupyter notebook or pycharm, this worning always comes.
I have run:
pip install pandas --upgrade
Successfully installed pandas-1.1.0
pycharm 2020.1.3 community Edition
![ta1](https://user-images.githubusercontent.com/68882045/88744628-ea153c00-d115-11ea-88ca-aa52c4db47c9.JPG)
![ta](https://user-images.githubusercontent.com/68882045/88744631-ef728680-d115-11ea-8714-d80cbf1706f5.JPG)

**Comment by twopirllc** [comment]
@wenny0501 

That's weird. Well it's just a **Pandas** warning and not an error with ```pandas-ta```.  You can disable the **Pandas** warning like so:

```python
import warnings
warnings.filterwarnings("ignore")
```

Other than that, ```pandas-ta``` appears to be working correctly as intended.

Thanks for getting back to me.
KJ

**Comment by twopirllc** [comment]
@wenny0501,

I assume by no response that the response provided was sufficient. Thus I will be closing this issue in a few days.

Don't forget to ⭐ if you find the library useful.

Thanks,
KJ
