### ISSUE TITLE
Ehler SSF inital values lookahead bias 

### ISSUE THREAD

**Issue by bangxiangyong** [twopirllc/pandas-ta#830]
https://github.com/twopirllc/pandas-ta/blob/b465491f226d9e07fffd4e59cd0affc9284521ca/pandas_ta/overlap/ssf.py#L35C53-L35C56

I think there is a bug or incorrect calculation with the Ehler SSF initial values when i==0, i==1, or i==2:
 `ssf.iloc[i] = c1 * close.iloc[i] + c2 * ssf.iloc[i - 1] + c3 * ssf.iloc[i - 2] + c4 * ssf.iloc[i - 3]` 

for instance, when `i=0`, `ssf.iloc[i-1]` would access the `-1` entry which is the last value in the series. such initialisation error would then propagate throughout the remaining series.

**Comment by twopirllc** [comment]
Hello @bangxiangyong,

Please verify that the _development_ version of [ssf](https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/overlap/ssf.py) **&** [ssf3](https://github.com/twopirllc/pandas-ta/blob/development/pandas_ta/overlap/ssf3.py) does not have this unfortunate issue and works as expected. Thanks!

Kind Regards
KJ
