### ISSUE TITLE
Suggesting the owner to add a contribution file 

### ISSUE THREAD

**Issue by SharifDer** [twopirllc/pandas-ta#832]
Hey there, I'm working on a project that requires technical analysis and there some indicators that I would like to use that are not available on the pandas_ta, so I thought it would be a good idea to contribute what I can for the this amazing lib. The issue is that I can't a contribution file that can give me the instruction of contribution should work in this lib.

**Comment by twopirllc** [comment]
Hello @SharifDer,

Sorry if I am uncertain what you are asking. Are you asking how to contribute?

If so, it is pretty simple. First, check out the _development_ branch and find an indicator(s) that are similar to the ones you want to include. Then follow the pinned Issue [Creating a Custom Indicator: The Big 4](https://github.com/twopirllc/pandas-ta/issues/355). Although some details are out dated, the concepts still apply:

1. Create the indicator
2. Make sure you can run it and the tests are up to your standards.
3. Then hook it up the the Pandas DataFrame Extension and test it.

If this is not what you meant, please clarify so I can address it properly.

Kind Regards,
KJ

**Comment by bhawani0x** [comment]
I think you need to update this [https://github.com/twopirllc/pandas-ta/issues/355](https://github.com/twopirllc/pandas-ta/issues/355) , its not working anymore

**Comment by twopirllc** [comment]
@bhawani0x 

Contributions are always welcome! So much to do. 😎
