### ISSUE TITLE
incorrect importing of nan in squeeze_pro

### ISSUE THREAD

**Issue by skanduru** [twopirllc/pandas-ta#840]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
>>> import pandas_ta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/pandas_ta/__init__.py", line 116, in <module>
    from pandas_ta.core import *
  File "/usr/local/lib/python3.11/dist-packages/pandas_ta/core.py", line 18, in <module>
    from pandas_ta.momentum import *
  File "/usr/local/lib/python3.11/dist-packages/pandas_ta/momentum/__init__.py", line 34, in <module>
    from .squeeze_pro import squeeze_pro
  File "/usr/local/lib/python3.11/dist-packages/pandas_ta/momentum/squeeze_pro.py", line 2, in <module>
    from numpy import NaN as npNaN
ImportError: cannot import name 'NaN' from 'numpy' (/usr/local/lib/python3.11/dist-packages/numpy/__init__.py)
>>>

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

**Describe the bug**
There is no `NaN` in the numpy package and for all the indicators except squeeze_pro, the variable `nan` is correctly imported.

In squeeze_pro the variable `NaN` is imported.   The statement

from numpy import NaN as npNaN 

should have been

from numpy import nan as npNaN
 
After fixing this error the importing of pandas_ta was successful

>>> import pandas_ta as ta
>>> print(ta.version)
0.3.14b0
>>>

**To Reproduce**
Provide sample code.
import pandas_ta as ta     causes this error

**Expected behavior**
The import of pandas_ta shouldn't cause an error
**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @skanduru,

Again...
> Have you tried the development version? Did it resolve the issue?

**Comment by Ascensao** [comment]
I had the same problem:
![error2](https://github.com/user-attachments/assets/b84ed9fc-6a30-4b5b-98bd-156b3aaa82b0). 

But I managed to fix it by **replacing** this line:

`from numpy import NaN as npNaN`

**for this ones**:

`import numpy as np
npNaN = np.nan`

in the `squeeze_pro.py`

**Comment by ewan777** [comment]
This issue seems to be fixed on the development version. However, withe the development version I am getting the following error:

An error occurred while loading the file: No module named 'numpy._core.numeric'
Updating to numpy==2.0.0 seemed to resolve this issue.

I also had to install setuptools to make this package work

**Comment by dmike23** [comment]
> I had the same problem: ![error2](https://private-user-images.githubusercontent.com/8701603/380248744-b84ed9fc-6a30-4b5b-98bd-156b3aaa82b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MzI4MTgsIm5iZiI6MTczMjgzMjUxOCwicGF0aCI6Ii84NzAxNjAzLzM4MDI0ODc0NC1iODRlZDlmYy02YTMwLTRiNWItOThiZC0xNTZiM2FhYTgyYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjhUMjIyMTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEwNTRkNjkzNTEyYTdlMzNhNDVmMDc1Yzk4MDg4YTBlNWJjM2I2YTM5YmNkN2VkZWEzMmQ3YzdlMjA4OTNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wMeceVrE9L8Vaje5PEZNaTSTAZKh3T-pY_rwE66HhKw).
> 
> But I managed to fix it by **replacing** this line:
> 
> `from numpy import NaN as npNaN`
> 
> **for this ones**:
> 
> `import numpy as np` `npNaN = np.nan`
> 
> in the `squeeze_pro.py`

wait what?

You changed "from numpy import NaN as npNaN" 

to  `import numpy as np` `npNaN = np.nan` , ????

what am I missing here?
