### ISSUE TITLE
 No module named 'numpy._core.numeric'

### ISSUE THREAD

**Issue by ewan777** [twopirllc/pandas-ta#842]
I installed the _development_ version to resolve the NaN as npNaN bug.

TA_LIB not installed

With the _development_ version I encountered the following error:

```An error occurred while loading the file: No module named 'numpy._core.numeric```

Installing ```numpy==2.0.0``` seemed to resolve this issue (is this safe?) 

NB: Also I had to install  setuptools to get pandas_ta to work.

**Comment by Philip030601** [comment]
Hi Ewan, I got rid of that NaN as npNan bug.  thanks for posting how to get rid of it.  Hopefully, I dont have to do the rest that you did to get it to work.  lol

**Comment by twopirllc** [comment]
Hello @ewan777  and @Philip030601,

> NB: Also I had to install setuptools to get pandas_ta to work.

Python 3.12 [removed setuptools](https://docs.python.org/3.12/whatsnew/3.12.html), hence it is required for installation. Furthermore, it is listed in the _development_ [requirements.txt](https://github.com/twopirllc/pandas-ta/blob/development/requirements.txt). 

> With the development version I encountered the following error:
> ```An error occurred while loading the file: No module named 'numpy._core.numeric```
&
> Installing ```numpy==2.0.0``` seemed to resolve this issue (is this safe?)

Ok. But you also haven't provided the minimal necessary details requested from you in the [Bug Report](https://github.com/twopirllc/pandas-ta/issues/new/choose) so somone can isolate and replicate and potentially fix (if possible). 🤷🏼‍♂️ 

Furthermore, perhaps you should open a bug report with **numpy** and ask them about error and about safety.

**Comment by twopirllc** [comment]
Doh! 🤦🏼‍♂️  (Accidently "closed" issue by mistake.)

Also if _numpy 2.x_ is not working, then try the last _1.x._ release. There are several numpy 2 issues here suggesting that if you absolutely do not need 2.x **now**. 😓 

Kind Regards,
KJ
