### ISSUE TITLE
Pandas_ta not working

### ISSUE THREAD

**Issue by Patsy2024** [twopirllc/pandas-ta#845]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
Python version 3.13
Pandas_ta version 0.3.14B
MAC OS Sequoia

**Do you have _TA Lib_ also installed in your environment?**
No

**Have you tried the _development_ version? Did it resolve the issue?**
I did not

**Describe the bug**
The following error code states:  "ModuleNotFoundError: No module named 'pkg_resources'"

**To Reproduce**
import pandas_ta as ta

**Expected behavior**
Apply technical indicators without error message

**Screenshots**
Not necessary.

**Additional context**
pandas_ta works on python version 3.12.6
Numpy 2.1.2 is installed

Thanks for using Pandas TA!

**Comment by ewan777** [comment]
install setuptoos

pip install setuptools

you may need to install  numpy 2.0.0

pip install numpy==2.0.0

This worked for me on Linux Mint using a virtual environment

**Comment by Patsy2024** [comment]
Is there a release date for non development version?

**Comment by twopirllc** [comment]
@Patsy2024 

It is not a high churn library, so unfortunately not. Although some are been helping, this project still needs more assistance.
