### ISSUE TITLE
QQE indicator

### ISSUE THREAD

**Issue by cbogithub** [twopirllc/pandas-ta#85]
hi, i see a QQE indicator is nice :
https://www.tradingview.com/script/IYfA9R2k-QQE-MT4/

 i converted it to python, can you see and show me your idea 

https://pastebin.com/upES9U3A
```
	def qqe_pd2(self, rsi_period2: object, rsi_period: object, rsi_smooth: object, qqe_factor: object, array: object = False) :

		close = pd.Series(self.close)
		open = pd.Series(self.open)
		high = pd.Series(self.high)
		low = pd.Series(self.low)

		if not rsi_period: rsi_period = 14
		if not rsi_smooth: rsi_smooth = 5
		if not qqe_factor: qqe_factor = 4.236

		rsi_period2 = 14

		wilders_period = rsi_period * 2 - 1

		rsi = talib_pd.rsi(close, rsi_period)
		rsima = talib_pd.ema(rsi, rsi_smooth)
		atrrsi = abs(rsima.shift(1) - rsima)
		maatrrsi = talib_pd.ema(atrrsi, wilders_period)
		dar = talib_pd.ema(maatrrsi, wilders_period) * qqe_factor

		deltafastatrrsi = dar
		rsindex = rsima

		longband = rsindex.replace(rsindex.tolist(), 0)
		shortband = rsindex.replace(rsindex.tolist(), 0)
		trend = 0

		newshortband = rsindex + deltafastatrrsi
		newlongband = rsindex - deltafastatrrsi

		# longband := rsindex[1] > longband[1] and rsindex > longband[1]?max(longband[1], newlongband): newlongband
		if (rsindex.shift(1) > longband.shift(1)) and (rsindex > longband.shift(1)):
			longband = np.maximum(longband.shift(1), newlongband)
		else:
			longband = newlongband

		# shortband := rsindex[1] < shortband[1] and rsindex < shortband[1]?min(shortband[1], newshortband): newshortband
		if (rsindex.shift(1) < shortband.shift(1)) and (rsindex < shortband.shift(1)):
			shortband = np.minimum(shortband.shift(1), newshortband)
		else:
			shortband = newshortband

		# trend := cross(rsindex, shortband[1])?1: cross(longband[1], rsindex)?-1: nz(trend[1], 1)

		if talib_pd.cross(rsindex,shortband.shift(1),above=True):
			trend = 1
		elif talib_pd.cross(rsindex,shortband.shift(1),above=False):
			trend = -1
		else:
			trend = 0


		# fastatrrsitl := trend == 1? longband: shortband
		if  trend == 1:
			fastatrrsitl = longband
		else:
			fastatrrsitl = shortband

```

**Comment by twopirllc** [comment]
Hello @cbogithub,

QQE looks interesting. How is it looking visually compared to data in TradingView? Relatively close? We can add it no problem. I do not have a timeframe yet of when I will implement it as I am in the middle of fixing and adding another indicator currently.

Keep me posted.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hi @cbogithub,

I finally had some time to work on **QQE**. It is largely completed, but there is some additional cleanup to do before I put it on the _development_ branch. Hopefully not later by the end of this week.

Here is a screenshot:
<img width="684" alt="Screen Shot 2020-11-03 at 4 04 38 PM" src="https://user-images.githubusercontent.com/18198392/98053946-9db15a80-1dee-11eb-9ade-ad283875d98f.png">

versus TradingView:
<img width="647" alt="Screen Shot 2020-11-03 at 4 05 51 PM" src="https://user-images.githubusercontent.com/18198392/98053952-a0ac4b00-1dee-11eb-82f8-bf08d925bca1.png">

Thanks for your patience.

Regards,
KJ

**Comment by cbogithub** [comment]
👍 .thanks

**Comment by twopirllc** [comment]
@cbogithub,

It is ready on Github:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Let me know how it works for you. Thanks for your patience.

Thanks,
KJ
