### ISSUE TITLE
Indicator: Fisher Transform (FISHT)

### ISSUE THREAD

**Issue by alexonab** [twopirllc/pandas-ta#86]
The indicator in its current form does not return the signal line.  Could this be updated to return a DataFrame with the FT and FT signal values?

https://library.tradingtechnologies.com/trade/chrt-ti-ehler-fisher-transformation.html

**Comment by twopirllc** [comment]
Hello @alexonab,

Sure. I'll append it to the list or someone else can modify it and make a pull request.

In the mean time, you can do the following:
```python
df = <your_ohlcv>
df.ta.fisher(append=True)
df.ta.ema(close=df[df.columns[-1]], length=5, prefix="FISHERT", append=True)
```

Don't forget to ⭐ if you find the library useful.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hey @alexonab,

I'm digging into **fisher**. I will have to break it up into different implementations: _Trading Tech_, _Trading View_ and _Tulip_. Slight variations even with the signal line.

KJ
