### ISSUE TITLE
Fix issue with "from numpy import NaN as npNaN" 

### ISSUE THREAD

**Issue by peanutsee** [twopirllc/pandas-ta#860]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
Yes

**Have you tried the _development_ version? Did it resolve the issue?**
Yes

**Describe the bug**
Error from `from numpy import NaN as npNaN` in `squeeze_pro.py`.

**To Reproduce**
Run `import pandas-ta as ta`

**Expected behavior**
`import pandas-ta as ta` to run without errors.

**Comment by peanutsee** [comment]
@twopirllc How do I contribute to the code base?

**Comment by gguan** [comment]
Downgrade numpy version to 1.26.4 or manually install development version of pandas-ta

**Comment by twopirllc** [comment]
Hello @peanutsee 

The resolution provided by @gguan is correct.

Please do **not** open _duplicate_ Issues. This is a common and known (see Issue #857) for those running Pandas TA _v0.3.14b_ and trying to run Numpy 2.x. It has been addressed more than once. Please read my comments and the links I provided for more context.

Contributing is easy:

1. Fork the repo
2. Checkout the _development_ branch and **NOT** the _main_ branch.
3. Make edits & check your work.
4. Submit PR

Kind Regards,
KJ
