### ISSUE TITLE
Attribute error when using yfinance for data loading

### ISSUE THREAD

**Issue by miracle-a-osigwe** [twopirllc/pandas-ta#861]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
[pandas_ta version 0.3.14b0]

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
[Not the cause]

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
[I checked the development, did not find the integration in it]

**Describe the bug**
When I try using yfinance to fetch data, it is throwing an attribute error.

**To Reproduce**
Provide sample code.
[
import pandas as pd
import pandas_ta as ta

df = pd.DataFrame() # Empty DataFrame

# Load data
# df = pd.read_csv("path/to/symbol.csv", sep=",")
# OR if you have yfinance installed
df = df.ta.ticker("aapl")
]

**Expected behavior**
[
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 4
      1 # Load data
      2 # df = pd.read_csv("path/to/symbol.csv", sep=",")
      3 # OR if you have yfinance installed
----> 4 df = df.ta.ticker("aapl")

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas_ta\core.py:851, in AnalysisIndicators.ticker(self, ticker, **kwargs)
    849 ds = ds.lower() is not None and isinstance(ds, str)
    850 # df = av(ticker, **kwargs) if ds and ds == "av" else yf(ticker, **kwargs)
--> 851 df = yf(ticker, **kwargs)
    853 if df is None: return
    854 elif df.empty:

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas_ta\utils\data\yahoofinance.py:86, in yf(ticker, **kwargs)
     84 if Imports["yfinance"] and ticker is not None:
     85     import yfinance as yfra
---> 86     yfra.pdr_override()
     88     # Ticker Info & Chart History
     89     yfd = yfra.Ticker(ticker)

AttributeError: module 'yfinance' has no attribute 'pdr_override'
]

**Screenshots**
![Screenshot 2024-12-14 151915](https://github.com/user-attachments/assets/a22adae7-c643-4861-bcf0-4ff20808361f)

**Additional context**

[This has to do with the attempt to run .pdr_override()]

Thanks for using Pandas TA!

**Comment by miracle-a-osigwe** [comment]
I encountered the issue when using yfinance version '0.2.50'

**Comment by Sinansi** [comment]
I believe this library should be better archived. It is outdated and full of bugs and not compatible anymore with its dependencies.

**Comment by twopirllc** [comment]
Hello @miracle-a-osigwe 

> [I checked the development, did not find the integration in it]

Of course it is there! ⬇️ 

https://github.com/twopirllc/pandas-ta/blob/438f3a97b71b26bc17efb1a204fb0e0fdc48e0aa/pandas_ta/core.py#L754-L830


@Sinansi 

Please familiarize yourself with the [Guidelines](https://github.com/twopirllc/pandas-ta/blob/development/CODE_OF_CONDUCT.md) before making baseless claims.

Kind Regards
KJ

**Comment by miracle-a-osigwe** [comment]
Apologies for the error, I followed the main branch structure, and did not observe that it was implemented differently in the dev branch. Thank you for the correction
