### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by vinaychuri** [twopirllc/pandas-ta#866]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
**Python 3.12.8
pandas_ta , dev(0.4.19b0), stable(0.3.14b)**

**Do you have _TA Lib_ also installed in your environment?**
**ta-lib 0.5.1**

**Have you tried the _development_ version? Did it resolve the issue?**
Yes, same issue

**Describe the bug**
_...python3.12/site-packages/pandas_ta/maps.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import get_distribution, DistributionNotFound_

**To Reproduce**
import pandas_ta as ta

**Comment by twopirllc** [comment]
Hello @vinaychuri 

See if #821 solves your issue.

Kind Regards,
KJ
