### ISSUE TITLE
RSI resulting in None value

### ISSUE THREAD

**Issue by iamaakashbasnet** [twopirllc/pandas-ta#869]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
TA-Lib 0.4.32

**Have you tried the _development_ version? Did it resolve the issue?**
No

**Describe the bug**
RSI resulting None value

![Screenshot from 2024-12-30 23-33-14](https://github.com/user-attachments/assets/08a055ed-3a9a-45c0-8cd6-88be9dbb5ae7)

**Comment by iamaakashbasnet** [comment]
@twopirllc Doing this way I'm finally able to get the values.

![Screenshot from 2024-12-31 10-10-25](https://github.com/user-attachments/assets/a1ad6703-7d10-429c-8e5e-8b20f8404cfb)

**Comment by twopirllc** [comment]
Hello @iamaakashbasnet 

Great! Glad you figured it out.
Though I recommend running the _development_ version instead.

Kind Regards,
KJ
