### ISSUE TITLE
Relative strength

### ISSUE THREAD

**Issue by SoftDevDanial** [twopirllc/pandas-ta#88]
Hi , is it possible for you to add relative strength? The only thing i found was relative strength and not relative strength. Here is a few links about relative strength.

[Relative Strength]
https://www.investopedia.com/terms/r/relativestrength.asp 

[Relative Strength vs Relative Strength Index]
https://advisoranalyst.com/2016/11/01/relative-strength-vs-relative-strength-index-whats-the-difference.html/

**Comment by SoftDevDanial** [comment]
Hi, can you also add force index?

https://www.investopedia.com/terms/f/force-index.asp#:~:text=The%20force%20index%20is%20a,book%20Trading%20for%20a%20Living.

https://www.daytrading.com/force-index

https://tlc.thinkorswim.com/center/reference/Tech-Indicators/studies-library/E-F/ForceIndex#:~:text=The%20Force%20Index%20study%20combines,negative%20values%20indicate%20the%20downtrend.

**Comment by twopirllc** [comment]
Hello @SoftDevDanial,

To be fair, I am confused by: 

> The only thing i found was relative strength and not relative strength.

# Relative Strength Index

**Done!** The _Relative Strength Index_, is called **rsi** under the _Momentum_ category in ```Pandas TA```'s README. Also see Issue #89 on help to easily get a list of the indicators.

Using **rsi** is simple with ```Pandas TA```.

```python
import pandas as pd
import pandas_ta as ta

data = pd.read_csv("path/to/symbol.csv", **kwargs) # Or whatever your data source...

# Help about rsi
help(ta.rsi)

# There are multiple ways of calling an indicator:
# 1) TA Lib Way
rsi14 = ta.rsi(data["close"], length=14)

# 2) With the Pandas DataFrame extension 'ta'
data.ta.rsi(length=14, append=True) # append=True, adds it to the data DataFrame

# 3) A less common way
data.ta(kind='rsi', length=16, append=True)

# Sanity check
data.columns
```

# Relative Strength

There is no _Relative Strength_. According to the second link, _Relative Strength_ belongs to Comparative Analytics. Fundamental and Technical Analysis libraries would be part of a Comparative Analytics Application. That package would allow a user to maintain different universes of assets grouped in different ways with different types of analytics to be performed on them, compared and ranked. That is beyond the scope of the purpose of this library. ```Pandas TA``` is built to easily apply Technical Analysis Indicators. There is a good chance someone has something similar to a Comparative Analytics Library/Module/Framework/Application already on Github.

Again, I recommend reading the README and looking at the Example Notebooks and the _Watchlist Class_ under the [Examples Directory](https://github.com/twopirllc/pandas-ta/tree/master/examples). The _Watchlist Class_ is a simple Class to load/download financial market data and automatically apply Technical Analysis indicators with a Pandas TA Strategy. Edit the _Watchlist Class_ to hookup your Data Source. That should get you close to creating your own Comparative Analytics program, with the actual comparisons left up to the user.

Lastly, please make different issues for different topics.

Hope this helps!

Don't forget to ⭐ if you find the library useful.

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
Oh sorry i mistyped.. what i mean to say was i found relative strength index and not relative strength. Oh so its not technical analysis? I thought that the studies in thinkorswim is considered as technical analysis. Here thinkorswim compares the current stock with SPX then returns the ratio relationship between them
![image](https://user-images.githubusercontent.com/64815604/89628529-ff852580-d8ce-11ea-93f1-bd14fad5d2f2.png)

![image](https://user-images.githubusercontent.com/64815604/89628636-2ba0a680-d8cf-11ea-81eb-14d93abe54e7.png)

If its still not technical analysis can you please close this. Probably need to lookup on comparitive analysis python.

Thank you!

**Comment by twopirllc** [comment]
Hello @SoftDevDanial,

Yes, **Relative Strength** is a part of the Technical Analysis umbrella. But it the next abstraction above classical Technical Analysis, i.e. SMA, MACD, RSI, et al.

```Pandas TA``` by design is built so that a DataFrame represents one asset and you can run any or all indicators on that asset. **Relative Strength** is technically doable and I can add an independent function to divide two or more assets (or Series) together. However it will not be a DataFrame indicator like all the others, like ```df.ta.macd()``` or ```df.ta.efi()``` et al. So it can be called like: ```ta.relstr(base, other, **kwargs)``` if that works for you?

Since I am knee deep in adding and fixing some other issues, it will be added to the queue with no expected implementation time yet. For the mean time, I have written a preliminary version that you can use till I do roll it into ```Pandas TA```.

```python
import pandas as pd

def relstr(base: pd.Series, other: pd.Series, unit: bool = False):
    ratio = other[0] / base[0]
    rs = (other / base)
    
    # If you want the Relative Strength to start from 1 instead
    # of it's initial ratio
    if unit: 
        rs /= ratio
    return rs, ratio

rs, sratio = relstr(XLK.close, AAPL.close, unit=False)
print(f"Relative Strength Ratio: {sratio}")
rs.plot(figsize=(16, 8), color=['black'], grid=True)
```

Ideas? Thoughts?

Hope this helps!

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
Ohh i see. Actually i already tested it out and the code you gave me works perfectly. The only thing i could think off adding from it is probably another argument which is to select the initial date (the position of the date in the series e.g other[20]) for the ratio because probably some people would be pulling maybe 600 days data and probably would want the ratio and rs to be at position 365 instead of 600. Probably need to slice the list for other and base . I mean people can code them themselves to slice it but i do feel like its much easier if it was already in it so they can simply type a few numbers instead of typing the line or maybe more code to slice it.

**Comment by twopirllc** [comment]
Yes. That was one of the additional features that has to be added to find the first non-NaN value shared between them. Plus the feature to detect and process a list of *others* so you can easily see a larger subset besides only one. That i why I called it preliminary, a minimum working function to get you going till a more robust one is completed and added to the library.

**Comment by twopirllc** [comment]
Also because it is "basically" division, you can pass in indicators for comparison also if the indicator returns a Series. If an indicator returns a DataFrame, then you will need to select the same column for both DataFrames. 

For example:
```python
rs, sratio = relstr(ta.rsi(XLK.close), ta.rsi(AAPL.close), unit=False)
print(f"Relative Strength Ratio: {sratio}")
rs.plot(figsize=(16, 8), color=['black'], grid=True, title="RSI RELSTR")

rs, sratio = relstr(ta.macd(XLK.close).iloc[:,0], ta.macd(AAPL.close).iloc[:,0], unit=False)
print(f"Relative Strength Ratio: {sratio}")
rs.plot(figsize=(16, 8), color=['black'], grid=True, title="MACD RELSTR")
```

**Comment by kgonia** [comment]
There is also Relative strength described by Robert Levy . It says how far is price from average price. 

The formula is as follows:
RS  = (close_price – SMA 130)/ SMA 130*100

Then it can be used in Comparative Analytics but calculation is based on one asset like for any other TA indicator.

@twopirllc Do you think such implementation would be useful? I will be happy to do that.

**Comment by twopirllc** [comment]
Hello @kgonia,

You can, but there is the **bias** indicator that is largely the same thing.

You can implement Levy's Relative Strength by modifying **bias** like so:
```python
import pandas_ta as ta

rs = 0.01 * ta.bias(close, length=130)
```

If you want to code something up, it would be great if you tried out Bill Williams' Fractals or Alligator Indicators as mentioned in Issue #194. If that sounds doable, please let me know.

Kind Regards,
KJ

**Comment by mollawas10** [comment]
> 
> 
> Hi, can you also add force index?
> 
> https://www.investopedia.com/terms/f/force-index.asp#:~:text=The%20force%20index%20is%20a,book%20Trading%20for%20a%20Living.
> 
> https://www.daytrading.com/force-index
>
> https://www.forexing.com/broker-reviews
> 
> https://tlc.thinkorswim.com/center/reference/Tech-Indicators/studies-library/E-F/ForceIndex#:~:text=The%20Force%20Index%20study%20combines,negative%20values%20indicate%20the%20downtrend.

Hi, can you also add force index?

**Comment by twopirllc** [comment]
Hello @mollawas10,

> Hi, can you also add force index?

In Pandas TA, it is [**efi**](https://github.com/twopirllc/pandas-ta/blob/main/pandas_ta/volume/efi.py).

Please make a new Issue for future indicator requests. It is easier to keep track of things.

Kind Regards,
KJ

**Comment by abstract-thinking** [comment]
> Hello @kgonia,
> 
> You can, but there is the **bias** indicator that is largely the same thing.
> 
> You can implement Levy's Relative Strength by modifying **bias** like so:
> 
> ```python
> import pandas_ta as ta
> 
> rs = 0.01 * ta.bias(close, length=130)
> ```
> 
> If you want to code something up, it would be great if you tried out Bill Williams' Fractals or Alligator Indicators as mentioned in Issue #194. If that sounds doable, please let me know.
> 
> Kind Regards, KJ

Hi @twopirllc,

I'm interested in calculating the relative strength levy (rsl) as well.

But I don't understand you answer:

```
data = yf.download('AAPL', (now - relativedelta(years=1)).date(), now.date())

rs = 0.01 * ta.bias(data['Adj Close'], length=130)
```

The result is:

2022-04-19    0.000156

I would expect 0,992?

It bias really the solution?

Thanks,
Markus

**Comment by twopirllc** [comment]
@abstract-thinking,

> It bias really the solution?

At the time, I did not have the actual source for comparison, so I went off what @kgonia shared, so I may have interpreted it incorrectly and bias was the most similar.

```python
sma130 = ta.sma(df.close, 130)
RS = (df.close – sma130) / sma130 * 100  # Incorrect version
```

<br/>

Now that you have brought it up again, I was able to find one on [TradingView](https://www.tradingview.com/script/SDCx5OWv-Relative-Strength-Levy/) and it is rather simple:

```python
data = yf.download('AAPL', (now - relativedelta(years=1)).date(), now.date())
rsl = df.Close / ta.sma(df.Close, length=130)
```

<br/>
<img width="342" alt="Screen Shot 2022-04-20 at 2 51 00 PM" src="https://user-images.githubusercontent.com/18198392/164330482-b866e2f2-ba5e-4c20-a6cb-dba09f35b561.png">

<br/>

Apologies for the confusion and misinformation.

Kind Regards,
KJ
