### ISSUE TITLE
Hi, can you also add force index?

### ISSUE THREAD

**Issue by twopirllc** [twopirllc/pandas-ta#89]
Hi, can you also add force index?

https://www.investopedia.com/terms/f/force-index.asp#:~:text=The%20force%20index%20is%20a,book%20Trading%20for%20a%20Living.

https://www.daytrading.com/force-index

https://tlc.thinkorswim.com/center/reference/Tech-Indicators/studies-library/E-F/ForceIndex#:~:text=The%20Force%20Index%20study%20combines,negative%20values%20indicate%20the%20downtrend.

_Originally posted by @SoftDevDanial in https://github.com/twopirllc/pandas-ta/issues/88#issuecomment-670031445_

**Comment by twopirllc** [comment]
Hello @SoftDevDanial,

## Elder's Force Index

**Done!** _Elder's Force Index_'s short name is called  **efi** located under the _Volume_ category way at the bottom of the README. 

<img width="522" alt="Screen Shot 2020-08-06 at 1 51 00 PM" src="https://user-images.githubusercontent.com/18198392/89581871-8f05d800-d7ec-11ea-871d-447b3b39ce57.png">

Also in the README are examples on getting help with ```Pandas TA```.

```python
import pandas as pd
import pandas_ta as ta

# Help about this, 'ta', extension
help(pd.DataFrame().ta)

# Prints out a list of all indicators
pd.DataFrame().ta.indicators()

# Returns a list of indicators as a list if needed
indicator_list = pd.DataFrame().ta.indicators(as_list=True)

# Help about the log_return indicator
help(ta.log_return)
```

## Examples

I suggest looking at the [Example Notebook](https://github.com/twopirllc/pandas-ta/blob/master/examples/example.ipynb). The second [Notebook](https://github.com/twopirllc/pandas-ta/blob/master/examples/PandasTA_Strategy_Examples.ipynb) is helpful if you want to build your custom Strategy.

Hope this helps!

Don't forget to ⭐ if you find the library useful.

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
Oh wow i didn't no there was a readme for the names of the indicator. I had to click and check the names one by one before this haha. 

Thank You!

**Comment by twopirllc** [comment]
No worries.

What did you have to click and check?

Thanks,
KJ

**Comment by SoftDevDanial** [comment]
![image](https://user-images.githubusercontent.com/64815604/89667092-1ac35580-d90e-11ea-87e7-49e083670853.png)

Had to press each code and look at the comments to see what indicator it was haha

**Comment by twopirllc** [comment]
Yeah, that's a good way to deep dive into the indicators. But I publish the list of them all in the README.
