### ISSUE TITLE
could you add SMIIO?

### ISSUE THREAD

**Issue by wenny0501** [twopirllc/pandas-ta#92]
Hi, twopirllc,
I find that you maintain pandas-ta very diligent. Thank you for your work.
I find a indicator is useful, SMIIO, SMI Ergodic Indicator/Oscillator.
[https://www.tradingview.com/chart/LOCO/wsKsWzWo-Momentum-based-SMIIO-Indicator/](url)
yes, I find  Stochastic in pandas-ta, I think  Stochastic is too sensitive.
I tried to code SMIIO but not success.
Could you add SMIIO to pandas-ta?

**Comment by twopirllc** [comment]
Hello @wenny0501,

Thanks! Glad you like the library. Don't forget to ⭐ if you find the library useful.

I will add **SMIIO** to the queue. Thanks for the link as well, saves me time looking around. 👍 

Regards,
KJ

**Comment by twopirllc** [comment]
Hi @wenny0501,

Just checked the link and it doesn't work. Redirects to Github.

Thanks,
KJ

**Comment by wenny0501** [comment]
[https://www.tradingview.com/chart/LOCO/wsKsWzWo-Momentum-based-SMIIO-Indicator/](https://www.tradingview.com/chart/LOCO/wsKsWzWo-Momentum-based-SMIIO-Indicator/)

**Comment by twopirllc** [comment]
Thank you!

**Comment by twopirllc** [comment]
Hello @wenny0501,

Trying to get this out this week.

Thanks for your patience,
KJ

**Comment by twopirllc** [comment]
@wenny0501,

Currently on the _development_ branch. Doing a final review of changes before updating the _master_ on Github.

KJ
