### ISSUE TITLE
Shutdown the log

### ISSUE THREAD

**Issue by Morgiver** [twopirllc/pandas-ta#93]
Hi, i'm changing my language project, coming from Javascript NodeJS to Python, so i'm little lost for this little thing.
I'm pretty new in Python ^^

I have a message that i would like to delete, i don't want use multiprocessing 'cause i'm using it for another thing in my project.
```
[i] Set 'df.ta.mp = True' to enable multiprocessing. This computer has 12 cores. Default: False
```

Someone know how i can shut down the log of pandas-ta ?

**Comment by twopirllc** [comment]
Hello @Morgiver,

Welcome to Python and thanks for trying ```Pandas TA```!

To remove the following message:
```[i] Set 'df.ta.mp = True' to enable multiprocessing. This computer has 12 cores. Default: False```

Edit ```/path/to/pandas_ta/core.py``` and remove the following lines in the ```strategy()``` method:
```python
            if random() < 0.1:
                print(f"[i] Set 'df.ta.mp = True' to enable multiprocessing. This computer has {cpus} cores. Default: False")
```

Hope that helps!

Drop a :star: if you find the library useful.

Thanks,
KJ

**Comment by Morgiver** [comment]
hi ! Thank you, exactly what i need :)

It could be interresting to have a parameter to set the verbose on or off !

**Comment by twopirllc** [comment]
@Morgiver,

Thanks for the prompt reply. It only shows 10% of the time it runs so it's not too invasive and just a helpful hint.

Thanks for the suggestion. Maybe I'll make a ```hints``` property instead since it really doesn't fall into the ```verbose``` category.

How come you are switching to Python from JS? Or are you expanding your skill set?

Regards,
KJ

**Comment by Morgiver** [comment]
@twopirllc 

I'm working on a Trading Bot. 
NodeJS is really slow and the multithreading is not easy to handle. I take one big week to approach Python and change the langage on my project. It was more easy than i expect.

Python have many really good package, i'm demanding my self why i don't take Python in the first place sooner.
Now i don't even look at JS, Python is my new girlfriend :p 

I have a lot of work to handle Python properly but it's a pleasure to discover it !

Your package is really usefull, i thank you for your great work ! :)

Regards, 
Morgiver

**Comment by twopirllc** [comment]
@Morgiver,

Thank you! It's come along way from a private repo to Open Sourcing as well as learning Python 3 and the other plethora of frameworks and libraries in the Fintech spectrum.

A couple of years ago I built a MVP Discord Bot. It would download data, do TA, make chart and send it back to the channel. Now I need a compatible back testing library and then build a better Bot again soon.

> Now i don't even look at JS, Python is my new girlfriend :p

😆

Regards,
KJ
