### ISSUE TITLE
 module 'pandas_ta' has no attribute 'Strategy'

### ISSUE THREAD

**Issue by jaymasimba** [twopirllc/pandas-ta#94]
Hallo,
I had imported pandas_ta as ta

Was trying to test the pandas_ta module using the examples provided and I always get the below errors whenever I try using the ta.Strategy or the others as well

module 'pandas_ta' has no attribute 'Strategy'
module 'pandas_ta' has no attribute 'AllStrategy'
module 'pandas_ta' has no attribute 'CommonStrategy'

Kindly advice

**Comment by twopirllc** [comment]
Hello @jaymasimba,

Why did you close the issue? Did you figure it out? What code did you use specifically? Did you look at the [Example Notebooks](https://github.com/twopirllc/pandas-ta/tree/master/examples)?

```python
import pandas as pd
import pandas_ta as ta

data = pd.read_cs("path/to/your/symbol.csv")
print(ta.AllStrategy)
data.ta.strategy() # Automatically run ta.AllStrategy and appends to data DataFrame

# Or you can run the Common Strategy
print(ta.CommonStrategy)
data.ta.strategy(ta.CommonStrategy)

# Or create your own Strategy like the Examples in the Notebook
jays_ta = [
    {"kind": "sma", "length": 10},
    {"kind": "rsi"},
    {"kind": "macd"}
]
my_strategy = ta.Strategy(name="jay's strategy", ta=jays_ta)
data.ta.strategy(my_strategy)
```

Hope this helps!

Thanks,
KJ

**Comment by andybrewer** [comment]
Running into the same error using your code above and the example docs:
`AttributeError: module 'pandas_ta' has no attribute 'AllStrategy'`

**Comment by twopirllc** [comment]
Hello @andybrewer,

By default: ```data.ta.strategy()``` is equivalent to ```data.ta.strategy(ta.AllStrategy)```.

Let me know if that works.

Thanks,
KJ

**Comment by andybrewer** [comment]
This fails on Kaggle as well:

```
!pip install pandas_ta
import pandas as pd
import pandas_ta as ta

print(ta.AllStrategy)
```

**Comment by twopirllc** [comment]
Which version are you running? Latest? I just updated it today.

```$ pip install -U git+https://github.com/twopirllc/pandas-ta```

KJ

**Comment by andybrewer** [comment]
That worked! I installed it for the first time only a few minutes ago. Maybe right before you updated it? Regardless, it's working now. Thanks!

**Comment by twopirllc** [comment]
Thanks for using **Pandas TA**!

Drop a ⭐ if you find it useful.

Thanks,
KJ

**Comment by jaymasimba** [comment]
The pip install pandas-ta install the version 0.1.66b that did not contain the strategy attributes. So I cloned and installed the latest version from github which worked.

**Comment by twopirllc** [comment]
@jaymasimba,

Thanks for getting back to me. Glad you were able to resolve the issue. Yes, pandas version 0.1.66b via pip was the last version before Strategy was implemented. The pip version contains the last most stable version while the Github version is the latest version. Hopefully soon, pip will get the current version should no further killer bugs creep up.

Drop a ⭐ if you find the library useful.

Thanks,
KJ
