### ISSUE TITLE
FISHERT_5 & KAMA_10_2_30 - Only Get NaNs     

### ISSUE THREAD

**Issue by AcudoDev** [twopirllc/pandas-ta#97]
Hello,

Thank you for your work, it's incredible.

When running a AllStrategy, the FISHERT_5 and KAMA_10_2_30 columns only contain NaNs. I tried it on the Apple's max historical data (10002 data points). No error raised during calculations and other indicators are correct. 

Sample code:

```
import pandas as pd

import yfinance as yf
import pandas_ta as ta

Symbol = "AAPL"
Period = "max"
Interval = "1d"
GroupBy = 'column'
AutoAdjust = True
PrePost = False

AssetTicker = yf.Ticker(Symbol)
AssetHData = AssetTicker.history(period=Period, interval=Interval, group_by=GroupBy, auto_adjust=AutoAdjust, prepost=PrePost)
AssetHData.columns = AssetHData.columns.str.lower()

AssetTS = AssetHData.copy()
AssetTS.ta.mp = True
AssetTS.ta.strategy(name='all', verbose=True, timed=True)

test = len(AssetTS) - AssetTS.count()
test[test > 1000]

```
What's wrong? Perhaps I missed something..

Thanks

**Comment by twopirllc** [comment]
Hello @AcudoDev,

Thanks for using **Pandas TA**!

That's interesting! Thanks for bringing it to my attention. I'll look into it.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hello @AcudoDev,

Should be fixed now and available via Github. Check it out before I push this version to ```pip```.

Thanks for your patience,
KJ

**Comment by AcudoDev** [comment]
Hello @twopirllc 

Tested with the github version and now the indicators have values - didn't verify the values themselves.

Thank you a lot for the fix,

AcudoDev
