### ISSUE TITLE
custom ta.Strategy does not work when df.ta.mp = True

### ISSUE THREAD

**Issue by umit77** [twopirllc/pandas-ta#98]
If we create a custom strategy like this one:
custom_a = ta.Strategy(name="A", ta=[{"kind": "sma", "length": 50}, {"kind": "sma", "length": 200}])
and call
df.ta.mp = True
df.ta.strategy(custom_a, cores=3)

Indicators are not added.

**Comment by twopirllc** [comment]
Hello @umit77,

The only bug is that it should create the indicators regardless of whether or not ```df.ta.mp =True```. However, ```df.ta.mp =True``` only applies to running **all** the indicators as described in the README.

<img width="564" alt="Screen Shot 2020-08-14 at 7 03 50 AM" src="https://user-images.githubusercontent.com/18198392/90257724-60938880-ddfc-11ea-86d0-233a86ed98b6.png">

Thanks,
KJ

**Comment by umit77** [comment]
Thank you @twopirllc for prompt response. It will be nice to have multiprocessing with other cases as well because with many indicators and many rows of data, calculation is really taking time.

**Comment by twopirllc** [comment]
Hello @umit77,

It is definitely **true** for All the indicators. Not true with two indicators. I am willing to look into enabling for a certain minimum (threshold) number of indicators to process. What the number is, has yet to be determined. Do you have a suggested minimum?

Please add a ⭐ if you find the library useful.

Thanks,
KJ

**Comment by umit77** [comment]
I have added star. Yes find the library is very useful and I think it has the highest number of indicators available among similar libraries. 
In my use case, I generate the indicator values, scale them and feed them to ml model for prediction using flask and waitress. Response is too slow due to time it takes to compute the indicators. Because of that I wanted to use mp option.

I can recommend allowing mp when the number of indicators >= cores option.

**Comment by twopirllc** [comment]
I understand Pandas TA is part of processing pipeline. I too am trying to finish building my own Algo Trading Platform with my nonexistent free time 🤣 . What is your input size and how many indicators are you processing?

Thanks for the input. I'll add it to the queue of things. Unfortunately, I do not have a time frame on this issue but I will keep you posted.

Regards,
KJ

**Comment by umit77** [comment]
Thank you very much. You will also need faster calculations then. May be this affects your priorities :-)
I am still experimenting and trying to find something that works. For my test system I have 6 indicators calculated on 30 to 50 rows. 

But number of indicators may change as well as number of rows if I need to calculate indicators for higher period values.

**Comment by twopirllc** [comment]
Sure.

I know, you will be using larger sets and more indicators. However, with 1217 rows and four cores **without** _mp_, I get between 5 - 12 ms running Custom A Test.

<img width="671" alt="Screen Shot 2020-08-14 at 9 03 55 AM" src="https://user-images.githubusercontent.com/18198392/90269213-1ff03b00-de0d-11ea-85c0-32258bc32e3a.png">

Whereas with the same dataset and running **All**, I average under 3secs.

<img width="685" alt="Screen Shot 2020-08-14 at 9 04 40 AM" src="https://user-images.githubusercontent.com/18198392/90269330-50d07000-de0d-11ea-9586-95282630d7a5.png">

With better machines, cores and memory, I'm sure the performance would be much better.

> But number of indicators may change as well as number of rows if I need to calculate indicators for higher period values.

Well aware of this.

**Comment by umit77** [comment]
Thanks. Something else must be taking long then. I will investigate.

**Comment by twopirllc** [comment]
No worries.

Also, you can time your Strategy like so ```df.ta.strategy(custom, timed=True)```.

Hope this helps!

KJ

**Comment by umit77** [comment]
When I time my custom strategy, I see 18ms (5 indicators, 25 rows). If I add the indicators separately, total time is about 16ms.

**Comment by umit77** [comment]
I am also getting this warning: ...lib\site-packages\pandas\core\series.py:726: RuntimeWarning: invalid value encountered in sign
  result = getattr(ufunc, method)(*inputs, **kwargs)

**Comment by twopirllc** [comment]
It's a Pandas warning and not an error with ```pandas-ta```. You can disable the Pandas warning like so:

```python
import warnings
warnings.filterwarnings("ignore")
```

**Comment by umit77** [comment]
Thank you very much.

**Comment by Fr3d1sk** [comment]
even with the build in categories it won't append them, am I missing something?
```
    df = pd.read_csv("../data/price_data/XBTUSD-1h-data.csv")

    df.ta.strategy(name="Momentum", timed=True, append=True)
    print(df.columns)
```
The output is:
`Index(['timestamp', 'symbol', 'open', 'high', 'low', 'close', 'trades',
       'volume', 'vwap', 'lastSize', 'turnover', 'homeNotional',
       'foreignNotional'],
      dtype='object')`


Here is another example:
```
    df = pd.read_csv("../data/price_data/XBTUSD-1h-data.csv")
    print(ta.categories)
    df.ta.strategy(name="trend", verbose=True)
    print(df.columns)
```
Output:
```
['candles', 'momentum', 'overlap', 'performance', 'statistics', 'trend', 'volatility', 'volume']
[i] ta.strategy(name=trend)
[+] Strategy: trend
[i] Indicators with the following arguments: {'append': True}
[i] Total indicators: 0
[i] Columns added: 0
Index(['timestamp', 'symbol', 'open', 'high', 'low', 'close', 'trades',
       'volume', 'vwap', 'lastSize', 'turnover', 'homeNotional',
       'foreignNotional'],
      dtype='object')

Process finished with exit code 0
```

But when I try it with all indicators it works, but with everything else it won't

**Comment by twopirllc** [comment]
@umit77, @Fr3d1sk 

Multiprocessing is enabled for all kinds of Strategies by default now on the _development_ branch with the help of @DrPaprikaa. Test it out if you wish before I push it to the _master_ branch soon.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks for your patience,
KJ
