### ISSUE TITLE
ta.strategy doesnt include statistical measures?

### ISSUE THREAD

**Issue by sword134** [twopirllc/pandas-ta#99]
Using the below mentioned code, it doesnt seem that pandas_ta's ta.strategy includes the statistical indicators such as skew and zscore.

`data.ta.strategy(exclude=["dpo", "fisher", "kama", "brar", "decreasing", "increasing", "psar", "trix", "t3", "kst", "eom"], verbose=True)`

Any solution as to how to include the statistical indicators while also excluding the above ones?

**Comment by twopirllc** [comment]
Hello @sword134,

Did you resolve your own issue or how come you closed this?

Thanks,
KJ

**Comment by sword134** [comment]
@twopirllc it was a slipup on my side, nothing to do with pandas_ta. Sorry

**Comment by twopirllc** [comment]
@sword134 

Thanks for the prompt reply. Glad you resolved it.

Drop a ⭐ if you find the library useful.

Thanks,
KJ
